### ISSUE TITLE
feat: make env setup work in middleware

### ISSUE THREAD

**Issue by iduuck** [t3-oss/create-t3-app#1000]
### Is your feature request related to a problem? Please describe.

I am currently facing a problem, when using the environment variable setup from t3 and I am opening this issue, since the other issue about environment variables not working (#999) was closed by the author.

### Describe the solution you'd like to see

It would be necessary (for now – don't know, if this is being fixed, though) to also compose the server env vars, like we do for the client env vars.

### Describe alternate solutions

non that i can think of.

**Comment by c-ehrlich** [comment]
Could you explain more precisely what you are trying to do? Accessing env vars in middleware works just as it would anywhere else, see: https://github.com/c-ehrlich/mwenv/commit/492bef23be5c3b2a063d4ef07fa96d4f07529359

**Comment by iduuck** [comment]
Sorry, not speaking of trpc middleware, but of Next.js middleware.

**Comment by c-ehrlich** [comment]
Just tried and can confirm that this currently doesn't work, the import makes Next middleware blow up. Accessing the environment variables in a non-typesafe way (ie `process.env.SERVERVAR` does work, but obviously isn't ideal.

What would we need to do to get it to work, and are there any downsides?

**Comment by iduuck** [comment]
I think the only way to work around this, is to define the server env vars the same way, as we do with the client env vars (explicitly building our env object before verifying).

**Comment by iduuck** [comment]
fixed by #1021
