### ISSUE TITLE
bug (docs): Horizontal scrolling in docs in Arabic/RTL (Firefox)

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#1005]
### Provide environment information

Firefox 108.1 on MacOS 13. Doesn't happen in Chrome.

### Describe the bug

When browsing the docs in Arabic (and presumably any other RTL language) **in Firefox**, there is additional space to the left, which creates a horizontal scroll bar. This happens at all sizes.

Large:
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/8353666/209402737-9b1f0dc9-79df-4181-952e-e150fe9a0e33.png">

Medium:
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/8353666/209402879-23c53967-49da-4cdd-8907-56699b332f0f.png">

Small:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/8353666/209403050-9068ed19-934a-4ec4-81b0-37e848306b3e.png">

### To reproduce

Go to https://create.t3.gg/ar/introduction in Firefox

**Comment by ParalaxDev** [comment]
I've got the same issue in Firefox 108.0.1 on Windows 11. If you want to assign me I think I can fix it
