### ISSUE TITLE
bug: reverted link icon in Arabic docs

### ISSUE THREAD

**Issue by Sboonny** [t3-oss/create-t3-app#1014]
### Provide environment information

Environment: Gitpod

### Describe the bug

The direction of the link icon is reverted in Arabic docs, it starts from the left then tilt to the right. this could be reverted to be starting from the right and tilting to the left.

Here how it looks in [introduction](https://create.t3.gg/ar/introduction#t3-stack): 
 
![image](https://user-images.githubusercontent.com/88248797/209550790-f4e7a27a-bee6-49f4-9a73-4a4a2cf85702.png)

### To reproduce

1- Open development environment
2- Open `/www` folder
3- Open any file in `ar` folder
5- Add a link
6- Build the docs, and visit said folder

### Additional information

You can find Astro plug-in here: 

https://github.com/t3-oss/create-t3-app/blob/7cc1607ccc303c7d0b7647ae0aebc97f2c886db3/www/astro.config.mjs#L18-L29?plain=1

**Comment by c-ehrlich** [comment]
I've noticed this also.

What would be ideal for RTL? `↖`, to the left of the text?

I don't know if that's possible to implement with the plugin we are currently using. If not, we should either find a different solution, or scrap the external link arrows (but I would prefer keeping them).

**Comment by juliusmarminge** [comment]
> I've noticed this also.
> 
> What would be ideal for RTL? `↖`, to the left of the text?
> 
> I don't know if that's possible to implement with the plugin we are currently using. If not, we should either find a different solution, or scrap the external link arrows (but I would prefer keeping them).

We can target it with css and mirror it maybe?

**Comment by Sboonny** [comment]
> What would be ideal for RTL? `↖`, to the left of the text?

Yeab

> Not sure how that'd be done conditionally if its RTL though?

html has `dir='rtl'` attribute which we can use to target RTL.

![image](https://user-images.githubusercontent.com/88248797/209566023-ea4c7b16-080c-448a-a0c2-4b787362f62a.png)

```css
:is[dir='rtl'] .markdown a[rel~="noreferrer"] > span {
    @apply -scale-x-100;
}
```

The previous code my work, need to test it out tho.

**Comment by Sboonny** [comment]
Had to display it as `inline-flex`, but it works. Good call 👍 

```css
  :is([dir='rtl']) .markdown a[rel~="noreferrer"] > span {
    @apply -scale-x-100;
    display: inline-flex;
}
```

**Comment by juliusmarminge** [comment]
Completed via #1019
