### ISSUE TITLE
feat: Stage the template once created

### ISSUE THREAD

**Issue by Samathingamajig** [t3-oss/create-t3-app#1026]
### Is your feature request related to a problem? Please describe.

You run `package-manager-of-choice create t3-app@latest`. You work on making a quick app. You go to commit your changes, and boom you see a lot of extra files you never touched. These were from the template, they don't matter for your commit. Ideally, you would've committed the template to have a clean working tree, but it's too late now because you forgot.

### Describe the solution you'd like to see

In order of my preference, based on what others have said:

#### A.
* Stage the template

This gives the option to:
* Commit with custom message
* Commit just the template even if you made edits, since staging stores a snapshot
* Add everything (without even needing to unstage) if you want to have template + changes as your first commit

#### B.
* Prompt if user wants an initial commit (y/N) (default no)
* If yes, prompt the user for the commit message, with "Initial commit from Create T3 App"/"Initial commit from ct3a"/Initial commit from create-t3-app" (or similar) as the default entry that disappears (like the current input for directory name)

#### C.
* Prompt the user for the initial commit message (like A.2), but have <kbd>Space</kbd><kbd>Enter</kbd> or <kbd>Esc</kbd> cancel the initial commit (don't know if <kbd>Esc</kbd> is possible with inquirer)

#### D.
* Have a select dropdown with `no commit`, `"Initial commit from Create T3 App"` (or similar), or `custom commit message` as options
* If custom is selected, have a prompt like A.2
And of course, for all these options, relevant command line arguments.

#### Just don't forget

😐

#### Deal with it

🙄

#### Always commit the template

A lot of people on our Discord don't want the template committed or with a forced name, so doing this by default would require them to either deal with it, reinitialize git, or amend the commit.

### Additional information

|       Tool       |                                                       Git                                                       |
| :--------------: | :-------------------------------------------------------------------------------------------------------------: |
| create-next-app  |    Automatically creates a git repo, commits template with the message "Initial commit from Create Next App"    |
| create-react-app | Automatically creates a git repo, commits template with the message "Initialize project using Create React App" |
| create-astro-app |                                           Does not create a git repo                                            |
|   create-vite    |                                           Does not create a git repo                                            |

Discussed on Discord from [1057485366757687377](https://discord.com/channels/966627436387266600/988912020558602331/1057485366757687377) to [1057528318796234762](https://discord.com/channels/966627436387266600/988912020558602331/1057528318796234762)

**Comment by arcanistzed** [comment]
Alternate solution: stage the files, but don't create an actual commit

**Comment by Samathingamajig** [comment]
The more I think about it, that's reasonable since it gives the option to
* Commit with custom message
* Commit just the template even if you made edits, since staging stores a snapshot
* Add everything (without even needing to unstage) if you want to have template + changes as your first commit

**Comment by asrvd** [comment]
I'd like to go with something like -

1. Prompt the user for initial commit - `Yes/No` (only if they opted to initialize git of course)
2. If `No` continue scaffolding as usual
3. If `Yes` - ask for a commit message with `leave blank for default message` maybe

**Comment by c-ehrlich** [comment]
IMO for every additional prompt we give the user in the CLI we need to think very carefully first if there isn't a reasonable default that we can use instead (and maybe add a command line arg for those who really care). We don't want to turn the CLI into a choose your own adventure book.

Personally I think I like the idea of staging everything if git is chosen (and maybe explicitly tell the user in the CLI that this is happening) more than adding another prompt to the CLI, but let's leave the discussion open for a few days and see what everyone thinks :)

**Comment by complexengine** [comment]
Staging is a good middle ground, if the user is choosing to initialize a git repository, then most likely the user will make multiple commits so the prompt barely has any utility.

**Comment by juliusmarminge** [comment]
Staging makes sense to me and will satisfy both "arguments". Feel free to make a PR for this!
