### ISSUE TITLE
docs(i18n): add turkish translation

### ISSUE THREAD

**Issue by EgeOnder** [t3-oss/create-t3-app#1028]
### Is your feature request related to a problem? Please describe.

I believe that translation for an over 80 million native speaker language would be great.

### Describe the solution you'd like to see

Add Turkish language translations to create.t3.gg docs website.

### Describe alternate solutions

N/A

### Additional information

Any other native Turkish speakers are welcome to translate it with me. I think create-t3-app is awesome and everyone should understand the documentation.

**Comment by juliusmarminge** [comment]
Closing the issue. Anyone is free to add translations for any language and there are instructions to do so in `www/TRANSLATIONS.md` - draft PR is enough to let others know this is being worked on!
