### ISSUE TITLE
bug: incorrect exit codes on failure

### ISSUE THREAD

**Issue by jamesgeorge007** [t3-oss/create-t3-app#1033]
### Provide environment information

`create-t3-app` v6.11.6. Not including the environment information since this is directly related to the CLI.

### Describe the bug

Aborting installation while scaffolding in a non-empty directory results in a `0` exit code. An instance of failure should ideally result in a non-zero exit code. Ref: [lirantal/nodejs-cli-apps-best-practices#64-proper-use-of-exit-codes](https://github.com/lirantal/nodejs-cli-apps-best-practices#64-proper-use-of-exit-codes).

### To reproduce

- Create a new application on a path that exists and is non-empty.
- Choose `Abort installation` at the prompt asking for overwrite confirmation. Alternatively, proceed with any of the other two options, and choose `No` at the next prompt.
- Check the exit code - `0`.

![image](https://user-images.githubusercontent.com/25279263/210084200-ab6fd4f6-324e-4a15-8627-0617d25c1984.png)

![image](https://user-images.githubusercontent.com/25279263/210084259-cd9f895a-08ac-4b71-adc1-40d517d0d754.png)

### Additional information

I'd be happy to raise a PR 🙌

**Comment by c-ehrlich** [comment]
Does choosing to exit the CLI because the folder already exists count as an "error"? It's an intentional choice by the user. I'm not super familiar with exit codes so need to research this one.

**Comment by jamesgeorge007** [comment]
> Does choosing to exit the CLI because the folder already exists count as an "error"? It's an intentional choice by the user.

I understand your point. But doesn't it count as a failed attempt while scaffolding a new project? Currently, it is signified by the spinner status set to fail.

https://github.com/t3-oss/create-t3-app/blob/88ce6e50289281e009f1eea2223dbef4cb86df61/cli/src/helpers/scaffoldProject.ts#L61-L64

Consider a scenario in which the CLI is consumed in a CI environment; let's assume the existence of conflicting files isn't intended, and `No` is supplied if the prompt shows up, asking for the confirmation to overwrite. In this case, the job would succeed with the exit code being `0`. However, we'd want the job would fail since the scaffolding didn't happen.

- `create-vue` CLI handles it this way.

![image](https://user-images.githubusercontent.com/25279263/210128205-0a9ebb8f-7cdd-4202-843c-21bbbacbc2cb.png)

- `create-react-app` and `create-next-app` returns with an exit code of `1` on encountering conflicting files. They don't handle directory cleanup.

![image](https://user-images.githubusercontent.com/25279263/210128276-23430865-16c7-4c5a-a0e8-cdf9f45b02bd.png)

![image](https://user-images.githubusercontent.com/25279263/210128289-171090ba-f388-45d4-90c8-8c8402aeb29e.png)
