### ISSUE TITLE
bug: border-width around code element breaks in the wrong direction in the docs

### ISSUE THREAD

**Issue by Sboonny** [t3-oss/create-t3-app#1037]
### Provide environment information

Browser: Edge

### Describe the bug

In the AR docs, here is the heading url: https://create.t3.gg/ar/faq#%D9%84%D9%85%D8%A7%D8%B0%D8%A7-%D9%87%D9%8F%D9%86%D8%A7%D9%83-%D9%85%D9%84%D9%81%D8%A7%D8%AA-%D8%A8%D8%A7%D9%85%D8%AA%D8%AF%D8%A7%D8%AF-js-%D9%81%D9%8A-%D9%87%D8%B0%D8%A7-%D8%A7%D9%84%D9%85%D8%B4%D8%B1%D9%88%D8%B9-

The `border-width` breaks in the wrong direction, <s>because the `border-width` is a short-hand for the code below.</s> because of the direction of the code context.

![image](https://user-images.githubusercontent.com/88248797/210152599-d1ed6c6b-5ebe-44d4-a380-d181abe4fcb0.png)

### To reproduce

Visit: https://create.t3.gg/ar/faq#%D9%84%D9%85%D8%A7%D8%B0%D8%A7-%D9%87%D9%8F%D9%86%D8%A7%D9%83-%D9%85%D9%84%D9%81%D8%A7%D8%AA-%D8%A8%D8%A7%D9%85%D8%AA%D8%AF%D8%A7%D8%AF-js-%D9%81%D9%8A-%D9%87%D8%B0%D8%A7-%D8%A7%D9%84%D9%85%D8%B4%D8%B1%D9%88%D8%B9-

### Additional information

I thought applying `border-inline-width` and `border-block-width` in the selector below will fix the issue, but with no luck.

https://github.com/t3-oss/create-t3-app/blob/7cc1607ccc303c7d0b7647ae0aebc97f2c886db3/www/src/styles/global.css#L187-L189

Here is the desired looks with this border. Note: I used `direction: rtl` to get the desired looks, but the context of the code element isn't aligned right, ultimately it should still be `ltr` but with borders wrapped around it like below.

![image](https://user-images.githubusercontent.com/88248797/210152824-82d29b81-00d4-474a-aa80-61a88f98b858.png)

**Comment by AnujSsStw** [comment]
![Screenshot from 2023-01-01 22-56-58](https://user-images.githubusercontent.com/92370865/210179639-d2843a40-6889-412f-a9fe-8d32c26cf941.png)
i don't see a issue here

**Comment by Sboonny** [comment]
AnujSsStw, zoom in or change the layout's width to `768` or `1440` in the devtools, and you will be able to see it.

**Comment by c-ehrlich** [comment]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/8353666/210186152-c9d3f264-c3e4-4afc-bd0f-1c5dbfc2f92c.png">
It feels like inline code elements are buggy in general. See screenshot above, and `@ts-check` incorrectly being rendered as `ts-check@` in AnujSsStw's comment.

**Comment by Sboonny** [comment]
> It feels like inline code elements are buggy in general. See screenshot above (should be /app and /pages, and @ts-check incorrectly being rendered as ts-check@ in AnujSsStw's comment.

Note: These aren't a layout issue, but translation issue, because they are added as `app/` and `ts-check@` in the AR docs. 

The proofreading PR sorted these out.

**Comment by AnujSsStw** [comment]
> > It feels like inline code elements are buggy in general. See screenshot above (should be /app and /pages, and `@ts-check` incorrectly being rendered as ts-check@ in AnujSsStw's comment.
> 
> Note: These aren't a layout issue, but translation issue, because they are added as `app/` and `ts-check@` in the AR docs.
> 
> The proofreading PR sorted these out.

![Screenshot from 2023-01-03 17-28-03](https://user-images.githubusercontent.com/92370865/210356341-4eea397a-2317-469c-9538-2cd8ed272f7c.png)

Na bro AR docs is well an good. I think it's something in these lines [Css](https://github.com/t3-oss/create-t3-app/blob/next/www/src/styles/global.css#L187) 
```
```

**Comment by Sboonny** [comment]
Here are 2 important points, you are misunderstanding.

- I can type `ts-check@` and let the browser rotate it in `rtl` to be `@ts-check`, but screen readers won't read the right content as they will be reading `ts-check@` not the correct word, which is `@ts-check`.
- The context in code block and code elements follow the English direction `ltr`, because they are typed in the English language. Note: notice how `/app`, which is typed `/app` in the section's the description, is misaligned in your image.

---

The solutions are as mentioned by c-ehrlich, please don't change the code direction to `rtl`.

**Comment by juliusmarminge** [comment]
> Here are 2 important points, you are misunderstanding.
> 
> * I can type `ts-check@` and let the browser rotate it in `rtl` to be `@ts-check`, but screen readers won't read the right content as they will be reading `ts-check@` not the correct word, which is `@ts-check`.
> * The context in code block and code elements follow the English direction `ltr`, because they are typed in the English language. Note: notice how `/app`, which is typed `/app` in the section's the description, is misaligned in your image to be `app/`.
> 
> The solutions are as mentioned by c-ehrlich, if you have a third solution feel free to use it, as long as you don't change the code direction to `rtl`.

do you mean a rehype plugin that transforms the codeblocks into lrt won't work?

**Comment by Sboonny** [comment]
```html
<code class='border dir-ltr'>@ts-check</code>
```

Reading the comments in the link, changing how astro render the code above to the code below should sort it, without issues.

```html
<div class='border'>
   <code class='dir-ltr'>@ts-check</code>
</div>
```

I haven't tested it tho, because of the https://github.com/t3-oss/create-t3-app/labels/%3Abeginner%3A%20good%20first%20issue label.

**Comment by c-ehrlich** [comment]
> > Here are 2 important points, you are misunderstanding.
> > 
> > * I can type `ts-check@` and let the browser rotate it in `rtl` to be `@ts-check`, but screen readers won't read the right content as they will be reading `ts-check@` not the correct word, which is `@ts-check`.
> > * The context in code block and code elements follow the English direction `ltr`, because they are typed in the English language. Note: notice how `/app`, which is typed `/app` in the section's the description, is misaligned in your image to be `app/`.
> > 
> > The solutions are as mentioned by c-ehrlich, if you have a third solution feel free to use it, as long as you don't change the code direction to `rtl`.
> 
> do you mean a rehype plugin that transforms the codeblocks into lrt won't work?
> 
> Can confirm it doesn't... <img alt="CleanShot 2023-01-04 at 13 06 20@2x" width="1225" src="https://user-images.githubusercontent.com/51714798/210551740-85b7ad7f-e9f7-4bfa-91f9-7c38208e33aa.png">
As @Sboonny said, we would need to wrap a div around it (which would inherit rtl) that has the border styles, and then have the text itself in an ltr element

> I haven't tested it tho, because of the [ 🔰 good first issue](https://github.com/t3-oss/create-t3-app/labels/%3Abeginner%3A%20good%20first%20issue) Good for newcomers label.
Feel free to work on this - I'm going to remove the good first issue label because I placed it when I thought the solution was simpler than it is

**Comment by Sboonny** [comment]
I have tried to implement `remark-code-extra`, but I am getting the error below.

> Cannot set property message of [object Object] which has only a getter

I think, I have the wrong syntax but can't find it. Do you have a guess of what I am doing wrong?

```js
    remarkPlugins: [remarkCodeTitles, remarkCodeExtra, {
      transform: (node) => node && ({
        after: [
          {
            type: 'element',
            tagName: 'div',
            properties: {
              class: 'rounded border border-t3-purple-200 dark:border-t3-purple-400/30'
            }
          }
        ]
      })
    }
  ],
```

---

BTW, what is the proper channel to ask for help? should I stay here or go to discord 😅

**Comment by juliusmarminge** [comment]
No clue what's happening there... You could always do it in the PageContent.astro with JavaScript if you can't get remark to work ;)
