### ISSUE TITLE
feat: adding create-jd-app and create-t3svelte-app to other recommendations in docs

### ISSUE THREAD

**Issue by Svadrut** [t3-oss/create-t3-app#1041]
### Is your feature request related to a problem? Please describe.

I recently came upon [create-jd-app](https://github.com/OrJDev/create-jd-app) that is the solid-js version of create-t3-app and [create-t3svelte-app](https://github.com/zach-hopkins/create-t3svelte-app). I was surprised to see that it wasn't in the create-t3-app docs.

### Describe the solution you'd like to see

Add create-jd-app and create-t3svelte-app to the other section in recommendations.

### Describe alternate solutions

N/A

### Additional information

I can make a PR if this issue goes through.

**Comment by juliusmarminge** [comment]
The other recommendations section isn't for switching out the core part, i.e. the framework underneath - Next.js.

This would probably be better off in conjunction with #948.

**Comment by c-ehrlich** [comment]
Agreed with Julius, the recommendations page is for things we recommend to use alongside the stack. I'm definitely in favor of linking to Astro for example, and am not against linking to any of these other projects (although I haven't tried any of them myself), but it should go on a different page.

**Comment by juliusmarminge** [comment]
Moved to #948
