### ISSUE TITLE
bug: Unable to run example command from site (Syntax error)

### ISSUE THREAD

**Issue by Descent098** [t3-oss/create-t3-app#1042]
### Provide environment information

npx: installed 1 in 1.546s

  System:
    OS: Windows 10 10.0.19045
    CPU: (32) x64 AMD Ryzen Threadripper 1950X 16-Core Processor
    Memory: 14.24 GB / 31.90 GB
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

When running `npm create t3-app@latest` as suggested on the site I am getting a `SyntaxError` that prevents me running the script. It will go through and fetch everything correctly, then error out when trying to execute.

The output is:

```bash
>npm create t3-app@latest
npx: installed 110 in 9.627s
(node:24316) ExperimentalWarning: The ESM module loader is experimental.
file:///C:/Users/Kieran/AppData/Roaming/npm-cache/_npx/27912/node_modules/create-t3-app/dist/index.js:6
`,A="my-t3-app",N="create-t3-app";var J=({projectDir:e,packages:t})=>{let i=t?.nextAuth.inUse,s=t?.prisma.inUse,n=Oe(!!i,!!s),o=i&&s?"with-auth-prisma.mjs":i?"with-auth.mjs":s?"with-prisma.mjs":"";if(o!==""){let p=j.join(c,"template/extras/src/env/schema",o),m=j.join(e,"src/env/schema.mjs");M.copySync(p,m)}let r=j.join(e,".env"),l=j.join(e,".env.example");M.writeFileSync(r,n,"utf-8"),M.writeFileSync(l,Ne+n,"utf-8")},Oe=(e,t)=>{let i="# When adding additional env variables, the schema in /env/schema.mjs should be updated accordingly";return t&&(i+=`
                                                                              ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:117:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

### To reproduce

On my machine I did the following:

1. Setup a new folder on the desktop 
2. Ran `npm create t3-app@latest`

**Comment by Descent098** [comment]
Immediately after submitting I confirmed the issue is related to using old version of node/npm. 

Working correctly after updating to node 18 and npm 8. Might be worth adding to the docs somewhere as a FAQ suggestion, or to the new issue form for troubleshooting!

Thanks for all your great work on the project!

**Comment by c-ehrlich** [comment]
Just tried to reproduce, and was only able to do so on Node versions that are EOL. 14.x, which is the oldest version that is still officially supported, works fine. Since this is the first time we've ever had anyone run into this, and it requires having an extremely outdated node version, which wouldn't happen to anyone on a new setup, I think it's better to not add this to docs etc until we get more people with the same issue.
