### ISSUE TITLE
bug: Preact not working 

### ISSUE THREAD

**Issue by Lucasvo1** [t3-oss/create-t3-app#1047]
### Provide environment information

7.0.0

### Describe the bug

I did the usual configuration for Preact in next.config.js but the build is still using React. 

### To reproduce

Create a new app with all modules enabled.

Set up configuration for Preact.

Analyse the build.

**Comment by c-ehrlich** [comment]
Could you describe in more detail what you are trying to do? If it’s just swapping out React for Preact in a fully loaded T3 app, that’s not going to work.

**Comment by juliusmarminge** [comment]
This is not an issue in create-t3-app. 

I'm guessing it's @tanstack/react-query not supporting Preact. Open your issue there requesting a Preact adapter - after which you should be a bee to swap it out

**Comment by Lucasvo1** [comment]
Ah, pity. This stack looked fun to try out.
