### ISSUE TITLE
feat: mention Netlify T3 App Deployment page in scaffolded README.md

### ISSUE THREAD

**Issue by AyanavaKarmakar** [t3-oss/create-t3-app#1048]
### Is your feature request related to a problem? Please describe.

Since the T3 docs now have a page for Netlify under the "Deployment" section, mentioning it alongside Vercel and Docker will be a good addition IMO.

[![image](https://user-images.githubusercontent.com/89210438/210430229-7e7cd8ab-40b2-446e-8bb6-5cdd3cec7cd4.png)](https://github.com/t3-oss/create-t3-app/blob/next/cli/template/base/README.md#how-do-i-deploy-this)

### Describe the solution you'd like to see

Mention Netlify alongside Vercel and Docker, including a link pointing towards -> https://create.t3.gg/en/deployment/netlify

### Describe alternate solutions

Keep it as it is?

**Comment by juliusmarminge** [comment]
Done in https://github.com/t3-oss/create-t3-app/commit/020209c32f15ae0753632ee09ae02f8c0abda346
