### ISSUE TITLE
feat: Install Progress

### ISSUE THREAD

**Issue by Stoffberg** [t3-oss/create-t3-app#1049]
### Is your feature request related to a problem? Please describe.

When using the installer provided by the tool, there is no way to show what is is busy doing. This leads me to not understanding how long it still needs, how big it is or what it is busy doing.

### Describe the solution you'd like to see

Just a simple progress bar with the packages install progress or even just the output from the installer, pnpm, npm, yarn ect.

### Describe alternate solutions

Pass in a flag at the start that will display it at the bottom or open up a terminal with the command already typed in

**Comment by c-ehrlich** [comment]
We already give information about what step the installer is on:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/8353666/210679033-7acce324-1201-4348-9e5a-51f077fb2f24.png">

The only part that takes a meaningful amount of time is installing packages, especially when using npm. It might be possible to get information like "currently installing package x out of y", although I don't know to what extent we would need to hook into the package manager to be able to do it. Would be open for a PR for this if it works for all three package managers we support (npm, yarn classic, pnpm) and feels reasonably maintainable.

**Comment by Stoffberg** [comment]
I'll have a look into it in the next few days. Will keep you up to date

**Comment by PiotrekPKP** [comment]
I've tried to do a little research and build an implementation of that. The thing is, I've already got stuck on `npm`'s implementation. You basically have to somehow read the progress of the installation.

The way `npm` works, is that it either doesn't show any progress (this is the way is work when run in a non-TTY env) or it shows the progress bar (we could use it to calculate percentage) by sending data to the `stderr`. To show the progress we'd somehow have to simulate / pretend we're running in TTY.

The only other option is setting `{ stderr: "inherit" }` in `execa` function call's options, but the look would differ based on the selected package manager.

So, if anyone has any idea how to redirect the stderr from `npm`'s output while simulating tty in a pretty lightweight way, that's probably the only way. Please let me know if I'm missing something :thinking:

**Comment by juliusmarminge** [comment]
> The only other option is setting { stderr: "inherit" } in execa function call's options, but the look would differ based on the selected package manager.

I think most CLIs do this actually. See Next.js:

![CleanShot 2023-01-23 at 11 16 54](https://user-images.githubusercontent.com/51714798/214015254-a8fe71b0-673e-4682-a2bf-131780bc74f7.png)

and Astro:

![CleanShot 2023-01-23 at 11 17 28](https://user-images.githubusercontent.com/51714798/214015353-e9013918-7e19-4808-bb01-978b1cf1a24d.png)

(Astro's actually clean and the progress goes away after its done:)

![CleanShot 2023-01-23 at 11 17 55](https://user-images.githubusercontent.com/51714798/214015470-80de5768-6c08-4f06-9f0b-9ff9326df2a3.png)

**Comment by PiotrekPKP** [comment]
Tbf I wasn't aware that this is the case. I think we could actually implement that? What do others think?

**Comment by c-ehrlich** [comment]
would be nice to have! even better if we can make it look nice and give it the same color gradient as the logo.

**Comment by PiotrekPKP** [comment]
> would be nice to have! even better if we can make it look nice and give it the same color gradient as the logo.

If there's anyone willing to do it go ahead, if not I can implement it next weekend (I'm on vacation without my computer right now)
