### ISSUE TITLE
bug: 'name' attribute doesn't get replaced with the project name in `package-lock.json`.

### ISSUE THREAD

**Issue by prashantrahul141** [t3-oss/create-t3-app#1053]
### Provide environment information

System:
- OS: Windows 10 10.0.19044
- CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
- Memory: 1.35 GB / 7.42 GB

Binaries:
- Node: 18.11.0 - C:\Program Files\nodejs\node.EXE
- npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

When creating a new project using the cli, if the user chooses to say yes to `Would you like us to run npm install? (Y/n)`, the `package-lock.json` file gets created but the problem is, the name attribute in that file is still 'template'.  Also should be noted that it does get changed in `package.json` file.

### Reproduction repo

https://github.com/prashantrahul141/create-t3-package-lock-template-bug/blob/main/package-lock.json

### To reproduce

- create a new app using the cli
- say yes to `Would you like us to run npm install? (Y/n)`
- check 'name' in `package-lock.json`

### Additional information

example of `package-lock.json`:
![image](https://user-images.githubusercontent.com/59825803/211000270-59925a2e-fc00-4fc5-839e-52be30bc6b32.png)

example of `package.json`:
![image](https://user-images.githubusercontent.com/59825803/211000397-d44437db-ef5d-424b-92a1-47a851c97cba.png)

**Comment by TheDevMinerTV** [comment]
I can reproduce this behaviour.

**Comment by juliusmarminge** [comment]
We'd need go swap the order here:

https://github.com/t3-oss/create-t3-app/blob/06eab127cbba207495b608639f6454d1f5618e16/cli/src/index.ts#L48-L62

**Comment by c-ehrlich** [comment]
@prashantrahul141 do you want to open a PR for this? Otherwise I would tag it as Good First Issue - we have the desired solution outlined in Julius' comment so it would be a great first one for a newcomer :)

**Comment by prashantrahul141** [comment]
yes! created a pr https://github.com/t3-oss/create-t3-app/pull/1056, tested the cli now it does change the `name` attribute.
