### ISSUE TITLE
bug: Multiple API calls happening on window focus

### ISSUE THREAD

**Issue by realph** [t3-oss/create-t3-app#1055]
### Provide environment information

version: 0.1.0

### Describe the bug

I'm using the scaffolded app which makes the initial API call, but whenever I move focus (click) outside the browser window and then focus back (click) on the browser window a subsequent API call is made. Is this expected behaviour? See image below for multiple API calls in the Network Tab.

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/2334951/211151361-89e48dca-b877-4871-99f4-f703818c55b3.png">

### Reproduction repo

https://github.com/t3-oss/create-t3-app

### To reproduce

Move focus (click) outside the browser window and then focus back (click) on the browser window and a subsequent API call will be made.

**Comment by FeMaffezzolli** [comment]
It's not a bug, its the default behavior of react-query. 
You can disabled that: https://tanstack.com/query/v4/docs/react/guides/window-focus-refetching

**Comment by realph** [comment]
Thanks @FeMaffezzolli. Will close.
