### ISSUE TITLE
feat: add react hook form

### ISSUE THREAD

**Issue by jsun969** [t3-oss/create-t3-app#1062]
### Is your feature request related to a problem? Please describe.

I use react hook form and trpc with zod in my project. It makes me feel super awesome with a resuable schema to form and backend.
trpc have an official example: https://kitchen-sink.trpc.io/react-hook-form

### Describe the solution you'd like to see

Add react hook form option to add react hook form when create project

### Describe alternate solutions

Same as the description 😂

### Additional information

I can try to contribute if you think this feature can be added :P

**Comment by t3dotgg** [comment]
No. We don't include things as simple as an NPM install.
