### ISSUE TITLE
bug: TypeScript errors with stricter TSConfig

### ISSUE THREAD

**Issue by NiklasBurggraaff** [t3-oss/create-t3-app#1067]
### Provide environment information

7.2.0

### Describe the bug

With the TypeScript compiler option `exactOptionalPropertyTypes` set to true, there is a type error in the `src/pages/api/trpc/[trpc].ts` file. This is due to `onError` possibly being set to undefined, when the type should be `OnErrorFunction` (from `@trpc/server/src/internals/types.ts`).

This can be fixed by replacing line 18 in `src/pages/api/trpc/[trpc].ts` with `: () => undefined,`

Secondly, with the TypeScript compiler option `noImplicitReturns` set to true, there is a type error in the `src/env/client.mjs` file on line 11. This is due to the `map` having a path that does not return a value.

This can be fixed by after line 13 in `src/env/client.mjs` adding `return undefined;`

### Reproduction repo

https://github.com/NiklasBurggraaff/my-t3-ts-error-app

### To reproduce

Firstly, add `"exactOptionalPropertyTypes": true` to the `compilerOptions` inside the `tsconfig.json` file.
Open the `src/pages/api/trpc/[trpc].ts` file to see the TS error.

Secondly, add `""noImplicitReturns": true"` to the `compilerOptions` inside the `tsconfig.json` file.
Open the `src/env/client.mjs` file to see the TS error.

**Comment by juliusmarminge** [comment]
You can always find rules (typescript or lint) which will create warnings on any project - the configuration we ship (which is stricter than most) have no warnings so I wouldn't say this is a bug.

With that in mind, is your suggestion we introduce these rules or just modify these two cases directly - without any guarantee that it might regress later?

**Comment by NiklasBurggraaff** [comment]
That makes sense, did not consider what you said.

Basically, I had to make the code changes in my project because I used a different tsconfig. So I thought it might make sense to modify the template to already include the code changes (not config rules), so that others do not have to make the same change.

**Comment by juliusmarminge** [comment]
> That makes sense, did not consider what you said.
> 
> 
> 
> Basically, I had to make the code changes in my project because I used a different tsconfig. So I thought it might make sense to modify the template to already include the code changes (not config rules), so that others do not have to make the same change.

Sure, but there'll likely be regression later (here or in other placera) if we dont enforce the rules so in my opinion its a choice between enabling the rule or just leave it. We cant "secretely" support all possible configurations. As a matter of fact i think our tsconfig + tslint setup is stricter than most options out there
