### ISSUE TITLE
feat: Deprecate Manual Declarations of `clientEnv` and `serverEnv`

### ISSUE THREAD

**Issue by JacobADevore** [t3-oss/create-t3-app#1069]
### Is your feature request related to a problem? Please describe.

The current `env` folder structure requires manual declarations of client environment variables which is a duplicate of the client schema. An abstraction should be made to eliminate these manual declarations.

### Describe the solution you'd like to see

On client.mjs automatically create the client environment variables object by looping through the client schema.

`/** @type {{ [key: string]: string | undefined; }} */
let clientEnv = {};`

`Object.keys(clientSchema.shape).forEach(
  (key) => (clientEnv[key] = process.env[key])
);`

### Describe alternate solutions

Leaving as is...

**Comment by c-ehrlich** [comment]
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/8353666/211699693-f250656f-2184-40ab-955d-32b488d94b21.png">

inference is working but initial validation seems broken - i think it's related to this line: `/** @type {{ [key: string]: string | undefined; }} */ let clientEnv = {};`.

i would love it if we can get this to work, would be a huge upgrade!

**Comment by juliusmarminge** [comment]
> inference is working but initial validation seems broken 

You need `NEXT_PUBLIC_BAR: z.coerce.number()` since it will always be a string when read from process.env

**Comment by JacobADevore** [comment]
> Can you access the env through variable indices?
> 
> I.e does
> 
> ```ts
> const key = Math.random() > .5 ? "FOO" : "BAR";
> const value = process.env[key]
> //    ^? ???
> ```
> 
> grab the correct value or will it always be undefined?
> 
> If it works that'd be great 👍

You can, and it does get the correct values.

**Comment by c-ehrlich** [comment]
> > inference is working but initial validation seems broken
> 
> You need `NEXT_PUBLIC_BAR: z.coerce.number()` since it will always be a string when read from process.env

Wow I didn't know that, guess I've never used a number as an env variable before. Will think about a good way to add this to the docs.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/8353666/211715952-898a1b0c-ae26-45f4-a245-83d68c14a8e4.png">

It seems to me like everything works. @JacobADevore please feel free to open a PR for this :) Unless there's some problem I'm missing, this is a really nice dx win.

**Comment by JacobADevore** [comment]
#1071

**Comment by MartelliEnrico** [comment]
Should we do the same with `serverEnv` and `serverSchema`? They recently got aligned to their client equivalent.

**Comment by JacobADevore** [comment]
> Should we do the same with `serverEnv` and `serverSchema`? They recently got aligned to their client equivalent.

done

**Comment by danteissaias** [comment]
This works for me on the server-side but not on the client:

```typescript
import { env } from "../env/client.mjs";

console.log(env);
```

Throws the following error on the client:

```
next-dev.js?c87b:20 ❌ Invalid environment variables:
 NEXT_PUBLIC_URL: Required
 NEXT_PUBLIC_STRIPE_PK: Required
 NEXT_PUBLIC_SANITY_PROJECT_ID: Required
 NEXT_PUBLIC_SANITY_DATASET: Required
 NEXT_PUBLIC_GA_MEASUREMENT_ID: Required
```

**Comment by c-ehrlich** [comment]
> This works for me on the server-side but not on the client:
> 
> ```ts
> import { env } from "../env/client.mjs";
> 
> console.log(env);
> ```
> 
> Throws the following error on the client:
> 
> ```
> next-dev.js?c87b:20 ❌ Invalid environment variables:
>  NEXT_PUBLIC_URL: Required
>  NEXT_PUBLIC_STRIPE_PK: Required
>  NEXT_PUBLIC_SANITY_PROJECT_ID: Required
>  NEXT_PUBLIC_SANITY_DATASET: Required
>  NEXT_PUBLIC_GA_MEASUREMENT_ID: Required
> ```

same for me

**Comment by iduuck** [comment]
The problem here is that Next.js (or better said the compiler) is replacing **explicit** usage of `process.env.SOMETHING` with it's respective values. Accessing through an dynamic accessor isn't going to work. So environment variables are declared on *build time* not *runtime* (like on server).

Though the new env format was introduced since the server variables are also able to be used for middleware (middleware is compiled the same as the front end files though).

**Comment by JacobADevore** [comment]
What about this implementation? https://github.com/JacobADevore/next-validenv

**Comment by iduuck** [comment]
That is the same implementation which is not going to work properly for every case in Next.js

**Comment by danteissaias** [comment]
> The problem here is that Next.js (or better said the compiler) is replacing **explicit** usage of `process.env.SOMETHING` with it's respective values. Accessing through an dynamic accessor isn't going to work. So environment variables are declared on _build time_ not _runtime_ (like on server).
> 
> Though the new env format was introduced since the server variables are also able to be used for middleware (middleware is compiled the same as the front end files though).

So this prevents you from mixing implicit/explicit usage of environment variables?

**Comment by juliusmarminge** [comment]
> @juliusmarminge That's an awesome way, however, with this solution, we would have the same object type for client and server. And no linter or anything to tell us, that the server variables are not available on the client.

Yea I know - and that was sort of the goal, minimising the amount of different objects that the users have to think about. Although I get that we're now "lying" that the types are defined on the client even for server-vars and the app won't crash, just return undefined.

This is definitely a tradeoff and I'm not sure what's the best...

**Comment by iduuck** [comment]
My personal opinion on this is, that I would like to see more "explicitness" instead of "implicitness", but then also a little blindness of the user, when and where to use the variable.

**Comment by juliusmarminge** [comment]
> My personal opinion on this is, that I would like to see more "explicitness" instead of "implicitness", but then also a little blindness of the user, when and where to use the variable. And where the user can use the variable.

I'm thinking that we'd need to modify the object and the `get()` method in some way and check the name of the var and the typeof window and throw accordingly. You think this is possible?

**Comment by iduuck** [comment]
HAHA, that's awesome, just finished a proxy implementation. on my fork: https://github.com/iduuck/t3-env.git

**Comment by juliusmarminge** [comment]
Simplified it a bit. I don't think we need to run each access through the schema since that should already be done? Just a simple server-check should do it?

https://github.com/juliusmarminge/t3-env/blob/main/src/env.mjs
