### ISSUE TITLE
feat: add japanese translation

### ISSUE THREAD

**Issue by neko-kawaii-nyan** [t3-oss/create-t3-app#1072]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like to see

Add japanese (ja) translation of the brand new [create.t3.gg](https://create.t3.gg/) documentation

### Describe alternate solutions

n/a

### Additional information

Because I am new to t3, I would like someone to translate it. 
But if there is no one to assign, I will do it. 
And, if any other contributor already started this, I'll be happy to review the PR.

**Comment by juliusmarminge** [comment]
To keep issues clean we keep translation discussion in Discord or in draft PRs.

**Comment by c-ehrlich** [comment]
Nobody has started translating the docs into Japanese yet. We would be happy if someone can do it.

If you want to get started, take a look at [TRANSLATIONS.md](https://github.com/t3-oss/create-t3-app/blob/next/www/TRANSLATIONS.md), or on [Discord](https://discord.gg/tsdXFkfR) in the `#ct3a-translation` channel. Once the initial PR for a translation has been opened, this becomes the main place to discuss that translation :)

**Comment by c-ehrlich** [comment]
> @c-ehrlich I'll do it.

There's a draft PR open for a Japanese translation, but it only has one page translated so far: https://github.com/t3-oss/create-t3-app/pull/1086

I don't know if you can work on their branch, depends on how they have their own clone of the repo set up.

So far every other language was translated by two or more people together, who could review each other. Would be great if that can happen for Japanese as well :)
