### ISSUE TITLE
feat: Rename `prisma` to `db`

### ISSUE THREAD

**Issue by NiklasBurggraaff** [t3-oss/create-t3-app#1077]
### Is your feature request related to a problem? Please describe.

With the new folder structure from https://github.com/t3-oss/create-t3-app/pull/934 the `trpc` variable was renamed `api`.

Copilot autocompleted with the following `ctx.db.example.findMany()` in a tRPC procedure, which made me think could `prisma` also be renamed to something "abstracting" away that it is prisma?

### Describe the solution you'd like to see

Rename the `prisma` variable in `src/server/db.ts` to `db` and the `prisma` attribute in the return of `createInnerTRPCContext` in `src/server/api/trpc.ts`.

### Describe alternate solutions

Keep the `prisma` variable name

**Comment by c-ehrlich** [comment]
I'm leaning against this because it's called `prisma` everywhere in the Prisma docs. One of our main heuristics when deciding this stuff is that if we do something different than the docs of the libraries we use, we better have a **very** good reason for that.

**Comment by NiklasBurggraaff** [comment]
> I'm leaning against this because it's called `prisma` everywhere in the Prisma docs. One of our main heuristics when deciding this stuff is that if we do something different than the docs of the libraries we use, we better have a **very** good reason for that.

That makes sense.

Just out of curiosity, what was the reason that trpc was renamed then.

**Comment by c-ehrlich** [comment]
> > I'm leaning against this because it's called `prisma` everywhere in the Prisma docs. One of our main heuristics when deciding this stuff is that if we do something different than the docs of the libraries we use, we better have a **very** good reason for that.
> 
> That makes sense.
> 
> Just out of curiosity, what was the reason that trpc was renamed then.

Many users were confused by the boilerplate, one reason was that there were too many things named trpc

And there might be some docs changes on tRPC side coming soon ;)
