### ISSUE TITLE
next-auth: better env.example

### ISSUE THREAD

**Issue by wlechowicz** [t3-oss/create-t3-app#108]
**Is your feature request related to a problem? Please describe.**
When choosing to use next-auth, the generated .env-example file does not include config values template of things typically used with next-auth, which leads to warnings when running the app.

**Describe the solution you'd like**
When next-auth is selected, .env-example files should include `NEXTAUTH_SECRET=` and `NEXTAUTH_URL` as memos to teach and/or remind users that these need to be set up.

**Describe alternatives you've considered**
While console warnings such as `[next-auth][warn][NEXTAUTH_URL]` and `[next-auth][warn][NO_SECRET]` might be considered a "good enough" alternative, this app already includes required config keys in .env-example for Prisma (even when user does not opt in on Prisma!) and Github.

**Comment by juliusmarminge** [comment]
NEXTAUTH_URL is only for production (right?) so no need to include it in a dev .env-example.

**Comment by wlechowicz** [comment]
It's the secret that will sort of work in dev but will not in prod (they auto-generate a secret for dev).
The URL should be set always, but for things like Vercel previews and Vercel deployments, it will use VERCEL_URL.
https://next-auth.js.org/warnings#nextauth_url
https://next-auth.js.org/warnings#no_secret
https://next-auth.js.org/configuration/options#secret
The last one lists all the reasons why should not depend on the auto secret generation and that it will be removed, and it boggles my mind why they would ever come up with something like that in the first place.

**Comment by juliusmarminge** [comment]
Oh right. You dont need it with Vercel was probably what I was thinking about.

Add 2 rows to the .env-example then. I dont think we need to parametrize it or autogenerate a secret to use. The file is an example and it is up to the user to set their own secrets.

**Comment by juliusmarminge** [comment]
Oh right. You dont need it with Vercel was probably what I was thinking about.

Add 2 rows to the .env-example then. I dont think we need to parametrize it or autogenerate a secret to use. The file is an example and it is up to the user to set their own secrets.

**Comment by wlechowicz** [comment]
I totally agree that generating a secret goes too far beyond scaffolding so it's not a concern of this app.

**Comment by juliusmarminge** [comment]
Closed by #114
