### ISSUE TITLE
feat: Add an example of server side call in initial rollout

### ISSUE THREAD

**Issue by CR1AT0RS** [t3-oss/create-t3-app#1080]
### Add ServerSide call in T3-App as an example.

I think it would be helpful to show an example of a server side call. Calling a procedure within Trpc router from another function.
Example: 
````
import { env } from '@/env/server.mjs'
import { router, protectedProcedure, publicProcedure } from '@/server/trpc/trpc'
import { z } from 'zod'
````
````
export const stripeRouter = router({
  getOrCreateCustomer: protectedProcedure.query(async ({ ctx }) => {
    const { stripe, session, prisma } = ctx

    // create a new customer
    const customer = await stripe.customers.create({
      email: user.email ?? '',
      metadata: {
        userId: session.user.id,
      },
    })
      return updatedUser.stripeCustomerId
  }),
  
    createSubscription: protectedProcedure
    .input(
      z.object({
        priceId: z.string(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const { stripe, session, prisma, req, res } = ctx

      // TRPC server calls
      const authorizedCaller = stripeRouter.createCaller({
        req: req,
        res: res,
        prisma: prisma,
        stripe: stripe,
        session: session,
      })
      const customerId = await authorizedCaller.getOrCreateCustomer()

      if (!customerId) {
        throw new Error('Could not create customer')
      }

      // Create Subsciption and return the subscriptionId

        return { subscriptionId: subscription.id }
 
    }),
````

### Describe the solution you'd like to see

Would like to see an example protectedProcedure making a server side call. I don't think my code is the ideal way to do it. Also looking for suggestions. According to TRPC doc its supposed to be done like this: https://trpc.io/docs/server-side-calls

### Describe alternate solutions

Not sure about alternatives.

**Comment by c-ehrlich** [comment]
This is a similar issue as https://github.com/t3-oss/create-t3-app/issues/1079, but this specific example is way too specific to include in the boilerplate. That's what tRPC docs are for.

Your code looks ok, although the caller could probably be simplified by using [inner and outer context](https://trpc.io/docs/context#inner-and-outer-context) to avoid having to pass so much stuff to it.

**Comment by juliusmarminge** [comment]
Seems similar to this: https://github.com/trpc/trpc/issues/3548

Maybe we need to emphasise this in the tRPC docs but `createCaller` "should not" be used inside procedures since it is pure overhead to create context and run through the middleware-chain since you've already done that when you get to the procedure. Instead, extract the logic out into a normal function and call that function in the procedures which uses it

**Comment by juliusmarminge** [comment]
Example of your use-case:

![CleanShot 2023-01-15 at 11 06 58](https://user-images.githubusercontent.com/51714798/212534850-8c4ed918-0d50-4317-8962-0747bf0723b9.png)

**Comment by CR1AT0RS** [comment]
> Example of your use-case:
> 
> ![CleanShot 2023-01-15 at 11 06 58](https://user-images.githubusercontent.com/51714798/212534850-8c4ed918-0d50-4317-8962-0747bf0723b9.png)

Thank you this was helpful!
