### ISSUE TITLE
feat: add `Next-ValidEnv` for typesafe environment variables

### ISSUE THREAD

**Issue by JacobADevore** [t3-oss/create-t3-app#1083]
### Is your feature request related to a problem? Please describe.

I created a package called 'Next-ValidEnv', which allows the streamlining of creating typesafe environment variables in Next.js.

https://github.com/JacobADevore/next-validenv

### Describe the solution you'd like to see

Remove the 'env' folder and follow the 'Next-ValidEnv' installation.

### Describe alternate solutions

If create-t3-app wants to rely on something other than a package, I also made it extremely easy to implement this standard manually. (benefit of depending on the package is for monorepos, there is no copy-pasting + logic is abstracted away)

**Comment by juliusmarminge** [comment]
See https://github.com/JacobADevore/next-validenv/pull/2 why this breaks on our setup

**Comment by c-ehrlich** [comment]
I'd also say just in general that I'm hesitant to add external packages to the template, even when they're maintained by contributors - each package is a liability, and we've had enough examples of minor versions breaking stuff in the last few months as is. Doesn't mean we should never do it, just that we should be very careful about it.

**Comment by juliusmarminge** [comment]
Given the way this conversation is going on discord I think we can further discuss any progress in #404
