### ISSUE TITLE
Supabase Auth Integration 

### ISSUE THREAD

**Issue by rdylina** [t3-oss/create-t3-app#1087]
### Is your feature request related to a problem? Please describe.

NextAuth, now known as AuthJS is great but wrapping other full fledged auth providers in it seems like bad practice, ex Supabase auth. 

### Describe the solution you'd like to see

It would be great if Supabase Auth was available as a pre integrated auth choice. I know some people will say, just wrap it with NextAuth, now known as AuthJS. And that would make sense if Supabase Auth wasn't a full fledged auth solution. 

Wrapping a full auth provider inside a full auth provider just feels like bad practice to me from both a design principle and an overhead perspective. So in short I would just really love to see it be a native option that can be selected in lieu of AuthJS. 

Further, utilizing Supabase Auth provides a tighter and easier integration for things that I use like row level security policies without having to replicate data from AuthJS over to Supabase auth.

### Describe alternate solutions

If it is determined for some reason that it makes sense to wrap Supabase auth with AuthJS, then it would be nice if there was a premade integration that also automatically replicated the auth data into Supabase auth schema to make row level security policies as easy to implement as though you were using their native auth schema.

**Comment by juliusmarminge** [comment]
Our current recommendation for auth is using NextAuth.js so we won't add a Supabase Auth integration by default.

If that's what you like to use, just don't select NextAuth and add Supabase yourself - after all this stack is modular at its core and you pick only the pieces you like.
