### ISSUE TITLE
Next-auth 'secret' key missing

### ISSUE THREAD

**Issue by barrybtw** [t3-oss/create-t3-app#109]
**Next-auth 'secret' key missing.**
Whenever you start a t3 application with next-auth and start it up, in development it will keep yelling in console that you're missing a 'secret' key.

**Solution**
I thought it might be possible to generate a 504-bit WPA Key or something during build time and just built it into the config or .env file? What do you think

**Comment by wlechowicz** [comment]
I don't think generating a secret for the user is a good idea, that's the bit of configuration they have to do themselves. I was thinking more about a reminder that they need to do it and helping them figure out where it needs to be done, in #108

**Comment by juliusmarminge** [comment]
Implemented in #114
