### ISSUE TITLE
bug: error - ReferenceError: Cannot access 'createTRPCRouter' before initialization

### ISSUE THREAD

**Issue by nimeshvaghasiya** [t3-oss/create-t3-app#1093]
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 3.85 GB / 11.87 GB
  Binaries:
    Node: 16.16.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.14.0 - ~\AppData\Roaming\npm\npm.CMD

### Scaffolded app version
v7.3.1

### Describe the bug

I'm using nextauth signIn callback, and need to write some logic there, logic requires to use trpc router procedures.

```
....
const ctx = await createInnerTRPCContext({ session: null });
const caller = appRouter.createCaller(ctx);
const permissions = await caller.role.getAllPermissions();
....
```
So when I use as per above It throws error as per in title, If I have comment out above lines it works perfectly.

### Reproduction repo

https://github.com/nimeshvaghasiya/t3routererror

### To reproduce

Steps to reproduce error:

- Clone above repository, do npm install then npm run dev
- Click on "Roles"
- Click on "Sign in" button : throws error
- If you comment out signin callback, there will be no error.

Please note error comes randomly so might need jump between roles page and back to home page, and click "Sign in" button.

**Comment by juliusmarminge** [comment]
Not entirely sure what this is if I'm honest... definitely some weird and flaky behavior here...

However I'm starting to think it's not necessarily an issue with our setup since it seems to go away when you remove the JWT stuff too...

I've only used the JWT strategy once before I think so not quite sure of the limitations there, but I think there could be some stuff conflicting there, for example, this error shows up when using JWT but not without:

![CleanShot 2023-01-17 at 22 13 50](https://user-images.githubusercontent.com/51714798/213013715-0cb63432-652d-40f5-b254-ffcdab0c6a4d.png)

and the `error - ReferenceError: Cannot access 'createTRPCRouter' before initialization` also goes away when removing the JWT callback + strategy.

**Comment by nimeshvaghasiya** [comment]
@juliusmarminge I have removed JWT and changed strategy, error is still there. I have committed changes to reproduction repo.
Here is a recorded screen [createTRPCRouterError.webm](https://user-images.githubusercontent.com/6048622/213109314-6d717c06-6d2f-46b2-a27a-0ea3a5c30374.webm)

**Comment by nimeshvaghasiya** [comment]
@juliusmarminge I found more on this, If you set esmExternals to false, It works somewhat on client side and not throwing console errors. but on serverside it still logs same error on vs code terminal.
`  experimental: {
    esmExternals: false
  }
` 

may be something related to circular dependency - [webpack-issue](https://github.com/webpack/webpack/issues/12724)

**Comment by juliusmarminge** [comment]
Ok I can actaullt still repro this...

Fixed by pulling the context part of the trpc.ts file out to it's own context.ts file - not sure why that helped though....

**Comment by juliusmarminge** [comment]
It could also be a thing which only happens in the nextauth file cause you got circular deps between the session part

**Comment by juliusmarminge** [comment]
fwiw, I'm not sure i would do it like you do it here, you can just create a separate function and get the user's permission using the parameters you get back from the callback:

```ts
// somewhere
import { prisma } from "~/server/db";
export async function getPermissionsForUser(userId: string) {
  const perms = await prisma.permissions.findXXX
  // ...
}

// [...nextauth].ts
import { getPermissionsForUser } from "somewhere";

export const authOptions: NextAuthOptions = {
  // Include user.id on session
  callbacks: {
    async signIn({ user, account, profile, email, credentials }) {
      const permissions = await getPermissionsForUser(user.id);
      return permissions.includes("admin"); // or whatnot
    },
  },
};
```

There's no need for createCaller here as you got all the user info you need so running a bunch of createContext / middlewares / input parsers etc is just redundant work here.

**Comment by juliusmarminge** [comment]
@nimeshvaghasiya did the above fix things for you? If it did we can close this.

**Comment by nimeshvaghasiya** [comment]
> @nimeshvaghasiya did the above fix things for you? If it did we can close this.
will let you know ASAP but today.

**Comment by nimeshvaghasiya** [comment]
@juliusmarminge It did fix the things but by sacrifice for not to use trpc router inside signIn callback (even if I have moved code to separate file and function as below).

> ```ts
> // somewhere
> import { prisma } from "~/server/db";
> export async function getPermissionsForUser(userId: string) {
>   const perms = await prisma.permissions.findXXX
>   // ...
> }
> ```

I.e. I would like to use trpc route procedure from getPermissionsForUser function instead direct prisma query, due to need some zod validation on procedure.

**I have added reproduction code to another branch:** [trpc-context-issue](https://github.com/nimeshvaghasiya/t3routererror/tree/trpc-context-issue)

Hopefully, you would like to identify an issue:

Steps to reproduce:
- npm run dev 
- click on "Roles"
- src\server\api\routers\roleRouter.ts > LINE No: 6 you will always get ctx = undefined. (I have set debugger too)

Code Preview:
```import { createTRPCRouter, protectedProcedure, publicProcedure } from "../trpc";

export const roleRouter = createTRPCRouter({
  getAllPermissions: publicProcedure.query(({ ctx }) => {
    console.log(ctx); // Issue: context got undefined, and below query throws error.
    debugger
    //Note: schema is not updated with permissions table so commented out below query.
    //const permissions = ctx.prisma.permissions.findMany({where: { roleId: ctx.user.id}})
    //return permissions;
    return 'users,other';
  }),
});```

**Comment by juliusmarminge** [comment]
Yea so what I think is happening here is that when you call the tRPC procedures, createContext will be run. The createContext will then go and grab the session by calling unstable_getServerSession which will pull in the authOptions - where you try and use the router and create context again.

This causes circular deps and will trigger the `used before instantiated` error you're getting.

> I.e. I would like to use trpc route procedure from getPermissionsForUser function instead direct prisma query, due to need some zod validation on procedure.

`createCaller` can be a pitfall and cause some issues on its own. I've seen a lot of people getting into problems when trying stuff like this (see https://github.com/t3-oss/create-t3-app/issues/1080 https://github.com/trpc/trpc/issues/3548 & https://github.com/trpc/trpc/pull/3623 among others...). What is the reason you would like to call the function through tRPC? You want to see what permissions the user has should just be a prisma call like in my example above.

**Comment by juliusmarminge** [comment]
Made a PR to your repro with how I'd structure it: https://github.com/nimeshvaghasiya/t3routererror/pull/1

**Comment by nimeshvaghasiya** [comment]
@juliusmarminge Thanks a lot!
What is the reason you would like to call the function through tRPC? 
== Reason was code reusability and all database queries should run through trpc routes only(where I was wrong), but now understand another way to achieve same.

Below is a reason, you should not use createCaller OR use createCaller as min as you can. **May be we can improve the doc [here](https://create.t3.gg/en/usage/trpc#expose-a-single-procedure-externally).**
> There's no need for createCaller here as you got all the user info you need so running a bunch of createContext / middlewares / input parsers etc is just redundant work here.

**Comment by bhuynhdev** [comment]
Ran into this same issue today, but with the `CredentialsProvider`. I attempted to use my
```
async authorize(credentials, req) {
   const authCaller = authRouter.createCaller({
     session: null,
     prisma: prisma,
   });
   if (!credentials) {
     return null;
   }
   // tRPC call here
   const user = await authCaller.signIn(credentials);
   // If no error and we have user data, return it
   if (user) {
     return user;
   }
   // Return null if user data could not be retrieved
   return null;
 },
}),
```

in the `authorize` function of the `CredentialsProvider`, but ran into the referernce error. I could make a separate db call as shown above, but now I would need to parse/validate the input data manually, and I would prefer to let `tRPC` handle that for a more centralized code convention. But seems like it is not achievable.

**Comment by qwalker8408** [comment]
this happened for me when you have have 2 routers from app router, and in one of the routers you invoke another routers method. That error occurs, speaks to what julius was saying, the circular dependency kicks in because they both originate and are defined from the same place. I solved this by using a server action and invoking the seperate routers methods like a chain dependency thingy in that action. if that makes sense :(

**Comment by dir** [comment]
Just ran into a similar version of this issue.

I called one of my routes from my credentials provider using the trpc server client, and it caused all trpc/react queries to fail with this error, server still worked fine though.
