### ISSUE TITLE
bug: Starting with create-t3-app and trying `app` leads to 404

### ISSUE THREAD

**Issue by leerob** [t3-oss/create-t3-app#1096]
### Provide environment information

N/A

### Describe the bug

Hey, just a heads up – there is currently an open bug in Next.js for folks trying out the `app` directory (beta) as follows: if you are using `i18n` configuration inside of `next.config.js`, _and_ the `app` directory, you will see a 404 when routing to your index route.

This is a bug. The `i18n` routing configuration inside `next.config.js` is not being ported to `app`. You can view the documentation for [i18n routing here](https://beta.nextjs.org/docs/guides/internationalization). To make sure you can incrementally adopt from `pages` -> `app`, or to have them coexist for awhile, we will be fixing this bug.

But at least for now, I just wanted to make y'all aware.

### Reproduction repo

N/A

### To reproduce

Stated above.

**Comment by leerob** [comment]
Related issue: https://github.com/vercel/next.js/issues/41980

**Comment by nayaabkhan** [comment]
> To make sure you can incrementally adopt from pages -> app, or to have them coexist for awhile, we will be fixing this bug.

Thanks for the heads-up @leerob. Do you know what would be the behaviour after the fix?
- Would `i18n` have no effect on the routes inside the `app` directory? or
- Would locale be mapped to the `app/[locale]` folder? or
- Something entirely different?

This may help us who are facing this issue proceed development with correct assumptions while we wait for the fix.

**Comment by leerob** [comment]
`18n` will exist, but only affect routes inside of the `pages` directory 👍
