### ISSUE TITLE
bug: Selector for inline code elements does not work

### ISSUE THREAD

**Issue by fulopkovacs** [t3-oss/create-t3-app#1100]
### Provide environment information

 System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.82 GB / 32.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.2.0 - ~/.local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm

### Describe the bug

The following lines are supposed to return a list of the `code` nodes that are not the children of a `pre` node (`www/src/components/docs/pageContent.astro`):

```typescript
    const notACodeBlock = ":not(pre) code";
    const codeElements = document.querySelectorAll(notACodeBlock);
```

The problem is that `:not(pre) code` seems to select every `code` element on the page.

### Reproduction repo

https://create.t3.gg/en/usage/prisma

### To reproduce

 Try to run this code snippet in the dev console on the https://create.t3.gg/en/usage/prisma page:
```typescript
Array.from(document.querySelectorAll(':not(pre) code')).filter(e => e.parentNode.parentNode.nodeName === 'PRE')
```
I get 2 `code` elements inside of `pre` elements as a result:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/43729152/213416670-f980a013-6d43-47e0-8611-0b7d260f8373.png">

### Additional information

I don't know if this problem can be solved with CSS. Personally, I'd do something like this:

```typescript
   const codeElements = Array.from(document.querySelectorAll("code")).filter((codeElement) => codeElement.parentNode?.nodeName !== "PRE");
```

Happy to send a PR if this solution is acceptable! ☺️

**Comment by c-ehrlich** [comment]
Fixed by https://github.com/t3-oss/create-t3-app/pull/1099 and https://github.com/t3-oss/create-t3-app/pull/1102 :)

**Comment by fulopkovacs** [comment]
#1099 was a quickfix by me, but #1102 made it redundant (they applied the `.code-wrapper` class to the code wrapper `div`-s, which correctly sets the `position` CSS property to `inline`), but also broke the styling of the code blocks (`code` elements inside of `pre`), because of the broken selector:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/43729152/213676536-a1d58487-f8b0-4890-91d4-f496d503ea37.png">

https://create.t3.gg/en/usage/prisma#seeding-your-database

This part still selects **all** code blocks (including the children of `pre` elements) and applies the `.code-wrapper` class to them, hence the light background and double border:

```typescript
    const notACodeBlock = ":not(pre) code";
    const codeElements = document.querySelectorAll(notACodeBlock);
```

#1102 is a good fix to the issue it addressed btw, the selector is the faulty one here. ☺️
