### ISSUE TITLE
refactor: change process.env.VERCEL to process.env.VERCEL_URL in serverSchema

### ISSUE THREAD

**Issue by xoldyckk** [t3-oss/create-t3-app#1108]
### Is your feature request related to a problem? Please describe.

Zod validation object for serverSchema makes use of both **VERCEL** and **VERCEL_URL** environment variables for checking whether the user is deploying their app on **vercel** to preprocess the default value for **NEXTAUTH_URL** environment variable. Two files named **with-auth-prisma.mjs** and **with-auth.mjs** make use of this. Path to the files is this:-  _cli/template/extras/src/env/schema/_

This is what it currently looks like:-

![current](https://user-images.githubusercontent.com/82873939/213777352-2cae8be2-d6f4-41dd-b398-fdf40293da9a.png)

### Describe the solution you'd like to see

The environment variable **VERCEL** should be replaced by **VERCEL_URL** so that the **vercel** environment check works only against **VERCEL_URL** thus making serverSchema look more consistent.

This is what it should look like:-

![new](https://user-images.githubusercontent.com/82873939/213777544-36114ba3-8d01-407a-b5ce-92574ab0a5de.png)

### Describe alternate solutions

Nope

### Additional information

I have the changes ready for pull request just need your confirmation.

**Comment by juliusmarminge** [comment]
We could although it doesn't make a difference.
