### ISSUE TITLE
feat: Out of the box SVGR support

### ISSUE THREAD

**Issue by ahkhanjani** [t3-oss/create-t3-app#1111]
### Is your feature request related to a problem? Please describe.

I think the title says it all. Currently Next.js doesn't give any types for SVGs whatsoever and we also need to deal with Webpack config. SVGs shouldn't be so complicated.

### Describe the solution you'd like to see

Implement SVGR with best practices or an alternative.

### Describe alternate solutions

.

**Comment by c-ehrlich** [comment]
What advantages does SVGR give over just using next/Image?

**Comment by ahkhanjani** [comment]
> What advantages does SVGR give over just using next/Image?

SVGs are not images so they shouldn't be treated like one. They're like any other HTML tag that can be put into a React component. SVGR does exactly that. next/Image also requires an 'alt' that has no meaning for an icon inside a button. SVGs also don't need optimization or any of the utilities next/image provides. The code is also way more readable:

```javascript
import MyIcon from '../../public/my-icon.svg';

return (
  <button>
    <MyIcon />
  </button>
);
```

Compared to:

```javascript
import Image from 'next/Image';
import myIcon from '../../public/my-icon.svg';

return (
  <button>
    <Image src={myIcon} alt='My icon' />
  </button>
);
```

Nx also has an implementation commented in the config file. Just by uncommenting it you can use SVGR.

**Comment by zeeket** [comment]
> What advantages does SVGR give over just using next/Image?

- With SVGR you don't need to put 
` images: { dangerouslyAllowSVG: true, contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;"},` 
Into `next.config.mjs` to be able to serve SVGs. 

- next/Image never optimizes SVGs.  

- Next/image doesn't support custom fill colors for SVG, but SVGR does.

**Comment by PiotrekPKP** [comment]
The implementation is pretty easy if I'm not mistaken. You just use one svg loader: https://react-svgr.com/docs/webpack/.
I'm not sure how many of us would actually want to use svgs in our apps that often

**Comment by juliusmarminge** [comment]
I always just take my svgs and pop them in a react component:

```ts
export function MyIcon(props: ComponentProps<"svg">) {
  return (
    <svg {...props}>
      <path />
    </svg>
  );
}
```

**Comment by c-ehrlich** [comment]
I understand that this way of loading SVGs is better, but still leaning no on this.

reasons:
- iirc we currently don't mess with the webpack config at all. it would take something more important to convince me that we should start doing so
- will people even use this / know that it's there? its not really obvious unless you go looking in the webpack config. maybe it's better if they figure it out themselves once they need it.

from what I can tell, create-react-app, which is now paying for the decision to say yes to everything, includes this. but for example create-next-app doesn't.

**Comment by ahkhanjani** [comment]
> The implementation is pretty easy if I'm not mistaken. You just use one svg loader: https://react-svgr.com/docs/webpack/.
> I'm not sure how many of us would actually want to use svgs in our apps that often

The problem I issued was that Next intentionally blocks types for SVGR:
`Use any to avoid conflicts with @svgr/webpack plugin or babel-plugin-inline-react-svg plugin.`

I believe this comes from the line `/// <reference types="next/image-types/global" />` in the `next-env.d.ts` file and [exists since Next 11](https://duncanleung.com/next-js-typescript-svg-any-module-declaration/).

For utilizing TypeScript with Next which I believe is part of the reason this stack exists I think at least the option to do that would be convenient. Custom SVGs are pretty common.

> If i dont use an icon package I always just take my svgs and pop them in a react component:

Complex SVGs contain tens to a few hundreds of lines of code. Also they belong to a `.svg` file not `.js`; unless we want reactivity which is a niche case.

> * iirc we currently don't mess with the webpack config at all. it would take something more important to convince me that we should start doing so

That's understandable. Although I believe the only place we're manipulating the config is this part in `next.config.mjs`:

```js
 webpack(config) {
    config.module.rules.push({
      test: /\.svg$/i,
      issuer: /\.[jt]sx?$/,
      use: ['@svgr/webpack'],
    });
    return config;
  };
```

This is the entire configuration needed for SVGR. Users who add this will take the responsibility of  the Webpack configuration. If it's an option it won't affect people who don't use it.

> * will people even use this / know that it's there?

Nx has a good approach to this. This is the default `@nrwl/next` Next config file:

```js
const { withNx } = require('@nrwl/next/plugins/with-nx');

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  nx: {
    // Set this to true if you would like to to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },
};

module.exports = withNx(nextConfig);
```

I'm not sure if they include types for it though.

> * its not really obvious unless you go looking in the webpack config.

There is no Webpack config file in the project. Just the part in the Next config.

> * maybe it's better if they figure it out themselves once they need it.

The problem we have is the `any` type on SVGs.

> from what I can tell, create-react-app, which is now paying for the decision to say yes to everything, includes this. but for example create-next-app doesn't.

I don't think that's a good argument since the problem _is_ Next's forced any type on SVGs and types are actually what I'm asking for. Also as I mentioned something like Nx does include SVGR and is still a powerful tool.

Best regards

**Comment by gcavanunez** [comment]
Perhaps something to add to the docs, instead of taking a hard stance? 

I know I've hit this in the past when working with a designer, and the having to create a component per svg vs importing the svg and it being handled automatically as a component, was a nice dx improvement.

**Comment by dBianchii** [comment]
I like this idea

**Comment by jonbergan** [comment]
+1 to this also or at least adding it to the docs as a reference.

**Comment by juliusmarminge** [comment]
Maybe a docs addition could be in order but I don't see this as something required by default.

I personally prefer just inlining the svg in a JSX component with the same props as the icons coming from my icon package of choice

**Comment by phoneticallySAARTHaK** [comment]
> ... having to create a component per svg vs importing the svg and it being handled automatically as a component, was a nice dx improvement.

This should be supported by default
