### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by ebg1223** [t3-oss/create-t3-app#1112]
### Provide environment information

System:
OS: macOS 13.0.1
CPU: (10) arm64 Apple M1 Pro
Memory: 138.64 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 18.11.0 - /opt/homebrew/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 8.19.2 - /opt/homebrew/bin/npm
Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
Browsers:
Chrome: 109.0.5414.87
Safari: 16.1
npmPackages:
@tanstack/react-query: ^4.20.0 => 4.22.3
@trpc/client: ^10.8.1 => 10.9.0
@trpc/next: ^10.8.1 => 10.9.0
@trpc/react-query: ^10.8.1 => 10.9.0
@trpc/server: ^10.8.1 => 10.9.0
next: 13.1.2 => 13.1.2
react: 18.2.0 => 18.2.0
typescript: ^4.9.4 => 4.9.4

### Describe the bug

When defining a procedure, if input is present such as using procedure.query(({ctx, input}) => {return a}), autocomplete does not work for objects that are returned by the inner function.

Example shows multiple test cases, what works, and what doesn't. To reproduce, leave the return value present, and delete the inner const createdAt=e.createdAt. Replace it with another line(above the return), such as const ca = e.(Autocomplete fails)

### Reproduction repo

https://github.com/ebg1223/t3-test-autocomplete

### To reproduce

See Repo src/server/api/routers/example.ts

input must be present in the parameter deconstruction. Even if it is never used, its presence breaks type resolution. If only ctx is present, everything works fine.

When reproducing, autocomplete works up until the function has a return statement involving the variable. This means when writing the function initially, autocomplete may be fine. It is when going back and inserting / changing code above the return statement that type resolution no longer works. This can be a big potential for new bugs to be introduced and not noticed.

### Additional information

Posted a bug report to TRPC repo as well, but not sure if this is related to t3-app. If this is a tRPC problem only, feel free to close.

**Comment by ebg1223** [comment]
Link to tRPC report:
https://github.com/trpc/trpc/issues/3656

**Comment by c-ehrlich** [comment]
Closing for now as this doesn't seem to be reproducible. See comments on tRPC issue.
