### ISSUE TITLE
feat: Ukrainian localisation for the site 

### ISSUE THREAD

**Issue by hslcurry** [t3-oss/create-t3-app#1116]
### Is your feature request related to a problem? Please describe.

Could you please add Ukrainian localization for the main site

### Describe the solution you'd like to see

i18n mapping for the Ukrainian language

### Describe alternate solutions

N/A

### Additional information

Thank you for this project, its an awesome tool

**Comment by c-ehrlich** [comment]
Are you referring to docs or to the website itself?

For docs, nobody on the core team speaks Ukrainian so we are dependent on the community to translate. See https://github.com/t3-oss/create-t3-app/blob/next/www/TRANSLATIONS.md

For the actual website, it doesn't have i18n functionality yet but will hopefully get to this in the coming weeks :)

**Comment by juliusmarminge** [comment]
Closing issue. If anyone wants to pick it up they are free to for any language 🙏🏼

**Comment by pqoqubbw** [comment]
@hslcurry If it's still relevant, you can look at https://github.com/t3-oss/create-t3-app/pull/1756 PR, I made a translation into Ukrainian.
