### ISSUE TITLE
feat: framework agnostic core

### ISSUE THREAD

**Issue by nickmccurdy** [t3-oss/create-t3-app#1119]
### Is your feature request related to a problem? Please describe.

create-t3-app is currently coupled to React as a consequence of using Next for SSR. However, I think there's value in create-t3-app's best practices for full stack TypeScript that don't necessarily need to be coupled to React or Next.

Here are some advantages to supporting multiple framework backends over just React:
- **Migrating** to and from other frameworks
- **Ease of learning** for users and contributors experienced with frameworks
- **Flexibility** of not coupling your project to React and Next, but also not having to switch to an alternative like Vite or Astro that may not have as much type safety
  - One of the things I like about Vite and Astro is knowing I can change my mind later, but as it currently stands if I want to make a Next, Turbopack, or T3 app, I'm forced to choose React
- **Type safety** by using a framework written in TypeScript (Angular/Solid/Svelte/Vue/etc.)
  - Potentially better if you use a framework that doesn't use JSX due to https://github.com/Microsoft/TypeScript/issues/14729
- **Future proofing** by allowing the lifespan of create-t3-app to potentially be longer than React's or Next's

### Describe the solution you'd like to see

For now, I think the easiest way to achieve this would be to refactor some of the internals to use Vite and the [SSR plugin](https://vite-plugin-ssr.com/). This would make SSR support framework agnostic and should make it easy to support Preact, Vue, Svelte, Solid, and Angular. For back compatibility, we would either need to figure out how to bridge the gap between missing/different Next features, or move the current internals into a separate feature flag or plugin package.

### Describe alternate solutions

Turbopack could be an option in the future when it's no longer exclusively supported as a build system for Next.

Alternatively, if this is too high level or out of scope for the T3 maintainers, it could be maintained as a separate project, and create-t3-app could adapt parts of it for Next or React.

**Comment by c-ehrlich** [comment]
There are some Create T3 App-inspired init tools based on other frameworks already
Solid: https://github.com/OrJDev/create-jd-app
Nuxt: http://sidebase.io/
Svelte: https://github.com/zach-hopkins/create-t3svelte-app

These are great, but I think they should remain separate projects. Even when using a similar set of packages other than the framework itself, the codebases end up being so different that I don't see much value in unifying them as one project. It would also multiply (exponentially?) the work we'd need to do - we're often the first project to hit issues in the libraries that we use, which means we need to debug them, open issues, decide what to do in the meantime before it's fixed, etc.

Who knows what the future will bring, but for the foreseeable future we will be tied to Next. That's not the right choice in all cases, but it's a great choice in many cases, and we don't need to be everything for everyone.
