### ISSUE TITLE
fix: JavaScript should not be an option

### ISSUE THREAD

**Issue by nickmccurdy** [t3-oss/create-t3-app#1120]
### Is your feature request related to a problem? Please describe.

Currently the wizard includes a "Will you be using TypeScript or JavaScript?" question, which overrides the answer to TypeScript. I understand this is a bit of a joke, but the additional question could cause confusion or frustration with users that are trying to use JavaScript (for example #117). Also consider that many users of templates are beginners, and every question you ask them adds cognitive overhead that could cause them to quit if they don't understand the decision.

### Describe the solution you'd like to see

I think a better DX would be to simply remove this question from the template, which would better represent that the template is specifically for TypeScript. If you want to be extra explicit, you could still add "Using TypeScript!" somewhere in the log.

### Describe alternate solutions

Keep the question but have it automatically be answered like this:

```
? Will you be using TypeScript or JavaScript? TypeScript
```

This would look similar to what's there now, but still require less user input.

**Comment by nickmccurdy** [comment]
If someone isn't sure if they should learn TypeScript, telling them they should (and possibly that it's the only supported option) is better than telling them they're wrong.

**Comment by dBianchii** [comment]
I like the joke as is, however I can see why it could add confusion to people. In my opinion, if T3 becomes hyper successful (as I think it should), then perhaps one day it would be better to remove the joke. But to be honest, I like it as is

**Comment by c-ehrlich** [comment]
We're going to keep this until it's no longer possible to justify, maybe even a bit longer than that

**Comment by nickmccurdy** [comment]
@c-ehrlich May I ask what the reason/advantage is? I'm a little uncomfortable with recommending create-t3-app to JavaScript users as it stands because of this, which is unfortunate because I think there's an opportunity to give them a friendly invitation to learn TypeScript here.
