### ISSUE TITLE
feat: CODEOWNERS for translation

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#1121]
I would like to set up code owners for the translations. Being a code owner means you get a notification from GitHub when there is a PR with changes to the files of your language, so you can review them. If you want to be a code owner for your language, please reply below.

I've tagged people who have contributed in the past below. I just made this list by skimming through old PRs so I might have missed some people. If you've contributed in the past (writing or reviewing) and I forgot to tag you, or you notice that someone else who contributed to your language is not on the list, please let me know and I will tag them as well.

AR
@a4addel
@Sboonny

FR
@Defranos
@joachimjusth

NO
@estubmo
@josephayman

PO
@matibox
@Infiplaya
@PiotrekPKP

PT
@claudiofreitas
@minsk-dev
@Sn0wye
@victoriaquasar

RU:
@AmadeusTwi
@ronanru
@Yevhenii-Bakhmat

ZH-HANS:
@fernandoxu
@lodisy

**Comment by AmadeusTwi** [comment]
Sure, sign me in!

**Comment by matibox** [comment]
I'm up for it

**Comment by victoriaquasar** [comment]
You can label me, thanks for the invite.

**Comment by a4addel** [comment]
I'm In

**Comment by lodisy** [comment]
count me in

**Comment by PiotrekPKP** [comment]
I'm in

**Comment by Sboonny** [comment]
👍

**Comment by Yevhenii-Bakhmat** [comment]
my mom will be proud of me :)

**Comment by minsk-dev** [comment]
sure

**Comment by Infiplaya** [comment]
me too!

**Comment by josephayman** [comment]
👍

**Comment by Nsttt** [comment]
Add me in for Spanish !

**Comment by chalop** [comment]
I can contribute for spanish! How's the progress on the spanish translation?

**Comment by c-ehrlich** [comment]
So apparently I overpromised as it's not possible to make someone a code owner without also giving them full write access and access to repo secrets, see https://github.com/orgs/community/discussions/29982

I basically trust that everyone here is acting in good faith, but the goal is to have everyone who contributes to a language also become a codeowner (or similar) for that language - contributors in most OSS come and go, and we want translations to stay strong. This would make "fix one typo, become codeowner, delete the repo" an obvious attack vector.

Will go back to the drawing board and try to come up with a different solution. In the meantime it's back to tagging people manually  😅 If anyone knows how other projects handle this, let me know.

**Comment by Sn0wye** [comment]
Totally in

**Comment by estubmo** [comment]
Great! I'll try to find time to update the NO translations soon.

**Comment by fernandoxu** [comment]
Great!👍

**Comment by lodisy** [comment]
@c-ehrlich Please replace this account (@lodisy) with @escwxyz, it would be merged.
