### ISSUE TITLE
bug: GetServerSideProps doesn't pass session as props if it's called session !?

### ISSUE THREAD

**Issue by zanzlender** [t3-oss/create-t3-app#1125]
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 8.42 GB / 15.86 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

When I get the session in GetServerSideProps like this: 

![image](https://user-images.githubusercontent.com/44570474/214844200-8db2746e-1d09-4578-8893-f6d1bcc82b1b.png)

it works normally: 

![image](https://user-images.githubusercontent.com/44570474/214844364-3db28fcf-dbf5-4b85-8468-f0edbd3700a1.png)

However if inside the props object I set the name as *session* 

![image](https://user-images.githubusercontent.com/44570474/214844500-2b5581a6-38f4-43c7-9eda-23a14a57c632.png)

it doesn't get passed into my component:

![image](https://user-images.githubusercontent.com/44570474/214844601-74b258ba-7a55-415f-9ed0-b4ad385e19dd.png)

Am I missing something or has anyone had the same behavior?

### Reproduction repo

-

### To reproduce

Start your normal `npx create-t3-app` with all features.

Try to use GetServerSideProps to pass session in props named session to any component. I tried in /index

### Additional information

Although I don't think it should matter, I use GoogleProvider for login.

**Comment by c-ehrlich** [comment]
Are you calling useSession in the frontend?

https://create.t3.gg/en/usage/next-auth#retrieving-session-server-side

**Comment by juliusmarminge** [comment]
Duplicate #1039.

You don't access the session through props but instead from useSession
