### ISSUE TITLE
feat(RFC): sync example apps to separate repos

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#1126]
### Is your feature request related to a problem? Please describe.

Currently, we have https://t3.new which opens a fresh t3-app in Codesandbox - but it doesn't sync up to new releases.

I'm thinking we could build some apps automatically on each release that would then be subtree'd down to separate repos which could then be forked on CodeSandbox / Stackblitz. It would also make it quite easy to browse how a t3-app looks without needing to run the CLI.

### Describe the solution you'd like to see

I think we'd need to have each app in the main monorepo workspace like `examples/*` and then when we publish new releases, git subtree them down to separate repos so that they are kept up to date.

tRPC does something similar: 
Workspace: https://github.com/trpc/trpc/tree/main/examples/next-minimal-starter
Subtree workflow: https://github.com/trpc/trpc/blob/main/.github/workflows/subtree.yml
Repo: https://github.com/trpc/examples-next-minimal-starter

Then, we could update the `https://t3.new` to accept some query params for what packages you would like to use and it would launch that repo in CodeSandbox/Stackblitz accordingly:

- `https://t3.new?prisma&next-auth`
- `https://t3.new?prisma&trpc&tailwind`
- etc...

### Describe alternate solutions

Technically, we wouldn't need both example workspaces and separate repos - but I'm unsure how to do one without the other? We could only do workspace and launch Stackblitz from the example/* directory - although then they wouldn't have lockfiles which would cause long installation times 🤔 

Open to suggestions on the implementation.

### Additional information

I think we can switch to Stackblitz since the swc issue seems to be fixed there now.

**Comment by harshsinghatz** [comment]
For this we would first have to create different repos for all the individual repositories and then we can git subtree them down right? 
Have we created them yet or is it yet to be created?

**Comment by juliusmarminge** [comment]
> For this we would first have to create different repos for all the individual repositories and then we can git subtree them down right? Have we created them yet or is it yet to be created?

Nope - haven't created them yet but that can be done

**Comment by harshsinghatz** [comment]
I can pick this but repos should be created as i won't have the access to that!

**Comment by juliusmarminge** [comment]
> I can pick this but repos should be created as i won't have the access to that!

Lets try first with just having them in the monorepo and see if we need separate repos for them later?

**Comment by mqshaikh8** [comment]
Hey y'all,
Are you(@harshsinghatz ) taking care of this? I would love to try to work on this too

**Comment by c-ehrlich** [comment]
this is from half a year ago, so feel free to pick it up.

**Comment by mqshaikh8** [comment]
Hey @juliusmarminge ,
Is this kind of what you were expecting? [examples](https://github.com/mqshaikh8/t3_examples. ) . I don't know if I should add more examples or not.Should I host it somewhere?

**Comment by mqshaikh8** [comment]
Hey @juliusmarminge  ,
I created a repo with some examples, Do we want people to have access to the code? I was thinking of making an app that could push people to something like stackblitz so people can have access to the code? Let me know what you think

https://github.com/mqshaikh8/t3_examples

**Comment by juliusmarminge** [comment]
The initial plan was probably to have them generated inside the repo and then we could do stackblitz links like https://stackblitz.com/github/t3-oss/create-t3-app/tree/main/examples/with-drizzle-trpc-tailwind or something

**Comment by mqshaikh8** [comment]
I just wanted to kind of generate a a sample, I am going to fork the repo and create those examples there.

**Comment by mqshaikh8** [comment]
Hi @juliusmarminge,
I created a pull request with the examples. Let me know if there is something I should change. (sorry if the pr is weird, This is my first open source pr)
#1573

**Comment by mqshaikh8** [comment]
Hi @juliusmarminge,
I created a pull request with the examples. It lets people pick the different combinations and view them on stackblitz.
#1576

**Comment by mqshaikh8** [comment]
Can I close this? I am not sure what the process is @juliusmarminge
