### ISSUE TITLE
bug: may not work with Node 18 ?

### ISSUE THREAD

**Issue by bradparks** [t3-oss/create-t3-app#1138]
### Provide environment information

$ npx envinfo --system --binaries

Need to install the following packages:
  envinfo
Ok to proceed? (y) y

  System:
    OS: macOS 13.1
    CPU: (20) x64 Intel(R) Core(TM) i9-10910 CPU @ 3.60GHz
    Memory: 15.15 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.9.1 - ~/Library/pnpm/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/Library/pnpm/npm
    Watchman: 2023.01.23.00 - /usr/local/bin/watchman

### Describe the bug

This may not be a real issue, and I'm a newb with modern javascript tooling, so, with that having been said

When I had node 18 installed, I could create ane run an app

$ npm create t3-app@latest

but when I went to signin using discord, I got to an url like so

http://localhost:3000/api/auth/callback/discord

which was 404, so I couldn't signin even after fully configuring discord in .env file

I then saw you mentioned cal.com, and thought I'd look at it, but noticed it suggested I needed node < 17, which I think I misread, lol, but I installed node 17, and then later on went back to my original app I created, and the login link worked now

I created another sample app using create t3-app, and it worked too, by just copying in my .env file

### Reproduction repo

na

### To reproduce

- Create app using node 18
- Try and login using discord
- Gives a 404.

### Additional information

Mostly logging here so it may come up in Google searches, if it's a true issue

**Comment by c-ehrlich** [comment]
Are you referring to the node version used at init time, or when running the app?

> I then saw you mentioned cal.com, and thought I'd look at it, but noticed it suggested I needed node < 17, which I think I misread, lol, but I installed node 17, and then later on went back to my original app I created, and the login link worked now

This seems like you're referring to runtime.

Either way, it definitely works with Node 18:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/8353666/215314344-c8754589-3905-45a3-bae7-37d9037ef991.png">

Closing this for now but feel free to reopen if you have a reproduction repo that works with only some node versions.
