### ISSUE TITLE
bug: does not work on Git Bash

### ISSUE THREAD

**Issue by Zamiell** [t3-oss/create-t3-app#1139]
### Provide environment information

$ npx envinfo --system --binaries
npm WARN exec The following package was not found and will be installed: envinfo@7.8.1

  System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 21.04 GB / 31.93 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\.yarn\bin\yarn.CMD
    npm: 9.3.0 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

Whatever library you are using to generate the prompts does not work on Git Bash for Windows.

![image](https://user-images.githubusercontent.com/5511220/215308196-45fcb036-6cc6-4161-9eaa-5d4c981668ed.png)

Here, no matter what buttons I press, the arrows don't move, and so on.

### Reproduction repo

n/a

### To reproduce

1) Install Windows 10.
2) Install Node JS.
3) Install Git.
4) Open Git Bash.
5) Type `npm create t3-app@latest foo`

### Additional information

n/a

**Comment by royanger** [comment]
`git bash` is horrible, but it works. There is a cursor at the end of the line that you can move up and down. When you select something it doesn't properly highlight/select it. 

```
$ npm create t3-app@latest test
   ___ ___ ___   __ _____ ___   _____ ____    __   ___ ___
  / __| _ \ __| /  \_   _| __| |_   _|__ /   /  \ | _ \ _ \
 | (__|   / _| / /\ \| | | _|    | |  |_ \  / /\ \|  _/  _/
  \___|_|_\___|_/‾‾\_\_| |___|   |_| |___/ /_/‾‾\_\_| |_|


? Will you be using TypeScript or JavaScript? (Use arrow keys)
? Will you be using TypeScript or JavaScript? TypeScript
Good choice! Using TypeScript!
? Which packages would you like to enable? tailwind, trpc
? Initialize a new git repository? (Y/n)

```
You can see from the above I was able to select JavaScript and use arrows and space to select only 'trpc' and 'tailwind' from the list. 

I strongly suggest using the [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701) app. It far exceeds git bash and I am able to easily navigate the menus in the T3 CLI.

**Comment by Zamiell** [comment]
> You can see from the above I was able to select JavaScript and use arrows and space to select only 'trpc' and 'tailwind' from the list.

for the purposes of this issue, i dont think that we should consider "ghost inputs" to be classified as working, as the end-user will obviously have no idea that they are working.

> I strongly suggest using the [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701) app

windows terminal doesn't have any of the bash builtins though (grep, find, sed, less, etc.), so it is basically unusable.

**Comment by royanger** [comment]
> i dont think that we should consider "ghost inputs" to be classified as working

The CLI does work, but the terminal is handling it poorly. Powershell, Command Prompt, Ubuntu Terminal, Developer Command Prompt for VS 2022 and Developer Powershell for VS 2022 all worked fine. 

Also `npx create-remix@latest` and `npm create astro@latest` (and no doubt others) have the same problem. 

`(grep, find, sed, less, etc.` There are ways to do this stuff in Powershell. I also highly recommend Windows Terminal with WSL. However, I don't think this Issue is a place to talk about sed, grep, etc.

**Comment by c-ehrlich** [comment]
This issue seems to exist in both `inquirer` and `prompts`. A good compromise might be to detect git-bash and suggest the user to use something else, similar to what we already do for yarn 2/3 and used to do for node 18.

**Comment by c-ehrlich** [comment]
Both `inquirer` and `prompts`, by far the two most popular packages for building CLI apps in node, are broken in git-bash. We would probably need to fully rewrite the CLI in something else in order to support a terminal that not many people use. A good compromise might be to detect git-bash and suggest the user to use something else, similar to what we already do for yarn 2/3 and used to do for node 18.

**Comment by iAverages** [comment]
> > You can see from the above I was able to select JavaScript and use arrows and space to select only 'trpc' and 'tailwind' from the list.
> 
> for the purposes of this issue, i dont think that we should consider "ghost inputs" to be classified as working, as the end-user will obviously have no idea that they are working.
> 
> > I strongly suggest using the [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701) app
> 
> windows terminal doesn't have any of the bash builtins though (grep, find, sed, less, etc.), so it is basically unusable.

You can use git bash with the built-in terminal to VSC or Windows Terminal and both seem to handle input correctly with the ct3a cli.

I believe the main issue here isn't git bash but instead, the default terminal that git bash uses (MinTTY) which you can change during the installation.

VSC: 
![vscode](https://avrg.dev/oWhGl.png)

Windows Terminal:
![windows terminal](https://avrg.dev/P1Tvs.png)

**Comment by juliusmarminge** [comment]
Seems like no prompt library support this so the best thing we can do is try detecting it and just quitting with a good message - but we wont try working around the prompt libraries and support this
