### ISSUE TITLE
feat: remove @ts-check in favor of checkJs

### ISSUE THREAD

**Issue by Zamiell** [t3-oss/create-t3-app#1149]
From [the docs](https://create.t3.gg/en/faq#why-are-there-js-files-in-the-project):

> Also, all the js files in this project are still typechecked using a @ts-check comment at the top.

Duplicating `@ts-check` on every file violates DRY. It also makes the repository prone to failures when new JavaScript files are created and end-users forget to add the comment to the new file.

I propose that all of the `@ts-check` comments should be deleted and then the `checkJs` compiler flag is turned on. (Unless there is some other specific disadvantage of this that I am not aware of?)

**Comment by c-ehrlich** [comment]
I checked an app outputted by the current version of the CLI. Switching to `checkJs` seems to work (it builds and runs ok), and I think we might have not been fully type checking some of the `.cjs` files in the current setup. 

I'm trying to find potential downsides of this change, and this is the best I can come up with: someone might add a new js file (config for another package, etc) that doesn't have proper typings, and be confused by why TS is finding errors in a JS file. The `@ts-check` on the top of a file would give a clue here. However this doesn't feel like a good enough counterargument to me. We should always err on the side of type safety, and if people want to circumvent it, that's on them.

Do you want to open a PR for this?

**Comment by Zamiell** [comment]
> Do you want to open a PR for this?

Sure, after my other PR goes through.

**Comment by esotuvaka** [comment]
I can make a PR for it while you wait for approval on your other one

**Comment by Zamiell** [comment]
go for it

**Comment by esotuvaka** [comment]
> go for it

Just opened the PR. I put it as a fix rather than feat as I believe it better enforces the typesafety, and should add some futureproofing

**Comment by Zamiell** [comment]
Thanks @esotuvaka.
