### ISSUE TITLE
bug: prettier-plugin-tailwindcss doesn't work with default t3 template

### ISSUE THREAD

**Issue by zanzlender** [t3-oss/create-t3-app#1157]
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 6.56 GB / 15.86 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

I watched Theo's video today about Prettier auto formatting class names. However I never noticed anything changing whenever I used the T3 stack, and even after I tried to make it work it didn't. 

That made me find this article [Prettier autoformat for TS not working](https://dev.to/timo_ernst/prettier-autoformat-for-typescript-not-working-13d8)

In short I made it work by adding a .code-workspace file to override the VSCode settings with this:

```
{
  ...
  "settings": {
     ...
    "[typescript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[typescriptreact]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
  },
}

```

Note the [typescript] and [typescriptreact] settings.

### Reproduction repo

-

### To reproduce

Run ```npx create-t3-app``` and try to see if Prettier formats class names for Tailwind. Doesn't work for me.

### Additional information

I don't know if other people encounter this or if my settings were not good, however I didn't notice until now, If this is common I think the worskpace file should be included in the template as well. FYI Prettier is set as my default formatter in my settings.

**Comment by c-ehrlich** [comment]
If prettier is enabled as your default formatter, it should work out of the box, see video below 

(the `"editor.defaultFormatter": "esbenp.prettier-vscode"` line in `settings.json` corresponds to selecting prettier as the default formatter in the settings ui)

maybe there's something else in your specific settings file that's overriding it?

https://user-images.githubusercontent.com/8353666/215894590-d57d1999-f541-49e9-9b52-bfb7ed8e4e76.mov

**Comment by zanzlender** [comment]
Very interesting... 

https://user-images.githubusercontent.com/44570474/215898872-6d70e176-1439-4692-a517-9cc944d0543f.mp4

**Comment by juliusmarminge** [comment]
> Very interesting... Will try to find the reason but so far no luck...
> 
>  2023-01-31-23-32-15.mp4

You might have conflicting settings somehow? What happens if you put the formatter setting in a `.vscode/settings.json` file in the project?

**Comment by zanzlender** [comment]
I found it. I had some obscure settings set in my OG VSCode settings which I wrote years ago... That would override any other settings I had later on, and they were Synced across all my devices....
