### ISSUE TITLE
feat: page protection

### ISSUE THREAD

**Issue by niikeec** [t3-oss/create-t3-app#1159]
### Is your feature request related to a problem? Please describe.

Not a problem, but might come in handy for users that opt for db auth, if a function was available that redirects if a session doesn't exist.

### Describe the solution you'd like to see

Function that can be used inside server props, which redirects if a session doesn't exist.

### Describe alternate solutions

N/A

### Additional information

I'd be down to file a PR.

**Comment by c-ehrlich** [comment]
Are you talking about a function that DRYs [this pattern](https://next-auth.js.org/configuration/nextjs#in-getserversideprops)? What would this look like?

Either way I'm not sure this is necessary in the template - the more stuff we add there, the less likely people are to find any particular thing. If there is a very elegant way of doing it, maybe in the docs?

**Comment by niikeec** [comment]
That pattern yes.

It would look like this.
```
// auth.ts
export const requireAuth =
  (func: GetServerSideProps) => async (ctx: GetServerSidePropsContext) => {
    const session = await getServerAuthSession(ctx);

    if (!session) {
      return {
        redirect: {
          destination: `/api/auth/signin?callbackUrl=${encodeURIComponent(
            ctx.resolvedUrl
          )}`,
          permanent: false,
        },
      };
    }

    return await func(ctx);
  };
```
And then you would use it like this.
```
// page.tsx
export const getServerSideProps = requireAuth(async () => {
  return { props: {} };
});
```

**Comment by c-ehrlich** [comment]
Makes sense, and seems like a helpful thing to show people. Kind of annoying that the next-auth docs don't have this. I feel like it would be a much better fit for them than for us, we want to avoid "being the docs" for individual libraries as much as possible.

Maybe suggest it over there, and if they decline then we'll include it?

**Comment by niikeec** [comment]
I agree, docs wise it makes much more sense if it's included in their docs. Here I feel like only an implementation would make sense or a mention in docs with a link to it.

**Comment by niikeec** [comment]
Made a PR there. Will update once I get a response.

**Comment by niikeec** [comment]
It's a no from them, as it's (quote) a stylistic opinion.

**Comment by juliusmarminge** [comment]
Do we really want to "provide a solution" here? There are many ways to do this - middlewares, gSSP or on the client to name a few

**Comment by niikeec** [comment]
No need at all. Sorry for wasting your time.
