### ISSUE TITLE
bug: prettier/prettier rule is used

### ISSUE THREAD

**Issue by Zamiell** [t3-oss/create-t3-app#1182]
Is there a particular reason that the `prettier/prettier` ESLint rule is used?
This is not recommended by Prettier and is an anti-pattern AFAIK: https://prettier.io/docs/en/integrating-with-linters.html

If there isn't a particular reason, I can submit a PR that fixes this.

**Comment by bai** [comment]
IIRC this rule is used on CI to ensure we don't have outstanding prettier corrections. Those could be introduced when someone submits a PR and doesn't have prettier installed locally, or uses an editor that doesn't apply prettier on save.

I think prettier's best-practices are way stricter than their real-world usage, plugins like prettier-plugin-tailwindcss (and others) are also considered an anti-pattern but here we are 🤷‍♀️

**Comment by Zamiell** [comment]
> I get that there's prettier --check . but I guess it would just be an extra workflow step to maintain for something that already works?

The idea is that you integrate `prettier --check .` into the existing lint workflow such that the workflow doesn't change. Specifically, if you want to lint the monorepo, you still type the same command that you did before: `turbo lint`

**Comment by Zamiell** [comment]
> plugins like prettier-plugin-tailwindcss (and others) are also considered an anti-pattern

Where's that coming from? I don't see how a plugin that makes prettier work on new file types could be considered an anti-pattern.
