### ISSUE TITLE
feat: folder structure query params

### ISSUE THREAD

**Issue by NiklasBurggraaff** [t3-oss/create-t3-app#1192]
### Is your feature request related to a problem? Please describe.

I set up a project using Create T3 App with just TailwindCSS and tRPC (not NextAuth.js and Prisma). When sharing a link of the folder structure docs page I had to add a note to indicate that team members should unselect NextAuth.js and Prisma in order to for it to match the folder structure of the project.

### Describe the solution you'd like to see

Instead of passing the options selected from `folderStructureForm.astro` to `folderStructureDiagram.astro` through the custom event:

- Have `folderStructureForm.astro` set a query param to indicate the options selected
- Have `folderStructureDiagram.astro` read the query param to determine the options selected.

No query param would indicate all options are selected, which is the default behaviour now. When an option is unselected make the query param contain the selected options.

Having the query param would allow sharing the URL after making a selection such that this can be shared more easily.

### Describe alternate solutions

Potentially the exact behaviour of the query param could be adjusted. For example, add the unselected options, or have the default be that the query param is added containing all the options.

### Additional information

Happy to implement this!

**Comment by c-ehrlich** [comment]
I like this idea, PR for this is welcome :)

IMO it would be best if a plain `https://create.t3.gg/en/folder-structure` (without any query param) continues to link to a page with everything selected as it currently does, ideally without a redirect / changing the url to something longer. `https://create.t3.gg/en/folder-structure&selected=<options>` (or similar, feel free to propose whatever naming you think makes sense) would then do what you are suggesting.

**Comment by esotuvaka** [comment]
I'll take a look. Haven't touched Astro before, but there's no time to learn like the present

**Comment by NiklasBurggraaff** [comment]
> I'll take a look. Haven't touched Astro before, but there's no time to learn like the present 

I've almost finished an implementation for this already

**Comment by esotuvaka** [comment]
> 

Oh nice! Good luck
