### ISSUE TITLE
feat: vscode debugger settings

### ISSUE THREAD

**Issue by Toshimichi0915** [t3-oss/create-t3-app#1193]
### Is your feature request related to a problem? Please describe.

When I create a new project I always have to open a new tab in the browser and google "VSCode debugger Next.js" because VSCode's launch.json is too long to write manually.

### Describe the solution you'd like to see

I want this template to include vscode debugger settings

### Describe alternate solutions

Maybe we can include WebStorm settings as well, or ask which debugger settings you want to generate in the prompt.

### Additional information

Debugging settings for VSCode can be found here: https://nextjs.org/docs/advanced-features/debugging

**Comment by juliusmarminge** [comment]
As long as we don't want to include IDE-specific plugin recommendation, project settings i dont think we should include a debugger either by default

**Comment by drewdelano** [comment]
@juliusmarminge It might be nice to have it documented somewhere, even if it's not included
