### ISSUE TITLE
docs: add note about how to resolve `no-misused-promises` in JSX attributes

### ISSUE THREAD

**Issue by esotuvaka** [t3-oss/create-t3-app#1197]
### Provide environment information

```
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 3900XT 12-Core Processor
    Memory: 8.32 GB / 15.92 GB
  Binaries:
    Node: 19.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
    
"ct3aMetadata": {
    "initVersion": "7.5.1"
  }
```

### Describe the bug

TypeScript ESLint throws this error: "Promise-returning function provided to attribute where a void return was expected." in React Hook Forms handleSubmit function. 

I can't change the library code to return a Promise rather than void, and I believe that React Hook Form's TypeScript configuration they used when building the library was less strict than t3's. 

I'm not alone in this issue, as others in the discord seem to have encountered it with React Hook Forms and likely with other libraries. According to official TS ESLint documentation it is recommended to change the .eslintrc.json config file to include this: 

```json
"rules": {
  "@typescript-eslint/no-misused-promises": [2, {
    "checksVoidReturn": {
      "attributes": false
    }
  }]
},
```

I'll open a PR soon

### Reproduction repo

https://github.com/esotuvaka/change-tracker/blob/main/src/pages/issues/index.tsx

### To reproduce

In this file I'm using react-hook-form, and have the default tsconfig settings that come with create-t3-app. Setting onSubmit={onSubmit} shows the error: 

"Promise-returning function provided to attribute where a void return was expected.eslint[@typescript-eslint/no-misused-promises](https://typescript-eslint.io/rules/no-misused-promises)"

In general, to recreate use the current default tsconfig settings and try to feed a Promise-returning function to one that normally returns void. 

```ts
import { useForm } from "react-hook-form";
import type { Resolver } from "react-hook-form";

type FormValues = {
  title: string;
  description: string;
  environment: string;
};

const resolver: Resolver<FormValues> = async (values) => {
  return Promise.resolve({
    values: !values.title ? {} : values,
    errors: !values.title
      ? {
          title: {
            type: "required",
            message: "This is required.",
          },
        }
      : {},
  });
};

export default function Issues() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<FormValues>({
    resolver: resolver,
  });
  const onSubmit = handleSubmit((data) => alert(JSON.stringify(data)));

  return (
    <section className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-neutral-700 to-black pt-[10vh]">
      <div className="mx-auto h-[90vh] w-4/5 text-5xl text-white">
        <div>
          <h1>Add new issue</h1>
          <form className="flex flex-col" onSubmit={onSubmit}>
            <label>Title</label>
            <input {...register("title")} />
            {errors.title ? <p>{errors.title.message}</p> : <></>}
            <label>Description</label>
            <input {...register("description")} />
            <label>Environment</label>
            <input
              {...register("environment")}
              placeholder="Steps to reproduce the issue"
            />
            <input type="submit" />
          </form>
        </div>
      </div>
    </section>
  );
}
```

**Comment by esotuvaka** [comment]
I'm not sure if this is too opinionated / too unsafe for typesafety. Please give feedback or any other workarounds / solutions you can think of

**Comment by juliusmarminge** [comment]
I think for your use case this is definitely the way - just wondering if this should be the general solution that comes pre-installed 🤔

**Comment by juliusmarminge** [comment]
react-hook-form is saving you here by providing the onError function as the 2nd argument instead of throwing an error if the initial handler fails.

```ts
const onSubmit = methods.handleSubmit(
    (data) => {
      setResult(data);
    },
    (e) => {
      console.error(e);
    }
  );
```

not sure if this is the de-facto standard? if not ignoring these lint-errors could be kinda bad...

**Comment by esotuvaka** [comment]
> I think for your use case this is definitely the way - just wondering if this should be the general solution that comes pre-installed 🤔

Agreed. Maybe instead of a hard change I could add a section to the documentation, possibly in FAQs, that gives recommendations on typescript rules to ignore when using libraries like React-hook-form. Could be a new section like "typescript errors with imported libraries" or something similar, where we list out commonly used 3rd party libraries like react-hook-form and give the appropriate tsconfig / eslint fix or exception to use.

I just wish there was a way to do this without changing the config file. I'll see if I can ask around in Matt Pocock's discord server. Man is a typescript wizard and knows a bunch of weird tricks.

**Comment by juliusmarminge** [comment]
Ref: https://github.com/t3-oss/create-t3-app/pull/1198#issuecomment-1435714843

**Comment by chrishoermann** [comment]
@esotuvaka 
This would definitly be a good addition - took me some time to figure this one out.
> Agreed. Maybe instead of a hard change I could add a section to the documentation, possibly in FAQs, that gives recommendations on typescript rules to ignore when using libraries like React-hook-form. Could be a new section like "typescript errors with imported libraries" or something similar, where we list out commonly used 3rd party libraries like react-hook-form and give the appropriate tsconfig / eslint fix or exception to use.
> 
> I just wish there was a way to do this without changing the config file. I'll see if I can ask around in Matt Pocock's discord server. Man is a typescript wizard and knows a bunch of weird tricks.

**Comment by juliusmarminge** [comment]
will be added when appdir option is merged where we use async stuff
