### ISSUE TITLE
feat: add react-query-devtools

### ISSUE THREAD

**Issue by erfanansari** [t3-oss/create-t3-app#1206]
### Is your feature request related to a problem? Please describe.

I was thinking if it's a good idea to add react query devtools by default in the template, as it can help to debug and inspect fetch requests.

### Describe the solution you'd like to see

Installing `@tanstack/react-query-devtools` package and putting `ReactQueryDevtools` component in the `_app.tsx` file.

### Describe alternate solutions

There is no alternate solution.

**Comment by c-ehrlich** [comment]
We had this discussion a few months ago and decided to add the tRPC logger by default, but leave the RQ devtools for the user to add as this is a one line change. https://github.com/t3-oss/create-t3-app/issues/329

**Comment by juliusmarminge** [comment]
It is a nice thing to have and even though it is a one-line addition might be worth it just for educational purposes?

**Comment by erfanansari** [comment]
I can create a PR for it if you are okay with it.
