### ISSUE TITLE
T3 - Importing router from `../trpc`

### ISSUE THREAD

**Issue by mxcdh** [t3-oss/create-t3-app#1208]
### Provide environment information

I am using t3-oss https://github.com/t3-oss.
In latest version of t3, when I want to create a new router and want to import {router} from trpc, I have error:
```
import { router, publicProcedure, protectedProcedure } from "../trpc";

```
Module '"../trpc"' has no exported member 'router'.ts(2305)

I checked the trpc documentation, and {router} should include the `trpc.ts' file. -> https://trpc.io/docs/router

What should I do? When is router in T3?

### Describe the bug

Module '"../trpc"' has no exported member 'router'.ts(2305)

### Reproduction repo

Module '"../trpc"' has no exported member 'router'.ts(2305)

### To reproduce

Module '"../trpc"' has no exported member 'router'.ts(2305)

### Additional information

Module '"../trpc"' has no exported member 'router'.ts(2305)

**Comment by PiotrekPKP** [comment]
It's called `createTRPCRouter` in T3 App
