### ISSUE TITLE
bug: New t3 project eslint does not work correctly

### ISSUE THREAD

**Issue by StringKe** [t3-oss/create-t3-app#1210]
### Provide environment information

```
  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.70 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
```

### Describe the bug

New t3 project eslint does not work correctly

eslint always prompts this error, in a different file.

Cannot read properties of undefined (reading 'type')

### Reproduction repo

https://github.com/StringKe/t3-eslint

### To reproduce

Operation steps
https://asciinema.org/a/560173

**Comment by c-ehrlich** [comment]
Can reproduce.

**Comment by juliusmarminge** [comment]
Can repro on other apps too, seems to be the `type-checking` override rule which causes it :/

**Comment by aschnebelext** [comment]
I can also reproduce this error.

**Comment by juliusmarminge** [comment]
I think this is fixed upstream now? Seems to work on my end atleast

**Comment by c-ehrlich** [comment]
Works for me now as well.
