### ISSUE TITLE
bug: prisma schema changes are not recognized by trpc 

### ISSUE THREAD

**Issue by danielmarkow** [t3-oss/create-t3-app#1224]
### Provide environment information

`  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 356.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm`

### Describe the bug

trpc does not recognize the prisma schema has changed after running `npx prisma db push`. For example a prisma schema with a field that is made optional. Model prior to change:
`model UserCar {
    id        String   @id @default(cuid())
    user      User     @relation(fields: [userId], references: [id])
    userId    String
    car       Car      @relation(fields: [carId], references: [id])
    carId     String
    role      String
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}`
Model after the change:
`model UserCar {
    id        String   @id @default(cuid())
    user      User     @relation(fields: [userId], references: [id])
    userId    String
    car       Car      @relation(fields: [carId], references: [id])
    carId     String
    role      String?
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}`
Then I run `npx prisma db push` but when I write a procedure that creates an entry in that schema, it errors stating that role value needs to be provided. If I restart the development server everything works as designed.

### Reproduction repo

https://github.com/danielmarkow/will-u-be-my-carbuddy

### To reproduce

create a t3 app, create a prisma schema without an optional field. push the schema. make one field optional and push the schema. write a trpc procedure that writes into the table omitting the now optional field.

### Additional information

Hope this is a sufficient description. Never submitted one of these before :)

**Comment by juliusmarminge** [comment]
When you say doesn't recognize do you mean in runtime or just that the new types aren't being recognized?

Everytime you push a prisma schema you need to restart the typescript server otherwise it wont look for the new generated type in your node modules. This should solve the problem if it's the latter.

Restarting the TS server in vscode is done by opening the command palette (CMD+SHIFT+P) and search for "restart" and select the restart typescript option.

**Comment by danielmarkow** [comment]
No what I am referring to is that requests fail until I restart the dev server. To go with my earlier example: I make one field in the prisma schema optional, run `npx prisma db push` and then trigger a mutation that writes to that table without the optional data and it gives me an error that this column is not optional. When I restart the dev server everything suddenly works fine.

**Comment by juliusmarminge** [comment]
I'm not sure if this is a problem on our side or if that's just how Prisma works? I don't know if i ever have pushed a schema while the dev server is running 🤔

**Comment by hannanel100** [comment]
i got a typescript error in a router, when trying to access ctx.prisma.topic... (where Topic is a model in my prisma.schema), i restarted vscode and it was gone...

**Comment by c-ehrlich** [comment]
Updated schema not being picked up is a known issue between Prisma and VSCode / the TS server, see: https://github.com/prisma/prisma/discussions/3474

Not much we can do here.

**Comment by Arkirion** [comment]
> Today, I had the same problem with the newest t3 build.
> 
> * restarting TS server didn't work
> * reloading TS project didn't work
> * restarting vsCode worked!
> 
> Thanks

cant believe that this works
