### ISSUE TITLE
bug: CLI: setting [dir] doesn't work when --trpc etc. are also specified

### ISSUE THREAD

**Issue by hamishcunningham** [t3-oss/create-t3-app#1236]
### Provide environment information

```bash
$ npx envinfo --system --binaries
  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz
    Memory: 9.06 GB / 31.24 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.14.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm

$ pnpm --version
7.27.1
```

### Describe the bug

Thanks for a great CLI!

Is this a bug or am I doing something wrong? The following command creates a scaffolded app in the directory `my-t3-app-all`, as expected:

`pnpm create t3-app@latest --CI --noGit --noInstall my-t3-app-all`

This command ignores the directory spec and creates `my-t3-app`:

`pnpm create t3-app@latest --CI --noGit --noInstall --trpc my-t3-app-trpc`

Looks like a bug?

Also, when I ran the examples with npm instead of pnpm all the arguments seemed to be ignored.

### Reproduction repo

https://github.com/nodejs/docker-node/tree/main/18

### To reproduce

Run this command (on e.g. the `node:lts` docker image) and check the name of the directory created:

`pnpm create t3-app@latest --CI --noGit --noInstall --trpc my-t3-app-trpc`

**Comment by joachimjusth** [comment]
If I type like you:
```sh
pnpm create t3-app@latest --CI --noGit --noInstall --trpc my-t3-app-trpc
```
I got the same result, it scaffold the app inside `my-t3-app`

---

If you check the source code of the CLI, the option `--trpc` could take a boolean/value just after it.
https://github.com/t3-oss/create-t3-app/blob/55c87af37f64fbf778a5091b9cca75f9c9546468/cli/src/cli/index.ts#L106

So the cli thought that `my-t3-app-trpc` is part of the `--trpc` option.

For the `--noInstall` there are no value followed.
https://github.com/t3-oss/create-t3-app/blob/55c87af37f64fbf778a5091b9cca75f9c9546468/cli/src/cli/index.ts#L71

Hope that I explained correctly ^^.

**Comment by hamishcunningham** [comment]
Makes sense, tnx! Perhaps a docs comment might help :)
Anyhow I'll close this; have a good one!
