### ISSUE TITLE
bug: Global prisma instance type is slightly incorrect 

### ISSUE THREAD

**Issue by JingLi1998** [t3-oss/create-t3-app#1239]
### Provide environment information

N/A

### Describe the bug

(I don't think this is a bug/feature but rather a nit. However I was forced to select one when creating this issue.)

The current code for the prisma global instance is slightly misleading:
1. It is actually undefined until initialised but the types don't represent that
2. We should probably use nullish coalescing `??` instead of `||` 

The current snippet is this:
```
const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma =
  globalForPrisma.prisma ||
  new PrismaClient({
    log:
      env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"],
  });

if (env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
```

However I propose that it should be:
```
const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log:
      env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"],
  });

if (env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
```

The code as it currently stands does indeed work. But I see no harm in making it 'more accurate' 🤷 

### Reproduction repo

N/A

### To reproduce

N/A

**Comment by juliusmarminge** [comment]
Its from the docs https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices

**Comment by JingLi1998** [comment]
Agreed it follows the best practices recommended by the doc and it makes sense to follow their example as close as possible.

Taking a step back though, are the Prisma doc's recommended snippet is fully correct? If so does that mean there will always be a global prisma instance that **is not undefined** prior to instantiation?

**Comment by juliusmarminge** [comment]
Feel free to reopen if you get prisma to update - no reason to move away from the docs since it works
