### ISSUE TITLE
feat: Queue support, asynchronous tasks, timed tasks

### ISSUE THREAD

**Issue by StringKe** [t3-oss/create-t3-app#1241]
### Is your feature request related to a problem? Please describe.

None

### Describe the solution you'd like to see

We usually use queues to synchronize data, or to schedule tasks

For example

1. asynchronously send welcome emails, password retrieval emails
2. synchronize CRM information or other information in the system on a regular basis
3. etc.

| Feature                   |   BullMQ-Pro    |     BullMQ      |      Bull       |  Kue  | Bee      | Agenda |
| :------------------------ | :-------------: | :-------------: | :-------------: | :---: | -------- | ------ |
| Backend                   |      redis      |      redis      |      redis      | redis | redis    | mongo  |
| Observables               |        ✓        |                 |                 |       |          |        |
| Group Rate Limit          |        ✓        |                 |                 |       |          |        |
| Group Support             |        ✓        |                 |                 |       |          |        |
| Parent/Child Dependencies |        ✓        |        ✓        |                 |       |          |        |
| Priorities                |        ✓        |        ✓        |        ✓        |   ✓   |          | ✓      |
| Concurrency               |        ✓        |        ✓        |        ✓        |   ✓   | ✓        | ✓      |
| Delayed jobs              |        ✓        |        ✓        |        ✓        |   ✓   |          | ✓      |
| Global events             |        ✓        |        ✓        |        ✓        |   ✓   |          |        |
| Rate Limiter              |        ✓        |        ✓        |        ✓        |       |          |        |
| Pause/Resume              |        ✓        |        ✓        |        ✓        |   ✓   |          |        |
| Sandboxed worker          |        ✓        |        ✓        |        ✓        |       |          |        |
| Repeatable jobs           |        ✓        |        ✓        |        ✓        |       |          | ✓      |
| Atomic ops                |        ✓        |        ✓        |        ✓        |       | ✓        |        |
| Persistence               |        ✓        |        ✓        |        ✓        |   ✓   | ✓        | ✓      |
| UI                        |        ✓        |        ✓        |        ✓        |   ✓   |          | ✓      |
| Optimized for             | Jobs / Messages | Jobs / Messages | Jobs / Messages | Jobs  | Messages | Jobs   |

### Describe alternate solutions

I think the queue should be started separately from nextjs?

I don't have an ideal solution.

### Additional information

https://github.com/taskforcesh/bullmq

**Comment by c-ehrlich** [comment]
Implementing any Node-based message queue in a T3 app won't be fundamentally different from doing so in any other Next.js app. If you are deploying to a serverless environment there is no persistence so in that case you will need an external service. There is no plan to anything related to this to the template or documentation.
