### ISSUE TITLE
feat: disable dark reader browser extension

### ISSUE THREAD

**Issue by prashantrahul141** [t3-oss/create-t3-app#1264]
### Is your feature request related to a problem? Please describe.

Dark reader extension messes with the colors of the site.

### Describe the solution you'd like to see

Simple adding the meta tag as described [here](https://github.com/darkreader/darkreader/pull/9181) will fix the issue.

### Describe alternate solutions

I think the meta tag is the only easy way to fix it.

### Additional information

original:
![original](https://user-images.githubusercontent.com/59825803/223382713-41ed9807-5798-4759-aefa-5fe0291379bd.png)

when dark reader is enabled:
![withDarkReader](https://user-images.githubusercontent.com/59825803/223382777-74ec517c-1006-4493-8b72-d3443acbac41.png)

**Comment by c-ehrlich** [comment]
Do we really need to add a meta tag that's specific to one browser extension, just so that it doesn't break our site? What % of people visiting the docs use this?

**Comment by nexxeln** [comment]
> Do we really need to add a meta tag that's specific to one browser extension, just so that it doesn't break our site? What % of people visiting the docs use this?

fwiw, darkreader is a used by a lot of people, its the most popular dark mode extension

**Comment by LukaHietala** [comment]
Dark Reader extension is really popular and even I use it, but it would just be better to let the user disable it themselves in my opinion

**Comment by ObaidQatan** [comment]
The extension is quite popular, however isn't this related to how users want to see their web pages? I believe it's more likely to be custom style preferences that cannot be united under a single rule.

**Comment by nexxeln** [comment]
Yeah I agree, we should let the user disable it if they want to. Closing this for now.
