### ISSUE TITLE
bug: Prisma Query in _app.tsx > getInitialProps throws client environment error.

### ISSUE THREAD

**Issue by maxtotheguenther** [t3-oss/create-t3-app#1271]
### Provide environment information

**System:**
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 7.18 GB / 15.95 GB
**Binaries:**
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

Hello, 
I have difficulties loading the data for my header in _app.tsx on the server side.
When you try to query some data with prisma an error occures. Its due to the env variables inside server/db.ts

### Code from _app.tsx
```ts
const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, headerProps, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Header />
      <div className={fonts.className}>
        <Component {...pageProps} />
      </div>
    </SessionProvider>
  );
};

MyApp.getInitialProps = async (context: AppContext) => {
  const appProps = await App.getInitialProps(context);
  const headerProps = await prisma.creator.findMany({});
  return { session: null, headerProps, ...appProps };
};

export default api.withTRPC(MyApp);
```
### Client Error i receive

![image](https://user-images.githubusercontent.com/35257419/224384772-33a198b4-0950-4735-9382-8b21bda33546.png)
 

### Reproduction repo

tbd

### To reproduce

1. Install frech t3 app.
2. Add getInitialProps function in which you query some data with prisma
3. Reload the app in the browser

**Comment by c-ehrlich** [comment]
`getInitialProps` runs on the client, not the server, so you won't have access to Prisma.

**Comment by maxtotheguenther** [comment]
Thank you  @c-ehrlich.
But how can i load the data for my basic _app layout (header, footer) once? I dont want to make for each page a header + footer query to my database.
