### ISSUE TITLE
bug: ts-check remains

### ISSUE THREAD

**Issue by Zamiell** [t3-oss/create-t3-app#1276]
the following is still in the `next.config.mjs` template:

```
// @ts-check
```

so I think it should be removed

maybe it should have been removed in #1171 ?

**Comment by c-ehrlich** [comment]
I think you're right. Do you want to open a PR for it?

**Comment by arielconti10** [comment]
@c-ehrlich https://github.com/t3-oss/create-t3-app/pull/1279
