### ISSUE TITLE
Adding git (and no-install) prompt

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#128]
**Is your feature request related to a problem? Please describe.**
- I noticed when creating a new Astro project that they have prompts for installing dependencies and initializing the git repo. I find this easier than having to remember a flag to provide.

**Describe the solution you'd like**
- Adding in prompts similar to the ones below (we currently don't support no-install but eventually we probably should):
![CleanShot 2022-07-06 at 01 18 17](https://user-images.githubusercontent.com/51714798/177432417-966567ab-eae8-474d-9ee0-d24dc8ee620a.png)

**Describe alternatives you've considered**
- We have flags right now but for new users that doesn't know they exist or even old users who just forget to provide them, a prompt seems easier and more intuitive.

**Comment by MWhite-22** [comment]
Agreed, but we should keep both as those without interactive terminals, or those that just want o bypass the options, can still pass in flags.

**Comment by Alexanderdunlop** [comment]
Noticed when skipping npm install the console still logs "Adding packages..."
Is that intentional?

<img width="529" alt="image" src="https://user-images.githubusercontent.com/22138454/177910051-c9a6b6fe-b650-443b-b2e1-6792fbbd0143.png">

**Comment by juliusmarminge** [comment]
Implemented in #130 and #133.

**Comment by juliusmarminge** [comment]
> Noticed when skipping npm install the console still logs "Adding packages..."
Is that intentional?

I intentionally made the message different from when it is actually installing the dependencies. Maybe change to like `Adding boilerplate for <package>`? Also should probably not say anything if a blank app is requested without any of the extras.
