### ISSUE TITLE
bug: Terminal is detected incorrectly on windows terminal running Git-Bash

### ISSUE THREAD

**Issue by msyavuz** [t3-oss/create-t3-app#1281]
### Provide environment information

  System:

    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 9.75 GB / 15.88 GB

  Binaries:

    Node: 16.14.2 - D:\programlar\nodejs\node.EXE
    Yarn: 1.22.15 - D:\programlar\nodejs\yarn.CMD
    npm: 9.4.2 - D:\programlar\nodejs\npm.CMD

### Describe the bug

When i run `npm create t3-app@latest` from my windows terminal running git-bash, i can only create the default project. Since windows terminal is interactive i expect to be able to see options and choose accordingly.

### Reproduction repo

https://github.com/t3-oss/create-t3-app

### To reproduce

Run `npm create t3-app@latest` on a windows terminal running git-bash.

### Additional information

This is due to the check of process.env.SHELL containing bash in windows terminal. If a check for terminal instead of shell could be implemented, bug should disappear.

**Comment by luisvinicius09** [comment]
Apparently, in release [7.5.6](https://github.com/t3-oss/create-t3-app/releases/tag/create-t3-app%407.5.6) the git-bash was treated as un-interactive (#1222). I couldn't clearly find a reason though.

I used it perfectly like last month. I wonder if this is something they are working on or planning to do. I would love to see compatibility with git-bash again.

**Comment by c-ehrlich** [comment]
see https://github.com/t3-oss/create-t3-app/issues/1139

it's possible that the real problem is MinTTY rather than git-bash itself. Feel free to test this and if so open a PR that detects MinTTY instead.
