### ISSUE TITLE
feat: SSR True, 404 page

### ISSUE THREAD

**Issue by Donivanes** [t3-oss/create-t3-app#1289]
### Is your feature request related to a problem? Please describe.

Hi, on the file. `utils/api.ts` when I set `ssr: true` the default 404 page from nextjs when I enter on a page that is not in the project doesn't appear, instead I get this `Application error: a client-side exception has occurred (see the browser console for more information).`

### Describe the solution you'd like to see

I would like to keep the 404 page

### Describe alternate solutions

I don't think there are alternate solutions

### Additional information

I'll paste the whole code file here 

```
import { httpBatchLink, loggerLink } from "@trpc/client";
import { createTRPCNext } from "@trpc/next";
import { type inferRouterInputs, type inferRouterOutputs } from "@trpc/server";
import superjson from "superjson";

import { type AppRouter } from "~/server/api/root";

const getBaseUrl = () => {
  if (typeof window !== "undefined") return ""; // browser should use relative url
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`; // SSR should use vercel url
  return `http://localhost:${process.env.PORT ?? 3000}`; // dev SSR should use localhost
};

/** A set of type-safe react-query hooks for your tRPC API. */
export const api = createTRPCNext<AppRouter>({
  config({ ctx }) {
    return {
      /**
       * Transformer used for data de-serialization from the server.
       *
       * @see https://trpc.io/docs/data-transformers
       */
      transformer: superjson,

      /**
       * Links used to determine request flow from client to server.
       *
       * @see https://trpc.io/docs/links
       */
      links: [
        loggerLink({
          enabled: (opts) =>
            process.env.NODE_ENV === "development" ||
            (opts.direction === "down" && opts.result instanceof Error),
        }),
        httpBatchLink({
          url: `${getBaseUrl()}/api/trpc`,
          headers() {
            if (ctx?.req) {
              // To use SSR properly, you need to forward the client's headers to the server
              // This is so you can pass through things like cookies when we're server-side rendering
              // If you're using Node 18, omit the "connection" header
              const {
                // eslint-disable-next-line @typescript-eslint/no-unused-vars
                connection: _connection,
                ...headers
              } = ctx.req.headers;
              return {
                ...headers,
                // Optional: inform server that it's an SSR request
                "x-ssr": "1",
              };
            }
            return {};
          },
        }),
      ],
      queryClientConfig: {
        defaultOptions: {
          queries: {
            refetchOnMount: false,
            refetchOnWindowFocus: false,
          },
        },
      },
    };
  },
  /**
   * Whether tRPC should await queries when server rendering pages.
   *
   * @see https://trpc.io/docs/nextjs#ssr-boolean-default-false
   */
  ssr: true,
  responseMeta({ ctx, clientErrors }) {
    if (clientErrors.length) {
      // propagate http first error from API calls
      return {
        status: clientErrors[0]?.data?.httpStatus ?? 500,
      };
    }
    // cache request for 2 hours + revalidate once every second
    const ONE_DAY_IN_SECONDS = 60 * 60 * 2; // 2 hours
    return {
      headers: {
        "cache-control": `s-maxage=1, stale-while-revalidate=${ONE_DAY_IN_SECONDS}`,
      },
    };
  },
});

/**
 * Inference helper for inputs.
 *
 * @example type HelloInput = RouterInputs['example']['hello']
 */
export type RouterInputs = inferRouterInputs<AppRouter>;

/**
 * Inference helper for outputs.
 *
 * @example type HelloOutput = RouterOutputs['example']['hello']
 */
export type RouterOutputs = inferRouterOutputs<AppRouter>;
```

**Comment by c-ehrlich** [comment]
I can confirm this issue, but I'm afraid it's probably not something that we can change. Could open an issue on tRPC and see if they can do something about it.

That being said you can create a `pages/404.tsx` file that default exports a React component, and this will give you a working 404 page even with `ssr: true`.

**Comment by PiotrekPKP** [comment]
> I can confirm this issue, but I'm afraid it's probably not something that we can change. Could open an issue on tRPC and see if they can do something about it.
> 
> That being said you can create a `pages/404.tsx` file that default exports a React component, and this will give you a working 404 page even with `ssr: true`.

Opened an issue in tRPC's repo :)

**Comment by PiotrekPKP** [comment]
@Donivanes  It seems like it's not a bug in tRPC either: https://github.com/trpc/trpc/issues/4084#issuecomment-1484664753

Probably an issue with NextJS.

**Comment by Donivanes** [comment]
> 

Thank you so much for the help @PiotrekPKP

**Comment by Donivanes** [comment]
> I can confirm this issue, but I'm afraid it's probably not something that we can change. Could open an issue on tRPC and see if they can do something about it.
> 
> That being said you can create a `pages/404.tsx` file that default exports a React component, and this will give you a working 404 page even with `ssr: true`.

@c-ehrlich  I think that it doesn't matter as it never reaches the 404 error

**Comment by c-ehrlich** [comment]
it does. 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/8353666/227937253-d7c7f274-b800-4edb-9071-ca90654f7054.png">
