### ISSUE TITLE
feat: add tutorial to readme

### ISSUE THREAD

**Issue by nickmccurdy** [t3-oss/create-t3-app#1292]
### Is your feature request related to a problem? Please describe.

The [tutorial](https://www.youtube.com/watch?v=YkOSUVzOAA4) should probably replace the [overview](https://www.youtube.com/watch?v=PbjHxIuHduU) as it has a better overview in the beginning of the detail, skips over history, goes into more detail, and has more up to date code examples.

### Describe the solution you'd like to see

Link to tutorial instead of overview

### Describe alternate solutions

Link to overview and then tutorial

**Comment by nexxeln** [comment]
Feel free to make a PR
