### ISSUE TITLE
feat: update tailwind from 3.2.7 -> 3.3.3

### ISSUE THREAD

**Issue by FinnDore** [t3-oss/create-t3-app#1311]
### Is your feature request related to a problem? Please describe.

New tailwind update just dropped https://tailwindcss.com/blog/tailwindcss-v3-3

### Describe the solution you'd like to see

Update tailwind

### Describe alternate solutions

Dont update tailwind

### Additional information

#

**Comment by Nsttt** [comment]
Time to `tailwind.config.ts` baby.

**Comment by FinnDore** [comment]
Apparently not. its borked atm lol

**Comment by Nsttt** [comment]
This is why we can't have nice things

**Comment by FinnDore** [comment]
So it looks like `prettier-plugin-tailwind` does not play nicely with a ts config file . for now ive just bumped he tailwind version. #1312

**Comment by FinnDore** [comment]
raised https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/136#issue-1644584784

**Comment by Nsttt** [comment]
Fixed now [here](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/137)

**Comment by FinnDore** [comment]
Perfect. Looks like I should be able to migrate the tailwind configs now.
