### ISSUE TITLE
feat: Asset update, "brand guidelines" page

### ISSUE THREAD

**Issue by t3dotgg** [t3-oss/create-t3-app#1325]
### Is your feature request related to a problem? Please describe.

It's time for us to have an actual brand assets page. Host the assets themselves on Github so we don't eat the bandwidth costs.

![light](https://user-images.githubusercontent.com/6751787/229332757-90055187-e13d-45cb-9f16-01ced0367969.svg)
![dark](https://user-images.githubusercontent.com/6751787/229332759-899b2a55-8f00-4985-bc48-e6e47a29bc00.svg)

New logos provided above and here https://drive.google.com/drive/folders/1LSo6-_qtu3g-SJC-YnCo9tpu2iMGqedq?usp=sharing

### Describe the solution you'd like to see

I think Astro nailed this (see their [brand page](https://astro.build/press#assets), accessible by right clicking logo on their website)

Ideally we'd offer dark and light mode versions as SVG and PNG.

We should also credit [Zak](https://github.com/zaknaj), @zaknaj, for designing the new logo

### Describe alternate solutions

Idk y'all let me know if you have any other concepts or ideas or if you even think this is worth it.

**Comment by t3dotgg** [comment]
Might also be fun to have a few photos of me with transparent bgs now that I think about it

**Comment by matibox** [comment]
I'd like to work on this. Do you want the branding page to open by right clicking the logo as well?

**Comment by nexxeln** [comment]
> I'd like to work on this. Do you want the branding page to open by right clicking the logo as well?

yes!

**Comment by matibox** [comment]
Is there anything I should keep in mind? This will be my first pull request
