### ISSUE TITLE
feat: Opinionated import order

### ISSUE THREAD

**Issue by rortan134** [t3-oss/create-t3-app#1332]
### Is your feature request related to a problem? Please describe.

Is there any plans on creating an opinionated prettier import auto-sorter for the t3 base template?

### Describe the solution you'd like to see

Something like [@trivago/prettier-plugin-sort-imports](https://www.npmjs.com/package/@trivago/prettier-plugin-sort-imports) or [@ianvs/prettier-plugin-sort-imports](https://www.npmjs.com/package/@ianvs/prettier-plugin-sort-imports) would be very nice to have already set-up.

![Code_656t1Kovbi](https://user-images.githubusercontent.com/37253958/229556130-42f99612-4b80-4dd8-a7ff-603b02786e8f.gif)

### Describe alternate solutions

Import order structure example:

```js
importOrder: [
        "^react",
        "^next/*",
        "<THIRD_PARTY_MODULES>",
        "",
        "^@/components/(.*)$",
        "^@/utils/(.*)$",
        "",
        "^@/lib/(.*)$",
        "",
        "^[./]", // local files
        "^@public/*", // root/public
    ],
  ```

**Comment by c-ehrlich** [comment]
I think I'm in favor of this. It's something I have in all of my non trivial projects. We would need to make it work with the custom base path, but that should be doable.

I guess the argument against is "user can add it", and we tend to stay away from opinionated linting/formatting by default. Curious to see what others think.

**Comment by juliusmarminge** [comment]
We wouldn't need to do a custom sort order, the default from ianvs is enough and if devs want their own they can add themselves. Just having the plugin and some basic rules (like no duplicates etc) goes a long way for consistency and keeping git diffs small

**Comment by FinnDore** [comment]
Oh that's true tbf

**Comment by ronanru** [comment]
I like [prettier-plugin-organize-imports](https://www.npmjs.com/package/prettier-plugin-organize-imports). It uses TypeScript LSP to sort imports.

**Comment by iAverages** [comment]
I'd definitely like to see this added :)

**Comment by its-monotype** [comment]
[eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort)?

**Comment by FinnDore** [comment]
Is someone doing this, i see a couple of prs but not much movement. i can bash a pr out today if people want?

**Comment by FinnDore** [comment]
So something i forgor was that the default cta app does not incude prettier. so do we only want to include this if they chose tailwind?

**Comment by FinnDore** [comment]
not technically closed yet.
