### ISSUE TITLE
feat: Support app directory in t3 app?

### ISSUE THREAD

**Issue by zwelhtetyan** [t3-oss/create-t3-app#1336]
### Is your feature request related to a problem? Please describe.

___

### Describe the solution you'd like to see

___

### Describe alternate solutions

____

**Comment by ImBIOS** [comment]
`appDir` is still in public beta and I have seen several unstable features that has changed. I think it's not yet the right time to build something for it, we should wait it to becoming more stable.

**Comment by PiotrekPKP** [comment]
https://create.t3.gg/en/faq#why-are-we-using-pages-and-not-app-from-nextjs-13 :)

**Comment by c-ehrlich** [comment]
We're working on some stuff 😉

**Comment by curiouscod3** [comment]
> `appDir` is still in public beta and I have seen several unstable features that has changed. I think it's not yet the right time to build something for it, we should wait it to becoming more stable.

It's now in stable.

**Comment by c-ehrlich** [comment]
> > `appDir` is still in public beta and I have seen several unstable features that has changed. I think it's not yet the right time to build something for it, we should wait it to becoming more stable.
> 
> It's now in stable. It's now ready for production.

https://github.com/t3-oss/create-t3-app/issues/1364#issuecomment-1537363163
