### ISSUE TITLE
bug: `prisma` type error

### ISSUE THREAD

**Issue by ImBIOS** [t3-oss/create-t3-app#1337]
### Provide environment information

System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M2
    Memory: 55.59 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/99917_1680623854545/bin/node
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/99917_1680623854545/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman

### Describe the bug

'prisma' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)

### Reproduction repo

https://github.com/t3-oss/create-t3-app

### To reproduce

I dunno just trying to get started here

**Comment by juliusmarminge** [comment]
Have you generated the types?

`pnpm prisma generate`

Or just restart the TypeScript server
