### ISSUE TITLE
feat: Fix Default Discord Auth With Adjusted Code

### ISSUE THREAD

**Issue by codingwithmanny** [t3-oss/create-t3-app#1339]
### Is your feature request related to a problem? Please describe.

When using the default out of the box templated app with `pnpm create t3-app@latest` there are two errors that are present when using the default DiscordProvider with nextAuth.

The goal would be to get the developer to just enter the Discord credentials and be up and running with next-auth.

## 1 - NEXTAUTH_SECRET should come with a default value

When just using a local development environment with pnpm dev, the authentication fails with a JWT error. This is because the `NEXTAUTH_SECRET` is commented out in the `.env` file.

### Error/Problem:

```bash
# FROM: ./

pnpm dev;

# Output:
# [next-auth][warn][NO_SECRET] 
# https://next-auth.js.org/warnings#no_secret
# [next-auth][error][JWT_SESSION_ERROR] 
# https://next-auth.js.org/errors#jwt_session_error decryption operation failed {
# ...
```

**File:** `./.env` & `./.env.example`

```
# Next Auth
# You can generate a new secret on the command line with:
# openssl rand -base64 32
# https://next-auth.js.org/configuration/options#secret
# NEXTAUTH_SECRET=""
NEXTAUTH_URL="http://localhost:3000"
```

### Suggested Solution:

Modify the `./env.example` to have the uncommented and pre-filled with a secret.

_Example:_

**File:** `./.env` & `./.env.example`

```
# Next Auth
# (Recommended) You can generate a new secret on the command line with:
# openssl rand -base64 32
# https://next-auth.js.org/configuration/options#secret
NEXTAUTH_SECRET="A-REALLY-LONG-SECRET-PASSWORD-32"
NEXTAUTH_URL="http://localhost:3000"
```

### Error/Problem:

```bash
# FROM: ./

pnpm dev;

# Login with Discord

# Output:
# [next-auth][error][JWT_SESSION_ERROR] 
# https://next-auth.js.org/errors#jwt_session_error Cannot read properties of undefined (reading 'id') {
#   message: "Cannot read properties of undefined (reading 'id')",
# ...
```

**File:** `./src/server/auth.ts`

```ts
// ...

export const authOptions: NextAuthOptions = {
  callbacks: {
    session({ session, user }) {
      if (session.user) {
        // user.id = undefined
        session.user.id = user.id;
        // session.user.role = user.role; <-- put other properties on the session here
      }
      return session;
    },
  },

// ...
```

### Suggested Solution:

Modify the `auth.ts` to reference `token` and `token.sub` for the user id.

_Example:_

**File:** `./src/server/auth.ts`

```ts
// ...

export const authOptions: NextAuthOptions = {
  callbacks: {
    session({ session, token }) {
      if (session.user) {
        /*
        {
          token: {
            name: 'username',
            email: 'username@email.com',
            picture: 'https://cdn.discordapp.com/avatars/123456/somephoto.png',
            sub: '123456',
            iat: 1680643518,
            exp: 1683235518,
            jti: '7fbdf683-2c4b-48e0-9b83-b28c618f98c3'
          }
        }
        */
        // session.user.id = '123456'
        session.user.id = token.sub as string;
        // session.user.role = user.role; <-- put other properties on the session here
      }
      return session;
    },
  },

// ...
```

### Describe the solution you'd like to see

Solution in description.

### Describe alternate solutions

Solution in description.

**Comment by c-ehrlich** [comment]
1. This is on purpose. Including a default secret is a security risk. NextAuth works without a secret in dev (it adds one itself at runtime), at least with session auth, which we default to.
2. This "fix" is specific to JWT, which again we don't default to. With session auth, there is no `token.sub`. If we made this change, session auth would break.

We can only ship one default configuration. If you want to do something else, you will need to make changes. There is no such thing as a config that will

**Comment by codingwithmanny** [comment]
@c-ehrlich any reason why it wouldn't work with session auth by default?

That's sort of why I made the suggestion was that it wasn't working without setting a secret.

```bash
# Output:
# [next-auth][warn][NO_SECRET] 
# https://next-auth.js.org/warnings#no_secret
# [next-auth][error][JWT_SESSION_ERROR] 
# https://next-auth.js.org/errors#jwt_session_error decryption operation failed {
# ...
```
