### ISSUE TITLE
feat: prompt to choose between hard and soft tabs

### ISSUE THREAD

**Issue by alessiocancian** [t3-oss/create-t3-app#1345]
### Is your feature request related to a problem? Please describe.

Most people use soft tabs just because it's the default setting and it's hard to convert a project to hard tabs after the initial setup.
Most editors are preconfigured to automatically detect indentetion but if some dev changes that setting on his editor it's easy to mess up the indentation.
I don't want to start a debate on hard vs soft tabs, but when you work in a team it's common to have different opinions on tab size and if the project uses hard tabs everyone can configure his editor as he prefers.

### Describe the solution you'd like to see

I'd like create-t3-app to prompt to choose between hard and soft tabs and add configuration files to make it easier to configure editors and code formatters to the choosen tab setting.
These configuration files are useful also for soft tabs when people have different editor settings, and maybe in that case it should always prompt for the tab size and add it to the config files.

That should include:

- `.vscode/settings.json` which is useful to override VSCode user settings for this project
Example config for tabs is:
  ```json
  {
    "editor.detectIndentation": true,
    "editor.insertSpaces": false,
    "prettier.useTabs": true
  }
  ```

- `.editorconfig` which I think it's quite standard and understood by most editors and tools like prettier

  For tabs should be:
  ```
  root = true
  
  [*]
  indent_style = tab
  ```
  For spaces:
  ```makefile
  root = true

  [*]
  indent_style = space
  indent_size = 2 # choosen tab size
  ```

### Describe alternate solutions

I've considered asking hard tabs to be the default setting without even the prompt but may be too opinionated.

### Additional information

I know it may be not a feature you'd like to include but indentation settings are a huge problem on many projects and I think it may be useful for a lot of teams.
If you like this feature I could try working on it and open a PR.

**Comment by juliusmarminge** [comment]
This seems a bit too opinionated to include a setting for. We have discussed including a `.vscode` folder before but I don't think this justifies overruling the prior decisions on this matter.

**Comment by nickmccurdy** [comment]
Note that some Prettier plugins, including the VSCode extension, change the editor's indentation based on the Prettier config.

While I think tabs would be a better default, you could always add `useTabs: true` to the generated Prettier config yourself.
