### ISSUE TITLE
feat: Add upgrade capabilities

### ISSUE THREAD

**Issue by andreifilip123** [t3-oss/create-t3-app#1353]
### Is your feature request related to a problem? Please describe.

Since when creating a t3-app you're kinda stuck on the version you created on with no way to upgrade, I want to create an upgrade function.

### Describe the solution you'd like to see

The upgrade function should:
1. get the version of your app from ct3aMetadata in your package version
2. figure out the latest version
3. ask you if you want to upgrade to latest or to a specific version (?)
4. figure out which features you use (suggestion: should we add these into ct3aMetadata ?)
5. generate a diff between a ct3a of your version and the selected version

### Describe alternate solutions

I'm not sure if that's the best way and also don't have an idea of how to emulate the creation of the apps to get the diff between them so I'm open to suggestions from people with more experience on the repo.

**Comment by c-ehrlich** [comment]
Create T3 App is an init tool, not a framework or library. Once you create the app, it's yours.

https://create.t3.gg/en/faq#how-do-i-keep-my-app-up-to-date

**Comment by c-ehrlich** [comment]
Actually let's leave this open :)

This approach avoids the main problem of the previous attempts at "upgrades", which is that the user could have done _anything_ to their app, file structure, etc since initializing, can be sidestepped.

**Comment by LubomirGeorgiev** [comment]
When I want to upgrade what I do is I initialize the current version of T3 in an entirely separate directory and commit locally then I initialize the latest version in a separate directory and I copy all of the files and paste them in the previous directory.
That way, I can use git diff to see all of the differences and apply them manually in my own repo.

Maybe we can describe this whole process in the docs.

**Comment by andreifilip123** [comment]
In the meantime, I got this working:

https://upgrade-t3-app.vercel.app
