### ISSUE TITLE
bug: Running my T3 app takes up way too much RAM

### ISSUE THREAD

**Issue by Beefy-py** [t3-oss/create-t3-app#1360]
### Provide environment information

System information:
```
  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 2.35 GB / 7.88 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD```
```

Version in the `package.json`:
```
  "ct3aMetadata": {
    "initVersion": "7.10.3"
  }
```

### Describe the bug

When I run my create-t3-app project, it uses a large amount of CPU and RAM, making my system unresponsive.
[See a video of what is going on in my VScode terminal](https://jmp.sh/k9v7bwH4)

### Reproduction repo

https://github.com/Beefy-py/chat-app.git

### To reproduce

1. Clone the create-t3-app production repo project which I made public from GitHub.
2. Install all dependencies using `npm install`.
3. Start the application using `npm run dev`.
4. Navigate to [localhost](http://localhost:3000) in your browser and interact with the application for a few minutes.
5. Check task manager

#### Expected behavior:
The application should run smoothly with minimal resource usage.

#### Actual behavior:
The application causes my system to become unresponsive, and when I check my task manager, it's using more than 70% of my device RAM and more than 80% CPU. It's crazy.

#### System Info
`npx envinfo --system --binaries:`
```
  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 2.35 GB / 7.88 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
   ```
   
#### Screenshot performance
*Running in VSCode terminal*
![Capture](https://user-images.githubusercontent.com/52549888/232209111-d345a087-bf3d-40bf-8070-c16b9ff3633a.PNG)
*Running in Windows Powershell*
![Capture](https://user-images.githubusercontent.com/52549888/232210635-5fcda23f-c4b2-480c-8bd3-b0f03e9aaa95.PNG)

#### Errors
I got this after some time in the VScode terminal before it continued wreaking havoc again:
```
warn  - The server is running out of memory, restarting to free up memory.
error - Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {        
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}```

**Comment by joerambo** [comment]
Remove:
```console.log(ctx.prisma);```
from 
`/src/server/api/routers/chat.ts:11` 

It's gonna keep eating all your available memory when that tRPC method gets called.

**Comment by JohnBakhmat** [comment]
Should it be considered resolved ?
<img width="503" alt="image" src="https://user-images.githubusercontent.com/34962307/232279378-1e29dfc1-681c-4ef1-b67c-7d7e613f16a9.png">

**Comment by Beefy-py** [comment]
Yup, 
Solved.
