### ISSUE TITLE
feat: Use app directory as an option

### ISSUE THREAD

**Issue by joaomendoncaa** [t3-oss/create-t3-app#1361]
### Is your feature request related to a problem? Please describe.

I tried to have a glance at issues and PRs and didn't seem like `src/app` "support" was being worked on for now so here's my vouch for it's existence!

### Describe the solution you'd like to see

Would love to have an option for the file structure + markup boilerplate + examples to come with src/app + src/app/api instead of the current pages directory!

### Describe alternate solutions

n/a

**Comment by juliusmarminge** [comment]
it'll come when we feel like it's a good option to build apps with. we atleast need server actions to land before we add it as an option.
