### ISSUE TITLE
feat: astro - It seems hypocritic that create-t3-app uses astro for its website when it is telling everyone to use nextjs

### ISSUE THREAD

**Issue by sarvex** [t3-oss/create-t3-app#1367]
### Is your feature request related to a problem? Please describe.

Roadmap

### Describe the solution you'd like to see

Migrate from NextJs to Astro

### Describe alternate solutions

Stay with NextJS and implement the NextJS App Directory

**Comment by Zeko369** [comment]
They're fundamentally different things...

It sounds like: "Why are you telling me to use a car for driving around the city when you have use a large semi truck for transporting large cargo"

**Comment by ThatGuySam** [comment]
As Astro gets *more* application friendly, it may make sense to have it as an option for those that want to build t3 apps using their preferred component framework like Svelte, Vue, etc...

Plus, I may be wrong but I believe neither Next.js nor React start with the letter T

There's already a template for t3-astro here: 
https://github.com/t3dotgg/t3-astro
