### ISSUE TITLE
docs: rewrite env-variables docs page to use/reference new package

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#1384]
cba rewriting this now. creating an issue for it

_Originally posted by @juliusmarminge in https://github.com/t3-oss/create-t3-app/pull/1377#discussion_r1177128855_
            
Ref: https://env.t3.gg

**Comment by esau-morais** [comment]
May I work on this issue?

**Comment by juliusmarminge** [comment]
Sure! Feel free to link to the documentation over at t3-env if necessary
