### ISSUE TITLE
bug: Using auth without Prisma doesn't work

### ISSUE THREAD

**Issue by justinh-kairos** [t3-oss/create-t3-app#1388]
### Provide environment information

  System:
    OS: Linux 5.14 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (72) x64 Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz
    Memory: 473.95 GB / 503.24 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 3.5.0 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm

### Describe the bug

When using auth.js without an adapter, it defaults to saving the user session via JWE. This means that in the [session callback](https://next-auth.js.org/configuration/callbacks#session-callback), the `user` parameter is undefined, and the `token` parameter is passed in instead. Creating a new T3 app adds the following code (in /src/server/auth.ts) to the session callback, which causes an error:
```ts
  callbacks: {
    session: ({ session, user }) => ({
      ...session,
      user: {
        ...session.user,
        id: user.id,
      },
    }),
  },
```

### Reproduction repo

n/a

### To reproduce

Create a new t3 app with auth but not Prisma, and configure any auth provider

**Comment by c-ehrlich** [comment]
Can confirm. Not sure what the ideal solution is here.

- use a proper jwt setup when installing next-auth without prisma (seems like the most obvious choice)
- don't allow installing next-auth without prisma
- something else?

**Comment by justinh-kairos** [comment]
Not sure about most providers, but the one I'm using (Azure AD B2C) provides the user ID in the jwt's `sub` claim. In case anyone else runs into this before it's fixed, I was able to resolve this by changing the session callback to:
```ts
  callbacks: {
    session: ({ session, token }) => {
      return {
        ...session,
        user: {
          ...session.user,
          id: token.sub,
        },
      };
    },
  },
```

**Comment by juliusmarminge** [comment]
yep token.sub is the one you want - we should fix that...
