### ISSUE TITLE
feat: session authentication like express-session

### ISSUE THREAD

**Issue by codelover2k** [t3-oss/create-t3-app#1393]
### Is your feature request related to a problem? Please describe.

there are many next.js libs that offers JWT for authentication and allow you to use different providers to use authentication servers like google, github and so on.

Is there a way get session authentication and be able to store the session data in memory on a database or in redis.

### Describe the solution you'd like to see

I would like to have req.session like in express-session where I store only the userId.
Then, on every request, I can use req.session.userId to get the user from the database and get its username, email, first and last name, its permissions, if it is blocked by the admin or not. All that on every request!

for that I use express-session, redis to store the session data and a database or redis for user data.

is that somehow possible with next-auth?

### Describe alternate solutions

there are other cookie based authentication for node, but express-session is the most used
it is very simple, gives you crazy options to configure your cookie like the maxAge, the way you want to signature your cookie,  where the cookie should be accessed only (http or https) and many many more

**Comment by juliusmarminge** [comment]
Not sure what you mean here? Care to elaborate with some pseudo code or an example or similar?

**Comment by codelover2k** [comment]
Sure :)

In express, if you want to sessions with cookies, you have something like this
```ts
// set and check session for every http-verb
app.use(expressSessionMiddleware);

app.get('/add-session', (req, res, next) => {
  req.session.userId = 42;
  res.json({ message: "session created" })
});

app.get('/test-session', (req, res, next) => {
  if (req.session.userId) {
    const userId = req.session.userId
    console.log("session-exists with the userId: " + userId);
  }
  
   if (!req.session.userId) {
    console.log("no session");
  }
});;
```
with that we can implement sessions for authentication, without the need of JWTs.
We can also use the session that is inside of req, to fetch user informations like permissions and use these informations to inject them in our models, which ables us to more advanced authorization.

It would be great to have such an authentication strategy, with express-session, in tRPC that you can pick from create-t3-app.

**Comment by juliusmarminge** [comment]
So I've never used this but where are the sessions stored? If its just in memory it won't work on serverless. 

The way we setup next-auth, you have session based authentication that persists the sessions in your database, we don't use JWT if you choose Prisma along with NextAuth.js

**Comment by codelover2k** [comment]
> So I've never used this but where are the sessions stored?
this is where express-session kicks in, one of the most used session module.
It allows you to use any storage that you like.
To name a few:
aerospike, better-sqlite3, cassandra, cluster, arango, azuretables, cloudant, couchbase, bluemix, google cloud, ibm_db, dynamodb, firestore, hazelcast, loki, lowdb, memcache, memjs, marklogic, monetdb, mongo, mysql, microsoft sql, neo4j, postgres, redis, knex, sequelize, sqlite3, typeorm, couchDB, etcd, node-mysql, neDB, oracle, cache-manager, etcd3, levelDB and many many more :)

If there is a database that is not supported, you can easily implement your own connector, but never met one that had to do that :)

using next-auth with credentials requires JWT :(
It would be great to be able to use express-session, so we can also use other middlewares like helmet, caching middlewares or loggers that are already implemented and battle tested :)

**Comment by codelover2k** [comment]
since T3 uses next.js server, I guess it would be the easiest to use a custom next.js server.
saying that, would it be possible to offer this option so we can tell create-t3-app to create an T3 project with a custom next.js server. where we have all the options a liberties that we know from express?

**Comment by c-ehrlich** [comment]
I'm sure there are some libraries in the Express ecosystem that offer a lot of convenience. But at that point why not just use Next.js for the frontend and "regular" Express for the backend, with tRPC acting as the API layer between them? What is a custom Next.js server offering here?
