### ISSUE TITLE
bug: tailwind autocomplete not working with webstorm

### ISSUE THREAD

**Issue by rkohava** [t3-oss/create-t3-app#1396]
### Provide environment information

System:
OS: macOS 13.2
CPU: (12) arm64 Apple M2 Pro
Memory: 56.02 MB / 16.00 GB
Shell: 5.8.1 - /bin/zsh

Binaries:
Node: 20.0.0 (issue existed with 18.16.0 as well)
npm: 9.6.4

app scaffolded with version 7.12.1

### Describe the bug

TailwindCSS intellisense is not working with WebStorm 2023.1 and JetBrains' TailWind CSS 231 plugin. 
Changing tailwind.config.ts to tailwind.config.cjs (with appropriate edits in the file) seems to fix the issue.

### Reproduction repo

NIL

### To reproduce

scaffold app with create-t3-app with tailwind enabled.
code in WebStorm with Tailwind enabled.

### Additional information

Changing tailwind.config.ts to tailwind.config.cjs (with appropriate edits in the file) seems to fix the issue.

**Comment by juliusmarminge** [comment]
File this issue to the guys maintaining the WebStorm plugin instead.

We contributed the fix for the prettier plugin https://github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/137

**Comment by rkohava** [comment]
I mostly just added this to let people know about a possible workaround. I'm fairly new to all this and do not know what the most appropriate place would be to add this.

**Comment by dipta10** [comment]
hey @rkohava did you find any workaround for this?
I can see this issue being mentioned  [here](https://youtrack.jetbrains.com/issue/WEB-57744) as well.

**Comment by rkohava** [comment]
Hey @dipta10 

Changing tailwind.config.ts to tailwind.config.cjs (with appropriate edits in the file) seems to fix the issue for me. This (or a similar) issue has been mentioned a couple of times in their different issue threads, but ultimately none of the solutions worked for me (I have not tried the specific one you linked to).
