### ISSUE TITLE
feat(cli): add clerk

### ISSUE THREAD

**Issue by Sn0wye** [t3-oss/create-t3-app#1409]
### Is your feature request related to a problem? Please describe.

Recently, I've been using clerk and saw a lot of people wanting that, so I thought it was plausible.

### Describe the solution you'd like to see

I'd like to implement the clerk auth provider to the cli tool, once a lot of people are starting to use it, and it seems like its gonna be the next part of the stack.

### Describe alternate solutions

Thoughs on that?

**Comment by louisunlimited** [comment]
I believe Theo once said in a live stream or somewhere that ct3a will always remain OSS and only use other OSS projects so idk this is what they wanted to do

**Comment by Sn0wye** [comment]
Now i'm working on that when i have the time to, but WIP....

**Comment by FleetAdmiralJakob** [comment]
I think this would be a great addition

**Comment by w3bdesign** [comment]
I believe this has already been done, so I am not sure if this is actually needed:

https://github.com/clerkinc/t3-turbo-and-clerk
