### ISSUE TITLE
feat: Logging (winston) by default, auto exit and set global error handler

### ISSUE THREAD

**Issue by codelover2k** [t3-oss/create-t3-app#1411]
### Is your feature request related to a problem? Please describe.

Logging is a very important part of every server or web app.
I noticed that we do not have anything already set up and it would be great to have something that we can pick from create-t3-app
I would recommend winston, because it is the most popular and the one that has a lot of plugins

### Describe the solution you'd like to see

It would be great to have a logger that logs on every error that is not caught or of type INTERNAL_SERVER_ERROR.
tRPC has like express an global error handler and having a basic setup with `process.exit(1);` would be great.

Furthermore it would be good to have a logger and process.exit(1) in
`process.on('uncaughtException', (ex) => { })`
and in
`process.on('unhandledRejection', (error) => { })`

to have better start, setting up your servers!

### Describe alternate solutions

The solution would be to install winston and set up the global error handler and the events if winston is picked, if not we can neglect these settings

**Comment by juliusmarminge** [comment]
I think we've has this up for debate before and everyone probably has their own favorite (Theo uses Axiom for example) so this is not something we're looking to include by default.
