### ISSUE TITLE
bug: tailwind.config.ts breaks Tailwind CSS IntelliSense

### ISSUE THREAD

**Issue by mattiaz9** [t3-oss/create-t3-app#1414]
### Provide environment information

  System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 168.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm

### Describe the bug

Having the tailwind config as a .ts file breaks the autocompletion of the Tailwind CSS intellisense extension in VS Code.

### Reproduction repo

npm create t3-app@latest

### To reproduce

- Run `npm create t3-app@latest`
- Install https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss
- check the tailwind autocompletion in any .tsx files

### Additional information

Renaming the file to `tailwind.config.js` fixes the issue

**Comment by mattiaz9** [comment]
I tried but I didn't help. I don't think is my VS Code setup because using .js works fine:

https://github.com/t3-oss/create-t3-app/assets/9766700/ffaa176b-fd92-4e93-a8c3-9915d660e341


I also tried to reload VS Code with extensions disabled.

**Comment by raiyansarker** [comment]
Can you try creating a new vs code profile and then see if that works?
__*N.B. You need to install tailwind intellisense again*__

**Comment by mattiaz9** [comment]
Yes, that worked. Thank you. 
I guess I'll need to investigate my environment to find out what's wrong!
