### ISSUE TITLE
feat: ServerSideProps

### ISSUE THREAD

**Issue by mweel1** [t3-oss/create-t3-app#1417]
### Is your feature request related to a problem? Please describe.

The tRPC documentation is very confusing on how to use ServerSideProps and would be nice to have a working example.

### Describe the solution you'd like to see

A page using serverSideProps

### Describe alternate solutions

I've read the tRPC docs, but it doesn't nice with the design especially around getting context.

**Comment by alez04** [comment]
To use getServerSideProps you have to use server side calls.
https://trpc.io/docs/server/server-side-calls

**Comment by juliusmarminge** [comment]
Yep.

`router.createCaller` or `ssgHelpers` is the way

https://trpc.io/docs/nextjs/server-side-helpers

Note that if you have `ssr: true` in your config you can't use gSSP due to limitations in Next.js - then you can use `getStaticProps` for example
