### ISSUE TITLE
feat: Please add Next.js app directory update

### ISSUE THREAD

**Issue by MusabDev** [t3-oss/create-t3-app#1419]
### Is your feature request related to a problem? Please describe.

No, it's not a problem.

### Describe the solution you'd like to see

I want to see the new app directory of Next.js 13 - https://github.com/vercel/next.js/

### Describe alternate solutions

There are no alternate solutions. I would like to have this update.

**Comment by c-ehrlich** [comment]
duplicate of this pinned issue https://github.com/t3-oss/create-t3-app/issues/1364
