### ISSUE TITLE
feat: create-t3-app with Express Adapter as an option

### ISSUE THREAD

**Issue by codelover2k** [t3-oss/create-t3-app#1441]
### Is your feature request related to a problem? Please describe.

There are many middlewares and patterns that are easy to implement with express because the solutions are already there.
For example there are middlewares like helmet, express-session, loggers and many more.

It would be great to have this option in create-t3-app, so we can use that without setting up the rest of the stack like nextjs.

### Describe the solution you'd like to see

Adding tRPC inside an Express context via Express-Adapter is easy like that:

```ts
import { inferAsyncReturnType, initTRPC } from '@trpc/server';
import * as trpcExpress from '@trpc/server/adapters/express';

// created context for all requests
const createContext = ({ req, res }: trpcExpress.CreateExpressContextOptions) => ({
  // add data here like your models
});

type Context = inferAsyncReturnType<typeof createContext>;

const t = initTRPC.context<Context>().create();

const appRouter = t.router({
  // add your routers here
});

const app = express();

app.use(
  '/trpc',
  trpcExpress.createExpressMiddleware({
    router: appRouter,
    createContext,
  }),
);

app.listen(3000, () => {
  console.log("Express with tRPC is running on port 3000");
});
```
the only thing that we have to do now is to add next.js or other options of create-t3-app

### Describe alternate solutions

---

**Comment by c-ehrlich** [comment]
We are not planning to add this.
