### ISSUE TITLE
bug: Typo in landing page npx command

### ISSUE THREAD

**Issue by LazyThursday** [t3-oss/create-t3-app#1442]
### Provide environment information

Not really needed?

### Describe the bug

The landing page which includes the npx create-t3-app copiable command has a type
should be
`npx create-t3-app`
actual
`npx create t3-app`

### Reproduction repo

next

### To reproduce

Go to https://create.t3.gg/ and look at the command

**Comment by juliusmarminge** [comment]
if you look closely it's actaully `npm` and not `npx`, so the create is a valid subcommand
