### ISSUE TITLE
bug: create t3-app@latest generates unresolving tRPC example

### ISSUE THREAD

**Issue by bcavs** [t3-oss/create-t3-app#1444]
### Provide environment information

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 147.16 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm

### Describe the bug

When I generate a brand new t3-app using `create t3-app@latest`, the example index page shows the 'Loading tRPC query...' state indefinitely and never resolve the example hello query.
<img width="1512" alt="Screenshot 2023-05-23 at 5 56 45 PM" src="https://github.com/t3-oss/create-t3-app/assets/64060308/80cfb638-9740-444f-b82b-2813d79fdf33">

I've tried generating a new project on an M2 MacBook to see if the issue was there as well however that one seemed to work. I've tried with multiple new projects on this MacBook and every one replicates this issue. 

### Reproduction repo

https://chef-brains-t3-jwq2.vercel.app/

### To reproduce

run `create t3-app@latest` and select all the packages except NextAuth. Keep all default options then follow the next steps listed: 
`cd project
npx prisma db push
npm run dev`

open up localhost:3000 and the text at the bottom should say "Hello from tRPC!" but instead will say "Loading tRPC query..."

**Comment by bcavs** [comment]
Looks like it's my Chrome that's causing the issue. Seems to work fine on Safari. Not sure what the issue is with Chrome but closing this since it's local. Apologies.

**Comment by manuelxaguilar** [comment]
@bcavs I can confirm I'm also having this same issue with my project on Chrome. On Safari, TRPC mutations/queries work just fine but nothing will happen on Chrome other than throw a permanent loading state... Looking into it now. I'm glad I ran into your issue because I had not bothered to test other browsers, I couldn't figure out what was happening.

**Comment by bcavs** [comment]
Glad I could help. It was incredibly frustrating for me as well haha, took about 6 hours of debugging for me to try it on a different computer and that's when I realized it was just the Chrome version I had.

**Comment by c-ehrlich** [comment]
Can you still reproduce this on latest Chrome? If not, do you know what Chrome version it happens in? And does it also happen in an incognito tab without any extensions etc? If so, might be worth opening an issue on tRPC.

**Comment by huzaifahj** [comment]
Happening with me on `Version 115.0.5790.170 (Official Build) (arm64)`

**Comment by huzaifahj** [comment]
Happens in incognito too
