### ISSUE TITLE
bug: Create-T3-app accepts more than just 'Y' and 'n' answers. 

### ISSUE THREAD

**Issue by rrohans** [t3-oss/create-t3-app#1455]
### Provide environment information

```
  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 72.78 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.6.1 - ~/.nvm/versions/node/v16.14.2/bin/npm

```

```
"ct3aMetadata": {
    "initVersion": "7.13.0"
  }
```

### Describe the bug

When scaffolding an app using Create-T3, the choices that require a 'Y' or 'n' input will implicitly choose 'n' if the answer does start with a 'Y' or the answer is not either 'Y' or 'n' explicitly. 

### Reproduction repo

N/A

### To reproduce

Run Create-T3-app and type in an answer that either starts with 'Y' or does not start with either 'Y' or 'n'.

For example:

`Yno' -- Implicit Yes
'asdf' -- Implicit No
'nY' -- Implicit No
'Y123' -- Implicit Yes

**Comment by c-ehrlich** [comment]
This is a limitation in [inquirer](https://github.com/SBoudrias/Inquirer.js). Might be worth opening an issue there. That being said I agree that this isn't great UX and we could consider building our own implementation that only accepts yYnN. Feels low priority to me personally but would be open to a PR that doesn't add too much complexity and still works with CI.

**Comment by rrohans** [comment]
Ah I see, I'll report it to Inquirer too then, maybe someone there can fix it and then we can just upgrade down the line.
