### ISSUE TITLE
feat: CLI add a ./ option for the project name

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [t3-oss/create-t3-app#1460]
### Is your feature request related to a problem? Please describe.

I want to use ./ to create all the files in my already create directory, but I get this error: `App name must consist of only lowercase alphanumeric characters, '-', and '_'`

### Describe the solution you'd like to see

If I type in the app name ./ all the files are going into the the directory I'm currently in

### Describe alternate solutions

No alternative

**Comment by c-ehrlich** [comment]
`.` works. I guess we could change the CLI to ignore any `/` at the end of the name, but not sure if that's an improvement.

**Comment by juliusmarminge** [comment]
I guess it doesn't hurt allowing for trailing /'s

Feel free to make a PR

**Comment by brunoeduardodev** [comment]
it should support only trailing /'s or support them at all?

say I'm on my $HOME dir, and I want to initialize the project at `$HOME/www/projects/my-project`, should this be supported?

it seems like an easy win

**Comment by juliusmarminge** [comment]
> it should support only trailing /'s or support them at all?
> 
> 
> 
> say I'm on my $HOME dir, and I want to initialize the project at `$HOME/www/projects/my-project`, should this be supported?
> 
> 
> 
> it seems like an easy win

Both with and without trailing slash, so . ./ foo foo/ foo/bar/ etc

Supporting home would be cool too i guess with `~`

**Comment by brunoeduardodev** [comment]
3 days ago I didn't know that full/relative paths were already supported on the prompt, lol

The PR solving this is almost there, but talking about allowing `~` through the prompt, it sounds useful and an easy win, should I also add it on #1466 or should this be a different PR?

**Comment by c-ehrlich** [comment]
i merged 1466 now because it does what it needs to do, feel free to open a separate PR for `~` :)
