### ISSUE TITLE
bug: Broken link to the top tutorial in the docs (FAQ)

### ISSUE THREAD

**Issue by matijaSos** [t3-oss/create-t3-app#1467]
### Provide environment information

docs

### Describe the bug

A top link under Articles is broken: https://create.t3.gg/en/faq#what-learning-resources-are-currently-available

### Reproduction repo

https://create.t3.gg/en/faq#what-learning-resources-are-currently-available

### To reproduce

https://create.t3.gg/en/faq#what-learning-resources-are-currently-available -> click on the first link in Articles section

**Comment by brunoeduardodev** [comment]
This is weird, it's like the article was removed from the author's website

**Comment by c-ehrlich** [comment]
Cc @nexxeln

**Comment by nexxeln** [comment]
Yeah I archived it in the new rewrite cause it was really outdated, and it showed up on google when people searched for a create-t3-app tutorial. We should remove that link from the docs and I'll write a new blog post when we migrate to the app router
