### ISSUE TITLE
feat: Use typescript-eslint@v6's reworked configs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [t3-oss/create-t3-app#1474]
### Is your feature request related to a problem? Please describe.

Following up on #1035 -> #1036: typescript-eslint is soon going to release a new v6 major version with reworked configurations. You can read up on it here: https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta

Specifically, the [configurations are reworked](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6-beta#reworked-configuration-names) so that the recommended equivalents to what create-t3-app uses now are:

* `'plugin:@typescript-eslint/recommended-type-checked'`
* `'plugin:@typescript-eslint/stylistic-type-checked'`

### Describe the solution you'd like to see

I'd like to send a PR to try the new configs out here. I like this repo and think you'll all do a good job of letting us know if you hate the changes! ❤️ 

https://github.com/typescript-eslint/typescript-eslint/issues/6760

### Describe alternate solutions

I suppose create-t3-app could opt to stay on typescript-eslint@v5, or use your own bespoke lint configs... neither option seems very appealing to me. 😉 

### Additional information

Please let me know if I'm being annoying / overly intrusive with this. The v6 has been a long time coming, and I really want to get the configs right.

**Comment by c-ehrlich** [comment]
Not annoying at all! People use CT3A and other starters as references to copy/paste from, so it's really important that our configs are as good as possible. Happy to get this in as soon as it's ready :)
