### ISSUE TITLE
Can I package this project into an app?

### ISSUE THREAD

**Issue by homestylew** [t3-oss/create-t3-app#1475]
### Is your feature request related to a problem? Please describe.

Can I package this project into an app?

### Describe the solution you'd like to see

I want to generate an app application

### Describe alternate solutions

no solution

### Additional information

Can I package this project into an app?

**Comment by ninja-1337** [comment]
Can you elaborate more on what you mean by packaging create-t3-app into an app?

**Comment by homestylew** [comment]
> 
Thank you for your reply. I would like to directly convert the web page I have written into an app application. That is, like other common hybrid development, packaging h5 pages into apk applications.

**Comment by ninja-1337** [comment]
You can check out Progressive Web Apps.

**Comment by homestylew** [comment]
> 

That is, cannot the create t3 app project be directly transformed into a hybrid mobile application?

**Comment by c-ehrlich** [comment]
If you want to build a PWA, there are some options for Next.js but we don't specifically support or endorse anything.

If you want to use React Native, look into [Create T3 Turbo](https://github.com/t3-oss/create-t3-turbo)
