### ISSUE TITLE
feat: add commit reminder to next steps

### ISSUE THREAD

**Issue by benmarg** [t3-oss/create-t3-app#1481]
### Is your feature request related to a problem? Please describe.

Currently when creating a new T3 app, it can be easy to forget to commit the changes before pushing the repo to GitHub. T3 stages all the changes but you still need to commit, and it can be an easy step to miss

### Describe the solution you'd like to see

Currently the next steps are:

```
Next steps:
  cd name
  npx prisma db push
  npm run dev
```
 
I suggest adding a 4th step:  `git commit -m "initial commit"`

### Describe alternate solutions

Leave as is

**Comment by ImBIOS** [comment]
Closed per #1482
