### ISSUE TITLE
feat: components folder

### ISSUE THREAD

**Issue by MenaiAla** [t3-oss/create-t3-app#1490]
### Is your feature request related to a problem? Please describe.

As we know NextJS app is made of components.

Each time I need to create my `components` folder with my custom hierarchy.

### Describe the solution you'd like to see

It would be better if you provide a `components` including two different approaches:

- [x]  By role: Buttons, Tabs, TextFields ...
-[x] By feature: Signup, Login,...

### Describe alternate solutions

NO

**Comment by c-ehrlich** [comment]
there are many different ways to set up the folder structure of a project, and many of them don't involve `src/components`. we don't want to be opinionated about this.
