### ISSUE TITLE
feat: change next step when no git repo

### ISSUE THREAD

**Issue by marcos-rojas** [t3-oss/create-t3-app#1497]
### Is your feature request related to a problem? Please describe.

After running cli, next steps are shown but I think the message _git commit -m "initial commit"_(see image bellow) can be removed when a git repo is not initialized. I have the prepared change if change is needed.
<img width="587" alt="message shown when no git is selected" src="https://github.com/t3-oss/create-t3-app/assets/74158005/1e62c05b-c6c7-4c0a-bd7b-ef3d9664e257">

### Describe the solution you'd like to see

Remove the next step with a commit message in case no git is selected. 
<img width="587" alt="commit message removed" src="https://github.com/t3-oss/create-t3-app/assets/74158005/4c8f6241-43fa-44ab-97fd-3afbd2cec444">

### Describe alternate solutions

An aditional git init message can be shown (before the git commit message) when no git option is selected

**Comment by Mvmo** [comment]
Have implemented it with pr #1502
