### ISSUE TITLE
feat: Support for Prisma 5?

### ISSUE THREAD

**Issue by martiiinthomas** [t3-oss/create-t3-app#1512]
### Is your feature request related to a problem? Please describe.

No not a problem no, just a better feature.

### Describe the solution you'd like to see

Make current Prisma in the t3 app instantiate with the latest Prisma 5

### Describe alternate solutions

Add Drizzle?

### Additional information

Prisma 5 is a great deal faster comparable to drizzle.

**Comment by c-ehrlich** [comment]
the pr is merged, will release probably today :)

**Comment by martiiinthomas** [comment]
Ah cool!, thanks for letting me know.
