### ISSUE TITLE
create.t3.gg appears to be down. Can anyone else confirm?

### ISSUE THREAD

**Issue by maxxheth** [t3-oss/create-t3-app#1514]
### Provide environment information

N/A

### Describe the bug

N/A

### Reproduction repo

N/A

### To reproduce

N/A

### Additional information

![Screenshot from 2023-07-18 16-45-25](https://github.com/t3-oss/create-t3-app/assets/10247792/b1a96bce-bba2-4511-9e0e-f5655f1db9c9)

**Comment by Cherry** [comment]
You can use https://create.t3.wtf/ temporarily. Tweet thread for more info: https://twitter.com/t3dotgg/status/1681386508559978497

**Comment by maxxheth** [comment]
Cool, thanks!

**Comment by c-ehrlich** [comment]
was an issue with the domain registrar. it's back now :)
