### ISSUE TITLE
.env.example file and the guide to get environment variable

### ISSUE THREAD

**Issue by Lantianyou** [t3-oss/create-t3-app#1515]
### Is your feature request related to a problem? Please describe.

This is a feature request,

### Describe the solution you'd like to see

 However, when using t3 stack. I found after running the CLI, the App is not successfully launched because of lacking environment variable.

### Describe alternate solutions

I think adding guide on docs about how to environment variable would be super helpful.

Or just have a `.env.example` file and a link to how to get those environment variable.

### Additional information

Hi Theo. Big fan of you, appreciate your work and tech choice.

**Comment by juliusmarminge** [comment]
> I found after running the CLI, the App is not successfully launched because of lacking environment variable.

That shouldn't the the case. We generate a gitignored .env as well as a checked in .env.example.

If you didn't get that, please submit a bug report with reproduction steps
