### ISSUE TITLE
"dev" css class for red border 

### ISSUE THREAD

**Issue by piyush-panpaliya** [t3-oss/create-t3-app#1516]
### Is your feature request related to a problem? Please describe.

I usually use this class while making the UI and have to add it manually after every fresh install 

### Describe the solution you'd like to see

add this to global.css

```css
.dev {
    border: 2px solid red;
}
```

### Describe alternate solutions

add this css manually after setting up a fresh t3 app

### Additional information

there is no css class nnamed dev in tailwind. so its safe to use

**Comment by c-ehrlich** [comment]
there are so many ways to do this sort of thing, and it's so easy to set up manually, that it doesn't make sense to add.
