### ISSUE TITLE
Upgrading from create-t1-app to create-t3-app

### ISSUE THREAD

**Issue by codymurphyjones** [t3-oss/create-t3-app#1518]
### Is your feature request related to a problem? Please describe.

I've got carpal tunnel from clicking roughly 2 more times every time I start a proejct.

### Describe the solution you'd like to see

Hello, esteemed maintainers of the create-t3-app!

I've been on a bit of a journey of self discovery recently you see, blissfully unaware of the horrors that awaited me in the world of "create-t3-app". But alas, I heard the call.

Imagine my disgust when I observed the cruelest reality that one could dream to wake up in.  Sure, some are gonna say that its dramatic, and "overreacting". 

BUT two of the three "t"s in t3-app - tailwind and trpc - are in fact, not enabled by default. I was expecting the radiant aura of unrelenting greatness that t3 has been a beacon of for so long only to be struck by a tidal wave of disappointment and irreverence.

I'm all for DIY, but if you promise a triple treat, don't be hiding in the dugout.

I, Cody Jones, humbly submit that this has gone on for long enough and it is time to redress this injustice and enable tailwind and trpc by default. 

### Describe alternate solutions

Delete Angular

### Additional information

Thank You

(yes this is satire, but I also think this is a good move, how many people are picking up the t1 stack ya know?)

**Comment by FleetAdmiralJakob** [comment]
I think in one video Theo explained that the t stands for Theo not for tRPC Tailwind and Typescript
