### ISSUE TITLE
bug: Incorrect Prisma types in freshly scaffolded create-t3-app project

### ISSUE THREAD

**Issue by xenostar** [t3-oss/create-t3-app#1519]
### Provide environment information

  System:
    OS: macOS 12.6.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 711.81 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2023.04.24.00 - /usr/local/bin/watchman

```
  "ct3aMetadata": {
    "initVersion": "7.16.0"
  }
```

### Describe the bug

Type information from Prisma appears to be incorrect in routers.

### Reproduction repo

Not required - can be created from freshly scaffolded app

### To reproduce

1. Create a new create-t3-app using `npm create t3-app@latest`
2. Follow installation instructions. I chose Prisma, Tailwind, and trpc for my project.
3. Once the project is finished, open it.
4. Open the example router file: `src/server/api/routers/example.ts`.
5. Rewrite the the `getAll` function like so to see an example of the issue:

```ts
  getAll: publicProcedure.query(async ({ ctx }) => {
    const test = await ctx.prisma.example.findMany();
    return test;
  }),
```

When hovering over `test`, we get a type of:

```ts
const test: (GetResult<{
    id: string;
    createdAt: Date;
    updatedAt: Date;
}, unknown> & {})[]
```

What we _should_ be seeing is something more like:

```ts
const test: Example[]
```

### Additional information

It seems to be occurring only after Prisma versions 4.16.X:

<img width="577" alt="Screen Shot 2023-07-28 at 5 40 12 PM" src="https://github.com/t3-oss/create-t3-app/assets/1480285/e2f00b9a-0f58-402e-a36f-288d5f558cda">

Versions before that (4.15.X and lower) seem to produce the expected type information:

<img width="577" alt="Screen Shot 2023-07-28 at 5 42 21 PM" src="https://github.com/t3-oss/create-t3-app/assets/1480285/ccfbce81-cdcd-4451-9e2b-2a16fb072a80">

That could indicate this is a Prisma-only bug, but I figured it would be worth reporting since this is visible in a fresh project. Considering Prisma is already on v5 and this isn't resolved yet, I wonder if there is something else at play here that is causing an issue.

**Comment by juliusmarminge** [comment]
<img width="447" alt="CleanShot 2023-08-27 at 20 42 27@2x" src="https://github.com/t3-oss/create-t3-app/assets/51714798/f544eee7-cb5b-42dc-b366-8f0486376fe0">

Might be fixed in prisma since you opened cause I'm not seeing that `GetResult` wrapper
