### ISSUE TITLE
feat: Disable typescript-eslint's array-type and consistent-type-definitions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [t3-oss/create-t3-app#1520]
### Is your feature request related to a problem? Please describe.

In #1476, create-t3-app started using [`"plugin:@typescript-eslint/stylistic-type-checked"`](https://typescript-eslint.io/linting/configs#stylistic-type-checked), which includes [`"plugin:@typescript-eslint/stylistic"`](https://typescript-eslint.io/linting/configs#stylistic). Those opinionated stylistic config presets include a couple of rules that seem to be [irritating users on Twitter](https://twitter.com/mehulsharmamat/status/1685014858868137984):

* [`@typescript-eslint/array-type`](https://typescript-eslint.io/rules/array-type): Requires consistently using either `T[]` or `Array<T>` for arrays.
* [`@typescript-eslint/consistent-type-definitions`](https://typescript-eslint.io/rules/consistent-type-definitions): Enforce type definitions to consistently use either `interface` or `type`.

Some folks like them enabled as-is. Others prefer the opposite. Either way, it looks like enabling them by default is turning people off of create-t3-app and/or linting and/or TypeScript in general. Although _we_ know ESLint rules are straightforward you can turn off or reconfigure, it's still a bad first impression for others.

For reference, here are all the rules in the stylistic configs: https://typescript-eslint.io/rules/?supported-rules=stylistic

### Describe the solution you'd like to see

These two rules seem to be the most consistently chafe-y from `stylistic(-type-checked)`. Perhaps we should disable them in the `.eslintrc.cjs` template?

```diff
  extends: [
    "next/core-web-vitals",
    "plugin:@typescript-eslint/recommended-type-checked",
    "plugin:@typescript-eslint/stylistic-type-checked",
  ],
  rules: {
+   // These opinionated rules are enabled in stylistic-type-checked above.
+   // Feel free to reconfigure them to your own preference.
+   "@typescript-eslint/array-type": "off",
+   "@typescript-eslint/consistent-type-definitions": "off",
    // ...
  }
```

### Describe alternate solutions

Not extending from `stylistic-type-checked` at all? This would mean less friction for users... but less benefit too. _Most_ of the rules are pretty nice: [`no-inferrable-types`](https://typescript-eslint.io/rules/no-inferrable-types), [`prefer-nullish-coalescing`](https://typescript-eslint.io/rules/prefer-nullish-coalescing), [`prefer-optional-chain`](https://typescript-eslint.io/rules/prefer-optional-chain), ...

### Additional information

I think this was a misplay on my end. We never resolved https://github.com/t3-oss/create-t3-app/pull/1476/files#r1234060608 over whether to include `consistent-type-definitions`, and I could have predicted that folks wouldn't like `array-type`. Sorry for causing user pain and tooling churn. 🙂 

This is also making me wonder if we should turn those rules off in `stylistic` in a future major version of typescript-eslint... TBD.

**Comment by JacobMGEvans** [comment]
I support this! @nexxeln @juliusmarminge it's you all's call though.
