### ISSUE TITLE
bug: drizzle - timestamp("created_at").defaultNow().notNull() throws error on planetscale mysql

### ISSUE THREAD

**Issue by EkaanshArora** [t3-oss/create-t3-app#1525]
### Provide environment information

System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 22.08 GB / 31.95 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.6 - C:\Program Files\nodejs\pnpm.CMD

### Describe the bug

I get the following error executing `pnpm db:push` with a new planetscale db. I think this is a [known issue with drizzle](https://github.com/drizzle-team/drizzle-orm/issues/657).
```bash
Error: target: drizzle.-.primary: vttablet: rpc error: code = InvalidArgument desc = Invalid default value for 'created_at' (errno 1067) (sqlstate 42000) (CallerID: df4v3wi4zdg3gwgn1wx4): Sql: "alter table project1_example add UNIQUE INDEX name_idx (`name`)", BindVars: {REDACTED}
    at PromiseConnection.query (C:\Users\Ekaansh\Desktop\drizzle\node_modules\.pnpm\drizzle-kit@0.18.1\node_modules\drizzle-kit\index.js:43626:26)
    at Command2.<anonymous> (C:\Users\Ekaansh\Desktop\drizzle\node_modules\.pnpm\drizzle-kit@0.18.1\node_modules\drizzle-kit\index.js:51315:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ER_INVALID_DEFAULT',
  errno: 1067,
  sql: 'CREATE UNIQUE INDEX `name_idx` ON `project1_example` (`name`);',
  sqlState: '42000',
  sqlMessage: 'target: drizzle.-.primary: vttablet: rpc error: code = InvalidArgument desc = Invalid default value for \'created_at\' (errno 1067) (sqlstate 42000) (CallerID: df4v3wi4zdg3gwgn1wx4): Sql: "alter table project1_example add UNIQUE INDEX name_idx (`name`)", BindVars: {REDACTED}'
}
```
 I think this got missed because if you have created your tables and then add the not null constraint then this error isn't thrown.
 I got around this by removing the not null constraint.

### Reproduction repo

https://github.com/EkaanshArora/ct3a-drizzle-repro

### To reproduce

1. create a new project using the cli, pick everything except prisma
2. set the env with a planetscale db
3. execute `pnpm db:push`

**Comment by headshigh** [comment]
I too encountered the issue, but i am not  able to get around it by removing not null constraint in createdAt column.

**Comment by nexxeln** [comment]
I think `defaultNow()` will be deprecated in favour of `defaultCurrentTimestamp()`. See [this issue](https://github.com/drizzle-team/drizzle-orm/issues/921). After this gets fixed we'll fix it here as well.

**Comment by juliusmarminge** [comment]
Added `.default(sql`CURRENT_TIMESTAMP`)` in https://github.com/t3-oss/create-t3-app/commit/ce5f31b08b8ed9d232c229efabf4878dc7106d0c

**Comment by EkaanshArora** [comment]
awesome, thank you!

**Comment by HugeLetters** [comment]
> Added
> 
> ```ts
> .default(sql`CURRENT_TIMESTAMP`)
> ```
> 
> in [ce5f31b](https://github.com/t3-oss/create-t3-app/commit/ce5f31b08b8ed9d232c229efabf4878dc7106d0c) to fix this

I'm uzing Drizzle with Planetscale too and for me it seems that ``.default(sql`(CURRENT_TIMESTAMP)`)`` works, with parenthesis only.

In Planetscale console too.
![image](https://github.com/t3-oss/create-t3-app/assets/119697239/725e75c3-e0a3-41b4-8fd5-51591c455f5f)

**Comment by amirakbulut** [comment]
All of the solutions above don't seem to work for me, I'm on `"drizzle-kit": "^0.19.13"`.

**Comment by HugeLetters** [comment]
> All of the solutions above don't seem to work for me, I'm on `"drizzle-kit": "^0.19.13"`.

This issue doesn't depend on `drizzle-kit`, it depends on `drizzle-orm`. You should check directly in Planetscale console first what works for you - like I've shown on my screenshot above.

**Comment by anasmohammed361** [comment]
> All of the solutions above don't seem to work for me, I'm on `"drizzle-kit": "^0.19.13"`.

Yeah I had the same issue , The issue is that you can't use second precisions, When you remove the fsp:3 from you schema , your code will work fine 

` addedAt:timestamp('addedAt',{mode:"date"}).default(sql`CURRENT_TIMESTAMP`).notNull()`
