### ISSUE TITLE
bug: Using auth without Prisma and firebase adapter causes error

### ISSUE THREAD

**Issue by peculiarnewbie** [t3-oss/create-t3-app#1526]
### Provide environment information

 System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 16.69 GB / 31.42 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.10 - C:\Program Files\nodejs\pnpm.CMD

### Describe the bug

a problem resulting from #1436, which solves issue #1388.

```javascript
callbacks: {
    session: ({ session, token }) => ({
      ...session,
      user: {
        ...session.user,
        id: token.sub
      },
    }),
  },
```

the problem is when using firebase (and maybe other adapters), token is undefined.

I'm not even sure if this template support/recommends adapters without prisma. If it is supposed to, then the solution I've found is checking for token like so:

```javascript
callbacks: {
    session: ({ session, token }) => ({
      ...session,
      user: {
        ...session.user,
        ...(token && { id: token.sub }),
      },
    }),
  },
```

or perhaps removing id entirely because i don't think that field is used anywhere else in the template

### Reproduction repo

n/a

### To reproduce

Create a new t3 app with auth but not Prisma, and configure firebase adapter

**Comment by juliusmarminge** [comment]
token should be available for most adapters, weird that firebase doesn't.

however i don't think we must handle all cases for all adapters so i'm going to close this as not planned.
