### ISSUE TITLE
feat: sequelize

### ISSUE THREAD

**Issue by DraconPern** [t3-oss/create-t3-app#1529]
### Is your feature request related to a problem? Please describe.

Prisma is great but Sequelize still offers more features.  I needed bitwise operations, prisma has 0 support for it.  For explicit many-to-many relation, Sequelize has complete support, but Prisma doesn't.  

### Describe the solution you'd like to see

Offer Sequelize for advanced usage

### Describe alternate solutions

not sure there's an alternative..

**Comment by c-ehrlich** [comment]
we are experimenting with support for kysely and/or drizzle, but are not planning to include sequelize.
