### ISSUE TITLE
bug: themeToggler not working 

### ISSUE THREAD

**Issue by dreyfus92** [t3-oss/create-t3-app#1533]
### Provide environment information

I don't have any issue with the a local project.

### Describe the bug

I was reading the docs and wanted to switch dark mode to light mode. I couldn't achieve it.
![t3](https://github.com/t3-oss/create-t3-app/assets/85648028/523fffc8-4f21-4b24-a7b8-dec8c892a614)

### Reproduction repo

https://github.com/t3-oss/create-t3-app

### To reproduce

Just go to the docs website and try clicking the themeToggler.

**Comment by c-ehrlich** [comment]
thanks for the report. there seem to have been a bunch of regressions on the site. might all be related?

<img width="1604" alt="CleanShot 2023-08-13 at 09 41 57@2x" src="https://github.com/t3-oss/create-t3-app/assets/8353666/4a7e205c-de99-4ae3-a346-26ed0b0bd0b9">

i'll try to bisect the vercel deployments tonight or tomorrow and find where it broke.

**Comment by juliusmarminge** [comment]
cc @FinnDore :)

**Comment by FinnDore** [comment]
oh, theres no way. wtf

**Comment by juliusmarminge** [comment]
Promoted the previous one to prod so should work again.

**Comment by FinnDore** [comment]
https://github.com/t3-oss/create-t3-app/assets/34718806/4c67e841-c0ab-4a64-ac6f-6c192efc4e2f

🤔 its working locally

**Comment by FinnDore** [comment]
however it does break once deployed, oh boy
<img width="1512" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/34718806/3d7a973c-58ef-4a59-bb59-e1fd5fa91dc8">

**Comment by FinnDore** [comment]
Noticing this in the console. but dont know enough about astro to know what the js bundle does 
<img width="310" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/34718806/21a28974-3b47-49bc-bb40-0b7207cbc847">

**Comment by FinnDore** [comment]
opend a pr that fixes the issue, turns out some random astro dep got bumped which broke things. pinning deps are cool :)
