### ISSUE TITLE
feat: set `pkgJson.packageManager` on init?

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#1538]
### Is your feature request related to a problem? Please describe.

the `packageManager` field in `package.json` is used by things like corepack and github actions. it's very annoying when that field isn't set

### Describe the solution you'd like to see

automatically add the field on project init. probably use the current version of the package manager that the user is using (simple parse on `npm -v`, `pnpm -v` or `yarn -v` depending on the user agent)

### Describe alternate solutions

not doing it, shifting the responsibility to the user

**Comment by c-ehrlich** [comment]
sounds good, open to PRs on this

**Comment by xonx4l** [comment]
Waiting for your thoughts on this @juliusmarminge .

**Comment by juliusmarminge** [comment]
Submit a PR!
