### ISSUE TITLE
feat: Adding Chakra-UI as a tailwind alternative

### ISSUE THREAD

**Issue by crimson-med** [t3-oss/create-t3-app#1543]
### Is your feature request related to a problem? Please describe.

Some people would like to have a more component ready ui framework

### Describe the solution you'd like to see

In the cli option it would be greate to have the choice between either tailwind or chakra

### Describe alternate solutions

I have created my own template but this makes it difficult to maintain. I would not mind working on a PR for this if there was a bit of guidance on how to structure the templates and how the flow would work.

https://github.com/crimson-med/t3-chakra-template

**Comment by c-ehrlich** [comment]
The setup for Chakra in pages dir is an npm install and one provider added to the app. I don't think the additional maintenance cost for us is worth it. If we were to add a "batteries-included components" library, it would probably be shadcn ui.
