### ISSUE TITLE
feat: get ts-node to work?

### ISSUE THREAD

**Issue by archywillhe** [t3-oss/create-t3-app#1544]
### Is your feature request related to a problem? Please describe.

Is there an easy way to get `ts-node` to work? Right now I keep running into problem with `.mjs` 

```
node:11200) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/arch/moodboard_t3/src/server/auth.ts:56
      return true
                ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/arch/moodboard_t3/src/env.mjs not supported.
Instead change the require of /Users/arch/moodboard_t3/src/env.mjs to a dynamic import() which is available in all CommonJS modules.
```

### Describe the solution you'd like to see

ts-node work out of the box for debugging?

### Describe alternate solutions

-

**Comment by juliusmarminge** [comment]
We recommend using `tsx` instead of `ts-node`.

**Comment by message** [comment]
@juliusmarminge do you have any working examples? It looks like `env.mjs` is the only struggle to run custom server with imports from `./src`.

**Comment by juliusmarminge** [comment]
tsx doesn't load environment variables so you'd need to do that yourself, with for example `dotenv-cli`: `dotenv tsx src/some-file`
