### ISSUE TITLE
feat: Initiate Bahasa Indonesia Documentation

### ISSUE THREAD

**Issue by Deri-Kurniawan** [t3-oss/create-t3-app#1546]
### Is your feature request related to a problem? Please describe.

Currently, there is no documentation in Bahasa Indonesia available, which poses a challenge for users seeking information and guidance in their native language. 

This lack of documentation hinders their ability to understand and implement the technology effectively.

Also, most new developers prefer to learn through tutorial content from YouTube creators in the same language due to the difficulty and unfamiliarity of understanding the technology through documentation in a different language. 

### Describe the solution you'd like to see

Translating key documentation into Indonesian allows Indonesian speaking users to better understand information and guides.

### Describe alternate solutions

Creating comprehensive translations not only enables Indonesian-speaking users to gain a better understanding of information and guides but also emphasizes the importance of accuracy and an easy-to-understand language style in these translations.

**Comment by juliusmarminge** [comment]
We currently don't track issues of what languages are translated and not.

If you want this to exist, feel free to open a PR
