### ISSUE TITLE
feat: add #1500 to changelog / release notes

### ISSUE THREAD

**Issue by mrienstra** [t3-oss/create-t3-app#1551]
This merged PR:
> https://github.com/t3-oss/create-t3-app/pull/1500 chore: update prettier and migrate to an esm config

... seems worth mentioning in [cli/CHANGELOG.md](https://github.com/t3-oss/create-t3-app/blob/144c746/cli/CHANGELOG.md) & in the release notes for the corresponding tag ([`create-t3-app@7.19.0`](https://github.com/t3-oss/create-t3-app/releases/tag/create-t3-app%407.19.0))

... given that it bumped `prettier` from v2 to v3, which includes [some breaking changes](https://prettier.io/blog/2023/07/05/3.0.0.html), and requires [plugin changes as well](https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F).

**Comment by juliusmarminge** [comment]
Not sure how to add changesets after the fact and dont wanna change it manually as its generated by changeset
