### ISSUE TITLE
bug: prettier sort input order has wrong regex

### ISSUE THREAD

**Issue by afonsopimenta** [t3-oss/create-t3-app#1555]
### Provide environment information

System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
    Memory: 58.94 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.asdf/installs/nodejs/20.2.0/bin/node
    npm: 9.6.6 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.7.4 - /opt/homebrew/bin/pnpm

### Describe the bug

`prettier.config.mjs` on `cli`, `upgrade` and `www` packages have the setting:
```js
importOrder: ["<THIRD_PARTY_MODULES>", "", "^~/", "^[../]", "^[./]"],
```
I believe the intended behaviour for `^[../]` and `^[./]` is to match imports that start with `../` and `./` respectively.
However what these regex are matching are anything that starts with `.`, `.` or `/` and `.` or `/` respectively.
This could lead to some weird edge cases since both `../` and `./` are being matched on the first regex as well as other unintended strings.

I'd be happy to fix this issue if it is confirmed.

### Reproduction repo

inapplicable

### To reproduce

inapplicable

**Comment by c-ehrlich** [comment]
the way we have it definitely looks wrong. would be happy to merge a pr to fix this :)
