### ISSUE TITLE
feat: Add support for drizzle orm also

### ISSUE THREAD

**Issue by KSSaiTeja** [t3-oss/create-t3-app#1563]
### Is your feature request related to a problem? Please describe.

when users run `npx create t3-app` the users are getting only prisma. It is better to add the drizzle orm also

### Describe the solution you'd like to see

after the adding solution it should ask to include `drizzle`

### Describe alternate solutions

nothing

**Comment by c-ehrlich** [comment]
drizzle is included in `npm create t3-app@latest`
