### ISSUE TITLE
bug: Drizzle seems to be using it's DATABASE_URL on the client-side

### ISSUE THREAD

**Issue by calthejuggler** [t3-oss/create-t3-app#1569]
### Provide environment information

**System:**
- OS: macOS 14.0
- CPU: (10) arm64 Apple M1 Pro
- Memory: 947.08 MB / 16.00 GB
- Shell: 3.6.1 - /opt/homebrew/bin/fish
 
**Binaries:**
- Node: 20.6.1 - /opt/homebrew/bin/node
- Yarn: 1.22.19 - /opt/homebrew/bin/yarn
- npm: 9.8.1 - /opt/homebrew/bin/npm
- pnpm: 8.7.5 - ~/Library/pnpm/pnpm
- Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
- Bun: 1.0.0 - /Users/calthejuggler/.bun/bin/bun. **< -- I'm using Bun**

- ct3aMetadata.initVersion: 7.20.2

### Describe the bug

I setup a t3-app today including Drizzle and followed the commented instructions as best as I could.

Everything was working fine until I added a mutation to the client (this happened with both `mutate` and `mutateAsync`:
```tsx
// ...
    const { mutateAsync } = api.projects.create.useMutation();

    const onSubmit = async (values: CreateProjectInput) => {
        await mutateAsync(values);
    }

    return (
        <Form {...form}>
            <form onSubmit={(event) => void form.handleSubmit(onSubmit)(event)} className="space-y-4">
// ...
```
I am now receiving the following error:
<img width="973" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/30095183/c2fa1085-29ae-4d05-b144-e5a61a997910">

So, it seems like Drizzle is trying to access the server-side env variable on the client side. I could prefix it with `NEXT_PUBLIC_`, but I've scaffolded a few projects with `create-t3-app` and I've never had to do that before.

So, this could be an issue with Bun, an issue with Drizzle, an issue with `create-t3-app`, or an issue with my configuration 😅 

Does anybody have any advice? If anybody needs more configuration code, please let me know!

### Reproduction repo

N/A

### To reproduce

1. Create a t3 app with Bun, choose Tailwind, Drizzle and NextAuth
2. Add a PlanetScale DATABASE_URL to the `.env` file and change the query params as requested in the comment.
3. Setup nextAuth with Discord.
4. Create a router with the following code:
```ts
import { z } from "zod";
import { createTRPCRouter, protectedProcedure } from "~/server/api/trpc";
import { projects } from "~/server/db/schema";

export const createProjectSchema = z.object({
    name: z.string().min(3).max(64),
    description: z.string().max(256),
})

export type CreateProjectInput = z.infer<typeof createProjectSchema>;

export const projectsRouter = createTRPCRouter({
    getAll: protectedProcedure.query(({ ctx }) => {
        return ctx.db.query.projects.findMany({
            where: (projects, { eq }) =>
                eq(projects.createdById, ctx.session.user.id),
        });
    }),
    create: protectedProcedure.input(createProjectSchema).mutation(({ ctx, input }) => {
        return ctx.db.insert(projects).values({
            ...input,
            createdById: ctx.session.user.id,
        })
    }),
});
```
5. Make a `CreatePage` in the pages directory with the following code (Note: this one is using `shadcn/ui` components):
```tsx
import { type NextPage } from "next"
import { type FC } from "react"
import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { Button } from "~/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "~/components/ui/card"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "~/components/ui/form"
import { Input } from "~/components/ui/input"
import Link from "next/link"
import { Textarea } from "~/components/ui/textarea"
import { type CreateProjectInput, createProjectSchema } from "~/server/api/routers/projects"
import { api } from "~/utils/api"

const CreateProjectForm: FC = () => {
    const form = useForm<CreateProjectInput>({
        resolver: zodResolver(createProjectSchema),
        defaultValues: {
            name: "",
            description: "",
        },
    })

    const { mutateAsync } = api.projects.create.useMutation();

    const onSubmit = async (values: CreateProjectInput) => {
        await mutateAsync(values);
    }

    return (
        <Form {...form}>
            <form onSubmit={(event) => void form.handleSubmit(onSubmit)(event)} className="space-y-4">
                <FormField
                    control={form.control}
                    name="name"
                    render={({ field }) => (
                        <FormItem>
                            <FormLabel>Name</FormLabel>
                            <FormControl>
                                <Input {...field} />
                            </FormControl>
                            <FormDescription>Give your project a name that will make it stand out!</FormDescription>
                            <FormMessage />
                        </FormItem>
                    )}
                />
                <FormField
                    control={form.control}
                    name="description"
                    render={({ field }) => (
                        <FormItem>
                            <FormLabel>Description</FormLabel>
                            <FormControl>
                                <Textarea {...field} />
                            </FormControl>
                            <FormDescription>A short summary of what the project is about.</FormDescription>
                            <FormMessage />
                        </FormItem>
                    )}
                />
                <div className="gap-2 flex items-center">
                    <Button type="submit">Let&apos;s go!</Button>
                    <Button variant="secondary" asChild>
                        <Link href="/dashboard">
                            Maybe later...
                        </Link>
                    </Button>
                </div>
            </form>
        </Form>
    )
}

const CreateProjectPage: NextPage = () => {
    return (
        <div className="flex flex-col items-center pt-12">
            <Card>
                <CardHeader>
                    <CardTitle>New Project</CardTitle>
                    <CardDescription>You&apos;re well on your way!</CardDescription>
                </CardHeader>
                <CardContent>
                    <CreateProjectForm />
                </CardContent>
            </Card>
        </div>
    )
}

export default CreateProjectPage;
```
6. Navigate to the create page after running `bun run dev`
7. See the error:
<img width="973" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/30095183/7daa5b6f-022f-4bbb-b7a5-696f12b03639">

### Additional information

Let me know of any more info that is needed! Also, this might just be a known configuration thing, so I'm sorry if that's the case 😅

**Comment by calthejuggler** [comment]
It turns out this was caused by me trying to import the createProjectSchema and the ProjectSchemaInput type from the server side. Duplicating the code on the client-side fixed it 🙂 

Sorry for the inconvenience!

**Comment by c-ehrlich** [comment]
This is an issue that a lot of people will run into sooner or later - not necessarily through the env var issue, but it manifests itself in many ways. 

The easiest way to ensure you don't run into this, without having to duplicate code, is to put zod schema into their own file. Personally I use `<routername>.schema.ts`. Then you should be able to import it on both client and server without any issues.

**Comment by calthejuggler** [comment]
> This is an issue that a lot of people will run into sooner or later - not necessarily through the env var issue, but it manifests itself in many ways. 
> 
> 
> 
> The easiest way to ensure you don't run into this, without having to duplicate code, is to put zod schema into their own file. Personally I use `<routername>.schema.ts`. Then you should be able to import it on both client and server without any issues.

Thanks for the tip! 😊
