### ISSUE TITLE
feat: use token instead of session(cookie)  and support  email password provider ? 

### ISSUE THREAD

**Issue by vaynevayne** [t3-oss/create-t3-app#1574]
### Is your feature request related to a problem? Please describe.

1. modern app is use token authorize
2. Third-party providers are banned in some countries, and large software does not use third-party licenses

### Describe the solution you'd like to see

token and passwordProvider

### Describe alternate solutions

no

**Comment by c-ehrlich** [comment]
We include Discord auth because it's the most minimal setup. There are a million different ways to do auth, implement the one that makes sense for your app.

Next-Auth specifically discourages using the CredentialsProvider, see: https://next-auth.js.org/providers/credentials
