### ISSUE TITLE
bug:  npx create-t3-app@latest is not working

### ISSUE THREAD

**Issue by Boby900** [t3-oss/create-t3-app#1575]
### Provide environment information

```System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
    Memory: 659.46 MB / 3.92 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
```

### Describe the bug

I was trying to install the T3 App by running the command `npx create-t3-app@latest` but it was giving me an error ***It looks like you are using MinTTY, which is non-interactive. This is most likely because you are
  using Git Bash*** though I am on Git bash

![Screenshot (167)](https://github.com/t3-oss/create-t3-app/assets/111265239/22bea206-691b-489a-a437-ef1007363acb)

### Reproduction repo

NA

### To reproduce

just by running `npx create-t3-app@latest` on Git Bash

**Comment by c-ehrlich** [comment]
This is not a bug, the error message states what the problem is and how to solve it. Please use Windows Terminal, or ideally a bash terminal through WSL. There's nothing we can do about the Git Bash / MinTTY issue.

**Comment by Boby900** [comment]
okay, thanks @c-ehrlich  I am gonna use Windows Terminal then
