### ISSUE TITLE
feat: Appreciate another channel for help

### ISSUE THREAD

**Issue by weisisheng** [t3-oss/create-t3-app#1577]
### Is your feature request related to a problem? Please describe.

Unable to use discord easily since I am abroad currently and they are rejecting my google voice IP phone number. 

### Describe the solution you'd like to see

Would appreciate another forum resource.

### Describe alternate solutions

Wrestle with discord issues?

### Additional information

New to trpc and t-3.  Love the framework BTW, after coming from AWS amplify/appsync headaches!

**Comment by juliusmarminge** [comment]
Discord is our goto for support channels. I've found it hard to keep track of multiple forums when you introduce them, for example using both Github Discussions and Discord is hard and one will naturally get more focus than the other, leading to one being left with a bunch of questions unanswered.

If you have issues, feel free to open issues here on Github, but for more general support Discord will be our goto for the unforeseeable future...
