### ISSUE TITLE
question: create-t3-app as bun create-template

### ISSUE THREAD

**Issue by polderleo** [t3-oss/create-t3-app#158]
Hi all,
i just stumbled across the [bun project](https://github.com/Jarred-Sumner/bun) and wanted to test if you can build the t3 stack with it. Bun create gives you the possibility to publish create-templates. 

Since i am quite inexperienced in the whole open-source world, here is the question if it is allowed to add create-t3-app in the bun project as create-template?

**Comment by nexxeln** [comment]
I think you should open this issue in bun's repo not here.

**Comment by nexxeln** [comment]
I asked Jarred (creator of Bun) and he said we can only use bun to run the scripts for now using `bun run`. 

![ss](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/Discord_01ULAAUXyx.png)

Will be closing this now.
