### ISSUE TITLE
feat: improve docker images version in docs

### ISSUE THREAD

**Issue by Nsttt** [t3-oss/create-t3-app#1580]
### Is your feature request related to a problem? Please describe.

The current configuration of the Docker images in the documentation is not utilizing more updated and secure versions of Node, which could potentially introduce vulnerabilities or miss out on the latest optimizations and features provided by the newer versions. 

Additionally, the final runner image can be optimized for production environments.

### Describe the solution you'd like to see

I propose updating the Docker images used in the documentation to Node 18 or 20 (preferably 20).

Moreover, it would be beneficial to transition the final runner image to a distroless image. Distroless images are minimal images that do not include any unnecessary software, you can take a look at them [here](https://github.com/GoogleContainerTools/distroless)

### Describe alternate solutions

Don't do it. Although the first part I consider it vital.

**Comment by Nsttt** [comment]
Not sure if to add to this issue, but it will also be nice to add a few lines about dev containers with the t3 app.

Related to this discussion https://github.com/vercel/next.js/discussions/27754

**Comment by Girishbari** [comment]
I could help, please assign it to me

**Comment by Nsttt** [comment]
Here's some draft that might need a bit of further testing.

```docker
##### DEPENDENCIES

FROM --platform=linux/amd64 node:20-alpine AS deps
RUN apk add --no-cache libc6-compat openssl1.1-compat
WORKDIR /app

# Install Prisma Client - remove if not using Prisma

COPY prisma ./

# Install dependencies based on the preferred package manager

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./

RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
    else echo "Lockfile not found." && exit 1; \
    fi

##### BUILDER

FROM --platform=linux/amd64 node:20-alpine AS builder
ARG DATABASE_URL
ARG NEXT_PUBLIC_CLIENTVAR
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ENV NEXT_TELEMETRY_DISABLED 1

RUN \
    if [ -f yarn.lock ]; then SKIP_ENV_VALIDATION=1 yarn build; \
    elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm run build; \
    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && SKIP_ENV_VALIDATION=1 pnpm run build; \
    else echo "Lockfile not found." && exit 1; \
    fi

##### RUNNER

FROM --platform=linux/amd64 gcr.io/distroless/nodejs20-debian12 AS runner
WORKDIR /app

ENV NODE_ENV production

# ENV NEXT_TELEMETRY_DISABLED 1

COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
ENV PORT 3000

CMD ["server.js"]
```

**Comment by MohamedAli00949** [comment]
Hi There,
This is the first time to contribute open source project and I hope to solve this issue.

### The solution I'd like to see
- [ ] Updating the Dockerfile content at [this file](www/src/pages/en/deployment/docker.md) and other languages. 
- [ ] Also at  [ajcwebdev/ct3a-docker repo](https://github.com/ajcwebdev/ct3a-docker/blob/main/Dockerfile).

**Comment by harshbsharma** [comment]
Can I work on it. Please assign

**Comment by mhenke** [comment]
Does this allow hot-reloading, if editing source code locally?

**Comment by avarayr** [comment]
Nextjs dropped the support of Node 16 in Nextv14. 


Dockerfile provided at t3.gg will NOT work on fresh installation of next14, for quickfix replace all instances of
`FROM node:16-alpine3.17 AS deps`
to
`FROM node:20.9.0-alpine3.18 AS deps`

until official t3 docs are updated.

**Comment by Nsttt** [comment]
Made a PR for the change in the documentation about the Docker images.

I will further create another issue with a proposal about the entire Docker setup that I feel might come handy for newcomers.
