### ISSUE TITLE
bug:  pnpm dev not working in older versions of Node 18

### ISSUE THREAD

**Issue by williamneves** [t3-oss/create-t3-app#1600]
### Provide environment information

System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 201.78 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.6.0 - ~/.nvm/versions/node/v19.6.0/bin/node
    npm: 9.4.0 - ~/.nvm/versions/node/v19.6.0/bin/npm
    pnpm: 8.8.0 - ~/.nvm/versions/node/v19.6.0/bin/pnpm

### Describe the bug

Just is not loading at the first installation. I tried ran pnpm create t3-app and use the AppRoute, but after all installation (with works well), when I open the localhost:3000, the error pops:

```
Unhandled Runtime Error
Error: Missing result

Call Stack
TRPCClientError.from
node_modules/.pnpm/@trpc+client@10.40.0_@trpc+server@10.40.0/node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs (37:15)
from
node_modules/.pnpm/@trpc+client@10.40.0_@trpc+server@10.40.0/node_modules/@trpc/client/dist/httpBatchLink-204206a5.mjs (200:55)
process.processTicksAndRejections
node:internal/process/task_queues (95:5)
```

### Reproduction repo

don't needed

### To reproduce

Just 
`pnpm create t3-app`

Options Selected:
- Auth: none,
- TS
- TW
- App Route
- ~/

`pnpm dev`

**Comment by luz33c** [comment]
when you run: pnpm build 
![image](https://github.com/t3-oss/create-t3-app/assets/62172559/aad9de57-58e1-4246-a60a-b22a39e3141a)

**Comment by kwerenta** [comment]
Downgrading to Next.js 13.5.4 fixes "Missing result" error

**Comment by c-ehrlich** [comment]
![CleanShot 2023-10-17 at 21 17 00@2x](https://github.com/t3-oss/create-t3-app/assets/8353666/b51b786a-697a-4198-aba3-1adfc2e85bba)

could you give more detailed steps or provide a repo from which this can be reproduced? it's working for me, including with Next 13.5.5

**Comment by pablasso** [comment]
@c-ehrlich hopefully you're able to reproduce with this repo: https://github.com/pablasso/reproduce-no-results, the same thing was happening with me with npm and latest next.

The problem is also solved for me when pegging nextjs to `13.5.4` like @kwerenta mentioned.

Error thrown:

```
Unhandled Runtime Error
Error: Missing result

Call Stack
TRPCClientError.from
node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs (37:15)
from
node_modules/@trpc/client/dist/httpBatchLink-204206a5.mjs (200:55)
process.processTicksAndRejections
node:internal/process/task_queues (95:5)
```

Installed versions:

- Node: v18.12.1
- NPM: 8.19.2
- NextJS: 13.5.5

Used options:

- Typescript
- Tailwind, yes
- tRPC, yes
- Auth provider, none
- ORM, none
- Nextjs App Router, yes

**Comment by williamneves** [comment]
> ![CleanShot 2023-10-17 at 21 17 00@2x](https://user-images.githubusercontent.com/8353666/275973331-b51b786a-697a-4198-aba3-1adfc2e85bba.png)
> 
> could you give more detailed steps or provide a repo from which this can be reproduced? it's working for me, including with Next 13.5.5

I just created a new project with the latest version, install and pnpm run the project and get this error.

**Comment by williamneves** [comment]
I found also the solution, but this not end the issue, but at least work,

go to the `package.json` and to `"next": "^13.5.4"` and change to `"next": "13.5.4"`, with this you get fixed to 13.5.4 and solve the error, so, next on version 13.5.5 is not working yet.

**Comment by sscotth** [comment]
Worked for me with Next v13.5.5

MacOS ARM 14.0
Node v20.8.1
pnpm v8.9.2

![image](https://github.com/t3-oss/create-t3-app/assets/1010488/36ec56cc-92d7-4b9a-a19a-a48bbfa4b4b2)

**Comment by c-ehrlich** [comment]
Thanks for the repo. I can reproduce with node v18.12.1. With the current Node 18 version (18.16.0), it works fine. So if you want a quick fix, upgrade your node version. But I guess we'll also need to think about how to guide people who run into this.

**Comment by pablasso** [comment]
You're right! I upgraded to latest LTS (v18.18.2) and it works fine. Thanks for looking into it.

IMO this could be closed.

**Comment by c-ehrlich** [comment]
opened a pr to prevent people from hitting this :)
