### ISSUE TITLE
bug: Session provider no longer wraps children when creating new T3 app with Next Auth and app dir.

### ISSUE THREAD

**Issue by L-Steinmacher** [t3-oss/create-t3-app#1607]
### Provide environment information

"initVersion": "7.22.0"

### Describe the bug

Session provider from Next auth not wrapping children in `src/app/layout.tsx` and must be added manually.  Calling useSession from Next auth not available till this is done. 

### Reproduction repo

https://stackblitz.com/github/L-Steinmacher/t3-app-dir-next-auth?file=src%2Fapp%2Flayout.tsx

### To reproduce

`npm create t3-app@latest` select options for Next Auth and app dir.  Calling hook `useSession` not available till wrapping children in the provider.

### Additional information

Not sure if it's a bug per se but thought I'd report this.

**Comment by L-Steinmacher** [comment]
Didn't do my research...

**Comment by L-Steinmacher** [comment]
My specific use case I was using the session to check if the user was logged in and rendering either a login or submit button dynamically as well as displaying some user data. Using the pages router this was fine but now using the app router I can't easily do this the way I did before.  I was thinking of making a TRPC endpoint to supply the session and user data to the client component but can't decide if that's jank/hacky. How would you suggest going about using the user session and user info in a client component?  Pass as prop or TRPC endpoint?  I'm asking from a JR dev point of view.

**Comment by c-ehrlich** [comment]
in general the best way to do it now is to use `getServerAuthSession` in a server component, and pass it as props to a client component. But `useSession` is also still fine, you can add the provider in a layout, similar to how it's implemented in the pages dir version.

**Comment by juliusmarminge** [comment]
I've been building with next-auth and appdir for a while now and never found myself missing `useSession`, it's easier to await it in a server component and pass it down as props, and not having to worry about the potential loading state when the hook is fetching.

If more report it as missing we might reconsider but this is a conscious decision for now

**Comment by juliusmarminge** [comment]
With NextAuth v5 (which is in beta and will be out in the next couple of weeks) you'll do this using server actions

**Comment by webertim** [comment]
What I always liked about handling the session client-side with `useSession` is the automatic nature of it. For example there is no need for a manual redirect after logging in, logging out or any other changes to the user state. Once session checks happen server side a call to the server is necessary to see those changes.

But maybe this only feels a bit clunky because NextAuth's singIn is a client-side functionality. Once this is a server-side functionality no redirects would be necessary. I am quite new to NextAuth but it seems like this could be server-side code since the client only needs the necessary cookies.

**Comment by rileybarabash** [comment]
@juliusmarminge You mentioned using server actions. How would you recommend doing so? For now, I'm just passing props from `getServerAuthSession` in a server component.

Use case is to conditionally render a sign in / sign out button and the content inside of it.

**Comment by asrvd** [comment]
https://authjs.dev/guides/upgrade-to-v5?authentication-method=client-component#authenticating-server-side

**Comment by ahkhanjani** [comment]
Considering how much easier it makes migrating from pages router, I'm also with adding the provider. Although making the migration easy might not be a priority for the maintainers.

**Comment by rudyorre** [comment]
At first I thought this was an oversight but reading through this thread, I've changed my mind. Specifically this from Julius:

> I've been building with next-auth and appdir for a while now and never found myself missing `useSession`, it's easier to await it in a server component and pass it down as props, and not having to worry about the potential loading state when the hook is fetching.

**Comment by zechdc** [comment]
For anyone looking for an example using `getServerAuthSession` and how to avoid `useSession` and `<SessionProvider>` in your RootLayout.

### page.tsx
Don't use "use client", let page.tsx render on the server so we can do `const session = await getServerAuthSession();`

Pass `session` as a prop to our client component, `InvoiceUpload.tsx`
```
import { getServerAuthSession } from "~/server/auth";
import InvoiceUpload from "./InvoiceUpload";

export default async function InvoicePage() {
  const session = await getServerAuthSession();

  return (
    <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          Invoice <span className="text-[hsl(280,100%,70%)]">Upload</span> App
        </h1>
        <InvoiceUpload session={session} />
      </div>
    </main>
  );
}
```

### InvoiceUpload.tsx
Client side component that accepts session as a prop
```
"use client";

import { signIn } from "next-auth/react";
import type { Session } from "next-auth";

interface InvoiceUploadProps {
  session: Session | null;
}

export default function InvoiceUpload({ session }: InvoiceUploadProps) {
  if (!session) {
    return (
      <div className="text-center">
        <p>You need to be signed in to upload invoices.</p>
        <button
          onClick={() => void signIn()}
          className="mt-4 rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
        >
          Sign In
        </button>
      </div>
    );
  }

  return (<div>Stuff you see if you are logged in</div>)
}
```
