### ISSUE TITLE
feat: Add Dropdown for Package Manager Options in Installation Command

### ISSUE THREAD

**Issue by Jacksonmills** [t3-oss/create-t3-app#1609]
## Summary
To enhance the developer experience, I propose adding a dropdown that allows users to select their preferred package manager (npm, pnpm, yarn, etc.) for the installation command displayed on https://create.t3.gg/.

## Background
While initializing a new create T3 app, the installation command provided on the site defaults to `npm`. This led to an issue when trying to integrate `shadcn/ui`[(issue)](https://github.com/shadcn-ui/ui/issues/1781), as I generally use `pnpm`. Manually changing the command to use `pnpm` resolved the issue, prompting me to suggest this enhancement.

## Benefits
User-friendly: Provides a tailored experience for developers using different package managers.
Reduces Issues: Minimizes dependency-related issues due to package manager incompatibility.

## Proposed Solution
Add a dropdown next to the installation command on the site.
Populate it with popular package managers like npm, pnpm, yarn, etc.
Upon selection, update the installation command accordingly.

## Alternate Solution
Would something like npx work for this?

**Comment by c-ehrlich** [comment]
We try to keep the number of prompts during scaffolding as small as possible, and this doesn't feel worth adding an additional one for imo

- i think it's reasonable to expect that a tool will default to the package manager that was used to run the command. most other scaffolding CLIs do the same.
- any command that uses `pnpm dlx` in that library's docs can also be run with `npx`
- you can "switch" package managers in an existing app by deleting the lockfile and running (for example) `pnpm i`

I could an argument for adding yarn/pnpm/bunx versions of the command to the landing page ([we already have them in the docs](https://create.t3.gg/en/installation)), but even that i'm not sure about.

**Comment by Jacksonmills** [comment]
![image](https://github.com/t3-oss/create-t3-app/assets/19780885/4c036c55-42f5-4ac1-a141-6c064702e801)

This is what I was picturing on the homepage, not necessarily another prompt during scaffolding, either way sounds good!

Thanks for the time 🫡

**Comment by c-ehrlich** [comment]
Oh yeah that makes a lot of sense!

**Comment by Jacksonmills** [comment]
I would love to contribute, so I will do that soon if I can beat you to it xD

**Comment by Jacksonmills** [comment]
Working on a fix now @c-ehrlich ... could we move this back to open so I can link a PR?

**Comment by Jacksonmills** [comment]
![image](https://github.com/t3-oss/create-t3-app/assets/19780885/6c6a4376-c10c-4082-9c90-2f02b7a61137)
