### ISSUE TITLE
feat: top level Drizzle migrations folder in template?

### ISSUE THREAD

**Issue by kellenproctor** [t3-oss/create-t3-app#1610]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like to see

T3 generates a Drizzle migrations folder, when you choose to use Drizzle.

### Describe alternate solutions

Leave it alone.

### Additional information

I'd be happy to work on a pull request for this over the weekend, if this is something the team would like to incorporate. Just need to add a top level Drizzle folder, add an "out" field to the drizzle config, add db:migrate/db:pull to the package.json, and include instructions on how to run these in your workflow.

Thoughts?

**Comment by ronanru** [comment]
A big percentage of users just use `npm run db:push`, instead of migrations.

**Comment by juliusmarminge** [comment]
Yea it's not our decision to make if you use push or migrate, so leaving it blank is the correct decision i think
