### ISSUE TITLE
bug: ESLint error in a generated app

### ISSUE THREAD

**Issue by ronanru** [t3-oss/create-t3-app#1615]
### Provide environment information

node 18.18.0
create-t3-app 7.22.0

### Describe the bug

I generated an app with `create-t3-app@latest` and these settings.

![image](https://github.com/t3-oss/create-t3-app/assets/35634442/e7dc5a7f-84c3-4945-872a-685f65c15c90)

Now after changing the `DATABASE_URL` in `.env`, if I run `npm run lint`, I get an error
![image](https://github.com/t3-oss/create-t3-app/assets/35634442/5c17c368-5a26-43a2-a806-aa00b6132cef)

### Reproduction repo

bun create t3-app@latest --CI --trpc --drizzle --appRouter

### To reproduce

1) Generate a t3 app with the options above
2) Change the default `DATABASE_URL` in `.env`
3) Run `npm run lint`

**Comment by c-ehrlich** [comment]
I can't seem to reproduce this

![CleanShot 2023-10-21 at 22 53 57@2x](https://github.com/t3-oss/create-t3-app/assets/8353666/bb13a2ae-1149-4949-99c7-1527a2548fc7)

Can anyone else reproduce?

**Comment by ronanru** [comment]
Fixed this issue by clearing bun cache and node_modules and reinstalling everything.
