### ISSUE TITLE
feat: Replace prettier-plugin-tailwindcss with eslint-plugin-tailwindcss?

### ISSUE THREAD

**Issue by DestroyerXyz** [t3-oss/create-t3-app#1616]
### Is your feature request related to a problem? Please describe.

IMO [eslint-plugin-tailwindcss](https://github.com/francoismassart/eslint-plugin-tailwindcss) offers a better experience than the [official prettier plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss).
It also comes with a few other rules for strictness and readability.

### Describe the solution you'd like to see

Replace prettier-plugin-tailwindcss with eslint-plugin-tailwindcss by default.

### Describe alternate solutions

N/A

### Additional information

Can open a PR if enough people are interested.

**Comment by ronanru** [comment]
prettier plugin is what tailwind team recommends

**Comment by DestroyerXyz** [comment]
Yeah that's true but at least partly because it's their official plugin.
I think it's about what can give a better experience and what people would prefer by default.

**Comment by juliusmarminge** [comment]
I dont think it makes sense to switch the default here;

- Formstting with a linter isnt the best, and from my experience just slows down your editor. Eslint is already slow as is so using it for formatting only makes it worse? I've never had prettier die on me.

- Iirc it took the eslint plugin quite a while for adding support for esm/ts config support (not sure if it even has it now but i assume it does), the prettier plugin had it day 1. Using the eslint plugin would perhaps "delay" us from updating the dependency for new tailwind releases?

I like the idea of the eslint plugin and it got some rules that are kinda nice, but i think there are more gotchas than benefits that makes the official prettier plugin a better default

**Comment by DestroyerXyz** [comment]
makes sense, thanks for considering it!

**Comment by FleetAdmiralJakob** [comment]
Could we rename this issue and talk about if we want to add the eslint-plugin-tailwindcss without its formatting which relies on the prettier plugin since the 3.6 anyways?
