### ISSUE TITLE
feat: Add neon || planetscale to relation database options (postgres || mysql)

### ISSUE THREAD

**Issue by Byevenes** [t3-oss/create-t3-app#1617]
### Is your feature request related to a problem? Please describe.

I think that for the cases that one has a preference between postgres or mysql we can choose which way to go.

### Describe the solution you'd like to see

Add an option within the command cli in which we can choose whether to use neon serverless || planetscale serverless

### Describe alternate solutions

Poder escoger si uno prefiere utilizar quizás postgres en cambio de mysql y de esa manera deducir si por default dejar neon || planetscale

**Comment by ronanru** [comment]
Great idea! I would love to see something like that!
```
Which database driver would you like to use?
> MySQL
  Postgres
  PlanetScale Edge Driver
  Neon Edge Driver
  Turso (LibSQL)
```

**Comment by arndeash** [comment]
This becomes more relevant now, as Planetscale killed their free tier.
