### ISSUE TITLE
feat: Add documentation about envs in testing frameworks

### ISSUE THREAD

**Issue by kyeshmz** [t3-oss/create-t3-app#1619]
### Is your feature request related to a problem? Please describe.

Add documentation about having to have a envPrefix for working with secrets in vitest or other documentation on how to handle test envs in other frameworks.

### Describe the solution you'd like to see

Add some documentation about [issue 99](https://github.com/t3-oss/t3-env/issues/99) in t3env.

I am proposing some kind of documentation like
```
For this to work within NextJS and secrets, consider adding the `envPrefix` argument to your config file.

```ts
export default defineConfig({
  plugins: [react()],
  envPrefix: "NEXT_PUBLIC_",
 ....
})
```

### Describe alternate solutions

Some other way to automatically pass all env.mjs files to vitest

**Comment by juliusmarminge** [comment]
don't see where this would fit in to the current documentation
