### ISSUE TITLE
bug (ci): changeset should only be required on changes to cli and outputted app 

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#1623]
### Describe the bug

Currently the CI throws an error on any PR that doesn't include a changeset. However the intended behaviour is that changesets should only be required on changes to the CLI or scaffolded app, ie anything in `/cli` (or maybe even anything in `/cli` except readmes etc)

**Comment by Jacksonmills** [comment]
I tried a fix for this, is there a good way to test the ci workflow locally?
