### ISSUE TITLE
bug: glitches out when you want to use js

### ISSUE THREAD

**Issue by joe-bro-1** [t3-oss/create-t3-app#1629]
### Provide environment information

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 88.28 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm

### create t3 app glitches out when i try to use JavaScript
i ran `npm create t3-app@latest` when asked if using JavaScript or typescript i selected JavaScript and it responded `Wrong answer, using TypeScript instead` i tried on my mac, on gitpod and codesanbox

### Reproduction repo

non applicable

### To reproduce

run `npm create t3-app@latest`
when prompted select javascript
<img width="437" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/117040706/27640a01-ed39-43fa-851c-17632d61fca7">

### Additional information

<img width="423" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/117040706/64c12c47-ec29-4956-959a-ce61764d601c">

**Comment by Jacksonmills** [comment]
Intended, t3 stack only supports typescript

**Comment by joe-bro-1** [comment]
so why is js an option

**Comment by Jacksonmills** [comment]
it is more of an easter egg/joke as far as I know 😄 t3 is type safe by default so it wouldn't really make sense to allow for javascript
