### ISSUE TITLE
feat: Suggestion to use the same import alias as Nextjs

### ISSUE THREAD

**Issue by davesierra** [t3-oss/create-t3-app#1630]
### Is your feature request related to a problem? Please describe.

Hello, I'm new to T3, and was giving it a try alongside the typical `create-next-app@latest` setup and I noticed that T3 uses `~` by default while nextjs uses `@` by default. Since T3 is based on Nextjs, I was wondering why the difference? It would be an easier transition/switch from one to the other if it was kept the same, avoids confusion, makes it one less step to change, etc.

Thanks, keep up the great work and excited to try t3 with the newly added app router support.

### Describe the solution you'd like to see

I'd like the default import alias to be the same as Nextjs, `@`

### Describe alternate solutions

In case Nextjs used `~` in a previous version (or such when using page instead of app router) be able to auto detect this?

**Comment by c-ehrlich** [comment]
The import alias has nothing to do with Next.js or any other framework. It's just a setting in the tsconfig. We are defaulting to `~` because a lot of npm packages start with `@` nowadays. If you want to use `@`, you can change it, that's why we made it an option in the CLI.

**Comment by davesierra** [comment]
I think you misunderstood me, but I get the feeling that the answer is "it's an opinionated decision", which is absolutely fine. Thank you.
