### ISSUE TITLE
bug: selector in landing page not working (right side button of `npm create t3-app@latest`)

### ISSUE THREAD

**Issue by FMGordillo** [t3-oss/create-t3-app#1632]
### Provide environment information

N/A

### Describe the bug

![bug](https://github.com/t3-oss/create-t3-app/assets/7970174/0ae67586-cfe0-46da-84b7-e188a41e5db1)

### Reproduction repo

Go to the landing page and select an option

### To reproduce

Go to the landing page and select an option

### Additional information

Browser: `[Version 1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit)](https://brave.com/latest/)`
OS: NixOS 23.05

**Comment by FMGordillo** [comment]
Will this be solved in [the `next` branch](https://github.com/t3-oss/create-t3-app/blob/next/www/src/components/landingPage/ClipboardSelect.tsx)?

**Comment by juliusmarminge** [comment]
The copied text should be the correct package manager though? That's the intended behavior and is similar to how shadcn does it which got really good reception

**Comment by FMGordillo** [comment]
Ah, I see, IMO it's not very intuitive, but we are not here to discuss usability, but rather a bug report

Thanks for the response @juliusmarminge! Closing
