### ISSUE TITLE
feat: Drizzle Postgres variant

### ISSUE THREAD

**Issue by zeevo** [t3-oss/create-t3-app#1633]
### Is your feature request related to a problem? Please describe.

Instead of MySQL/Planetscale being the default for the `drizzle` selection, can we have a choice of Postgres?

### Describe the solution you'd like to see

Postgres either being the default `dizzle` implementation or a selection between MySQL and Postgres.

### Describe alternate solutions

Postgres is the default solution for drizzle. No choice of MySQL.

**Comment by juliusmarminge** [comment]
Duplicate #1617
