### ISSUE TITLE
bug: byte index 6 is out of bounds of `\ud`byte index 6 is out of bounds of `\ud`

### ISSUE THREAD

**Issue by darklight9811** [t3-oss/create-t3-app#1637]
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 6.10 GB / 15.96 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.0.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.7 - ~\AppData\Local\pnpm\pnpm.CMD

### Describe the bug

When I scaffold a new project (no changes made) it throws the following error:

```
C:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.145.5\src\lib.rsC:\Users\JayJa\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_codegen-0.145.5\src\lib.rs::38723872::5353:
:
byte index 6 is out of bounds of `\ud`byte index 6 is out of bounds of `\ud`

 ⨯ ./node_modules/next/dist/client/components/app-router.js
Error: failed to process byte index 6 is out of bounds of `\ud`

Import trace for requested module:
./node_modules/next/dist/client/components/app-router.js
./node_modules/next/dist/server/app-render/entry-base.js
```

The bug doesnt occur when I create with the next default

### Reproduction repo

wasnt able to reproduce on codesandbox

### To reproduce

- scaffold a new project
- apply true to all options (include app)

**Comment by c-ehrlich** [comment]
Seems to be (yet another) issue with the terminal Windows. Please use WSL2. Unfortunately there isn't anything we can do about Windows terminal being terrible.
