### ISSUE TITLE
bug: tRPC error boilerplate code deploying to vercel breaks site

### ISSUE THREAD

**Issue by prestonButton** [t3-oss/create-t3-app#1639]
### Provide environment information

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 80.75 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - /opt/homebrew/bin/node
    npm: 10.2.0 - /opt/homebrew/bin/npm
    pnpm: 8.1.1 - /opt/homebrew/bin/pnpm

### Describe the bug

Used bun create t3-app@latest after upgrading to NextJS 14. I ran it locally and it all worked fine. I then created a repo and tried to deploy to Vercel but I got a build error related to tRPC and an error displayed in the window (Screenshots attached). I then tested this using pnpm and npm and same result. App without tRPC deployed fine. 
<img width="1171" alt="Screenshot 2023-10-31 at 4 52 16 PM" src="https://github.com/t3-oss/create-t3-app/assets/98365800/5cd6bdb3-b90b-4a65-a4c9-0ce454a06c2e">
![image](https://github.com/t3-oss/create-t3-app/assets/98365800/5ddffafa-1e66-4259-877a-cfafad540e3c)

### Reproduction repo

https://github.com/prestonButton/bbqapp

### To reproduce

This app is just the create-t3-app boilerplate code. I ran bun db:push, bun run dev, and then tried to deploy. and got the errors described above. Just wondering if this is because I am using NextJS 14.

**Comment by DeanJMorgan** [comment]
I'm getting the same issue at build time, also noticed the following error in the runtime logs.

```
[97;46m << query [1;97;46m #3 post.hello [0m {
  input: { text: 'from tRPC' },
  result: TRPCClientError: Unexpected token ; in JSON at position 4
      at TRPCClientError.from (/var/task/.next/server/chunks/152.js:1:25003)
      at /var/task/.next/server/chunks/152.js:1:29521
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    meta: undefined,
    shape: undefined,
    data: undefined,
    [cause]: SyntaxError: Unexpected token ; in JSON at position 4
        at JSON.parse (<anonymous>)
        at parse (/var/task/.next/server/chunks/152.js:5:4111)
        at /var/task/.next/server/chunks/152.js:5:3218
        at onChunk (/var/task/.next/server/chunks/152.js:5:3371)
        at readStandardChunks (/var/task/.next/server/chunks/152.js:5:3698)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async readLines (/var/task/.next/server/chunks/152.js:5:3452)
        at async parseJSONStream (/var/task/.next/server/chunks/152.js:5:3058)
  },
  elapsedMs: 24
}
TRPCClientError: Unexpected token ; in JSON at position 4
    at TRPCClientError.from (/var/task/.next/server/chunks/152.js:1:25003)
    at /var/task/.next/server/chunks/152.js:1:29521
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: SyntaxError: Unexpected token ; in JSON at position 4
      at JSON.parse (<anonymous>)
      at parse (/var/task/.next/server/chunks/152.js:5:4111)
      at /var/task/.next/server/chunks/152.js:5:3218
      at onChunk (/var/task/.next/server/chunks/152.js:5:3371)
      at readStandardChunks (/var/task/.next/server/chunks/152.js:5:3698)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async readLines (/var/task/.next/server/chunks/152.js:5:3452)
      at async parseJSONStream (/var/task/.next/server/chunks/152.js:5:3058)
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '1526301433'
}
```

**Comment by c-ehrlich** [comment]
could you confirm that this is still happening with a new app scaffolded with `bun create t3-app@latest` today? It should have been fixed two days ago with https://github.com/t3-oss/create-t3-app/pull/1644

<img width="868" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/8353666/8ba1db4b-9764-4d3e-8e56-07dad25e56cd">

Build and deployment on vercel is working for me currently

**Comment by DeanJMorgan** [comment]
Just tried again using `bun create t3-app@latest` and got the same error. 

Here is a link to the repo https://github.com/DeanJMorgan/t3-bun-test-deploy

Here is a link to the app https://t3-bun-test-deploy.vercel.app/

From the build logs: 
```
Creating an optimized production build ...
--
14:33:24.770 | ✓ Compiled successfully
14:33:24.771 | Linting and checking validity of types ...
14:33:31.715 | Collecting page data ...
14:33:33.064 | Generating static pages (0/4) ...
14:33:33.256 | << query  #1 post.hello  {
14:33:33.256 | input: { text: 'from tRPC' },
14:33:33.256 | result: TRPCClientError: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
14:33:33.256 | at TRPCClientError.from (/vercel/path0/.next/server/chunks/152.js:1:25003)
14:33:33.256 | at /vercel/path0/.next/server/chunks/152.js:1:29521
14:33:33.256 | at processTicksAndRejections (node:internal/process/task_queues:95:5)
14:33:33.256 | at runNextTicks (node:internal/process/task_queues:64:3)
14:33:33.257 | at listOnTimeout (node:internal/timers:538:9)
14:33:33.257 | at process.processTimers (node:internal/timers:512:7) {
14:33:33.257 | meta: undefined,
14:33:33.257 | shape: undefined,
14:33:33.257 | data: undefined,
14:33:33.257 | [cause]: DynamicServerError: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
14:33:33.257 | at staticGenerationBailout (/vercel/path0/.next/server/chunks/526.js:1:4547)
14:33:33.257 | at cookies (/vercel/path0/.next/server/chunks/526.js:1:1510)
14:33:33.257 | at Object.headers (/vercel/path0/.next/server/app/page.js:1:3699)
14:33:33.257 | at Object.headers (/vercel/path0/.next/server/chunks/152.js:5:4503)
14:33:33.257 | at fetchHTTPResponse (/vercel/path0/.next/server/chunks/152.js:1:26627)
14:33:33.257 | at streamingJsonHttpRequester (/vercel/path0/.next/server/chunks/152.js:5:3818)
14:33:33.257 | at Object.fetch (/vercel/path0/.next/server/chunks/152.js:5:4372)
14:33:33.257 | at Timeout.dispatch (/vercel/path0/.next/server/chunks/152.js:1:28130)
14:33:33.257 | at listOnTimeout (node:internal/timers:569:17)
14:33:33.258 | at process.processTimers (node:internal/timers:512:7) {
14:33:33.258 | digest: 'DYNAMIC_SERVER_USAGE'
14:33:33.258 | }
14:33:33.258 | },
14:33:33.258 | elapsedMs: 14
14:33:33.258 | }
14:33:33.258 | << query  #2 post.hello  {
14:33:33.258 | input: { text: 'from tRPC' },
14:33:33.258 | result: TRPCClientError: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
14:33:33.258 | at TRPCClientError.from (/vercel/path0/.next/server/chunks/152.js:1:25003)
14:33:33.258 | at /vercel/path0/.next/server/chunks/152.js:1:29521
14:33:33.258 | at processTicksAndRejections (node:internal/process/task_queues:95:5)
14:33:33.259 | at runNextTicks (node:internal/process/task_queues:64:3)
14:33:33.259 | at listOnTimeout (node:internal/timers:538:9)
14:33:33.259 | at process.processTimers (node:internal/timers:512:7) {
14:33:33.259 | meta: undefined,
14:33:33.259 | shape: undefined,
14:33:33.259 | data: undefined,
14:33:33.259 | [cause]: DynamicServerError: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
14:33:33.259 | at staticGenerationBailout (/vercel/path0/.next/server/chunks/526.js:1:4547)
14:33:33.259 | at cookies (/vercel/path0/.next/server/chunks/526.js:1:1510)
14:33:33.260 | at Object.headers (/vercel/path0/.next/server/app/page.js:1:3699)
14:33:33.260 | at Object.headers (/vercel/path0/.next/server/chunks/152.js:5:4503)
14:33:33.260 | at fetchHTTPResponse (/vercel/path0/.next/server/chunks/152.js:1:26627)
14:33:33.260 | at streamingJsonHttpRequester (/vercel/path0/.next/server/chunks/152.js:5:3818)
14:33:33.260 | at Object.fetch (/vercel/path0/.next/server/chunks/152.js:5:4372)
14:33:33.260 | at Timeout.dispatch (/vercel/path0/.next/server/chunks/152.js:1:28130)
14:33:33.261 | at listOnTimeout (node:internal/timers:569:17)
14:33:33.261 | at process.processTimers (node:internal/timers:512:7) {
14:33:33.261 | digest: 'DYNAMIC_SERVER_USAGE'
14:33:33.261 | }
14:33:33.261 | },
14:33:33.261 | elapsedMs: 1
14:33:33.262 | }
```

From the runtime logs:
```
NOV 05 14:57:14.54
-
t3-bun-test-deploy.vercel.app
[GET] /
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] { digest: '1526301433' }
NOV 05 14:57:14.52
-
t3-bun-test-deploy.vercel.app
[GET] /
TRPCClientError: Unexpected token ; in JSON at position 4 at TRPCClientError.from (/var/task/.next/server/chunks/152.js:1:25003) at /var/task/.next/server/chunks/152.js:1:29521 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { meta: undefined, shape: undefined, data: undefined, [cause]: SyntaxError: Unexpected token ; in JSON at position 4 at JSON.parse (<anonymous>) at parse (/var/task/.next/server/chunks/152.js:5:4111) at /var/task/.next/server/chunks/152.js:5:3218 at onChunk (/var/task/.next/server/chunks/152.js:5:3371) at readStandardChunks (/var/task/.next/server/chunks/152.js:5:3698) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async readLines (/var/task/.next/server/chunks/152.js:5:3452) at async parseJSONStream (/var/task/.next/server/chunks/152.js:5:3058) }
NOV 05 14:57:14.52
-
t3-bun-test-deploy.vercel.app
[GET] /
[97;46m << query [1;97;46m #2 post.hello [0m { input: { text: 'from tRPC' }, result: TRPCClientError: Unexpected token ; in JSON at position 4 at TRPCClientError.from (/var/task/.next/server/chunks/152.js:1:25003) at /var/task/.next/server/chunks/152.js:1:29521 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) { meta: undefined, shape: undefined, data: undefined, [cause]: SyntaxError: Unexpected token ; in JSON at position 4 at JSON.parse (<anonymous>) at parse (/var/task/.next/server/chunks/152.js:5:4111) at /var/task/.next/server/chunks/152.js:5:3218 at onChunk (/var/task/.next/server/chunks/152.js:5:3371) at readStandardChunks (/var/task/.next/server/chunks/152.js:5:3698) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async readLines (/var/task/.next/server/chunks/152.js:5:3452) at async parseJSONStream (/var/task/.next/server/chunks/152.js:5:3058) }, elapsedMs: 58 }
NOV 05 14:57:14.33
500
t3-bun-test-deploy.vercel.app
[GET] /
[GET] / status=500
```

**Comment by DeanJMorgan** [comment]
I'm also getting the same error in the build logs when using an earlier version (7.22.0) of create-t3-app and deploying to Vercel.

I'm not making any changes, just pushing the initial commit and then deploying. Not sure if that info helps, but thought it's worth sharing.

**Comment by sscotth** [comment]
Same issue with tRPC + App Router.

`TRPCClientError: Unexpected token ; in JSON at position 4`

Works on `localhost`, but not on vercel.  tRPC + Pages Router works fine. no tRPC + App Router works fine. Tested with both `bun create t3-app@latest` and `npm create t3-app@latest`

**Comment by sscotth** [comment]
Confirmed disabling Vercel Authentication fixes the issue.

<img width="946" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/1010488/785e35b3-755f-483e-9646-d608af18ef3f">

**Comment by FleetAdmiralJakob** [comment]
> I'm getting the same issue at build time, also noticed the following error in the runtime logs.
> 
> ```
> [97;46m << query �[1;97;46m #3 post.hello �[0m {
>   input: { text: 'from tRPC' },
>   result: TRPCClientError: Unexpected token ; in JSON at position 4
>       at TRPCClientError.from (/var/task/.next/server/chunks/152.js:1:25003)
>       at /var/task/.next/server/chunks/152.js:1:29521
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>     meta: undefined,
>     shape: undefined,
>     data: undefined,
>     [cause]: SyntaxError: Unexpected token ; in JSON at position 4
>         at JSON.parse (<anonymous>)
>         at parse (/var/task/.next/server/chunks/152.js:5:4111)
>         at /var/task/.next/server/chunks/152.js:5:3218
>         at onChunk (/var/task/.next/server/chunks/152.js:5:3371)
>         at readStandardChunks (/var/task/.next/server/chunks/152.js:5:3698)
>         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>         at async readLines (/var/task/.next/server/chunks/152.js:5:3452)
>         at async parseJSONStream (/var/task/.next/server/chunks/152.js:5:3058)
>   },
>   elapsedMs: 24
> }
> TRPCClientError: Unexpected token ; in JSON at position 4
>     at TRPCClientError.from (/var/task/.next/server/chunks/152.js:1:25003)
>     at /var/task/.next/server/chunks/152.js:1:29521
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   meta: undefined,
>   shape: undefined,
>   data: undefined,
>   [cause]: SyntaxError: Unexpected token ; in JSON at position 4
>       at JSON.parse (<anonymous>)
>       at parse (/var/task/.next/server/chunks/152.js:5:4111)
>       at /var/task/.next/server/chunks/152.js:5:3218
>       at onChunk (/var/task/.next/server/chunks/152.js:5:3371)
>       at readStandardChunks (/var/task/.next/server/chunks/152.js:5:3698)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async readLines (/var/task/.next/server/chunks/152.js:5:3452)
>       at async parseJSONStream (/var/task/.next/server/chunks/152.js:5:3058)
> }
> [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
>   digest: '1526301433'
> }
> ```

I got this error today. Is there a fix?

**Comment by c-ehrlich** [comment]
@FleetAdmiralJakob  The PR linked above your post will fix it. Needs one more change and then it can land :)
