### ISSUE TITLE
feat: Prisma Edge Client

### ISSUE THREAD

**Issue by Wundero** [t3-oss/create-t3-app#1646]
### Is your feature request related to a problem? Please describe.

Prisma 5.4.0 added support for driver adapters to use serverless adapters over HTTP (and WS, for neon). This completes support for the Edge via PlanetScale using Prisma, previously only possible using Drizzle. Note that this also does NOT require Prisma's "Accelerate" service to use, from what I have read.

This could work really well in concert with https://github.com/t3-oss/create-t3-app/pull/1622, as selecting PlanetScale Serverless as an option would work nicely both on Prisma and on Drizzle.

### Describe the solution you'd like to see

Add a separate DB client (or just use the edge client) for edge environments:

```ts
// Import required dependencies
import { connect } from '@planetscale/database';
import { PrismaPlanetScale } from '@prisma/adapter-planetscale';
import { PrismaClient } from '@prisma/client/edge';
import { env } from "~/env.mjs";

// Setup global primitives
const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

// Initialize Prisma Client with the PlanetScale serverless database driver
const connection = connect({ url: env.DATABASE_URL });
const adapter = new PrismaPlanetScale(connection);

export const db =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"],
    adapter,
  });

if (env.NODE_ENV !== "production") globalForPrisma.prisma = db;
```

Required dependencies:
`prisma` and `@prisma/client`: 5.4.0 or higher (latest as of writing is 5.5.2)
`@prisma/adapter-planetscale`: Same version as Prisma
`@planetscale/database`: Same version as used in current deployments with PlanetScale.

This also requires the `driverAdapters` feature flag to be enabled. Since it is technically not generally availaible, this combination of options might be best marked as "experimental" in the CLI.

I also am not entirely sure about whether the edge client requires the weird `global` manipulation that the normal client does, since it operates differently (and in theory, connection pooling that causes the normal one to be problematic isn't present on the edge variant), but that requires testing that I have not yet performed.

### Describe alternate solutions

N/A

**Comment by juliusmarminge** [comment]
Part of #1622 ?

**Comment by Wundero** [comment]
I tried this out in an experiment, and it seems that Prisma currently (artificially?) blocks the PlanetScale serverless driver when you use the Edge client - they plan to support it in the near future afaik, but there is currently a block that prevents URLs that don't start with `prisma://` in the client. This might be something that has to be put on hold for a while if that happens, though the serverless driver is probably still good to include even if it doesn't support edge yet.
