### ISSUE TITLE
bug: bun create t3-app@latest CLI freezes on tailwind step

### ISSUE THREAD

**Issue by tralawar** [t3-oss/create-t3-app#1653]
### Provide environment information

System:
    OS: Windows 11 10.0.22621
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 49.26 GB / 63.77 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.6 - ~\AppData\Roaming\npm\pnpm.CMD

### Describe the bug

`bun create t3-app@latest` CLI freezes on tailwind step

### Reproduction repo

na

### To reproduce

`bun create t3-app@latest`
`enter`
`enter`

**Comment by c-ehrlich** [comment]
can't reproduce. could you provide a more precise set of steps to reproduce this on another system?

![CleanShot 2023-11-09 at 09 14 31@2x](https://github.com/t3-oss/create-t3-app/assets/8353666/2371fbb5-1849-4e94-b7c2-1c786fc487cf)

**Comment by juliusmarminge** [comment]
bun on windows is still beta so we can't assure things will work there. most likely not an issue caused by create-t3-app

**Comment by rayhanasyraff** [comment]
I got the same problem, do anybody here know how to solve this on your wsl?
