### ISSUE TITLE
bug: Recent Commit Breaks Clerk Based Authentication w/ tRPC

### ISSUE THREAD

**Issue by Jacksonmills** [t3-oss/create-t3-app#1656]
### Provide environment information

  "initVersion": "7.23.2"
  
  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 9.02 GB / 15.58 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.9.2 - ~/.local/share/pnpm/pnpm
    bun: 1.0.7 - ~/.bun/bin/bun

### Describe the bug
I've encountered an issue with the recent changes introduced in commit [e6649f18963086b2d016815e60cc9915711a85d8](https://github.com/t3-oss/create-t3-app/commit/e6649f18963086b2d016815e60cc9915711a85d8). These changes appear to have broken the Clerk based authentication, which in turn is affecting the functionality of tRPC in my application.

### Reproduction repo
https://github.com/Jacksonmills/gpts-browser

### To reproduce
To reproduce, revert the changes back to main in this commit [e6649f18963086b2d016815e60cc9915711a85d8](https://github.com/t3-oss/create-t3-app/commit/e6649f18963086b2d016815e60cc9915711a85d8). Once reverted, log in with Clerk and visit a page with a query to get:
```
Unhandled Runtime Error
Error: Cannot read properties of undefined (reading 'resolve')
```
![image](https://github.com/t3-oss/create-t3-app/assets/19780885/d5694bc3-60e3-433c-a6bc-da99978beeba)

### Additional information
I was able to revert the changes in the problematic commit, which fixes all my issues. However, I would love if someone could further explain or suggest how we can go back to using cookies while also making Clerk work. That would be ideal! Thank you. 👏

**Comment by w00kie** [comment]
Hitting the same issue.

**Comment by Jacksonmills** [comment]
> Hitting the same issue.

In the meantime if you just revert the changes from the linked commit Clerk will work fine

**Comment by sfarrowGR** [comment]
same problem here.  Had to make the reversion mentioned above.

**Comment by weisisheng** [comment]
Does anyone have a good working version of a simple server/api/trpc.ts which incorporates clerk?  most of the docs floating around have not kept up with a myriad of changes, and I am still trying to wrap my head around combining numerous items in to inner/outer context.  TIA.

**Comment by Jacksonmills** [comment]
> Does anyone have a good working version of a simple server/api/trpc.ts which incorporates clerk?  most of the docs floating around have not kept up with a myriad of changes, and I am still trying to wrap my head around combining numerous items into inner/outer context.  TIA.

https://clerk.com/docs/references/nextjs/trpc

Clerk does provide a simple guide when setting up with tRPC

Aside from the bug with headers mentioned in the ticket I haven't had any issues integrating Clerk with t3

LMK if that helped you

**Comment by eula01** [comment]
unreal that this has been getting 0 attention in the community

**Comment by eula01** [comment]
@t3dotgg please be aware of this when shilling clerk – unuseable DX  – clerk is fundamentally broken + incompatible with trpc & app router – and clerk devs have been radio silent for >2 months – 100s and 100s of comments and discussions on clerk discord and nothing!

**Comment by michaelhvisser** [comment]
Hey everyone. I replaced my code in my trpc/server.ts with this code and thing are working for me now. 

`import {
  createTRPCProxyClient,
  loggerLink,
  unstable_httpBatchStreamLink,
} from "@trpc/client";
import { headers } from "next/headers";

import { type AppRouter } from "~/server/api/root";
import { getUrl, transformer } from "./shared";

export const api = createTRPCProxyClient<AppRouter>({
  transformer,
  links: [
    loggerLink({
      enabled: (op) =>
        process.env.NODE_ENV === "development" ||
        (op.direction === "down" && op.result instanceof Error),
    }),
    unstable_httpBatchStreamLink({
      url: getUrl(),
      headers() {
        const heads = new Map(headers());
        heads.set("x-trpc-source", "rsc");
        return Object.fromEntries(heads);
      },
    }),
  ],
});
`

**Comment by Arechii** [comment]
I had the same issue because Clerk was not happy that the user agent was missing after transitioning from headers to cookies only. My temporary fix was to include the bearer token.

```tsx
import { cookies } from "next/headers"
import { auth } from "@clerk/nextjs"
import {
  createTRPCProxyClient,
  loggerLink,
  unstable_httpBatchStreamLink,
} from "@trpc/client"
import { type AppRouter } from "~/server/api/root"

import { getUrl, transformer } from "./shared"

export const api = createTRPCProxyClient<AppRouter>({
  transformer,
  links: [
    loggerLink({
      enabled: (op) =>
        process.env.NODE_ENV === "development" ||
        (op.direction === "down" && op.result instanceof Error),
    }),
    unstable_httpBatchStreamLink({
      url: getUrl(),
      async headers() {
        return {
          cookie: cookies().toString(),
          "x-trpc-source": "rsc",
          Authorization: `Bearer ${await auth().getToken()}`,
        }
      },
    }),
  ],
})
```

**Comment by Jacksonmills** [comment]
> I had the same issue because Clerk was not happy that the user agent was missing after transitioning from headers to cookies only. I fixed it for now by including the bearer token.
> 
> ```tsx
> import { cookies } from "next/headers"
> import { auth } from "@clerk/nextjs"
> import {
>   createTRPCProxyClient,
>   loggerLink,
>   unstable_httpBatchStreamLink,
> } from "@trpc/client"
> import { type AppRouter } from "~/server/api/root"
> 
> import { getUrl, transformer } from "./shared"
> 
> export const api = createTRPCProxyClient<AppRouter>({
>   transformer,
>   links: [
>     loggerLink({
>       enabled: (op) =>
>         process.env.NODE_ENV === "development" ||
>         (op.direction === "down" && op.result instanceof Error),
>     }),
>     unstable_httpBatchStreamLink({
>       url: getUrl(),
>       async headers() {
>         return {
>           cookie: cookies().toString(),
>           "x-trpc-source": "rsc",
>           Authorization: `Bearer ${await auth().getToken()}`,
>         }
>       },
>     }),
>   ],
> })
> ```

nice much simpler fix 👏

**Comment by Jacksonmills** [comment]
Nice @Arechii this worked for me, much easier than fully reverting the previous commit. I wonder... is this a potential long term fix? Also don't forget to add to your `server.ts` asw as `react.tsx`

**Comment by Jacksonmills** [comment]
@juliusmarminge thoughts on this as a long term fix?

**Comment by juliusmarminge** [comment]
Looks like Clerk requires a bunch of headers...

https://github.com/clerk/javascript/blob/dde4399b5ea2ac30b0a066f3f97c90dabf6038ee/packages/backend/src/constants.ts#L20C10-L36

**Comment by JacobMGEvans** [comment]
> clerk is still broken + unuseable with next app router + trpc – unreal that this has been getting 0 attention in the community

Hey @eula01, which community are you referring to? In Clerk we are addressing this tRPC issue and Roy is working on definitive workarounds. If there is something in particular we haven't addressed or you have additional concerns, please let us know. 

@Jacksonmills I appreciate you bringing this up here and in Clerk, we will be collaborating with Julius and potentially tRPC members as well if necessary to find the right pattern/workaround, and then find the best path forward from there for a more permanent solution.

**Comment by Jacksonmills** [comment]
That's great to hear thanks!

**Comment by bhatvikrant** [comment]
"initVersion": "7.24.1"

Ik this issue is closed but I am facing the following error:
```
Cannot read properties of undefined (reading 'headers') 
```

I am using clerk with the latest version of T3, App router.


Contents of my `trpc.ts` file are:
```js
/**
 * YOU PROBABLY DON'T NEED TO EDIT THIS FILE, UNLESS:
 * 1. You want to modify request context (see Part 1).
 * 2. You want to create a new middleware or type of procedure (see Part 3).
 *
 * TL;DR - This is where all the tRPC server stuff is created and plugged in. The pieces you will
 * need to use are documented accordingly near the end.
 */
import { SignedInAuthObject, SignedOutAuthObject, getAuth } from "@clerk/nextjs/server";
import { TRPCError, initTRPC } from "@trpc/server";
import superjson from "superjson";
import { ZodError } from "zod";
import * as trpcNext from '@trpc/server/adapters/next';

import { db } from "~/server/db";

/**
 * 1. CONTEXT
 *
 * This section defines the "contexts" that are available in the backend API.
 *
 * These allow you to access things when processing a request, like the database, the session, etc.
 *
 * This helper generates the "internals" for a tRPC context. The API handler and RSC clients each
 * wrap this and provides the required context.
 *
 * @see https://trpc.io/docs/server/context
 */
interface AuthContext {
  auth: SignedInAuthObject | SignedOutAuthObject;
}
 
export const createContextInner = async ({ auth }: AuthContext  ) => {
  return {
    db,
    auth
  }
}


export const createTRPCContext = async (opts: trpcNext.CreateNextContextOptions) => {
  // return {
  //   db,
  //   ...opts,
  // };

  return await createContextInner({ auth: getAuth(opts.req) })
};

/**
 * 2. INITIALIZATION
 *
 * This is where the tRPC API is initialized, connecting the context and transformer. We also parse
 * ZodErrors so that you get typesafety on the frontend if your procedure fails due to validation
 * errors on the backend.
 */
const t = initTRPC.context<typeof createTRPCContext>().create({
  transformer: superjson,
  errorFormatter({ shape, error }) {
    return {
      ...shape,
      data: {
        ...shape.data,
        zodError:
          error.cause instanceof ZodError ? error.cause.flatten() : null,
      },
    };
  },
});

/**
 * 3. ROUTER & PROCEDURE (THE IMPORTANT BIT)
 *
 * These are the pieces you use to build your tRPC API. You should import these a lot in the
 * "/src/server/api/routers" directory.
 */

/**
 * This is how you create new routers and sub-routers in your tRPC API.
 *
 * @see https://trpc.io/docs/router
 */
export const createTRPCRouter = t.router;

/**
 * Public (unauthenticated) procedure
 *
 * This is the base piece you use to build new queries and mutations on your tRPC API. It does not
 * guarantee that a user querying is authorized, but you can still access user session data if they
 * are logged in.
 */
export const publicProcedure = t.procedure;


// check if the user is signed in, otherwise throw a UNAUTHORIZED CODE
const isAuthed = t.middleware(({ next, ctx }) => {
  if (!ctx.auth.userId) {
    throw new TRPCError({ code: 'UNAUTHORIZED', message: 'User is not logged in, from middleware.' })
  }
  return next({
    ctx: {
      auth: ctx.auth,
    },
  })
})

export const protectedProcedure = t.procedure.use(isAuthed)

```

as soon as I make this change I start getting errors in `src/trpc/server.ts` and `src/app/api/trpc/[trpc]/route.ts`

`src/trpc/server.ts file`
<img width="876" alt="src/trpc/server.ts file" src="https://github.com/t3-oss/create-t3-app/assets/50735025/994c5575-63b4-42fa-9d29-a2b4b8d0361c">

`src/trpc/server.ts error`
<img width="868" alt="src/trpc/server.ts error" src="https://github.com/t3-oss/create-t3-app/assets/50735025/f355fde9-fe52-467e-8372-7c769e97920c">

`src/app/api/trpc/[trpc]/route.ts file`
<img width="869" alt="src/app/api/trpc/[trpc]/route.ts file" src="https://github.com/t3-oss/create-t3-app/assets/50735025/c47688d8-f81f-4fc1-93a4-23aa433c6bf6">

`src/app/api/trpc/[trpc]/route.ts error`
<img width="918" alt="src/app/api/trpc/[trpc]/route.ts error" src="https://github.com/t3-oss/create-t3-app/assets/50735025/c5523b09-50fe-4add-a20f-54883945138b">

Not sure what is wrong here, I followed the [clerk docs for integrating with trpc](https://clerk.com/docs/references/nextjs/trpc#integrate-clerk-into-your-next-js-app-with-t-rpc)

@juliusmarminge @JacobMGEvans @Jacksonmills

**Comment by mkcode** [comment]
HI All - I got TRPC and Clerk, both server and client calls, working nicely in my app. Relevant changes are in this gist: https://gist.github.com/mkcode/a590d1c8f7b0a37b8299965de7f7e958

**Comment by imopbuilder** [comment]
can we use the ```auth``` function instead of ```getAuth()``` which will not require the **req** parameter

https://clerk.com/docs/references/nextjs/auth#auth

![image](https://github.com/t3-oss/create-t3-app/assets/150527559/5fb0e05e-7e3f-4bf4-8adf-1822f6bdf3da)

**Comment by mike-pete** [comment]
@imopbuilder thank you for [this note ^](https://github.com/t3-oss/create-t3-app/issues/1656#issuecomment-1891002143)
It was super helpful! 🙌
