### ISSUE TITLE
bug: "Error: fetch failed" with Drizzle + App Router

### ISSUE THREAD

**Issue by TheVoxcraft** [t3-oss/create-t3-app#1660]
### Provide environment information

System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 588.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v21.2.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v21.2.0/bin/pnpm

### Describe the bug

With no modification apart from changing DATABASE_URL (MySQL w/ Railway) in .env, Drizzle + App router doesn't seem to work. Tried with different setups and it seemed only this option wasn't working.
Error no longer occurs when disabling `CrudShowcase` component

Error on page:
```
Unhandled Runtime Error
Error: fetch failed

Call Stack
TRPCClientError.from
node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs (26:19)
from
node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/httpBatchLink-204206a5.mjs (189:59)
process.processTicksAndRejections
node:internal/process/task_queues (95:5)
```
Console output:
```
 >> query  #1 post.hello  { input: { text: 'from tRPC' } }
 << query  #1 post.hello  {
  input: { text: 'from tRPC' },
  result: { data: { greeting: 'Hello from tRPC' }, type: 'data' },
  elapsedMs: 50
}
 >> query  #2 post.getLatest  { input: undefined }
❌ tRPC failed on post.getLatest: fetch failed
 << query  #2 post.getLatest  {
  input: undefined,
  result: TRPCClientError: fetch failed
      at TRPCClientError.from (webpack-internal:///(rsc)/./node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs:30:20)
      at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/httpBatchLink-204206a5.mjs:196:105)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    meta: { response: [Response] },
    shape: { message: 'fetch failed', code: -32603, data: [Object] },
    data: {
      code: 'INTERNAL_SERVER_ERROR',
      httpStatus: 500,
      stack: 'TypeError: fetch failed\n' +
        '    at node:internal/deps/undici/undici:11754:11\n' +
        '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
        '    at async postJSON (webpack-internal:///(rsc)/./node_modules/.pnpm/@planetscale+database@1.11.0/node_modules/@planetscale/database/dist/index.js:147:22)\n' +
        '    at async Connection.execute (webpack-internal:///(rsc)/./node_modules/.pnpm/@planetscale+database@1.11.0/node_modules/@planetscale/database/dist/index.js:99:23)\n' +
        '    at async PlanetScalePreparedQuery.execute (webpack-internal:///(rsc)/./node_modules/.pnpm/drizzle-orm@0.28.6_@planetscale+database@1.11.0_mysql2@3.6.3/node_modules/drizzle-orm/planetscale-serverless/index.mjs:40:26)\n' +
        '    at async resolveMiddleware (webpack-internal:///(rsc)/./node_modules/.pnpm/@trpc+server@10.43.3/node_modules/@trpc/server/dist/index.mjs:431:30)\n' +
        '    at async callRecursive (webpack-internal:///(rsc)/./node_modules/.pnpm/@trpc+server@10.43.3/node_modules/@trpc/server/dist/index.mjs:467:32)\n' +
        '    at async resolve (webpack-internal:///(rsc)/./node_modules/.pnpm/@trpc+server@10.43.3/node_modules/@trpc/server/dist/index.mjs:497:24)\n' +
        '    at async inputToProcedureCall (webpack-internal:///(rsc)/./node_modules/.pnpm/@trpc+server@10.43.3/node_modules/@trpc/server/dist/resolveHTTPResponse-cd1a9112.mjs:54:22)\n' +
        '    at async resolveHTTPResponse (webpack-internal:///(rsc)/./node_modules/.pnpm/@trpc+server@10.43.3/node_modules/@trpc/server/dist/resolveHTTPResponse-cd1a9112.mjs:237:49)',
      path: 'post.getLatest',
      zodError: null
    },
    [cause]: undefined
  },
  elapsedMs: 341
}
 ⨯ node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs (26:19) @ TRPCClientError.from
 ⨯ Internal error: TRPCClientError: fetch failed
    at TRPCClientError.from (./node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs:30:20)
    at eval (./node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/httpBatchLink-204206a5.mjs:196:105)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
null
 ⨯ node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs (26:19) @ TRPCClientError.from
 ⨯ Internal error: TRPCClientError: fetch failed
    at TRPCClientError.from (./node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs:30:20)
    at eval (./node_modules/.pnpm/@trpc+client@10.43.3_@trpc+server@10.43.3/node_modules/@trpc/client/dist/httpBatchLink-204206a5.mjs:196:105)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
digest: "2399327667"
null
```

### Reproduction repo

https://github.com/TheVoxcraft/t3-drizzle-issue

### To reproduce

Follow normal t3 setup with Drizzle and App router:

◇  What will your project be called?
│  t3-test
│
◇  Will you be using TypeScript or JavaScript?
│  TypeScript
│
◇  Will you be using Tailwind CSS for styling?
│  Yes
│
◇  Would you like to use tRPC?
│  Yes
│
◇  What authentication provider would you like to use?
│  None
│
◇  What database ORM would you like to use?
│  Drizzle
│
◇   EXPERIMENTAL  Would you like to use Next.js App Router?
│  Yes
│
◇  Should we initialize a Git repository and stage the changes?
│  No
│
◇  Should we run 'pnpm install' for you?
│  Yes
│
◇  What import alias would you like to use?
│  ~/

Using: pnpm (tried with yarn too)

### Additional information

Using latest when submitting this: pnpm create t3-app@latest

**Comment by Wundero** [comment]
The default database adapter that gets used with Drizzle is PlanetScale's serverless driver, which uses HTTP to fetch data and not traditional, long-lived SQL connections. However, you have used Railway's traditional MySQL database instead of one that supports SQL over HTTP, and as such the setup doesn't work.

You should follow [this documentation on Drizzle](https://orm.drizzle.team/docs/quick-mysql/mysql2) to set up your `db` instance instead of using the default.

**Comment by TheVoxcraft** [comment]
> The default database adapter that gets used with Drizzle is PlanetScale's serverless driver, which uses HTTP to fetch data and not traditional, long-lived SQL connections. However, you have used Railway's traditional MySQL database instead of one that supports SQL over HTTP, and as such the setup doesn't work.
> 
> You should follow [this documentation on Drizzle](https://orm.drizzle.team/docs/quick-mysql/mysql2) to set up your `db` instance instead of using the default.
> 
> EDIT: The code might look something like this
> 
> ```diff
> - import { Client } from "@planetscale/database";
> - import { drizzle } from "drizzle-orm/planetscale-serverless";
> + import { drizzle } from "drizzle-orm/mysql2";
> + import mysql from "mysql2/promise";
> 
> import { env } from "~/env.mjs";
> import * as schema from "./schema";
> 
> + const connection = await mysql.createConnection({ url: env.DATABASE_URL });
> 
> export const db = drizzle(
> -  new Client({
> -    url: env.DATABASE_URL,
> -  }).connection(),
> +  connection,
>   { schema, logger: env.NODE_ENV !== "production" },
> );
> ```

Should have noticed that, thank you! Seems all is working as expected.
