### ISSUE TITLE
feat: Full Route Cache as a default

### ISSUE THREAD

**Issue by ThomasBouasli** [t3-oss/create-t3-app#1663]
### Is your feature request related to a problem? Please describe.

Since TRPCReactProvider is being render in the root layout and has cookies passing down to it, it counts as an dynamic function and opts out of the Full Route Cache.

### Describe the solution you'd like to see

 A way for the default Full Route Cache to be used and have TRPCProvider as a top level provider, I don't know if this is possible though.

### Describe alternate solutions

Maybe address that as a comment so it's clearer? I had trouble figuring out why my static pages weren't actually static.

**Comment by ArjobanSingh** [comment]
I also faced this exact issue, as my static pages were not working and it took me some time to figure out the TRPCProvider wrapped around the whole app was the culprit, as `headers()` are passed from there to client component.

**Comment by dBianchii** [comment]
+1.

This has been bothering me for quite a long time.
I really don't know if it is possible, but would love it if it was

**Comment by dBianchii** [comment]
I found that the only way to do this is to use
```ts
export const dynamic = "force-static"
```
![image](https://github.com/t3-oss/create-t3-app/assets/17372417/2203e336-9314-45cc-925b-707522ddea1c)

But it sucks having to do it like this

**Comment by ThomasBouasli** [comment]
@dBianchii I don't know how I didn't thought of this tbh. It's bad but better than ditching TRPC. One thing that I'm curious about is how partial pre-rendering will affect this, the content will load faster than the layout, which will probably look weird.

**Comment by dBianchii** [comment]
> @dBianchii I don't know how I didn't thought of this tbh. It's bad but better than ditching TRPC. One thing that I'm curious about is how partial pre-rendering will affect this, the content will load faster than the layout, which will probably look weird.

It does not work with PPR. If you go to canary and turn it on, building with `next build` completely fails.

I think T3 should definitely fix this. I am not sure if it is something that needs to wait TRPC v11

**Comment by ThomasBouasli** [comment]
That sucks. I do thinks it's more of an TRPC problem than anything else.

**Comment by raymclee** [comment]
> > @dBianchii I don't know how I didn't thought of this tbh. It's bad but better than ditching TRPC. One thing that I'm curious about is how partial pre-rendering will affect this, the content will load faster than the layout, which will probably look weird.
> 
> It does not work with PPR. If you go to canary and turn it on, building with `next build` completely fails.
> 
> I think T3 should definitely fix this. I am not sure if it is something that needs to wait TRPC v11

I just remove the `cookies` function from context and not passing it to the Provider.

Also, got PPR working with `unstable_noStore` function.

**Comment by ThomasBouasli** [comment]
@raymclee Can you share what you did in your middleware? I don't get how you're passing cookies to the TRPC route with this method.

**Comment by danieljpgo** [comment]
I did the same a few days ago; I didn't send the cookies to the provider through `next/headers` because this causes the page to opt-in to SSR. Instead, I passed `window.document.cookie` directly.

You can also opt-out of SSR by using `export const dynamic = "force-static"` on each page or in the layout. However, removing the `import { cookies } from "next/headers"` does the trick as well.

Also, I encountered problems using tRPC within `generateStaticParams()`. I needed to create another `createTRPCProxyClient()` that does not use cookies in `createContext()`. Even though the request does not require authentication, if it tries to read cookies within `createTRPCContext()`, it does not work and throws:
```js
Invariant: Method expects to have requestAsyncStorage, none available
```
To simplify, I divided my procedures/appRouter into public and authenticated. This way, I can use the public ones freely on static pages.

**Comment by raymclee** [comment]
> @raymclee Can you share what you did in your middleware? I don't get how you're passing cookies to the TRPC route with this method.

like this
```ts
const isAuthed = t.middleware(async (opts) => {
  const { ctx } = opts;
  const cookie = cookies().get("token")?.value;
  const session = await getSession(cookie);
  if (!session) {
    throw new TRPCError({ code: "UNAUTHORIZED" });
  }
  return opts.next({ ctx: { session} });
});
```

I think you could even call it inside procedure

**Comment by debatz** [comment]
> I did the same a few days ago; I didn't send the cookies to the provider through `next/headers` because this causes the page to opt-in to SSR. Instead, I passed `window.document.cookie` directly.
> 
> You can also opt-out of SSR by using `export const dynamic = "force-static"` on each page or in the layout. However, removing the `import { cookies } from "next/headers"` does the trick as well.
> 
> Also, I encountered problems using tRPC within `generateStaticParams()`. I needed to create another `createTRPCProxyClient()` that does not use cookies in `createContext()`. Even though the request does not require authentication, if it tries to read cookies within `createTRPCContext()`, it does not work and throws:
> 
> ```js
> Invariant: Method expects to have requestAsyncStorage, none available
> ```
> 
> To simplify, I divided my procedures/appRouter into public and authenticated. This way, I can use the public ones freely on static pages.

This sounds like a great solution. Could you share an example with us?

**Comment by dBianchii** [comment]
@juliusmarminge @c-ehrlich , do you have any opinion on these issues?

**Comment by debatz** [comment]
Thank you @danieljpgo 

I was interested in this thread based on principle...

...but I just got derailed on a side-project because it's impossible to create a dynamic route and use generateStaticParams()

As reported:

```
 ⨯ Failed to generate static paths for /[dashboard]:
Error [TRPCClientError]: Invariant: cookies() expects to have requestAsyncStorage, none available.
    at TRPCClientError.from (webpack-internal:///(rsc)/./node_modules/@trpc/client/dist/TRPCClientError-0de4d231.mjs:41:16)
    at eval (webpack-internal:///(rsc)/./node_modules/@trpc/client/dist/index.mjs:69:85)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'TRPCClientError'
}
```

**Comment by andrewdoro** [comment]
This is the issue preventing static generation https://github.com/vercel/next.js/issues/60009

**Comment by juliusmarminge** [comment]
> I eliminated the cookies function entirely from the root layout. I believe it's unnecessary in that context since its sole purpose was to be passed to the client component, which instantiates the trpcClient for React, and then we pass it as headers. If we look closely, it becomes evident that we don't actually need these headers to be transmitted from unstable_httpBatchStreamLink. In every browser-to-server request, all the required headers, including the HTTP cookies, are automatically transmitted from the browser. Therefore, if we only need to pass some additional headers, we can simply use new Headers() and pass them, as demonstrated in the following manner.

This is not the case when the client components are SSRed, then we need the headers passed from the server component. This should be possible using a Promise, which will never be consumed if you don't fetch anything on that page. I filed the above issue as I want to get this working too...

**Comment by statusunknown418** [comment]
are there any updates or solutions to this issue? btw: 

> > > @dBianchii I don't know how I didn't thought of this tbh. It's bad but better than ditching TRPC. One thing that I'm curious about is how partial pre-rendering will affect this, the content will load faster than the layout, which will probably look weird.
> > 
> > 
> > It does not work with PPR. If you go to canary and turn it on, building with `next build` completely fails.
> > I think T3 should definitely fix this. I am not sure if it is something that needs to wait TRPC v11
> 
> I just remove the `cookies` function from context and not passing it to the Provider. With app router, we can easily call the cookies function in middleware when needed
> 
> Also, got PPR working with `unstable_noStore` function. <img alt="image" width="618" src="https://private-user-images.githubusercontent.com/13248694/285562556-e4616636-8437-4944-9831-27087db7e659.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzkyODIsIm5iZiI6MTcwNTM3ODk4MiwicGF0aCI6Ii8xMzI0ODY5NC8yODU1NjI1NTYtZTQ2MTY2MzYtODQzNy00OTQ0LTk4MzEtMjcwODdkYjdlNjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA0MjMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OTAyZjliMTkxNzAxYTI3YjgzMDI5MjM5ZWMyNjljZWY4MTc3ODdkNWE2ZTcwZjg1OWVjZGE3MjIxMTU4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IF4QoO8Alar-Rn43CRuADxsM_REVIdHguHPx0uikaUc">

even if I remove the `cookies` function from the layout it still shows the same error and all pages become SSR, do you maybe have your code for `layout.tsx` and `trpc/react.tsx`?

**Comment by tbouasli** [comment]
@juliusmarminge since the issue you created is still open, shouldn't this issue be kept to open as a heads-up for anyone that is concidering using t3? This was a deal breaker for me, and it might be for other peolple as well.

**Comment by juliusmarminge** [comment]
what issue? this is resolved in t3 afaik
