### ISSUE TITLE
feat: Add internationalization support

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [t3-oss/create-t3-app#1665]
### Is your feature request related to a problem? Please describe.

Next.js' app router has no good packages or examples for good internationalization. So it would be cool if CT3A fixes this lack.

### Describe the solution you'd like to see

An example of how to implement internationalization, with the ability to use the example if you want.

### Describe alternate solutions

--

**Comment by juliusmarminge** [comment]
Use this: https://github.com/QuiiBz/next-international, we have no plans to do anything custom in this space
