### ISSUE TITLE
bug: `Cannot find module 'tailwindcss'` when deploying to Vercel

### ISSUE THREAD

**Issue by Axiol** [t3-oss/create-t3-app#1671]
### Provide environment information

initVersion: "7.23.2"

### Describe the bug

I generated a very simple app including Prisma and TW. Everything is fine localy, I can build the app and everything. But once I push it to Vercel, I have a build error 

```
Failed to compile.
node_modules/geist/dist/sans.js
An error occured in `next/font`.
Error: Cannot find module 'tailwindcss'
```

### Reproduction repo

https://github.com/Axiol/oaos-uat-status

### To reproduce

1. Generate a project with Prisma and TW
2. Replace Inter with Geist
3. Deploy to Vercel

**Comment by juliusmarminge** [comment]
gonna assume this is related to a bad cache somewhere and that it's fixed by now 😅
