### ISSUE TITLE
The latest ESLint config with `@next/eslint-plugin-next` doesn't lint dependency arrays

### ISSUE THREAD

**Issue by ahkhanjani** [t3-oss/create-t3-app#1674]
### Provide environment information

 System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 9.41 GB / 19.84 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - C:\Program Files\nodejs\pnpm.CMD

### Describe the bug

I upgraded an existing T3 repo from v7.20.2 to v7.24.0 and realized the ESLint not warning about dependency arrays anymore. I started a clean project and confirmed that this is true. I then removed `@next/eslint-plugin-next` and installed `eslint-config-next`, then replaced `plugin:@next/next/recommended` extension with the old `next/core-web-vitals` (not sure if it's necessary for this case) and it worked as intended.

Are you aware of this? Is this intentional?

### Reproduction repo

-

### To reproduce

I'll provide if necessary.

### Additional information

TypeScript 5.3.2

**Comment by ahkhanjani** [comment]
Has this been solved yet?

**Comment by c-ehrlich** [comment]
thanks for reporting and sorry for the delay :)
