### ISSUE TITLE
Lint script only lints /pages directory

### ISSUE THREAD

**Issue by menushka** [t3-oss/create-t3-app#168]
**Describe the bug**
Default linting completely misses anything not inside the /pages directory, specifically in my case /src/server/db/client

**To Reproduce**

1. Create default project
2. Update `.eslintrc.json` with the below for easy testing
```
"rules": {
  "quotes": [2, "single", { "avoidEscape": true }]
}
```
3. Run `yarn lint --fix`

**Expected behavior**
It should update all files in /src with single quoted imports / strings.

**Actual behavior**
Everything in /src/server/db, /src/server/router and /src/utils is missed

**My fix**
My fix was to add `--dir src` to the lint script.  Not sure why this is the default behaviour of `next lint`.

**Screenshots**
![Screen Shot 2022-07-10 at 4 16 18 PM](https://user-images.githubusercontent.com/5711536/178160761-d27a6f6f-cfd5-4a92-a473-bd85b61f077d.png)

**Comment by juliusmarminge** [comment]
> Not sure why this is the default behaviour of next lint.

It's not (or at least it shouldn't be) and it hasn't in the past. Maybe a bug in Next 12.2.

Can investigate this when I get home
later, but I don't think it is a problem on our end since Next.js does support `src` by default.

**Comment by menushka** [comment]
Hmmm after some further investigation this is an intensional, yet kinda stupid, feature on Next's side.  Its coming from `pathsToLint` variable [here](https://github.com/vercel/next.js/blob/3667eba38559e5ccb810bade4779cda3649f1413/packages/next/cli/next-lint.ts#L161).  I guess the proper fix to this problem then is to include the root directory in the `next.config.js` file.  I'll update the PR I guess with the correct fix 🤷‍♂️

**Comment by juliusmarminge** [comment]
From official docs: https://nextjs.org/docs/basic-features/eslint#linting-custom-directories-and-files

**Comment by menushka** [comment]
I guess its up to you guys then if you want to stick with linting only those two folders.  The more in-depth fix here would be to add folders to the config based on which options the user selects on create (add `server` folder if the user select to use trpc).

**Comment by TheoBr** [comment]
This definitely seems like a bug in next-lint, has anyone raised an issue up to them yet? 👀

**Comment by juliusmarminge** [comment]
Was about to until i found this in the source: https://github.com/vercel/next.js/blob/68047112d6ad9ac293161ecd3d594b05eda4d258/packages/next/lib/constants.ts#L60 and the same is documented on the official docs so seems rather intentional.


Maybe rise an issue to ask why that decision has been taken?

**Comment by TheoBr** [comment]
@juliusmarminge I like that plan, happy to bump the issue and get it to the right people 🙏

**Comment by juliusmarminge** [comment]
Closing this here since it seems like it will be fixed on `Next.js`'s side.
