### ISSUE TITLE
feat: Giest instead of Inter

### ISSUE THREAD

**Issue by wkaisertexas** [t3-oss/create-t3-app#1683]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when [Theo.gg makes a video](https://www.youtube.com/watch?app=desktop&v=pwbTN_vGmDs) about how he is so excited about Vercel's launch of [Giest](https://vercel.com/font) yet it is not supported by default in t3.

### Describe the solution you'd like to see

I would like to see `Inter` replaced with `GeistSans`

### Describe alternate solutions

`GeistMono` is also an option. But, I prefer sans.

**Comment by katungi** [comment]
Hey @c-ehrlich , can I pick this up and work on it?

**Comment by ypanagidis** [comment]
@katungi if you get on it and you need any help I would love to help out!
