### ISSUE TITLE
bug: trpc mutate not working with app directory

### ISSUE THREAD

**Issue by jmcelreavey** [t3-oss/create-t3-app#1685]
### Provide environment information

  System:
    OS: macOS 14.1.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 349.92 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.10.5 - /opt/homebrew/bin/pnpm

### Describe the bug

I've ran the @latest install for a t3 app with trpc enabled, tailwind disabled, nextauth disabled, prisma enabled and experimental app routing enabled but when I attempt to add an example post nothing happens. It doesn't make any network request or attempt to hit the mutate on the server.

### Reproduction repo

https://github.com/jmcelreavey/next

### To reproduce

Attempt to add a post

**Comment by SwankSkywalker** [comment]
@jmcelreavey You're having this issue when you try to initialize local runtime right? 'npm run dev'? I think i'm running into the same issue. [I need to take a look at my .env and .env.example files].

**Comment by kwerenta** [comment]
Were you connected to the network at that time? Because React Query by [default](https://tanstack.com/query/v4/docs/react/guides/network-mode) will not fire mutation unless you have network connection

**Comment by c-ehrlich** [comment]
React Query does not allow mutations while offline by default. Other than that, mutations work in `@latest` for the specified list of packages. The linked example does not seem to have been scaffolded with Create T3 App. If you have a more specific reproduction, please feel free to open another issue.
