### ISSUE TITLE
bug: Version 7.24.2 not building with app router and trpc 

### ISSUE THREAD

**Issue by josesei** [t3-oss/create-t3-app#1689]
### Provide environment information

System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 5.42 GB / 15.92 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD

### Describe the bug

#1599 seems to be still happening for me, for builds only, both locally and Vercel. I can run the dev server just fine.

I'm using npm and used:`"initVersion": "7.24.2"` 

--> known bandaid `import "server-only";` makes the error disappear

![image](https://github.com/t3-oss/create-t3-app/assets/34694779/34ef4856-c278-480e-a557-7de07cf08a97)

### Reproduction repo

https://github.com/josesei/bug-create-t3-app

### To reproduce

Create a fresh app with `create-t3-app` version `7.24.2`  using app router and trpc

**Comment by c-ehrlich** [comment]
It does build - check `./.next` or try starting a server with `pnpm start`.

what you are seeing is the same as this issue: https://github.com/t3-oss/create-t3-app/issues/1663
