### ISSUE TITLE
feat: Disable NextJS telemetry by default 

### ISSUE THREAD

**Issue by mbledkowski** [t3-oss/create-t3-app#1693]
### Is your feature request related to a problem? Please describe.

By default the NextJS comes with telemetry enabled by default.
Most developers would probably prefer for this feature to be opt-in instead of opt-out.

### Describe the solution you'd like to see

Disable NextJS telemetry by default - https://nextjs.org/telemetry

### Describe alternate solutions

N/A

**Comment by juliusmarminge** [comment]
> Most developers would probably prefer for this feature to be opt-in instead of opt-out.

I don't see a reason to override a default like this. The telemetry is to support the Next.js team and if you are one that wants to opt out, then you'll also know to lookup how.

**Comment by mbledkowski** [comment]
I do not believe this is a sane default. NextJS does not even give you an option, when you first run the app, it is just on. This might be illegal in multiple countries, especially the EU ones. I believe that everyone has a right to privacy, and users of open-source technologies, are mostly people that are very aware of that right. Predatory behavior like this was previously mostly seen in proprietary solutions, and those bad decisions made by the developers of proprietary technologies definitely should not set the precedent for the open-source ones.

**Comment by mbledkowski** [comment]
"Consent must be freely given, specific, informed and unambiguous. **In order to obtain freely given consent, it must be given on a voluntary basis**." Source: https://gdpr-info.eu/issues/consent/

**Comment by juliusmarminge** [comment]
Then you're better off opening an issue in Next.js.

**Comment by juliusmarminge** [comment]
fwiw I agree that everyone has a right to privacy, but the collected telemetry doesn't include anything about you, just like what nextjs version you're on. I don't think that's part of GDPR
