### ISSUE TITLE
feat: initial db type selection

### ISSUE THREAD

**Issue by addlistener** [t3-oss/create-t3-app#1701]
### Is your feature request related to a problem? Please describe.

I need to switch to database other than sqlite everytime

### Describe the solution you'd like to see

can we select postgres / mysql etc during setup? 

I know the connection might be broken etc, but if the connection cannot be established we can jump back to the database selection question and let the user select again.

### Describe alternate solutions

refer the above

**Comment by Wundero** [comment]
See #1622.
