### ISSUE TITLE
feat: update docs to use `t.createCallerFactory()`

### ISSUE THREAD

**Issue by KATT** [t3-oss/create-t3-app#1709]
### Is your feature request related to a problem? Please describe.

`router.createCaller()` is deprecated

### Describe the solution you'd like to see

Update docs and code to use `createCallerFactory()`, see https://trpc.io/docs/server/server-side-calls

### Describe alternate solutions

🤷

**Comment by pat-mw** [comment]
Second this!
Needed as I plan to upgrade to TRPC v11 when they get to a complete release.
