### ISSUE TITLE
bug: Vercel build fails with "Error: Cannot find module '/vercel/path0/install.js'"

### ISSUE THREAD

**Issue by DanClubb** [t3-oss/create-t3-app#1719]
### Provide environment information

System:
    OS: macOS 13.6.1
    CPU: (8) arm64 Apple M1
    Memory: 58.92 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh

  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    bun: 1.0.11 - ~/.bun/bin/bun

### Describe the bug

I come across this error when trying to deploy on Vercel. This happens when trying to deploy a project I had been working on and then also when trying to deploy a fresh create-t3-app which I made no changes to. 

on both of these occasions, I selected to use the following options: **ts, tailwind, trpc,  nextAuth, drizzle, App router**

- Link to the project I had been working on: https://github.com/DanClubb/Trello-Clone
- Link to fresh t3 app: https://github.com/DanClubb/drello

I am able to run locally however when I try to deploy through the Vercel dashboard I get the following logs
<img width="1204" alt="Screenshot 2024-01-09 at 12 16 26" src="https://github.com/t3-oss/create-t3-app/assets/79475404/56129965-3b19-4db8-90bd-e7bd08ecb343">

### Reproduction repo

https://github.com/DanClubb/drello

### To reproduce

1. Follow the installation instructions, select all options listed above (npm create t3-app@latest) or clone/fork https://github.com/DanClubb/drello
2. Get it running locally by creating env variable DATABASE_URL, DISCORD_CLIENT_ID, DISCORD_CLIENT_SECRET
3. Go to vercel, create the project
4. Add the env variables
5. Trigger a build
6. You get the error and the build fails

**Comment by RedBeardEth** [comment]
Updating the Vercel project settings to use Node 20 fixed this issue for me

**Comment by DanClubb** [comment]
> Updating the Vercel project settings to use Node 20 fixed this issue for me

Ah, yes. This has worked thank you

**Comment by kakeWasTaken** [comment]
@DanClubb Hey, if the issue has been resolved, please mark it as so.
