### ISSUE TITLE
bug: npm i in new app not working

### ISSUE THREAD

**Issue by dommich95** [t3-oss/create-t3-app#1722]
### Provide environment information

"initVersion": "7.25.1"

### Describe the bug

Soon as I run npm i, I'm gettng this error:

➜ npm i
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

### Reproduction repo

https://github.com/dommich95/repo-not-working

### To reproduce

npm create t3-app@latest

**Comment by juliusmarminge** [comment]
fixed in 0.7.3
