### ISSUE TITLE
bug: Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy. 

### ISSUE THREAD

**Issue by RahimGuerfi** [t3-oss/create-t3-app#1725]
### Provide environment information

**System:**
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    Memory: 3.21 GB / 7.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  **Binaries:**
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm

### Describe the bug

When creating a project using `npm create t3-app@latest`, I noticed that in **tsconfig.json**, the **moduleResolution** value is default to **Bundler** which raises the following error shown below:

**Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.**

Changing **moduleResolution** to **Node** fixed the problem.

![nextjs_error](https://github.com/t3-oss/create-t3-app/assets/89612748/adb3631b-2264-4c71-9646-2ad1d0599e4e)

### Reproduction repo

https://github.com/t3-oss/create-t3-app/blob/main/cli/template/base/tsconfig.json

### To reproduce

1. Create a T3 app using the command: **npm create t3-app@latest**
2. Open the **tsconfig.json** and you'll find the error.

**Comment by konnsim** [comment]
Getting a similar issue with the moduleResolution key in a new project, but not relative to resolveJsonModule.

![image](https://github.com/t3-oss/create-t3-app/assets/31266638/218ce886-3213-411e-bd98-87b272a6e9f9)

Looking at the JSON schema referenced on the webhint.io page linked in the tooltip shows Bundler as a valid value (as does the typescriptlang.org key definition of course).

https://webhint.io/docs/user-guide/hints/hint-typescript-config/is-valid/

![image](https://github.com/t3-oss/create-t3-app/assets/31266638/ec55c81b-72e1-4224-bd7d-698f38fe6d53)

![image](https://github.com/t3-oss/create-t3-app/assets/31266638/df053d45-72cd-4a9c-9b35-b246d1b6f871)

**Comment by konnsim** [comment]
Seems to be an issue with the VS Code extension "Microsoft Edge Tools for VS Code" in my case.
Given your OS it's probably an unrelated issue but take a look and see if you have it installed.

**Comment by juliusmarminge** [comment]
![CleanShot 2024-01-23 at 08 52 16@2x](https://github.com/t3-oss/create-t3-app/assets/51714798/7613e700-b3c5-4730-9115-c1e61b58997b)

No errors here. You definetely want to use `Bundler` module resolution though. `node` is old and doesn't support package.json#exports conditions etc etc. Make sure you use the workspace vscode setting (cmd+shift+p then select typescript version) and have an up-to-date vscode I guess could also help.

**Comment by yashsharma999** [comment]
@juliusmarminge thanks a lot, this worked. Just out of curiosity, can you explain why selecting workspace vscode setting fixes the error ?
