### ISSUE TITLE
bug: TRPCClientError.from(cause) raise `This is a client-only function.` error after upgrade to tRPC v11

### ISSUE THREAD

**Issue by Crayon-ShinChan** [t3-oss/create-t3-app#1738]
### Provide environment information

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 87.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.14.0 - ~/Library/pnpm/pnpm
    
  dependencies:
- @tanstack/react-query 4.36.1
+ @tanstack/react-query 5.17.19
+ @tanstack/react-query-devtools 5.17.19
- @trpc/client 10.44.1
+ @trpc/client 11.0.0-next-beta.228
- @trpc/next 10.44.1
+ @trpc/next 11.0.0-next-beta.228
- @trpc/react-query 10.44.1
+ @trpc/react-query 11.0.0-next-beta.228
- @trpc/server 10.44.1
+ @trpc/server 11.0.0-next-beta.228

### Describe the bug

after run `pnpm add @trpc/server@next @trpc/client@next @trpc/react-query@next @trpc/next@next @tanstack/react-query@latest @tanstack/react-query-devtools@latest`

Then `TRPCClientError.from(cause)` raise `This is a client-only function.` error after upgrade to tRPC v11

This is my `lin/trpc/server.ts`

```ts
import { cookies } from "next/headers";
import { cache } from "react";
import "server-only";
import {
  TRPCClientError,
  createTRPCProxyClient,
  loggerLink,
} from "@trpc/client";
import { callProcedure } from "@trpc/server";
import { observable } from "@trpc/server/observable";
import { type TRPCErrorResponse } from "@trpc/server/rpc";
import { appRouter } from "@/server/api/root";
import { createTRPCContext } from "@/server/api/trpc";
import { transformer } from "./shared";

/**
 * This wraps the `createTRPCContext` helper and provides the required context for the tRPC API when
 * handling a tRPC call from a React Server Component.
 */
const createContext = cache(() => {
  return createTRPCContext({
    headers: new Headers({
      cookie: cookies().toString(),
      "x-trpc-source": "rsc",
    }),
  });
});

export const api = createTRPCProxyClient<typeof appRouter>({
  transformer,
  links: [
    loggerLink({
      enabled: (op) =>
        process.env.NODE_ENV === "development" ||
        (op.direction === "down" && op.result instanceof Error),
    }),
    /**
     * Custom RSC link that lets us invoke procedures without using http requests. Since Server
     * Components always run on the server, we can just call the procedure as a function.
     */
    () =>
      ({ op }) =>
        observable((observer) => {
          createContext()
            .then((ctx) => {
              return callProcedure({
                procedures: appRouter._def.procedures,
                path: op.path,
                rawInput: op.input,
                ctx,
                type: op.type,
              });
            })
            .then((data) => {
              observer.next({ result: { data } });
              observer.complete();
            })
            .catch((cause: TRPCErrorResponse) => {
              observer.error(TRPCClientError.from(cause));
            });
        }),
  ],
});
```

### Reproduction repo

https://github.com/Crayon-ShinChan/trpc-v11-t3-bug

### To reproduce

Just use the latest t3 app, then run `pnpm add @trpc/server@next @trpc/client@next @trpc/react-query@next @trpc/next@next @tanstack/react-query@latest @tanstack/react-query-devtools@latest`

Then you will see
![CleanShot 2024-01-21 at 17 54 44@2x](https://github.com/t3-oss/create-t3-app/assets/38809606/8bf51867-99b4-4074-8997-ffab455287ff)

**Comment by juliusmarminge** [comment]
https://github.com/Crayon-ShinChan/trpc-v11-t3-bug/pull/1 shows how I'd recommend using v11
