### ISSUE TITLE
bug: Prisma link is presented in Readme.md file when Drizzle was selected as ORM

### ISSUE THREAD

**Issue by jd4d** [t3-oss/create-t3-app#1753]
### Provide environment information

  System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 159.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - ~/Library/pnpm/pnpm

### Describe the bug

I expected the README.md to have a link to Drizzle ORM instead of Prisma when I made the Drizzle selection in the creation flow.

### Reproduction repo

https://github.com/jd4d/timsfancywebsite

### To reproduce

Steps to repro:
- `npx create-t3-app` and select Drizzle.

In case it helps i made these selections in total: Typescript, Yes to tailwind, yes to tRPC, NextAuth, Drizzle, Pages router, Planetscale, yes to the git repo (I think that's all of the selections)

### Additional information

I love what y'all're doing. Keep it up! I hope this was helpful, it's not a huge thing. 

I think the repo I linked is private, let me know if you need that info and i can create a code sandbox. I didn't think it was super important to have the whole repo. Here's what my README has:

```
# Create T3 App

This is a [T3 Stack](https://create.t3.gg/) project bootstrapped with `create-t3-app`.

## What's next? How do I make an app with this?

We try to keep this project as simple as possible, so you can start with just the scaffolding we set up for you, and add additional things later when they become necessary.

If you are not familiar with the different technologies used in this project, please refer to the respective docs. If you still are in the wind, please join our [Discord](https://t3.gg/discord) and ask for help.

- [Next.js](https://nextjs.org)
- [NextAuth.js](https://next-auth.js.org)
- [Prisma](https://prisma.io)                                 <-- This line is what i was talking about
- [Tailwind CSS](https://tailwindcss.com)
- [tRPC](https://trpc.io)

## Learn More

To learn more about the [T3 Stack](https://create.t3.gg/), take a look at the following resources:

- [Documentation](https://create.t3.gg/)
- [Learn the T3 Stack](https://create.t3.gg/en/faq#what-learning-resources-are-currently-available) — Check out these awesome tutorials

You can check out the [create-t3-app GitHub repository](https://github.com/t3-oss/create-t3-app) — your feedback and contributions are welcome!

## How do I deploy this?

Follow our deployment guides for [Vercel](https://create.t3.gg/en/deployment/vercel), [Netlify](https://create.t3.gg/en/deployment/netlify) and [Docker](https://create.t3.gg/en/deployment/docker) for more information.
```

**Comment by mosesintech** [comment]
I think the README is the same regardless of what technologies you opt into. To test, I just ran `create-t3-app@latest` and chose TypeScript and nextAuth. This was in the README:

```
- [Next.js](https://nextjs.org)
- [NextAuth.js](https://next-auth.js.org)
- [Prisma](https://prisma.io)
- [Tailwind CSS](https://tailwindcss.com)
- [tRPC](https://trpc.io)
```

That said, should the README have a link to Drizzle as well?

I would love to open that PR, if yes. I haven't contributed yet and have been looking for some way too.
