### ISSUE TITLE
Include `user.id` on session

### ISSUE THREAD

**Issue by TheoBr** [t3-oss/create-t3-app#176]
I feel like I see this particular issue come up in the discord at least a few times a week, and it's always bothered me.

Should be as simple as:

```ts
// in [...nextAuth].ts
callbacks: {
  async session({ session, user }) {
    session.user.id = user.id;
    return Promise.resolve(session);
  },
}

// in a random next-auth.d.ts
declare module "next-auth" {
  /**
   * Returned by `useSession`, `getSession` and received as a prop on the `Provider` React Context
   */
  interface Session {
    userId: string;
  }
}
```

Ideally NextAuthJS would include this 😅 hoping us including it can work as a forcing function for them to get on it

**Comment by TheoBr** [comment]
Cut an issue on NextAuthJS because this should be fixed there IMO

https://github.com/nextauthjs/next-auth/issues/4903

**Comment by TheoBr** [comment]
Unhappy w/ response on NextAuth side, let's do this here instead

**Comment by bhatvikrant** [comment]
Hey I can pick this up @TheoBr

**Comment by bhatvikrant** [comment]
Yeah, that happened by mistake LoL @nexxeln

**Comment by TheoBr** [comment]
@bhatvikrant looks correct to me
