### ISSUE TITLE
feat(prisma): support typings for `.$extends`

### ISSUE THREAD

**Issue by andrewpeters9** [t3-oss/create-t3-app#1760]
### Provide environment information

- standard stack setup with Prisma

### Describe the bug

- current Prisma singleton always infers the Prisma client as `PrismaClient`
- this is problematic when models are extended as it won't pick up on typings for custom methods
- [the Prisma docs detail a more versatile solution](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices#solution)
- let me know if there are any objections, otherwise I'll open up an MR

Solution:
```ts
import { PrismaClient } from '@prisma/client'

const prismaClientSingleton = () => {
  return new PrismaClient()
}

declare global {
  var prisma: undefined | ReturnType<typeof prismaClientSingleton>
}

export const prisma = globalThis.prisma ?? prismaClientSingleton()

if (process.env.NODE_ENV !== 'production') globalThis.prisma = prisma
```

### Reproduction repo

main

### To reproduce

- extend the singleton with `.$extends`
- try to access the newly created method
- you'll receive a TS error

**Comment by juliusmarminge** [comment]
PRs accepted

**Comment by MadsFrost** [comment]
@andrewpeters9 I just wanted to personally thank you, been looking for a type-safe solution for this everywhere.. 👍🏻
