### ISSUE TITLE
bug: `useSuspenseQuery` will get "UNAUTHORIZED" tRPC error

### ISSUE THREAD

**Issue by Crayon-ShinChan** [t3-oss/create-t3-app#1765]
### Provide environment information

System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 196.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.14.0 - ~/Library/pnpm/pnpm

### Describe the bug

If we have a protected api like:
```ts
  hello: protectedProcedure
    .input(z.object({ text: z.string() }))
    .query(async ({ input }) => {
      // wait for 1 second
      await new Promise((resolve) => setTimeout(resolve, 1000));

      return {
        greeting: `Hello ${input.text}`,
      };
    }),
 ```
 
 Then we use `useSuspenseQuery` 
 ```tsx
"use client";

import { api } from "@/trpc/react";
import { Suspense } from "react";

export default function TestSuspense() {
  return (
    <div>
      <h1>Test Suspense</h1>
      <Suspense fallback={<div>Loading...</div>}>
        <SayHi />
      </Suspense>
    </div>
  );
}

function SayHi() {
  const [greet, getGreet] = api.post.hello.useSuspenseQuery({
    text: "Suspense user",
  });

  return <div>{greet.greeting}</div>;
}
```

We will get the error `UNAUTHORIZED` from 
```ts
export const protectedProcedure = t.procedure.use(({ ctx, next }) => {
  if (!ctx.session || !ctx.session.user) {
    throw new TRPCError({ code: "UNAUTHORIZED" });
  }
  return next({
    ctx: {
      // infers the `session` as non-nullable
      session: { ...ctx.session, user: ctx.session.user },
    },
  });
});
```

https://github.com/t3-oss/create-t3-app/assets/38809606/ee22bdae-d241-49cd-ac41-f002433b9d6e

You can check the detail of my code in this commit: https://github.com/Crayon-ShinChan/t3-trpc-suspense-bug/commit/b747bbac672c541a62925f35d2ddc9636cb1e316

### Reproduction repo

https://github.com/Crayon-ShinChan/t3-trpc-suspense-bug

### To reproduce

1. clone the repo
2. Go to [Discord Portal](https://discord.com/developers/applications) to create an oauth app for this repo and copy paste the `DISCORD_CLIENT_ID`,`DISCORD_CLIENT_SECRET` to .env file
3. `pnpm dev`

**Comment by mattiaseyram** [comment]
Any update or ways around this? Would be great to use useSuspenseQuery

**Comment by Crayon-ShinChan** [comment]
> Any update or ways around this? Would be great to use useSuspenseQuery

I use `isPending` to determine the UI

**Comment by 22JH** [comment]
Are you solved this problem?

**Comment by Crayon-ShinChan** [comment]
> Are you solved this problem?

I didn't use `useSuspenseQuery` and use isPending to determine if I need render skeleton instead

**Comment by sbkl** [comment]
Using this package [phryneas/ssr-only-secrets](https://github.com/phryneas/ssr-only-secrets#readme) seems to be working great to pass the cookie to the headers on the SSR piece

Add a new env variable:

```typescript
// .env.local

SECRET_CLIENT_COOKIE_VAR={"key_ops":["encrypt","decrypt"],"ext":true,"kty":"oct","k":"asdas....","alg":"A256CBC"}
```

I used the code provided to create the key above:
```typecript
crypto.subtle
  .generateKey(
    {
      name: "AES-CBC",
      length: 256,
    },
    true,
    ["encrypt", "decrypt"]
  )
  .then((key) => crypto.subtle.exportKey("jwk", key))
  .then(JSON.stringify)
  .then(console.log);
```

Then in the layout file, access the cookie, encrypt it and pass it to the TRPCReactProvider

```typescript
// app/layout.tsx

import { headers } from "next/headers";
import { TRPCReactProvider } from "@/trpc/react";

export default async function Layout(props: {
  children: React.ReactNode;
}) {
    const cookie = new Headers(headers()).get("cookie");
    const encryptedCookie = await cloakSSROnlySecret(cookie ?? "", "SECRET_CLIENT_COOKIE_VAR")
    
    return <html>
        <Head/>
        <body>
            ...
            <TRPCReactProvider ssrOnlySecret={encryptedCookie}>            
              {props.children}
            </TRPCReactProvider>
        </body>
    </.html>
}
```

Then decrypt the value and pass it to the headers on the client side. Reading the value on the browser always returns `undefined` so you won't be able to see it there.

```typescript
// trcp/react.ts

"use client";

import { readSSROnlySecret } from "ssr-only-secrets";

import type { AppRouter } from "@beebook/api";
import * as React from "react";
import { QueryClientProvider } from "@tanstack/react-query";
import { loggerLink, unstable_httpBatchStreamLink } from "@trpc/client";
import { createTRPCReact } from "@trpc/react-query";
import SuperJSON from "superjson";
import { getBaseUrl, getQueryClient } from "./utils";

export const api = createTRPCReact<AppRouter>();

export function TRPCReactProvider(props: { ssrOnlySecret:  string, children: React.ReactNode }) {
  const queryClient = getQueryClient();
  const [trpcClient] = React.useState(() =>
    api.createClient({
      links: [
        loggerLink({
          enabled: (op) =>
            process.env.NODE_ENV === "development" ||
            (op.direction === "down" && op.result instanceof Error),
        }),
        unstable_httpBatchStreamLink({
          transformer: SuperJSON,
          url: getBaseUrl() + "/api/trpc",
          async headers() {
            const headers = new Headers();
            const secret = props.ssrOnlySecret;
            const value = await readSSROnlySecret(secret,"SECRET_CLIENT_COOKIE_VAR")
            headers.set("x-trpc-source", "nextjs-react");
            if(value) {
              headers.set("cookie", value);
            }
            return headers;
          },
        }),
      ],
    }),
  );

  return (
    <QueryClientProvider client={queryClient}>
      <api.Provider client={trpcClient} queryClient={queryClient}>
        {props.children}
      </api.Provider>
    </QueryClientProvider>
  );
}

```

**Comment by jchao01** [comment]
> Using this package [phryneas/ssr-only-secrets](https://github.com/phryneas/ssr-only-secrets#readme) seems to be working great to pass the cookie to the headers on the SSR piece
> 
> Add a new env variable:
> 
> ```ts
> // .env.local
> 
> SECRET_CLIENT_COOKIE_VAR={"key_ops":["encrypt","decrypt"],"ext":true,"kty":"oct","k":"asdas....","alg":"A256CBC"}
> ```
> 
> I used the code provided to create the key above:
> 
> ```
> crypto.subtle
>   .generateKey(
>     {
>       name: "AES-CBC",
>       length: 256,
>     },
>     true,
>     ["encrypt", "decrypt"]
>   )
>   .then((key) => crypto.subtle.exportKey("jwk", key))
>   .then(JSON.stringify)
>   .then(console.log);
> ```
> 
> Then in the layout file, access the cookie, encrypt it and pass it to the TRPCReactProvider
> 
> ```ts
> // app/layout.tsx
> 
> import { headers } from "next/headers";
> import { TRPCReactProvider } from "@/trpc/react";
> 
> export default async function Layout(props: {
>   children: React.ReactNode;
> }) {
>     const cookie = new Headers(headers()).get("cookie");
>     const encryptedCookie = await cloakSSROnlySecret(cookie ?? "", "SECRET_CLIENT_COOKIE_VAR")
>     
>     return <html>
>         <Head/>
>         <body>
>             ...
>             <TRPCReactProvider ssrOnlySecret={encryptedCookie}>            
>               {props.children}
>             </TRPCReactProvider>
>         </body>
>     </.html>
> }
> ```
> 
> Then decrypt the value and pass it to the headers on the client side. Reading the value on the browser always returns `undefined` so you won't be able to see it there.
> 
> ```ts
> // trcp/react.ts
> 
> "use client";
> 
> import { readSSROnlySecret } from "ssr-only-secrets";
> 
> import type { AppRouter } from "@beebook/api";
> import * as React from "react";
> import { QueryClientProvider } from "@tanstack/react-query";
> import { loggerLink, unstable_httpBatchStreamLink } from "@trpc/client";
> import { createTRPCReact } from "@trpc/react-query";
> import SuperJSON from "superjson";
> import { getBaseUrl, getQueryClient } from "./utils";
> 
> export const api = createTRPCReact<AppRouter>();
> 
> export function TRPCReactProvider(props: { ssrOnlySecret:  string, children: React.ReactNode }) {
>   const queryClient = getQueryClient();
>   const [trpcClient] = React.useState(() =>
>     api.createClient({
>       links: [
>         loggerLink({
>           enabled: (op) =>
>             process.env.NODE_ENV === "development" ||
>             (op.direction === "down" && op.result instanceof Error),
>         }),
>         unstable_httpBatchStreamLink({
>           transformer: SuperJSON,
>           url: getBaseUrl() + "/api/trpc",
>           async headers() {
>             const headers = new Headers();
>             const secret = props.ssrOnlySecret;
>             const value = await readSSROnlySecret(secret,"SECRET_CLIENT_COOKIE_VAR")
>             headers.set("x-trpc-source", "nextjs-react");
>             if(value) {
>               headers.set("cookie", value);
>             }
>             return headers;
>           },
>         }),
>       ],
>     }),
>   );
> 
>   return (
>     <QueryClientProvider client={queryClient}>
>       <api.Provider client={trpcClient} queryClient={queryClient}>
>         {props.children}
>       </api.Provider>
>     </QueryClientProvider>
>   );
> }
> ```

you're a legend for this — thanks

**Comment by Vulxan** [comment]
I ended up using useQuery instead of useSuspenseQuery and setting throwOnError to true in the defaultOptions of QueryClient. It was too much work for me to prefetch every suspense query.

**Comment by musjj** [comment]
Is this issue tracked upstream somewhere (either tRPC or Next.js)? It's a critical issue, but this is basically the only thread I could find about it.

**Comment by Tatamo** [comment]
I disabled SSR around useSuspenseQuery by using [next/dynamic](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#skipping-ssr).

```
import dynamic from "next/dynamic";
import { Suspense, SuspenseProps } from "react";

export const SuspenseWithoutSsr = dynamic(
  () => Promise.resolve((({ children, ...props }) => <Suspense {...props}>{children}</Suspense>) as React.FC<SuspenseProps>),
  { ssr: false }
);
```

If you are using useSuspenseQuery, there should be a Suspense component wrapping it.
By replacing it with <SuspenseWithoutSsr>, everything seems to work as expected.
While disabling SSR for the entire Suspense might be too wide in some use cases and could impact performance, this approach is more convenient than finding where to use next/dynamic with useSuspnseQuery every time.

**Comment by nicofishman** [comment]
Is there any update on this issue?

**Comment by Nubebuster** [comment]
> Is there any update on this issue?

Okay, so the ssr only secrets thing had some issues. I stumbled upon this solution which is much better:


```ts
import "server-only";

import { headers, type UnsafeUnwrappedHeaders } from "next/headers";
import { cache } from "react";
import { createHydrationHelpers } from "@trpc/react-query/rsc";

import { createQueryClient } from "./query-client";
import { type AppRouter, createCaller } from "~/server/api/root";
import { createTRPCContext } from "~/server/api/trpc";

/**
 * This wraps the `createTRPCContext` helper and provides the required context for the tRPC API when
 * handling a tRPC call from a React Server Component.
 */
const createContext = cache(() => {
  const heads = new Headers(headers() as unknown as UnsafeUnwrappedHeaders);
  heads.set("x-trpc-source", "rsc");

  return createTRPCContext({
    headers: heads,
  });
});

const getQueryClient = cache(createQueryClient);
const caller = createCaller(createContext);

export const { trpc: api, HydrateClient } = createHydrationHelpers<AppRouter>(
  caller,
  getQueryClient,
);

```

query-client.ts
```ts
import {
  defaultShouldDehydrateQuery,
  QueryClient,
} from "@tanstack/react-query";
import SuperJSON from "superjson";

export const createQueryClient = () =>
  new QueryClient({
    defaultOptions: {
      queries: {
        // With SSR, we usually want to set some default staleTime
        // above 0 to avoid refetching immediately on the client
        staleTime: 30 * 1000,
      },
      dehydrate: {
        serializeData: SuperJSON.serialize,
        shouldDehydrateQuery: (query) =>
          defaultShouldDehydrateQuery(query) ||
          query.state.status === "pending",
      },
      hydrate: {
        deserializeData: SuperJSON.deserialize,
      },
    },
  });
```

Note you should also import this createQueryClient in your react.ts for trpc.

Then finally anything that needs hydration needs to be wrapped in 

import { HydrateClient } from "~/trpc/server";

you could put it in the layout.tsx for example.

**Comment by kaeon** [comment]
> > Is there any update on this issue?
> 
> Okay, so the ssr only secrets thing had some issues. I stumbled upon this solution which is much better:
> 
> import "server-only";
> 
> import { headers, type UnsafeUnwrappedHeaders } from "next/headers";
> import { cache } from "react";
> import { createHydrationHelpers } from "@trpc/react-query/rsc";
> 
> import { createQueryClient } from "./query-client";
> import { type AppRouter, createCaller } from "~/server/api/root";
> import { createTRPCContext } from "~/server/api/trpc";
> 
> /**
>  * This wraps the `createTRPCContext` helper and provides the required context for the tRPC API when
>  * handling a tRPC call from a React Server Component.
>  */
> const createContext = cache(() => {
>   const heads = new Headers(headers() as unknown as UnsafeUnwrappedHeaders);
>   heads.set("x-trpc-source", "rsc");
> 
>   return createTRPCContext({
>     headers: heads,
>   });
> });
> 
> const getQueryClient = cache(createQueryClient);
> const caller = createCaller(createContext);
> 
> export const { trpc: api, HydrateClient } = createHydrationHelpers<AppRouter>(
>   caller,
>   getQueryClient,
> );
> query-client.ts
> 
> import {
>   defaultShouldDehydrateQuery,
>   QueryClient,
> } from "@tanstack/react-query";
> import SuperJSON from "superjson";
> 
> export const createQueryClient = () =>
>   new QueryClient({
>     defaultOptions: {
>       queries: {
>         // With SSR, we usually want to set some default staleTime
>         // above 0 to avoid refetching immediately on the client
>         staleTime: 30 * 1000,
>       },
>       dehydrate: {
>         serializeData: SuperJSON.serialize,
>         shouldDehydrateQuery: (query) =>
>           defaultShouldDehydrateQuery(query) ||
>           query.state.status === "pending",
>       },
>       hydrate: {
>         deserializeData: SuperJSON.deserialize,
>       },
>     },
>   });
> Note you should also import this createQueryClient in your react.ts for trpc.
> 
> Then finally anything that needs hydration needs to be wrapped in
> 
> import { HydrateClient } from "~/trpc/server";
> 
> you could put it in the layout.tsx for example.

What exactly changed here? I compared this to my normal create-t3 app code but don't see any changes or I'm overlooking something. Still getting unauthorized :(

**Comment by Icestonks** [comment]
@Nubebuster Don't you still have to prefetch with that to get access to the headers?

**Comment by Nubebuster** [comment]
> @Nubebuster Don't you still have to prefetch with that to get access to the headers?

If you follow the steps in my comment it works. This is too long ago for me to remember what's happening. So idk if the headers are fetched, but this does the job
