### ISSUE TITLE
docs: number of stars on create.t3.gg is wrong

### ISSUE THREAD

**Issue by michaelboyles** [t3-oss/create-t3-app#1780]
### Provide environment information

NA

### Describe the bug

The number of github stars listed on https://create.t3.gg is 42k, which is almost double how many the project actually has

It was broken in this PR https://github.com/t3-oss/create-t3-app/pull/1750. `githubStars` is never reassigned to anything else and the fetch achieves nothing, whether or not it succeeds.

```javascript
let githubStars = 42069;

try {
  (await fetchGithub("https://api.github.com/repos/t3-oss/create-t3-app", {
    throwIfNoAuth: false,
    fetchType: "repo",
  }).then((data) => data?.stargazers_count)) ?? 42069;
} catch (e) {
  console.error("unable to fetch from github", e);
}
```

42069 is a very misleading fallback which should not be possible. Fall back to zero or a conservative number, rather than a massive one.

### Reproduction repo

NA

### To reproduce

NA

**Comment by oliviertassinari** [comment]
I was about to open an issue, I got confused 😄

**Comment by juliusmarminge** [comment]
Closed via https://github.com/t3-oss/create-t3-app/commit/276dde486b0b2d2db375d2607586b3d632e24ab6

**Comment by michaelboyles** [comment]
@juliusmarminge you haven't fixed it. 

Look carefully at the fetch. It does nothing. It has no side effect.

**Comment by juliusmarminge** [comment]
no astro caching is bust so we get ratelimited, we burned through like 3 api keys before github reached out and asked wtf we were doing xd...

 but i made the number closer to reality...

we'll fix it properly and get caching working if we update astro version or something in the future...
