### ISSUE TITLE
bug: "Cannot use namespace 'Database' as a type." TS error when using drizzle & better-sqlite-3 on a brand new T3 app

### ISSUE THREAD

**Issue by ibbyu** [t3-oss/create-t3-app#1793]
### Provide environment information

System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 18.68 GB / 31.94 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Local\pnpm\pnpm.EXE

### Describe the bug

TypeScript error "Cannot use namespace 'Database' as a type." & a few eslint errors when opening `src > server > db > index.ts` after initializing a brand new t3 app (version 7.28.0)

### Reproduction repo

https://github.com/ibbyu/t3-app-drizzle-sqlite-bug

### To reproduce

1. Initialize new t3 app
2. Choose Drizzle ORM
3. Choose SQLite database
4. Open index.ts file at `src > server > db > index.ts` 
5. Line 12: `Cannot use namespace 'Database' as a type.` & a few other eslint errors

**Comment by bryanjenningz** [comment]
I also experienced this problem.

It looks like a change was already made to fix it [here](https://github.com/t3-oss/create-t3-app/commit/60bd52d7f93a623b747fa16550318855cc2f8725).

For now, I was able to get rid of the "Cannot use namespace 'Database' as a type." error by applying this change locally. So you can go to the "src/server/db/index.ts" file and change this
```typescript
const globalForDb = globalThis as unknown as {
  conn: Database | undefined;
};
```
to this
```typescript
const globalForDb = globalThis as unknown as {
  conn: Database.Database | undefined;
};
```
which fixes the problem.

**Comment by juliusmarminge** [comment]
this has been fixed just wasn't released. should be included in latest release
