### ISSUE TITLE
bug: `.env.js` always validates `DATABASE_URL` for `YOUR_MYSQL_URL_HERE` even when using a different database provider

### ISSUE THREAD

**Issue by ibbyu** [t3-oss/create-t3-app#1795]
### Provide environment information

System:
OS: Windows 10 10.0.19045
CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
Memory: 18.68 GB / 31.94 GB
Binaries:
Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
pnpm: 8.14.1 - ~\AppData\Local\pnpm\pnpm.EXE

### Describe the bug

`.env.js` always validates `DATABASE_URL` for `YOUR_MYSQL_URL_HERE` even when using a different database.

`YOUR_MYSQL_URL_HERE` is used as a default value in `.env` and `.env.example` when choosing the planetscale option.

### Reproduction repo

N/A

### To reproduce

1. Initialize new t3 app
2. Choose any database ORM
3. Choose database provider
4. default `DATABASE_URL` in `.env` & `.env.example` does not match what `.env.js` validates

**Comment by c-ehrlich** [comment]
thanks for reporting this!
