### ISSUE TITLE
feat: is this template good for t3 collection page?

### ISSUE THREAD

**Issue by Parthvsquare** [t3-oss/create-t3-app#1806]
### Is your feature request related to a problem? Please describe.

i made a mvc-todo app with t3 and custom auth. 

### Describe the solution you'd like to see

the github repo: [github link](https://github.com/Parthvsquare/t3-todo-mvc/issues)

### Describe alternate solutions

not sure if this is the correct channel to ask this question

**Comment by juliusmarminge** [comment]
Sure why not. Just file a PR
