### ISSUE TITLE
NextAuth GitHub integration throws an error - `refresh_token_expires_in` missing in Prisma schema

### ISSUE THREAD

**Issue by EkaanshArora** [t3-oss/create-t3-app#182]
**Describe the bug**
When you scaffold a project with NextAuth and Prisma. Setting up the `env` file and using the GitHub provider throws an error as the Prisma Account schema is missing the `refresh_token_expires_in` field. The [NextAuth docs page](https://next-auth.js.org/providers/github) suggests adding it to the schema.

Exact error message:
```
Unknown arg `refresh_token_expires_in` in data.refresh_token_expires_in for type AccountUncheckedCreateInput. 
```

**To Reproduce**

1. Scaffold a new project
2. Select NextAuth & Prisma
3. Setup GitHub credentials in the `env` file
4. Use this snippet:
```tsx
import { signIn } from "next-auth/react"

export default function Component() {
  return <>
    <button onClick={() => signIn()}>Sign in</button>
  </>
}
```
5. Sign in with GitHub
6. See the error in the log

**Expected behavior**
The sign-in should succeed.

The default GitHub integration throwing an error can be confusing for someone new to NextAuth. I'm happy to create a PR and add the field to the schema if it makes sense. If we don't want to change the default Schema for NextAuth, it might make sense to explore another default provider instead of GitHub.

**Comment by nexxeln** [comment]
I think Discord is a good idea.

**Comment by ozgurrgul** [comment]
For anyone seeing this error like me when trying github provider: you basically need to extend `Account` schema in `schema.prisma`:

```
model Account {
    id                String  @id @default(cuid())
    userId            String
    .....
    refresh_token_expires_in Int <<< Added new to provide github support
}
```

I tested with only Github provider and it works, not sure with multiple providers.
