### ISSUE TITLE
tRPC is not working properly in server component in App router due to root.ts file

### ISSUE THREAD

**Issue by theonlyjunaid** [t3-oss/create-t3-app#1824]
### Provide environment information

  System:
    OS: macOS 13.6
    CPU: (8) arm64 Apple M1
    Memory: 76.05 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.15.1 - ~/Library/pnpm/pnpm
    bun: 1.0.11 - /opt/homebrew/bin/bun

### Describe the bug

tRPC is not working properly in the server component in the App router due to the root.ts file. I have corrected it for myself. If you assign me this issue, I can solve it for everyone as well.

### Reproduction repo

https://github.com/t3-oss/create-t3-app

### To reproduce

this bug is in by default setup of t3 app

### Additional information

<img width="471" alt="Screenshot 2024-04-15 at 12 45 45 PM" src="https://github.com/t3-oss/create-t3-app/assets/95287515/6eb18041-9d08-4aa5-83e3-31dcb8a48d0f"> 
<br/>
as you can see mutate option is not showing, assign this issue to me I will correct it out

**Comment by juliusmarminge** [comment]
serverside calls doesn't do http so there's no concept of query or mutation. you just call the function:

```ts
await api.post.create({ title: "foo" });
```
