### ISSUE TITLE
feat: tRPC with prisma is not that good

### ISSUE THREAD

**Issue by ziadx33** [t3-oss/create-t3-app#1832]
### Is your feature request related to a problem? Please describe.

the problem is while you are using prisma with tRPC, you maybe want the input or output be a prisma model, but tRPC accept only a zod schema in the input or output functions

### Describe the solution you'd like to see

so my solution is that I found a generator for prisma that generates zod schemas depending on your prisma schema ( zod-prisma package ), so this is pretty helpful for using tRPC with prisma

### Describe alternate solutions

tRPC library accept TS types in their routers

### Additional information

the zod-prisma package: https://www.npmjs.com/package/zod-prisma

**Comment by KATT** [comment]
You could prob use https://typia.io/docs/utilization/trpc/ and pass in a prisma where thing imported from the Prisma client

**Comment by ziadx33** [comment]
ok this is pretty good solution

**Comment by ziadx33** [comment]
ok this is good solution, thanks!

**Comment by juliusmarminge** [comment]
you can't combine 2 different validation libraries to a single validator object

without having tried typia, i'd assume you'd do something like this:

```ts
interface Input extends User {
  someProp: stirng
}

publicProcedure.input(typia.createAssert<User>())...
```

if you wanna use zod then use the codegen plugin
