### ISSUE TITLE
bug: In ./start-database.sh DB_CONTAINER_NAME should be changed

### ISSUE THREAD

**Issue by MahirAlam** [t3-oss/create-t3-app#1834]
### Provide environment information

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
    Memory: 1.46 GB / 2.85 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.12.2 - ~/.local/share/pnpm/node
    npm: 10.5.0 - ~/.local/share/pnpm/npm
    pnpm: 9.0.4 - ~/.local/share/pnpm/pnpm

### It is very unexpected bug!
I always cleate a folder then use the command (create t3-app).
So, in the name section I use a dot (.)
and then after finished creating my app when I run ./start-database.sh,
It gives me error!
SO, I think we should check the project name is a . (dot) then if it is, use any hard coded name?

### Reproduction repo

No need!

### To reproduce

Simply run the command   npx create-t3-app and in the name section use a . (dot) to use the directory name instead of a new one.

### I guess this solution can be implemented in 
[create-t3-app](https://github.com/t3-oss/create-t3-app/tree/main)/[cli](https://github.com/t3-oss/create-t3-app/tree/main/cli)/[template](https://github.com/t3-oss/create-t3-app/tree/main/cli/template)/[extras](https://github.com/t3-oss/create-t3-app/tree/main/cli/template/extras)/[start-database](https://github.com/t3-oss/create-t3-app/tree/main/cli/template/extras/start-database)/postgres.sh

## solution 👇👇
if ( project1=="." )
then
   DB_CONTAINER_NAME="${PWD##*/}-postgres"
else
   DB_CONTAINER_NAME="project1-postgres"
fi

echo "creating Database container as $DB_CONTAINER_NAME"

**Comment by xelacast** [comment]
I'd appreciate being assigned to work on and fix this issue. I recently encountered an error with # in the name when reproducing a potential issue, #1854, which is also related to the start-database.sh container name creation.
