### ISSUE TITLE
bug: Default scaffolded fails build on vercel

### ISSUE THREAD

**Issue by ThomasBouasli** [t3-oss/create-t3-app#1836]
### Provide environment information

```json
 "ct3aMetadata": {
    "initVersion": "7.30.2"
 }
```

### Describe the bug

When I scaffold a new T3 app with `pnpm create t3-app@latest` with:

- Typescript
- Tailwind
- TRPC
- NextAuth.js
- Drizzle
- App Router
- PostgreSQL

And attempt to deploy it completely unchanged, when building in vercel with the correct enviroment variables, i get the following error:

```
Failed to compile.
./src/server/auth.ts
53:7  Error: Unsafe assignment of an `any` value.  @typescript-eslint/no-unsafe-assignment
54:7  Error: Unsafe assignment of an `any` value.  @typescript-eslint/no-unsafe-assignment
./src/server/db/index.ts
15:43  Error: Unsafe argument of type `any` assigned to a parameter of type `Options<{}> | undefined`.  @typescript-eslint/no-unsafe-argument
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```

### Reproduction repo

https://github.com/ThomasBouasli/example/settings

### To reproduce

Clone the repository and attempt to publish it to vercel. Follow the .env.example to create your enviroment variables, I used a Vercel Postgres Database.

### Additional information

You can fix this by putting a `--no-lint` flag on the build script, but that is just ignoring the problem.

**Comment by juliusmarminge** [comment]
seems like the new zod release (3.23) has changed some types breaking t3-env. i've pinned the version to 3.22.4 for now until i have a time to look into t3-env

**Comment by ThomasBouasli** [comment]
@juliusmarminge The version I am using is `3.22.5`. I'll try to help if I can find time, but if you go looking for the breaking change, it probably happened on this version.

**Comment by ThomasBouasli** [comment]
Just for documentation sake, if anyone needs an imediate fix without disabling all eslint checks, do this:

```
//eslint ignore this line
const YOUR_VAR = env.YOUR_VAR as string
```

and use that value instead, it's ugly but it works as a temporary fix.

**Comment by juliusmarminge** [comment]
if you update to latest t3-env (0.10) it should be fixed
