### ISSUE TITLE
Use a base tsconfig to extend from

### ISSUE THREAD

**Issue by mitchell-abbott** [t3-oss/create-t3-app#184]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Use a library like [@tsconfig/next](https://www.npmjs.com/package/@tsconfig/next) for a base tsconfig to extend from. It could help keep the tsconfig settings up to date for the CLI users after they have already used the CLI with just a simple package update rather than having to go look at and compare examples to know what's changed. Let me know if that is something of interest and I (or someone else who has interest) can make the PR.

This config would ultimately look like this:
```json
{
  "extends": "@tsconfig/next/tsconfig.json",
  "compilerOptions": {
    "strict": true,
    "noUncheckedIndexedAccess": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.js"],
  "exclude": ["node_modules"]
}
```

**Describe alternatives you've considered**
Not using a base tsconfig.  😬

**Comment by MWhite-22** [comment]
I am not a fan of these sorts of packages as it obfuscates the options in TS away. For TS beginners, go right ahead and get something up and running, but as people progress in their TS knowledge, they should understand all of the flags in a tsconfig and see in one place which ones are on and which are off.

**Comment by juliusmarminge** [comment]
> as it obfuscates the options in TS away

My thought exactly. The Next default has some quirky stuff by default that we changed. Using a separate package that can change their configs at any time just makes this even more of a problem.

Since typesafety is one of the core principals in here (See [T3 Axioms](https://github.com/t3-oss/create-t3-app#t3-axioms)), I feel like we want to keep full control of what setting we turn on/off?

**Comment by mitchell-abbott** [comment]
I am fine closing this but I do want to point out. `@tsconfig/base` uses the default tsconfigs that come with things like Next, Nuxt, etc. It isn't an obfuscated outside opinion on how to config typescript. It's something you extend and make the quirky adjustments you need but provided a simple was to keep more in sync with Next defaults that you don't care about as Next updates in the future.
