### ISSUE TITLE
bug: Global styles not found when initially deployed to vercel 

### ISSUE THREAD

**Issue by psyfire25** [t3-oss/create-t3-app#1844]
### Provide environment information

  System:
    OS: macOS 12.7.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 162.34 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.5.0 - ~/.volta/tools/image/node/20.5.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.4.0 - ~/.volta/tools/image/npm/10.4.0/bin/npm
    pnpm: 8.15.7 - ~/.volta/tools/image/node/20.5.0/bin/pnpm
    Watchman: 2024.04.01.00 - /usr/local/bin/watchman

### Describe the bug

Very simple one here, when deploying to vercel the initial build is failing due to the path to the global style sheet not working.

### Reproduction repo

create-t3@latest

### To reproduce

deploy to vercel.

### Additional information

This is just following Theo's latest video. Not sure why but the file has this path when created  ~/styles/global.css

**Comment by juliusmarminge** [comment]
Can you provide an example?
