### ISSUE TITLE
feat: Update link to 2024 T3 Stack Tutorial

### ISSUE THREAD

**Issue by nicholashennellfoley** [t3-oss/create-t3-app#1845]
### Is your feature request related to a problem? Please describe.

The T3 Stack Tutorial on https://create.t3.gg/en/faq#videos links to the old video (https://www.youtube.com/watch?v=YkOSUVzOAA4)

### Describe the solution you'd like to see

Link to the current video: https://www.youtube.com/watch?v=d5x0JCZbAJs

### Describe alternate solutions

N/A

**Comment by juliusmarminge** [comment]
#1825
