### ISSUE TITLE
bug:  "[method] create t3-app@latest ."  will create broken codebase.

### ISSUE THREAD

**Issue by J-Giggles** [t3-oss/create-t3-app#1846]
### Provide environment information

pnpm create t3-app@latest
then 
pnpm dev

### Describe the bug

if you install the t3 stack using "." at the end of the npm create t3-app@latest then the dev server will not load routes.

### Reproduction repo

none

### To reproduce

pnpm create t3-app@latest . 
pnpm dev

**Comment by c-ehrlich** [comment]
Could you be more specific? `.` will create the app in the directory you're currently in. If there are already files in this directory, you are given the option to abort, delete the files, or continue. If you leave the other files around, any number of edge cases that break the app could occur.

**Comment by juliusmarminge** [comment]
Guessing this is the same issue as #1854 which is now completed. If not the OP can reopen with more detailed reproduction steps
