### ISSUE TITLE
bug: Starting an app with create t3-app@latest git issue

### ISSUE THREAD

**Issue by psyfire25** [t3-oss/create-t3-app#1847]
### Provide environment information

 System:
    OS: macOS 12.7.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 67.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.5.0 - ~/.volta/tools/image/node/20.5.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.4.0 - ~/.volta/tools/image/npm/10.4.0/bin/npm
    pnpm: 8.15.7 - ~/.volta/tools/image/node/20.5.0/bin/pnpm
    Watchman: 2024.04.01.00 - /usr/local/bin/watchman

### Describe the bug

When you run create t3-app the project created has a major git issue.

The styles folder seems to be git ignored but there is nmothing in the file. Also when any new folder in created it too seems to be git ignored. I have tried removing the git ignore file and adding bits of it back slowly but the same thing is happeneing.

### Reproduction repo

create t3-app

### To reproduce

pnpm create t3-app@latest
(from what i can see any of the options give you this result)

**Comment by xelacast** [comment]
What commands are you using on the create-t3 cli setup upon project creation? I want to recreate your workflow to see if I can help out 👍

**Comment by psyfire25** [comment]
Hey sorry for the delayed response

I was following Thoe's tutorial. 

│
◇  What will your project be called?
│  testing
│
◇  Will you be using TypeScript or JavaScript?
│  TypeScript
│
◇  Will you be using Tailwind CSS for styling?
│  Yes
│
◇  Would you like to use tRPC?
│  No
│
◇  What authentication provider would you like to use?
│  None
│
◇  What database ORM would you like to use?
│  Drizzle
│
◇  Would you like to use Next.js App Router?
│  Yes
│
◇  What database provider would you like to use?
│  PostgreSQL
│
◇  Should we initialize a Git repository and stage the changes?
│  Yes
│
◇  Should we run 'pnpm install' for you?
│  Yes
│
◇  What import alias would you like to use?
│  ~/

**Comment by xelacast** [comment]
@psyfire25 I ran through the workflow and could not reproduce your issue but I do have a few ideas that could be causing it.

1. A global .gitignore that is disrupting your work flow check out this [post](https://stackoverflow.com/questions/57331556/gitignore-of-the-parent-module-affects-add-and-commit-of-the-child-module)
2. Trouble shoot your .gitignore file check [this](https://stackoverflow.com/questions/9436405/why-is-git-is-ignoring-files-that-arent-in-the-gitignore-file)

Questions to further look into
- Does this issue persist outside of using the create t3-app in other git folders?
- When you remove your .gitignore in the folder does it fix the issue for the CSS and added folders?

I'll update this if I can think of anything else that could be causing the issue
Hope you can solve this issue 👍

**Comment by psyfire25** [comment]
it was my global git config thanks for the help

**Comment by xelacast** [comment]
Glad you fixed it! 💯
