### ISSUE TITLE
Add official tailwind plugins 

### ISSUE THREAD

**Issue by paolotiu** [t3-oss/create-t3-app#185]
**Is your feature request related to a problem? Please describe.**
Adding tailwind plugins isn't really a big problem, but it would be nice to include some non-intrusive offical plugins like `@tailwindcss/typography` , `@tailwindcss/line-clamp`, and `@tailwindcss/aspect-ratio`. `@tailwindcss/forms` creates an opinionated reset layer, so I don't think it should be included.

**Describe the solution you'd like**
Add a option to choose whether to include the plugins

**Describe alternatives you've considered**
Install each one manually

**Comment by nexxeln** [comment]
Please read [this](https://github.com/t3-oss/create-t3-app#1-solve-problems)
