### ISSUE TITLE
bug: Example query failing on new projects. Zod validation failing, input is undefined

### ISSUE THREAD

**Issue by danielcspaiva** [t3-oss/create-t3-app#1856]
### Provide environment information

System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 155.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.6.9 - /opt/homebrew/bin/pnpm

"ct3aMetadata": {
    "initVersion": "7.32.0"
  },

### Describe the bug

Apparently there is an issue with the example query in a newly created project.

As soon as I initiate a new project using pages router and try to run it I get the following error:

> GET /api/trpc/post.hello?batch=1&input=%7B%220%22%3A%7B%22text%22%3A%22from%20tRPC%22%7D%7D 400 in 6ms
> ❌ tRPC failed on post.hello: [
>   {
>     "code": "invalid_type",
>     "expected": "object",
>     "received": "undefined",
>     "path": [],
>     "message": "Required"
>   }
> ]

It seems that no matter what the input is always undefined and fails the zod validation, even though it is defined when calling the query in the example:

`const hello = api.post.hello.useQuery({ text: "from tRPC" });` 

Am I missing something? I've already started multiple t3 projects and never encountered this problem.

Thank you in advance.

### Reproduction repo

https://codesandbox.io/p/github/danielcspaiva/pages-router/main

### To reproduce

Run the t3 CLI.

Choose tRPC.

Run the project.

### Additional information

It seems to happen as soon as you open the page when using pages directory. When using app directory it happens as soon as you run a mutation.

**Comment by danielcspaiva** [comment]
I've checked the pnpm-lock and found the following:

This projct was using version 11.0.0-next-alpha.149 of tRPC, in which the problem is present wieh the current implementation of create t3 app.

I checked another recent project that is working just fine and it is running version 11.0.0-rc.351 of tRPC.

I then set the version 11.0.0-rc.351 of tRPC in package.json and it worked fine for this project. So it might be some problem with the newer versions of tRPC.

**Comment by danielcspaiva** [comment]
Closing this issue.

I realized this tRPC version 11.0.0-next-alpha.149 is a very old release and somehow it must have been cached locally in my pnpm. I manage to fix it and I'm confident there is no issue with create t3 app.

**Comment by danielcspaiva** [comment]
Closing this issue.

I realized this tRPC version 11.0.0-next-alpha.149 is a very old release and somehow it must have been cached locally in my pnpm. I manage to fix it and I'm confident there is no issue with create t3 app.

**Comment by e1pupper** [comment]
and for everyone else just run
`pnpm add @trpc/server@next @trpc/client@next @trpc/react-query@next @trpc/next@next @tanstack/react-query@latest zod`
