### ISSUE TITLE
feat: CLI Option for Postgres

### ISSUE THREAD

**Issue by cade-th** [t3-oss/create-t3-app#1865]
### Is your feature request related to a problem? Please describe.

Not related to a problem

### Describe the solution you'd like to see

add postgres to the --dbProvider [provider] flag

### Describe alternate solutions

anything for a cli option for postgres

### Additional information

pls

**Comment by juliusmarminge** [comment]
is it not?

**Comment by cade-th** [comment]
pls merge

**Comment by xelacast** [comment]
There are a few errors with the E2E GitHub actions. I'm looking into this
