### ISSUE TITLE
feat: add option to keep default Import alias of create-next-app

### ISSUE THREAD

**Issue by Parth589** [t3-oss/create-t3-app#1874]
### Is your feature request related to a problem? Please describe.

I personally use create-next-app import alias `@/*` alot in my projects. shadcn/ui is also an important tool in my recent projects. i dont want to change the pasted code from templates. it's so annoying to everytime change the import statements just for an alias. 

### Describe the solution you'd like to see

just add an option to keep the import alias to `@/` . i am tired of writing that while initializing all new projects.

### Describe alternate solutions

You can just remove the `~/` alias from this project so everyone could be happy. (no offence but it's my personal opinion)

**Comment by afonsopimenta** [comment]
@Parth589 You can just write `@/` when it prompts for what import alias you'd like to use when initializing a project.

**Comment by juliusmarminge** [comment]
yea this issue makes no sense. No matter what default we pick, some are gonna argue for another one. It's not a lot of work for you to just write `@/` when it prompts you.

We could also store your "preferred" setting in some global store (I think `create-next-app` does this) but that's a bigger task, although I'd be open for it!

But we settled on the current default after a community vote so we're not gonna change it just cause of individuals personal prefrence.
