### ISSUE TITLE
Add autoprefixer

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [t3-oss/create-t3-app#1877]
### Is your feature request related to a problem? Please describe.

Sometimes you write some tailwindcss and it does not work in some browsers. Often this is because Tailwind uses CSS properties that aren't usable in these browsers. Often the easiest solution to the problem is to add autoprefixer to add the neccessary vendor prefixes.

### Describe the solution you'd like to see

Add autprefixer to the postcss config

### Describe alternate solutions

Everyone has to do it himself

**Comment by juliusmarminge** [comment]
Just add it yourself if you need it. Some investigations from the next team showed autoprefixer to be quite slow, so I think it's better everyone who needs it just adds it themselves.
