### ISSUE TITLE
bug: next-auth v5 environment variables

### ISSUE THREAD

**Issue by tushcmd** [t3-oss/create-t3-app#1878]
### Provide environment information

System:
    OS: Windows 11 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 5.75 GB / 15.89 GB
  Binaries:
    Node: 21.7.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - ~\AppData\Local\pnpm\pnpm.EXE

### Describe the bug

The naming convention in V5 for auth secret and Oauth variables is as follows in this example respectively

```env
AUTH_SECRET=secret
#and
AUTH_GITHUB_ID="f25bcyudgdkjb95e1ecc01"
AUTH_GITHUB_SECRET="37d8d7db5a4756byuwcgyuvgdvhb1cf22d818"
```

Which is different from natural T3 requirement causing this error
![GNGLHXeWgAAjh9x](https://github.com/t3-oss/create-t3-app/assets/78159338/63c2e02c-11de-45ab-b6af-3e4095f28bd0)
I bypassed it this way but I believe it can be improved
![envrun](https://github.com/t3-oss/create-t3-app/assets/78159338/4e517aec-6740-4ed3-95f8-f3b2c9859033)

### Reproduction repo

https://github.com/tushcmd/anketa.git

### To reproduce

The bug is simply caused when you use these env variables formats in nextauth v5
```env
NEXT_AUTH_SECRET=secret

GITHUB_CLIENT_ID='YUTE8YFTEGVJKH23R67474TEUGHOGRH98'
GITHUB_CLIENT_SECRET='HDUIDFYIDGVDVBIYIUEWYF896T7DB78QW/-='
```
instead of 

```env
AUTH_SECRET=secret

AUTH_GITHUB_ID="f25bcyudgdkjb95e1ecc01"
AUTH_GITHUB_SECRET="37d8d7db5a4756byuwcgyuvgdvhb1cf22d818"
```

respectively for next-auth secret and Oauth env variables (used above are just examples not my variables)

**Comment by juliusmarminge** [comment]
We'll do this once we use v5. We're still on v4

**Comment by tushcmd** [comment]
Does not make sense to make developers remain in the old version when the new one is evidently easier and better to setup
