### ISSUE TITLE
Absolute paths?

### ISSUE THREAD

**Issue by ahhshm** [t3-oss/create-t3-app#188]
**Is your feature request related to a problem? Please describe.**
I don't like paths like this:
```ts
import { appRouter } from "../../../server/router";
import { createContext } from "../../../server/router/context";
```
because I have to open my editor's file browser to figure out where `appRouter` and `createContext` come from.

**Describe the solution you'd like**
We can set `"baseUrl": "."` in `tsconfig.json` so we can use absolute paths (relative paths still work):
```ts
import { appRouter } from "src/server/router";
import { createContext } from "src/server/router/context";
```
That's much clearer.

**Comment by nexxeln** [comment]
Please search for existing issues before making one. Closing this as it has been discussed in #85.
