### ISSUE TITLE
bug: Drizzle Studio requires a new version of Drizzle Kit to run locally

### ISSUE THREAD

**Issue by nathanwhyte** [t3-oss/create-t3-app#1880]
### Provide environment information

 System:
  - OS: macOS 14.4.1
  - CPU: (14) arm64 Apple M3 Max
  - Memory: 203.14 MB / 36.00 GB
  - Shell: 5.9 - /bin/zsh
  
Binaries:
  - Node: 22.1.0 - /opt/homebrew/bin/node
  - npm: 10.7.0 - /opt/homebrew/bin/npm
  - pnpm: 9.1.0 - /opt/homebrew/bin/pnpm

### Describe the bug

The version of drizzle-kit that's shipped with T3 _(version `0.20.14`)_ is out of date as of ~11:45 CST today, Friday, May 5th.

Neither the database or drizzle themselves are broken, it's just that drizzle-studio needs the newest version to run locally.

When running `pnpm run db:studio` using version `0.20.14`, the drizzle-studio page gives me this:
![image](https://github.com/t3-oss/create-t3-app/assets/54960203/f6cd25c2-5960-4fa4-bc9c-c8392824bd06)

The newest drizzle-kit version is `0.21.1` - https://www.npmjs.com/package/drizzle-kit

Drizzle has a guide for migrating to the new version - https://orm.drizzle.team/kit-docs/upgrade-21#how-to-migrate-to-0210

### Reproduction repo

N/A

### To reproduce

I couldn't provide an example repo since my database connections are local-only and this is a problem that only pops up in a local environment.

In a repo with a working DB connection _(i.e. drizzle studio would load fully as of yesterday)_ that's using drizzle-kit version `0.20.14`, run `pnpm run db:studio` and open the studio page to see the update prompt.

### Additional information

I'm opening this with the intention of fixing the bug myself, but if someone gets to it before I do that's all good.

**Comment by juliusmarminge** [comment]
Updated to latest kit
