### ISSUE TITLE
feat: Use executing package manager to install dependencies

### ISSUE THREAD

**Issue by C0RR1T** [t3-oss/create-t3-app#1887]
### Is your feature request related to a problem? Please describe.

When running the script with `bun create t3-app@latest` and then choosing to install the options results in npm installing the dependencies. This makes sense, because the CLI specifically asked if you want to `npm install`. It would be nice however to install the dependencies with the package manager you chose to run the script. 

### Describe the solution you'd like to see

When asking the user if they want to install the dependencies, display the correct install command for the package manager the script was started with (i.E. Bun --> "Should we run  `bun install` to install dependencies" etc.). if the user chooses to install the dependencies via CLI, the CLI calls the correct command based on the executing package manager. 

### Describe alternate solutions

The CLI only asks the user if he wants to install the dependencies when `npm` is used. In other cases, the user has to manually install the dependencies

### Additional information

Steps to reproduce the wrong package manager being used:
```
bun create t3-app@latest
What will your project be called --> test-project
Will you be using TS or JS -> TS
Would you like to use tRPC -> No
What auth provider would you like to use -> None
What DB ORM would you like to use -> Drizzle 
Would you like to use the app router -> Yes
What Database would you like to use -> Postgres
Initialize Git Repo -> Yes
Should we run `npm install` for you? -> Yes
```

**Comment by C0RR1T** [comment]
I could try to implement this myself if this is actually something you guys think would be worth implementing

**Comment by juliusmarminge** [comment]
hmm it works with `bunx`: 
![CleanShot 2024-05-17 at 13 53 04](https://github.com/t3-oss/create-t3-app/assets/51714798/8a0f6467-ba73-4d29-80bf-68b9be2f721d)

PRs accepted fixing `bun create` behavior

**Comment by C0RR1T** [comment]
I noticed that bun doesn't pass the correct env variables when running bun create (see https://github.com/oven-sh/bun/issues/11016)

**Comment by C0RR1T** [comment]
I will close this issue since it's a problem with bun, not ct3a.
