### ISSUE TITLE
docs: some of the redirect links in usage > tRPC page not working.

### ISSUE THREAD

**Issue by VinayakaHegade** [t3-oss/create-t3-app#1889]
### Is your feature request related to a problem? Please describe.

These below hyper links in [usage>trpc](https://create.t3.gg/en/usage/trpc) redirect to Page not found 
1. https://create.t3.gg/en/usage/trpc#-serverapitrpcts:~:text=and%20define%20reusable-,procedures%E2%86%97,-and%20middlewares%E2%86%97
2. https://create.t3.gg/en/usage/trpc#-serverapitrpcts:~:text=procedures%E2%86%97%20and-,middlewares%E2%86%97,-.%20By%20convention%2C%20you
3. https://create.t3.gg/en/usage/trpc#-serverapitrpcts:~:text=Here%20we-,merge%E2%86%97,-all%20the%20sub
4. https://create.t3.gg/en/usage/trpc#-serverapitrpcts:~:text=define%20your%20tRPC-,links%E2%86%97,-here%2C%20which%20determines
5. https://create.t3.gg/en/usage/trpc#-serverapitrpcts:~:text=use%20the%20%E2%80%9Cdefault%E2%80%9D-,httpBatchLink%E2%86%97,-which%20enables%20request
6. https://create.t3.gg/en/usage/trpc#-serverapitrpcts:~:text=well%20as%20a-,loggerLink%E2%86%97,-which%20outputs%20useful
7. https://create.t3.gg/en/usage/trpc#-serverapitrpcts:~:text=we%20export%20a-,helper%20type%E2%86%97,-which%20you%20can
8. https://create.t3.gg/en/usage/trpc#-serverapitrpcts:~:text=you%E2%80%99re%20looking%20for-,server%20side%20calls%E2%86%97.,-That%20would%20allow

### Describe the solution you'd like to see

Currently i don't have idea regarding what is the correct link. I would like to see it redirecting to relevant sections of documentations instead of Page not Found.

### Describe alternate solutions

NA

**Comment by dellamora** [comment]
I would like to work on this. Can you assign me this issue ^^

**Comment by juliusmarminge** [comment]
Please just file a PR @dellamora :)

**Comment by juliusmarminge** [comment]
Fixed in ff32e083970357a64ddf53e2e0469f9170c06412
