### ISSUE TITLE
bug: t3 App not building App Router Application

### ISSUE THREAD

**Issue by arvind-berrybox** [t3-oss/create-t3-app#1896]
### Provide environment information

"initVersion": "7.33.1"

### Describe the bug

![image](https://github.com/t3-oss/create-t3-app/assets/167168534/7baea36f-0607-4dc9-ae45-ddb2da31cf98)

### Reproduction repo

Not applicable

### To reproduce

yarn build

**Comment by c-ehrlich** [comment]
i can't reproduce this with yarn 1.22.22. could you give a more precise set of steps to make this happen?

**Comment by juliusmarminge** [comment]
> ### Reproduction repo
> Not applicable

Yes it is. You've also not provided any system information. All we can see is you're using Yarn.

Please reopen a valid issue providing necessary details for us to help you debug
