### ISSUE TITLE
Protected tRPC router example?

### ISSUE THREAD

**Issue by TheoBr** [t3-oss/create-t3-app#191]
Might be less relevant post-v10

Including this would make my life much easier
```ts
import * as trpc from "@trpc/server";
import { createRouter } from "./context";

export function createProtectedRouter() {
  return createRouter().middleware(({ ctx, next }) => {
    if (!ctx.session || !ctx.session.user) {
      throw new trpc.TRPCError({ code: "UNAUTHORIZED" });
    }
    return next({
      ctx: {
        ...ctx,
        // infers that `session` is non-nullable to downstream resolvers
        session: { ...ctx.session, user: ctx.session.user },
      },
    });
  });
}
```

**Comment by TheoBr** [comment]
Example of how much code I could delete https://github.com/TheoBr/zapdos/commit/73fd75d8d1c36c0b8132289c99114e1cdd568edb

**Comment by nexxeln** [comment]
Oh yeah we can do this. Are you free to make a PR?

**Comment by TheoBr** [comment]
> Oh yeah we can do this. Are you free to make a PR?

Not particularly :( will mark it as "good first issue" so someone else can take it if you're down

**Comment by bhatvikrant** [comment]
Hey folks, can I pick this up?

**Comment by nexxeln** [comment]
> Hey folks, can I pick this up? // @nexxeln @TheoBr

Feel free, should I assign you?

**Comment by bhatvikrant** [comment]
> > Hey folks, can I pick this up? // @nexxeln @TheoBr
> 
> Feel free, should I assign you?

Yes please
