### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by ZzyzxIsAlreadyTaken** [t3-oss/create-t3-app#1911]
### Provide environment information

 System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 73.17 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm

### Describe the bug

t3 app with sqlite and drizzle does not update the userid field in the databse and we get a login error.

![Screenshot 2024-06-10 at 13 35 23](https://github.com/t3-oss/create-t3-app/assets/18461079/01985d8e-9852-4cab-ac86-0c744870b549)

### Reproduction repo

https://github.com/ZzyzxIsAlreadyTaken/monthly

### To reproduce

npm create t3-app@latest

◇  What will your project be called?
│  trenelitt
│
◇  Will you be using TypeScript or JavaScript?
│  TypeScript
│
◇  Will you be using Tailwind CSS for styling?
│  Yes
│
◇  Would you like to use tRPC?
│  Yes
│
◇  What authentication provider would you like to use?
│  NextAuth.js
│
◇  What database ORM would you like to use?
│  Drizzle
│
◇  Would you like to use Next.js App Router?
│  Yes
│
◇  What database provider would you like to use?
│  SQLite (LibSQL)
│
◇  Should we initialize a Git repository and stage the changes?
│  Yes
│
◇  Should we run 'npm install' for you?
│  Yes
│
◇  What import alias would you like to use?
│  ~/

Set up a provider (Ive testet Discord and Google).

Fail to log in (create user in database)

### Additional information

I have tested this twice with two different project installations aswell. Also Ive tested to change the id in the user table schema to integer and autoincrement, and then the user is created, but the auth.ts file then shows errors.

This is if Im changing user table id:

auth.ts
![Screenshot 2024-06-10 at 13 40 56](https://github.com/t3-oss/create-t3-app/assets/18461079/6658d6ab-24c6-4599-a426-7c5448b049b3)

schema.ts
![Screenshot 2024-06-10 at 13 41 18](https://github.com/t3-oss/create-t3-app/assets/18461079/db792ab0-cb65-4837-a8f1-6e56978b5bda)

**Comment by n0ait** [comment]
See https://github.com/t3-oss/create-t3-app/issues/1906#issuecomment-2141022516

**Comment by ZzyzxIsAlreadyTaken** [comment]
Thanks for your reply. It seems like that was the exact same bug. I just did not find it by searching. Ive implemented the suggested fix, and it seems to work with the Google Adapter :) I can also see in the database that the id now is populated correctly with a string (a guid). I also see that a pull request has been submitted. So I hope that T3 will be updated as soon as possible :)

**Comment by ZzyzxIsAlreadyTaken** [comment]
Thanks for your reply. It seems like that was the exact same bug. I just did not find it by searching. Ive implemented the suggested fix, and it seems to work with the Google Adapter :) I can also see in the database that the id now is populated correctly with a string (a guid). I also see that a pull request has been submitted. So I hope that T3 will be updated as soon as possible :)
