### ISSUE TITLE
bug: Next Auth Sign Up Default User Id Missing

### ISSUE THREAD

**Issue by jcappel** [t3-oss/create-t3-app#1914]
### Provide environment information

  System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 249.63 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.0.0 - ~/.nvm/versions/node/v21.0.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.0 - ~/.nvm/versions/node/v21.0.0/bin/npm
    pnpm: 9.3.0 - ~/.nvm/versions/node/v21.0.0/bin/pnpm
    bun: 1.1.13 - ~/.bun/bin/bun

### Describe the bug

Following the t3 installation guide results and further using next auth, drizzle and postgres results in an oauth error when trying to login with an oauth provider. 
It seems like the t3 drizzle schema needs to be updated to allow creating a default user id as stated in the auth.js [docs](https://authjs.dev/getting-started/adapters/drizzle):

```
export const users = pgTable("user", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name"),
  email: text("email").notNull(),
  emailVerified: timestamp("emailVerified", { mode: "date" }),
  image: text("image"),
})
```

Currently the default function is missing in the default t3 installation.
By adding the default function the issue should be fixed.

### Reproduction repo

-

### To reproduce

Create a t3 app using CreateT3App and choose NextAuth, Drizzle and Postgres.

**Comment by Velua** [comment]
Just ran into this as well!

**Comment by abaudhuin** [comment]
Encounter the same issue after first setup.
Thanks for the fix

**Comment by juliusmarminge** [comment]
Fixed in https://github.com/t3-oss/create-t3-app/pull/1909
