### ISSUE TITLE
feat: License Selection

### ISSUE THREAD

**Issue by ShrootBuck** [t3-oss/create-t3-app#1916]
### Is your feature request related to a problem? Please describe.

Since CT3 is for scaffolding new projects, many of these projects would end up with a license. It would be a nice addition if users had an option to select their license of choice (or no license at all).

### Describe the solution you'd like to see

A simple license selection menu.

### Describe alternate solutions

N/A

### Additional information

I would be glad to implement this myself, but I'm looking for a greenlight before I spend a bunch of time on it.

**Comment by juliusmarminge** [comment]
Out of scope, there are many license generators out there or I believe there's like 2 clicks in Github to add any license you want
