### ISSUE TITLE
bug: Unable to login

### ISSUE THREAD

**Issue by dHarshMakwana** [t3-oss/create-t3-app#1918]
### Provide environment information

  System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1
    Memory: 124.30 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.9.0 - /usr/local/bin/pnpm
    bun: 1.0.30 - /usr/local/bin/bun

### Describe the bug

Hello these are the packages I am using 
Trpc
Next Auth
Drizzle
PostgreSQL

Env's are working fine for me 
Supabase for postgres data,  discord client and secret 

Auth error I am receiving:

https://next-auth.js.org/errors#adapter_error_createuser null value in column "id" of relation "test_user" violates not-null constraint {
  message: 'null value in column "id" of relation "test_user" violates not-null constraint',
  stack: 'PostgresError: null value in column "id" of relation "test_user" violates not-null constraint\n' +
    '    at ErrorResponse (webpack-internal:///(rsc)/./node_modules/postgres/src/connection.js:803:66)\n' +
    '    at handle (webpack-internal:///(rsc)/./node_modules/postgres/src/connection.js:489:6)\n' +
    '    at Socket.data (webpack-internal:///(rsc)/./node_modules/postgres/src/connection.js:330:9)\n' +
    '    at Socket.emit (node:events:518:28)\n' +
    '    at addChunk (node:internal/streams/readable:559:12)\n' +
    '    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n' +
    '    at Readable.push (node:internal/streams/readable:390:5)\n' +
    '    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)\n' +
    '    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)',
  name: 'PostgresError'
}

### Reproduction repo

new fresh t3 app template 

### To reproduce

use the supabase db url and then try signin 

### Additional information

I tried other env but not working

**Comment by JakubGluszek** [comment]
I am experiencing the same issue when using the drizzle database.

**Comment by jcappel** [comment]
Duplicate #1914
