### ISSUE TITLE
Update Context file ?

### ISSUE THREAD

**Issue by zanzlender** [t3-oss/create-t3-app#192]
**Is your feature request related to a problem? Please describe.**
I opened up an [issue](https://github.com/trpc/trpc/issues/2160) on the trpc repo regarding some TS errors in the context. There @KATT said that he doesn't recommend the current implementation because of the req/res objects.

**Describe the solution you'd like**
I don't know if this was considered before, nor do I have the knowledge to comment much on this, so I'm just putting this here if someone can check up on it :)

**Describe alternatives you've considered**
...

**Comment by nexxeln** [comment]
Closing this as Alex already opened an PR fixing this. See #186. It will be merged soon.
