### ISSUE TITLE
docs: Links to TRPC documentation in the TRPC section of create t3 docs are broken.

### ISSUE THREAD

**Issue by literallyJoel** [t3-oss/create-t3-app#1923]
### Provide environment information

N/A

### Describe the bug

In the [TRPC Section of the  Create T3 docs](https://create.t3.gg/en/usage/trpc), all links to trpc.io are broken, and lead to a "not found page".

### Reproduction repo

NA

### To reproduce

N/A - issue is with live docs page.

**Comment by mrinmoyf2** [comment]
Some are still not working. I make a PR here - https://github.com/t3-oss/create-t3-app/pull/1946
@literallyJoel  @juliusmarminge
