### ISSUE TITLE
feat: Improve "error" in start-database.sh when password is still default

### ISSUE THREAD

**Issue by TheDevilOnLine** [t3-oss/create-t3-app#1929]
### Is your feature request related to a problem? Please describe.

When you run `start-database.sh`, but haven't changed the password in `.env` from `password` to something else, the error says `Please set a password in the .env file and try again`, but this isn't really descriptive of what should be done.

Yes it says `You are using the default database password` before asking if you want to use the default password, but a lot of people will not read this.

### Describe the solution you'd like to see

Change the error message to something like `Please change the default password in the .env file and try again`

### Describe alternate solutions

Generate a random password in `.env` when generating the project

### Additional information

https://github.com/t3-oss/create-t3-app/issues/1927 is losely related to this as well.

**Comment by KrishanGoyal1** [comment]
@juliusmarminge fixed this, kindly review!!
