### ISSUE TITLE
Enable `skipLibCheck: true` in tsconfig

### ISSUE THREAD

**Issue by TheoBr** [t3-oss/create-t3-app#193]
...oops

https://twitter.com/mattpocockuk/status/1547486287443140614

**Comment by nexxeln** [comment]
I think we have this enabled.

**Comment by nexxeln** [comment]
In our code: https://github.com/t3-oss/create-t3-app/blob/main/tsconfig.json#L44
In the template: https://github.com/t3-oss/create-t3-app/blob/main/template/base/tsconfig.json#L6

**Comment by TheoBr** [comment]
nvm it's enabled my bad. Hrm.
