### ISSUE TITLE
feat: prisma-kysely integration

### ISSUE THREAD

**Issue by musjj** [t3-oss/create-t3-app#1935]
### Is your feature request related to a problem? Please describe.

Prisma has an amazing DX, probably the best-in-class among ORM libraries. But you will quickly find that its abstractions is still immature and lacks support for many forms of queries.

### Describe the solution you'd like to see

I've been recently using https://github.com/valtyr/prisma-kysely for my personal projects and it's an absolute god-send. You get the full power of raw queries while still retaining typesafety derived from your Prisma schema.

IMO the plugin is a must-have for any projects using Prisma.

### Describe alternate solutions

Dropping down to `$queryRaw` and giving up all typesafety in the process.

**Comment by juliusmarminge** [comment]
I like prisma-kysely the times I've used it, but I don't think this is worth adding as a default, it can be overwhelming for newbies coming to try Prisma seeing multiple ways to use it
