### ISSUE TITLE
bug: createApp with Drizzle, Postgres, and NextAuth is broken – "The types of _.config.columns.id are incompatible between these types."

### ISSUE THREAD

**Issue by FroeMic** [t3-oss/create-t3-app#1953]
### Provide environment information

**ct3aMetadata.initVersion:**
```
  "ct3aMetadata": {
    "initVersion": "7.36.2"
  },
```

**npx envinfo --system --binaries:**
```
  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 40.86 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 10.2.1 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.10.5 - ~/Library/pnpm/pnpm
```

**npm create t3-app@latest config**
- TypeScript
- Tailwind
- tRCP
- NextAuth.js
- Drizzle
- App Router
- PosgreSQL
- Git (yes)
- npm install (yes)
- alias: ~/

**Reproduction**
You should be able to reproduce the error by running `npm create t3-app@latest` with the above mentioned options and then opening `/src/server/auth.ts`

### CreateApp with Drizzle, Postgres, and NextAuth is broken – "The types of _.config.columns.id are incompatible between these types."

After running `npm create t3-app@latest` the NextAuth DrizzleAdapter throws a Typescript error in `/src/server/auth.ts`. It seems that the schemas generated by drizzle are not compatible with the ones the adapter expects. Some properties expected by the adapter are not provided by the schemas generated by drizzle.

```
// /src/server/auth.ts line 55

[...]
  adapter: DrizzleAdapter(db, {
    usersTable: users,
    accountsTable: accounts,
    sessionsTable: sessions,
    verificationTokensTable: verificationTokens,
  }) as Adapter,
[...]
```

**Typescript Error (formatted)**

```
// Type Error
Type 'PgTableWithColumns<{ ... }>' is not assignable to type 'DefaultPostgresUsersTable'.

// Detailed Error
Type 'PgTableWithColumns<{ ... }>' is not assignable to type 'PgTable<{ ... }>'.
  Type 'PgTableWithColumns<{ ... }>' = {
    name: "user";
    schema: undefined;
    columns: {
      id: PgColumn<{
        name: "id";
        tableName: "user";
        dataType: "string";
        columnType: "PgVarchar";
        data: string;
        driverParam: string;
        notNull: true;
        hasDefault: true;
        enumValues: [...];
        baseColumn: never;
      }, {}, {}>;
      name: PgColumn<...>;
      email: PgColumn<...>;
      // ...
    };
  };

// Expected Type
Type 'DefaultPostgresColumn<{ ... }>' = {
  columnType: "PgVarchar" | "PgText" | "PgUUID";
  isPrimaryKey: true;
  data: string;
  notNull: true;
  dataType: "string";
};

// Actual Type
Type 'PgColumn<{ ... }>' = {
  name: "id";
  tableName: "user";
  dataType: "string";
  columnType: "PgVarchar";
  data: string;
  driverParam: string;
  notNull: true;
  hasDefault: true;
  enumValues: [string, ...string[]];
  baseColumn: never;
};

// Missing Properties
Type 'PgColumn<{ ... }>' is missing the following properties from type 'DefaultPostgresColumn<{ ... }>':
  isAutoincrement: boolean;
  isPrimaryKey: true;
  hasRuntimeDefault: boolean;
  generated: any;
```

`DrizzleAdapter` from `@auth/drizzle-adapter` expects the that each `PGColumn` has the properties `isAutoincrement`, `isPrimaryKey`, `hasRuntimeDefault`, `generated` (see here in [pg.ts](https://github.com/nextauthjs/next-auth/blob/aef630d47fdf3da229e193059304d8e48a146c26/packages/adapter-drizzle/src/lib/pg.ts#L334)). However these are not not generated by the `createTable` calls in `/src/server/db/schema.ts`. 

### Reproduction repo

https://github.com/FroeMic/t3-auth-test

### To reproduce

**Reproduction**
You should be able to reproduce the error by running `npm create t3-app@latest` with the above mentioned options and then opening `/src/server/auth.ts`

- TypeScript
- Tailwind
- tRCP
- NextAuth.js
- Drizzle
- App Router
- PosgreSQL
- Git (yes)
- npm install (yes)
- alias: ~/

**Comment by gburtini** [comment]
Confirmed I ran into this last night after a version bump. The sessions table changed shape slightly and the authenticators table is slightly changed in a recent drizzle-adapter. You can find the correct [shape of the tables here](https://authjs.dev/getting-started/adapters/drizzle).

**Comment by diegodofe** [comment]
Ran a fresh `npm create t3-app@latest` this morning with the same config and can can confirm 

<img width="1065" alt="Screenshot 2024-08-02 at 9 51 54 AM" src="https://github.com/user-attachments/assets/4a05d16e-18c9-4d75-bf4f-c278f966a4cc">

**Comment by riteshreg** [comment]
![Screenshot from 2024-08-04 08-28-42](https://github.com/user-attachments/assets/b7bc454d-5ae5-4cf1-8162-fec9f614778f)

**Comment by riteshreg** [comment]
I also got same error
![Screenshot from 2024-08-04 08-53-00](https://github.com/user-attachments/assets/a5332bab-3533-47a5-92ad-5c5f5646531c)

**Comment by Phr33d0m** [comment]
For everyone in a hurry, rolling drizzle-adapter back down to 1.1.0 fixes the annoyance.

```
"@auth/drizzle-adapter": "1.1.0",
```

**Comment by nvegater** [comment]
Confirmed: 
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/310aa1ea-3d25-4e18-af06-7ba7d571772e">

**Comment by gtarraga** [comment]
Can confirm on my end as well, not using tRPC though

<img width="1241" alt="Screenshot 2024-08-05 at 23 34 53" src="https://github.com/user-attachments/assets/ee21860d-38d5-4278-896d-e89610f5aa33">



I tried rolling back the adapter like mentioned here but it didn't solve it

> For everyone in a hurry, rolling drizzle-adapter back down to 1.4.1 fixes the annoyance.
> 
> ```
> "@auth/drizzle-adapter": "1.4.1",
> ```
> 
> More info here: [nextauthjs/next-auth#11490](https://github.com/nextauthjs/next-auth/issues/11490)

**Comment by riteshreg** [comment]
same issue with mysql
![Screenshot (17)](https://github.com/user-attachments/assets/f30a44ce-c9e9-4a22-bc04-10155d8d2d70)
![Uploading Screenshot (18).png…]()

**Comment by juliusmarminge** [comment]
upgrade to latest drizzle-orm will fix these type-mismatches
