### ISSUE TITLE
bug: NextAuth uses features from a newer version of Drizzle/MySql which results in error when trying to insert a new user. 

### ISSUE THREAD

**Issue by ramoneres** [t3-oss/create-t3-app#1960]
### Provide environment information

.

### Describe the bug

When using the MySql adapter for drizzle, NextAuth fails to insert the user because it's calling $returningId() which does not exist in the drizzle version create t3-app provides. [$returningId() was introduced in 0.32.0](https://github.com/drizzle-team/drizzle-orm/releases/tag/0.32.0) but t3-app installs 0.30.10. 

### Reproduction repo

.

### To reproduce

Just install a new t3 instance with drizzle and mysql adapter and try logging in. User creation will fail.

### Additional information

To solve just update drizzle to at least 0.32.0

**Comment by brandon-arche** [comment]
I am experiencing this as well

**Comment by AndKenneth** [comment]
+1, also confirmed while using postgres. Upgrade to latest (`npm i drizzle-orm@0.33.0`) fixes
