### ISSUE TITLE
feat: use defineConfig function from drizzle-kit instead of using "satisfies Config" type

### ISSUE THREAD

**Issue by EkaanshArora** [t3-oss/create-t3-app#1963]
### Is your feature request related to a problem? Please describe.

The config section in the [docs](https://orm.drizzle.team/kit-docs/config-reference#configuration) now uses `defineConfig`, example:
```ts
import { defineConfig } from 'drizzle-kit'
export default defineConfig({
  dialect: "postgresql",
  schema: "./schema.ts",
  out: "./drizzle"
})
```
Is there a reason we still use the Config type to check the config object? 

### Describe the solution you'd like to see

Update the CLI template to use `defineConfig` function 

### Describe alternate solutions

Continue to use the Config type to check the object

### Additional information

Curious if this hasn't been used because it's low value, or if the current solution is better in some way. I see the [commit](https://github.com/t3-oss/create-t3-app/commit/9e5e7d0c4342542fec18fdc97552b494fe31f5a3) to upgrade to `v0.21.0` fixed the breaking changes but omited this change.

**Comment by juliusmarminge** [comment]
I don't see the value. To me it's better to use a `satisfies Config` as 

a) it shows intent, the defineConfig fn is [just an identity function](https://github.com/drizzle-team/drizzle-orm/blob/6adbd78748c8ecb687caa87b7cd775d86cdc0a2b/drizzle-kit/src/index.ts#L295-L297) with types which `satisfies` serves the same purpose just more explicit
b) no need to import runtime code from `drizzle-kit`

**Comment by EkaanshArora** [comment]
That makes sense, thank you!
