### ISSUE TITLE
bug: Suspense errors not caught by error boundary

### ISSUE THREAD

**Issue by musjj** [t3-oss/create-t3-app#1971]
### Provide environment information

  System:
    OS: Linux 6.6 NixOS 24.11 (Vicuna) 24.11 (Vicuna)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700F
    Memory: 3.12 GB / 15.46 GB
    Container: Yes
    Shell: 5.9 - /run/current-system/sw/bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nix-profile/bin/node
    npm: 10.7.0 - ~/.nix-profile/bin/npm

### Describe the bug

When a suspense query throws an error, the error will not be caught at the error boundary. This makes error handling for suspense queries really difficult/impossible.

### Reproduction repo

https://github.com/musjj/trpc-suspense-error

### To reproduce

1. In `src/server/api/routers/post.ts`, throw a tRPC error in `getLatest`:
   ```diff
   getLatest: publicProcedure.query(() => {
   -  return posts.at(-1) ?? null;
   +  throw new TRPCError({ code: "FORBIDDEN" });
   })
   ```

2. Wrap the `LatestPost` component in `src/app/page.tsx` with a suspense and error boundary:
   ```tsx
   <ErrorBoundary fallback={<div>ERROR!!!</div>}>
     <Suspense fallback={<div>LOADING...</div>}>
       <LatestPost />
     </Suspense>
   </ErrorBoundary>
   ```

3. Remove the prefetching in `src/app/page.tsx`, so that the error happens inside the component:

   ```diff
   - void api.post.getLatest.prefetch();
   ```

4. Run `npm run dev`. You'll see that the error is not caught at the boundary, they will show up as an unhandled runtime error in the overlay and console. You can also throw a normal error (`throw new Error(...)`) inside the `LatestPost` component, but they are properly caught at the boundary.

**Comment by juliusmarminge** [comment]
The error boundary displays is rendered?

![CleanShot 2024-08-27 at 22 13 03@2x](https://github.com/user-attachments/assets/5193dd79-9026-4c8b-af07-9a44b1199651)

**Comment by musjj** [comment]
Ah right, I forgot that the query retries a few times before error-ing :man_facepalming:
