### ISSUE TITLE
feat: AuthJS v5

### ISSUE THREAD

**Issue by lacymorrow** [t3-oss/create-t3-app#1979]
### Is your feature request related to a problem? Please describe.

What is still outstanding here? Are we just waiting for them to list the next JS flavor as not in beta?

### Describe the solution you'd like to see

AuthJS v5 implementation

### Describe alternate solutions

NextAuth v4What is still outstanding here? Are we just waiting for them to list the next JS flavor as not in beta

**Comment by maiconcarraro** [comment]
it's being updated on https://github.com/t3-oss/create-t3-app/pull/2000/files#diff-dd60a26d18c1b84913c096833058284ea3c679048534452710030a1bafe0b052L7

**Comment by kuchejak** [comment]
Is v5 production ready though? The package is still marked as beta (`"next-auth": "5.0.0-beta.25"`) and the only official comment regarding this from the maintainers I managed to find was [on their Discord](https://discord.com/channels/1200116961590399008/1272603115962503241/1280984017038217309), linking to [this tweet](https://x.com/balazsorban44/status/1802457422339899735):

> beta is stable enough for 90+% of our users
