### ISSUE TITLE
feat: add more `scripts` in `package.json`

### ISSUE THREAD

**Issue by programming-with-ia** [t3-oss/create-t3-app#1981]
### Is your feature request related to a problem? Please describe.

[add more scripts in p](feat: add more `scripts` in `package.json`)

### Describe the solution you'd like to see

```json
  "scripts": {
    "dev": "rimraf .next && next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "lint:fix": "next lint --fix",
    "preview": "next build && next start",
    "typecheck": "tsc --noEmit",
    "clean": "rimraf .next",
    "format:write": "prettier --write \"**/*.{ts,tsx,js,jsx,mdx}\" --cache",
    "format:check": "prettier --check \"**/*.{ts,tsx,js,jsx,mdx}\" --cache"
  },
```

### Describe alternate solutions

etc

**Comment by kamalxdev** [comment]
@juliusmarminge , assign this to me

**Comment by juliusmarminge** [comment]
Assigning people doesn't really work in OSS development from my experience as it just lets others think someone is working on it when in fact they may never pick it up.

So, if there's no PR up just open a PR (or draft) to let others know you're _actually_ working on it :)

**Comment by programming-with-ia** [comment]
@juliusmarminge 
Okay, I will work on this after a few days/weeks as I am busy right now 😌 🙏

**Comment by kamalxdev** [comment]
@juliusmarminge please review it and let me know if any modification needed

**Comment by programming-with-ia** [comment]
> Assigning people doesn't really work in OSS development from my experience as it just lets others think someone is working on it when in fact they may never pick it up.
> 
> So, if there's no PR up just open a PR (or draft) to let others know you're _actually_ working on it :)

@juliusmarminge

[PR Submitted](https://github.com/t3-oss/create-t3-app/pull/1997)
