### ISSUE TITLE
feat: Will the Next.js version consider updating to 15?

### ISSUE THREAD

**Issue by Deer404** [t3-oss/create-t3-app#1999]
### Is your feature request related to a problem? Please describe.

Next.js 15 is officially stable, and the official blog states that it can be used in production environments. Are there any plans to follow up with the official version?

### Describe the solution you'd like to see

Next.js updated to 15

### Describe alternate solutions

Refer to the update details in[Next.js 15 | Next.js --- Next.js 15](https://nextjs.org/blog/next-15)to check for breaking changes, modify the current code, and migrate to Next.js 15.

**Comment by juliusmarminge** [comment]
#2000

**Comment by maiconcarraro** [comment]
@juliusmarminge plans to upgrade eslint to v9 as well?

**Comment by juliusmarminge** [comment]
> @juliusmarminge plans to upgrade eslint to v9 as well?

#1955
