### ISSUE TITLE
bug: Crypto not defined in envVars cli installer

### ISSUE THREAD

**Issue by swyckoff** [t3-oss/create-t3-app#2009]
### Provide environment information

```
  System:
    OS: macOS 14.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 4.21 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 9.12.1 - /opt/homebrew/bin/pnpm

```

### Describe the bug

The envVariables cli runner fails to install because of an undefined package:

```
Adding boilerplate...
✔ Successfully setup boilerplate for drizzle
✔ Successfully setup boilerplate for tailwind
⠋ Boilerplating envVariables...Aborting installation...
ReferenceError: crypto is not defined
```

We should see this:

```

Adding boilerplate...
✔ Successfully setup boilerplate for drizzle
✔ Successfully setup boilerplate for tailwind
✔ Successfully setup boilerplate for envVariables
✔ Successfully setup boilerplate for eslint
```

### Reproduction repo

https://github.com/t3-oss/create-t3-app

### To reproduce

Scaffold with:
- TypeScript
- Tailwind: Yes
- tRPC: No
- Auth: None
- ORM: Drizzle
- App Router: Yes
- Run 'pnpm install': Yes
- Default Imports: use default

**Comment by AkritW** [comment]
I also got the same problem

**Comment by raihanmd** [comment]
i got this problem too

**Comment by juliusmarminge** [comment]
i'll soon be releasing the new version where we use `node:crypto` instead of global crypto 

ooc, what your node version? `globalThis.crypto` has been around for a bit now

**Comment by raihanmd** [comment]
18.20.4

**Comment by raihanmd** [comment]
nvm im using node v20 and its work

**Comment by juliusmarminge** [comment]
![CleanShot 2024-11-04 at 09 55 31](https://github.com/user-attachments/assets/1cf42c2d-7ff6-42b2-9c3f-c1f56bce21a4)

18.20 seems like it should work too

**Comment by AkritW** [comment]
I just tested it out as per the latest update. Node v18 doesn't work, even though v20 does work.
