### ISSUE TITLE
bug: Fonts Brokren in Next 15

### ISSUE THREAD

**Issue by IzaanAnwar** [t3-oss/create-t3-app#2042]
### Provide environment information

`"initVersion": "7.38.1"`

  System:
    OS: Linux 6.11 Manjaro Linux
    CPU: (4) x64 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
    Memory: 2.14 GB / 7.47 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v22.2.0/bin/npm
    pnpm: 9.8.0 - ~/.local/share/pnpm/pnpm
    bun: 1.1.17 - ~/.bun/bin/bun
    
    
    

### Describe the bug

Fonts installation is Broken in Next js15.
I just create the app, and ran `pnpm dev`, first I got an error with turbopack saying see next dev for more information, but nothing on console so I just removed the turbo flag form dev command.

After that I am not able to get the fonts thing working.

```
Failed to compile

node_modules/.pnpm/geist@1.3.1_next@15.0.4_react-dom@18.3.1_react@18.3.1__react@18.3.1_/node_modules/geist/dist/sans.js
An error occurred in `next/font`.

Error: Cannot find module '....../whatevermyapp/node_modules/.pnpm/sucrase@3.35.0/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'
```

I then tried google and local fonts with next/font/google and next/font/local, and nothing worked.

### Reproduction repo

null

### To reproduce

`pnpm create t3-app@latest some-app`

### Additional information

![image](https://github.com/user-attachments/assets/52852b55-70d8-454b-924c-c5729dc57a02)

**Comment by Ollebolle** [comment]
@IzaanAnwar If you need a quick fix you can try downgrading: `"@jridgewell/gen-mapping": "0.3.5",` manually. Also, make sure to remove `node_modules` and lock file(s).

**Comment by IzaanAnwar** [comment]
So I tried to create a Normal nextjs app and it seems this error is there too.

Might be specific to my system. But still keeping the issue open, so that if others encounter the same, maybe someone can help

**Comment by IzaanAnwar** [comment]
Seems it was an issue only for my machine
