### ISSUE TITLE
Thoughts on integrating trpc-shield

### ISSUE THREAD

**Issue by omar-dulaimi** [t3-oss/create-t3-app#207]
Thanks for creating this awesome project.

I was taking a look through the code base, thinking of auth logic and how it's currently implemented. 
I thought to myself, why not make use of `trpc-shield`?

```ts
import * as trpc from '@trpc/server'
import { rule, shield, and, or, not } from 'trpc-shield'

// Rules

const isAuthenticated = rule()(async (ctx, type, path, rawInput) => {
  return ctx.user !== null
})

const isAdmin = rule()(async (ctx, type, path, rawInput) => {
  return ctx.user.role === 'admin'
})

const isEditor = rule()(async (ctx, type, path, rawInput) => {
  return ctx.user.role === 'editor'
})

// Permissions

const permissions = shield({
  query: {
    frontPage: not(isAuthenticated),
    fruits: and(isAuthenticated, or(isAdmin, isEditor)),
    customers: and(isAuthenticated, isAdmin),
  },
  mutation: {
    addFruitToBasket: isAuthenticated,
  },
})

export function createRouter() {
  return trpc.router<Context>().middleware(permissions)
}
```

As it makes authorization super simple, and in a single place.

Is it something the project wants to provide in the near future at all?
If yes, I would love to work on that PR.

**Comment by TheoBr** [comment]
Not interested tbh, could fit in a more generic "t3 examples" repo in future

**Comment by der-ofenmeister** [comment]
@omar-dulaimi I'm down to collab on a t3 examples repo if you'd like!
