### ISSUE TITLE
Add discord link in readme

### ISSUE THREAD

**Issue by TheoBr** [t3-oss/create-t3-app#211]
We've had a few people leaking into the Ping discord asking for create-t3-app help, might be worth dropping a link to https://t3.gg/discord here somewhere

**Comment by nexxeln** [comment]
> We've had a few people leaking into the Ping discord asking for create-t3-app help, might be worth dropping a link to https://t3.gg/discord here somewhere

We have in the contributors section, but if you want it somewhere else sure.

**Comment by juliusmarminge** [comment]
Implemented in #229
