### ISSUE TITLE
Why is a global Prisma client exposed in development?

### ISSUE THREAD

**Issue by ChristianIvicevic** [t3-oss/create-t3-app#214]
Referring to this snippet over here:
https://github.com/t3-oss/create-t3-app/blob/59f8ad4f2104aa1f11508b55da75c333dce03625/template/addons/prisma/client.ts#L15-L17

Saw this without any specific explanation and out of curiosity wanted to know what the reason is for exposing Prisma like this. Just to have easy access in the browser console during development?

**Comment by nexxeln** [comment]
https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices

**Comment by ChristianIvicevic** [comment]
Thanks for the clarification. Didn't expect it to be that important until I read the respective documentation you just linked.
