### ISSUE TITLE
NEXTAUTH_URL is not required for production on Vercel

### ISSUE THREAD

**Issue by ChristianIvicevic** [t3-oss/create-t3-app#216]
I noticed that the `NEXTAUTH_URL` is marked as required in the schema over here:
https://github.com/t3-oss/create-t3-app/blob/59f8ad4f2104aa1f11508b55da75c333dce03625/template/addons/env/env-auth.mjs#L5

However there is an edge case when the application is deployed via Vercel on production. In those cases NextAuth.js automatically reads `VERCEL_URL` instead: 
* https://next-auth.js.org/deployment#vercel
> You do not need the NEXTAUTH_URL environment variable in Vercel.

* https://next-auth.js.org/configuration/options#nextauth_url
> Using [System Environment Variables](https://vercel.com/docs/concepts/projects/environment-variables#system-environment-variables) we automatically detect when you deploy to [Vercel](https://vercel.com/) so you don't have to define this variable. Make sure Automatically expose System Environment Variables is checked in your Project Settings.

One might consider making the schema a bit more dynamic and add `.optional()` in case `VERCEL_ENV='production'` and `VERCEL_URL` is defined.

**Comment by juliusmarminge** [comment]
Two perspectives to this:

a) set as optional and link related docs

+ deploying to vercel is a common deployment method for next apps so this would help sorting that out and make a smooth starting point.

b) let the dev fix this themselves

+ since we don't prescribe any deployment method, this seems like the sort of edgecase that is beyond our scope

**Comment by c-ehrlich** [comment]
AFAIK you need the NEXTAUTH_URL in dev so it should be required - in Vercel, where it's not required, it doesn't come from the .env file anyway. I could see adding a link to the relevant part of the docs to the .env file

something like:
```
# Next Auth
# For deploying to Vercel, see: https://next-auth.js.org/configuration/options#nextauth_url
NEXTAUTH_SECRET=
NEXTAUTH_URL=http://localhost:3000
```

**Comment by juliusmarminge** [comment]
@nexxeln thoughts?

**Comment by nexxeln** [comment]
Yeah I don't think this should be optional, not everyone is deploying to vercel. And of course the env variables aren't comping from the .env file either.
