### ISSUE TITLE
Getting a "EINVALIDPACKAGENAME" on fresh install

### ISSUE THREAD

**Issue by amyisdev** [t3-oss/create-t3-app#219]
**Describe the bug**
After a fresh t3 install using the latest version, `npm install` fails because of invalid package name "react-query@3.39.2".

**To Reproduce**

1. Run `npx create-t3-app@latest`
2. Answer no to run npm install 
3. Then manually run it

**Expected behavior**
Dependencies should be installed with no failure

**Screenshots**
![image](https://user-images.githubusercontent.com/94958349/179659431-d036760e-d911-4ac9-8029-7f31da8de03a.png)

**Comment by juliusmarminge** [comment]
Weird. Tested this out yesterday and was working fine.

Can you verify the version of:

- create-t3-app (npx create-t3-app --version)
- Node
- npm

**Comment by juliusmarminge** [comment]
> Either answer yes to run npm install or manually run it

On second thought I believe this is incorrect and that this is a bug with the noInstall flag. Also test answering yes when prompted in the CLI.

**Comment by amyisdev** [comment]
> On second thought I believe this is incorrect and that this is a bug with the noInstall flag. Also test answering yes when prompted in the CLI.

Ah, my bad. You are right, looks like it only fails with the noInstall flag.

**Comment by juliusmarminge** [comment]
This is the failing line:

https://github.com/t3-oss/create-t3-app/blob/cf7be5a70d5ed08611add10958bdfd88b1c23cba/src/utils/runPkgManagerInstall.ts#L41

Can fix it tonight if noone files a PR before then.
