### ISSUE TITLE
Give the option to migrate the database at the end of scaffolding?

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#224]
**Is your feature request related to a problem? Please describe.**
It's nice when a freshly scaffolded app 'just runs'. But we're currently not migrating the database by default, which means that all the prisma stuff fails, because those tables don't exist. 

**Describe the solution you'd like**
We could just migrate the sqlite database once everything else in the scaffolding is done, if the project includes Prisma.

**Describe alternatives you've considered**
Making it optional would add one more step to the CLI which I don't love. 

I'm not sure if this is necessary - hopefully users know how to migrate the db. But wanted to throw it out there to maybe get some comments and see how others feel.

**Comment by nramkissoon** [comment]
The CLI lists `npx prisma db push` as one of the next steps after it is done setting up the app with prisma. Also, I think running a migrate requires the DATABASE_URL environment variable to exist and the database has to be connected to. Both of those do not happen while the CLI is creating the app.  The user has to set up env variables and connect to the db afterwards.

**Comment by juliusmarminge** [comment]
> DATABASE_URL environment variable to exist and the database has to be connected to. Both of those do not happen while the CLI is creating the app

Actually they do. The problem is that sqlite does not support NextAuth so I think you would still get errors?
