### ISSUE TITLE
Cannot find module 'next/babel'

### ISSUE THREAD

**Issue by wlechowicz** [t3-oss/create-t3-app#225]
**Describe the bug**
ESlint errors on a fresh ct3a app due to wrong ESlint config. "Parsing error: Cannot find module 'next/babel'" on every `import`.

**To Reproduce**

1. npx create-t3-app
2. selected only next-auth
3. open any file with an `import`

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/24250766/179749168-2e82efa9-243f-4cea-9287-b1b514aaffdc.png)

**Fix**
Change .eslintrc.json from
```
{
  "extends": ["next/core-web-vitals"]
}
```
to
```
{
  "extends": ["next/babel","next/core-web-vitals"]
}
```

**Comment by wlechowicz** [comment]
Before I submit a PR with a fix, feel free to tell me if you can reproduce or was my mommy right in telling me I'm special.

**Comment by juliusmarminge** [comment]
Can't reproduce on my side.

Can you verify some versions for me:
- What package manager and version are you using?
- What Node version?
- What create-t3-app version?

**Comment by wlechowicz** [comment]
@juliusmarminge I just reproduced this on a different PC, first try.
```
PS G:\www> npx create-t3-app
Need to install the following packages:
  create-t3-app
Ok to proceed? (y) y

    ___ ___ ___   _ _____ ___   _____ ____    _   ___ ___ 
  / __| _ \ __| /_\_   _| __| |_   _|__ /   /_\ | _ \ _ \ 
 | (__|   / _| / _ \| | | _|    | |  |_ \  / _ \|  _/  _/ 
  \___|_|_\___/_/ \_\_| |___|   |_| |___/ /_/ \_\_| |_|   
                                                          
? What will your project be called? ct3a-repro
? Will you be using JavaScript or TypeScript? TypeScript
Good choice! Using TypeScript!
? Which packages would you like to enable? nextAuth
? Initialize a new git repository? No
Sounds good! You can come back and run git init later.
? Would you like us to run npm install? Yes
Alright. We'll install the dependencies for you!

Using: npm

✔ ct3a-repro scaffolded successfully!

Installing packages...
✔ Successfully installed nextAuth
✔ Successfully installed envVariables

Next steps:
  cd ct3a-repro
  npm run dev
```
PC on Windows 10 and env:
```
PS G:\www>node -v
v16.14.2
PS G:\www> npm --version
8.5.0
PS G:\www> npx create-t3-app --version

    ___ ___ ___   _ _____ ___   _____ ____    _   ___ ___ 
  / __| _ \ __| /_\_   _| __| |_   _|__ /   /_\ | _ \ _ \
 | (__|   / _| / _ \| | | _|    | |  |_ \  / _ \|  _/  _/
  \___|_|_\___/_/ \_\_| |___|   |_| |___/ /_/ \_\_| |_|  
                                                         
5.2.1
```

![obraz](https://user-images.githubusercontent.com/24250766/179868153-99a836ee-0179-442d-b0fd-461a9f30e779.png)

**Comment by wlechowicz** [comment]
Ok found the issue, it was due to bad `rootDir` in the root .eslintrc in a monorepo when using `eslint-plugin-next`, so both create-next-app and create-t3-app will produce the same error when used to create packages/apps unless `settings.next.rootDir` is properly set.
If you don't use a monorepo but create the app from IDE terminal and then don't reopen IDE on the app dir but stay in the parent dir instead, same old.

Closing.
