### ISSUE TITLE
Create T3 App logo renders incorrectly when using yarn or pnpx

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#234]
**Describe the bug**
The "Create T3 App" logo renders correctly when ct3a is invoked with npx. But when yarn or pnpx are used, the top line is shifted to the right by one character.

**To Reproduce**
`yarn create t3-app` or `pnpx create-t3-app`

**Expected behavior**
The logo should look correct regardless of which tool was used

**Proposed solution**
Adding a check to see which tool was used before rendering the logo seems annoying. Instead we could maybe just add another newline before the logo?

**Screenshots**
in order: npx, yarn, pnpx
<img width="848" alt="image" src="https://user-images.githubusercontent.com/8353666/180188265-5daa000d-46c3-41ea-9d41-4638aa18d418.png">

**Comment by nexxeln** [comment]
This is a known issue, will be fixed in the next release.

**Comment by c-ehrlich** [comment]
After seeing that screenshot, I agree

**Comment by juliusmarminge** [comment]
Added a newline when using yarn or pnpm, this is how it looks. Can't test with yarn cause my yarn flips out when doing `yarn create t3-app@beta`.

<img width="759" alt="CleanShot 2022-07-21 at 23 43 47@2x" src="https://user-images.githubusercontent.com/51714798/180320580-89c8bd95-8f10-4899-91cf-094fe3bc4f59.png">

**Comment by juliusmarminge** [comment]
Fixed in latest beta and will be pushed to latest in the near future.
