### ISSUE TITLE
Bad performance test using LightHouse (~48)

### ISSUE THREAD

**Issue by GabrielPedroza** [t3-oss/create-t3-app#241]
**Describe the bug**
Decided to test the t3 stack with very minor changes (similar results with no changes)

**To Reproduce**
Steps to reproduce the behavior: Just npx create or yarn create a t3 stack app and run lighthouse

**Screenshots**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/77304345/180488622-51071079-d447-40b7-a20e-de868ef23787.png">

**Comment by bhatvikrant** [comment]
@GabrielPedroza  @juliusmarminge any suggestions on how we can improve this? 
I can pick this up after our discussion

**Comment by nexxeln** [comment]
![lighthouse scores](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/brave_C0QdMgjcDd.png)

I'm getting good lighthouse scores.

Link to the website: https://t3-other-world.vercel.app

**Comment by bhatvikrant** [comment]
Same @nexxeln

**Comment by bhatvikrant** [comment]
@GabrielPedroza did you test this in an incognito browser tab or a regular one?

**Comment by GabrielPedroza** [comment]
@bhatvikrant I've tested this with both and have similar results on each. I'm using localhost to test this so I'm not sure if there is an intrinsic affect to the results though.

**Comment by GabrielPedroza** [comment]
I'm going to create a brand new t3 app and see if I get the same results using localhost

**Comment by bhatvikrant** [comment]
@GabrielPedroza can you please test here https://t3-other-world.vercel.app/

This is a deployed version of t3-app as shared by @nexxeln 
It should give the most precise results.

**Comment by GabrielPedroza** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/77304345/180504262-5ce870c1-fd82-4943-9b91-c7e5ba11f6a6.png">

I got the same results again (around 48 performance) in localhost.

**Comment by GabrielPedroza** [comment]
> @GabrielPedroza can you please test here https://t3-other-world.vercel.app/
> 
> This is a deployed version of t3-app as shared by @nexxeln It should give the most precise results.

I got a ? in performance. Chrome didn't collect any screenshots during the page load. Please make sure there is content visible on the page, and then try re-running Lighthouse. (SPEEDINDEX_OF_ZERO) (Tested on regular and incognito)

**Comment by GabrielPedroza** [comment]
Now, after hosting the test-t3 site on vercel, it gives me perfect performance. Does lighthouse have any barriers or affects from localhost?

**Comment by bhatvikrant** [comment]
> Before hosting, I got horrible performance. Now, after hosting the test-t3 site on vercel, it gives me perfect performance. Does lighthouse have any barriers or affects from localhost?

I'm guessing you tested locally on a development build.

But if you build the project locally 'pnpm build' and then test using lighthouse then it should give you the desired results.

**Comment by nexxeln** [comment]
Yup try this
```
npm run build && npm run start
```

This will run it in production mode on localhost. Check the scores there.

**Comment by bhatvikrant** [comment]
We can close this @nexxeln I think

**Comment by GabrielPedroza** [comment]
Awesome! Thanks for letting me know guys. I'll close this issue
