### ISSUE TITLE
feature: Add _document.tsx for accessibility reasons 

### ISSUE THREAD

**Issue by GabrielPedroza** [t3-oss/create-t3-app#249]
**Is your feature request related to a problem? Please describe.**
To add a _document.tsx in order to override the default nextjs document and implement a lang attribute. This will reach 100% accessibility in lighthouse since, by default, there is no html with lang.

**Describe the solution you'd like**
```tsx

import { Html, Head, Main, NextScript } from "next/document"

export default function Document() {
	return (
		<Html lang="en">
			<Head />
			<body>
				<Main />
				<NextScript />
			</body>
		</Html>
	)
}

```

**Comment by GabrielPedroza** [comment]
Very small implementation for perfect scores in every category in lighthouse. big flex 😎

**Comment by TheoBr** [comment]
This is not that simple as a user may have their own plans for HTML localization. Create-next-app doesn't even include this :(

Also generally better to set in next config not document fwiw

**Comment by GabrielPedroza** [comment]
I did have a setup in `next.config.js` pertaining to localization but it had no effect even though it should accomplish what was initially needed. I haven't looked under the hood on how the two work but prolly is something that is more of a waste of time.

**Comment by GabrielPedroza** [comment]
And this is just to pass with perfect scores in lighthouse. I'm sure devs will modify this to their liking and needs
