### ISSUE TITLE
Best way to protect routes (api and client)

### ISSUE THREAD

**Issue by tprjd** [t3-oss/create-t3-app#250]
Hi,

So the problem is that i can't figure out an effective way to protect every client-side route. Every route should only be available when you are logged in and I don't want to check the session in every page.
Next auth middleware would be a good and clean solution but it only works with jwt and not with database based sessions. 

_src/components/RouterGuard.tsx_
```javascript
export const RouterGuard: FC<PropsWithChildren> = ({ children }) => {
  const session = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!session.data && session.status !== 'loading') {
      void router.replace('/auth/signin');
    }
  }, [session]);

  if (router.pathname.includes('/auth')) {
    return <>{children}</>;
  }

  if (session.status === 'loading') {
    return <>Loading...</>;
  }

  return <>{children}</>;
};
```
__app.tsx_
```javascript
          <RouterGuard>
            <Component {...pageProps} />
          </RouterGuard>
```

This is what I have currently but I'm not sure how does this work with ssr.
I'm sorry if I'm missing something obvious, this stack is pretty new to me.

Thanks,
D

**Comment by juliusmarminge** [comment]
I am not familiar with this use-case, I have never had to protect every single route like this..

The way I usually do it is just via gSSP on a per-page basis:

```ts
export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const session = await getAuthSession(ctx);
  if (!session) {
    return { 
      redirect: { 
        destination: "/auth/signin", 
        permanent: false,
      }, 
      props: { from: ctx.req.url }, // so that you can redirect to where they came from after login
    };
  }
  return { props: {} };
};
```

I feel like your approach is going to fail as soon as you add a single page where you don't want to authenticate. You probably want a landing page so that your users can see what the app is about before forcing them to sign in?
