### ISSUE TITLE
Adding "paths" and "baseUrl" to `tsconfig.json` breaks module augmentations

### ISSUE THREAD

**Issue by zomars** [t3-oss/create-t3-app#254]
**Describe the bug**
It seems like the declared `next-auth.d.ts` is overriding the initial `next-auth` types instead of augmenting them.

**To Reproduce**

1. `pnpm dlx create-t3-app@next`
2. Select all packages
3. See `src/pages/api/auth/[...nextauth].ts` file

**Expected behavior**

Having default `next-auth` types PLUS the augmented ones.

**Screenshots**

<img width="777" alt="image" src="https://user-images.githubusercontent.com/3504472/180909657-519df48f-6fcf-4ee5-b7c0-46ff7b769751.png">

<img width="648" alt="image" src="https://user-images.githubusercontent.com/3504472/180909681-3f245988-9a14-4dbc-b4f5-74e75cb33d07.png">

**Comment by nexxeln** [comment]
Unable to reproduce, works fine for me.
![user has User type](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/Code_JhXLUy5Krx.png)

**Comment by zomars** [comment]
@nexxeln it may be out of scope, but it seems this happens as soon as you add path aliases (took them from this project btw):

<img width="387" alt="image" src="https://user-images.githubusercontent.com/3504472/180913329-1cbb182d-0161-491d-9e79-5b6c9603fcd0.png">

**Comment by nexxeln** [comment]
Yup thats the issue, I added path aliases and am now getting a type error.

**Comment by zomars** [comment]
It seems like even with #255 adding both "paths" and "baseUrl" to `tsconfig.json` keeps messing up with the module augmentations.

**Comment by nexxeln** [comment]
> It seems like even with #255 adding both "paths" and "baseUrl" to `tsconfig.json` keeps messing up with the module augmentations.

Yeah I'm not sure how to fix this, I'll open an issue in `next-auth`

**Comment by kroucher** [comment]
Some info for troubleshooting, when the `next-auth.d.ts` file is moved into any subdirectory, the types start working again.

![image](https://user-images.githubusercontent.com/99768034/180942900-1ab5377b-f1da-48de-819e-88f0b2708d9c.png)

Not sure if having a 'types' folder by default is too opinionated, but either way, the issue lies with the `next-auth.d.ts` file being in the root directory.

**Comment by JohnDaly** [comment]
I noticed that changing the filename of `next-auth.d.ts` to something else (e.g. `custom-next-auth.d.ts`) will clear the type errors as well

**Comment by nexxeln** [comment]
Thank you for sharing @JohnDaly @kroucher 

I'll mention this in the next-auth issue too, not sure if they have a better solution.

**Comment by JohnDaly** [comment]
Looks like TypeScript resolves the `next-auth` import to the `next-auth.d.ts` file, and doesn't go looking for the types in `node_modules`. When the name is different, it is able to find the types.

Here's the output from running `tsc --traceResolution`:

### With `next-auth.d.ts`
```
======== Resolving module 'next-auth' from '/my-t3-app/next-auth.d.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'baseUrl' option is set to '/my-t3-app', using this value to resolve non-relative module name 'next-auth'.
'paths' option is specified, looking for a pattern to match module name 'next-auth'.
'baseUrl' option is set to '/my-t3-app', using this value to resolve non-relative module name 'next-auth'.
Resolving module name 'next-auth' relative to base url '/my-t3-app' - '/my-t3-app/next-auth'.
Loading module as file / folder, candidate module location '/my-t3-app/next-auth', target file type 'TypeScript'.
File '/my-t3-app/next-auth.ts' does not exist.
File '/my-t3-app/next-auth.tsx' does not exist.
File '/my-t3-app/next-auth.d.ts' exist - use it as a name resolution result.
======== Module name 'next-auth' was successfully resolved to '/my-t3-app/next-auth.d.ts'. ========
```

### With `custom-next-auth.d.ts`
```
======== Resolving module 'next-auth' from '/my-t3-app/custom-next-auth.d.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'baseUrl' option is set to '/my-t3-app', using this value to resolve non-relative module name 'next-auth'.
'paths' option is specified, looking for a pattern to match module name 'next-auth'.
'baseUrl' option is set to '/my-t3-app', using this value to resolve non-relative module name 'next-auth'.
Resolving module name 'next-auth' relative to base url '/my-t3-app' - '/my-t3-app/next-auth'.
Loading module as file / folder, candidate module location '/my-t3-app/next-auth', target file type 'TypeScript'.
File '/my-t3-app/next-auth.ts' does not exist.
File '/my-t3-app/next-auth.tsx' does not exist.
File '/my-t3-app/next-auth.d.ts' does not exist.
Directory '/my-t3-app/next-auth' does not exist, skipping all lookups in it.
Loading module 'next-auth' from 'node_modules' folder, target file type 'TypeScript'.
Found 'package.json' at '/my-t3-app/node_modules/next-auth/package.json'.
'package.json' does not have a 'typesVersions' field.
File '/my-t3-app/node_modules/next-auth.ts' does not exist.
File '/my-t3-app/node_modules/next-auth.tsx' does not exist.
File '/my-t3-app/node_modules/next-auth.d.ts' does not exist.
'package.json' does not have a 'typings' field.
'package.json' has 'types' field 'index.d.ts' that references '/my-t3-app/node_modules/next-auth/index.d.ts'.
File '/my-t3-app/node_modules/next-auth/index.d.ts' exist - use it as a name resolution result.
Resolving real path for '/my-t3-app/node_modules/next-auth/index.d.ts', result '/my-t3-app/node_modules/.pnpm/next-auth@4.10.2.../node_modules/next-auth/index.d.ts'.
======== Module name 'next-auth' was successfully resolved to '/my-t3-app/node_modules/.pnpm/next-auth@4.10.2.../node_modules/next-auth/index.d.ts' with Package ID 'next-auth/index.d.ts@4.10.2'. ========
```

**Comment by juliusmarminge** [comment]
stumbled upon this a while back (and also helped someone in discord with similar issue) and cut this issue (https://github.com/vercel/next.js/issues/38571) for Next.js along with it.

The fix I had was just moving the file somewhere into `src` and then typescript found it. The problem then (as described in the issue) is that Next.js's typedefinition is in root and your others are in `src(/types)` which is not ideal imo.

They converted it to a discussion and since I haven't heard anything of it though...

**Comment by nexxeln** [comment]
> > @nexxeln it may be out of scope, but it seems this happens as soon as you add path aliases to the tsconfig.json (took them from [this project](https://github.com/t3-oss/create-t3-app/blob/8671e8d5e547c366b4c2f7a3dea4ff32fb9d51f6/tsconfig.json#L38-L42) btw):
> 
> that is correct. seems like when adding aliasing it doesn't find the type definition or something clashes :/
> 
> stumbled upon this a while back (and also helped someone in discord with similar issue) and cut this issue ([vercel/next.js#38571](https://github.com/vercel/next.js/issues/38571)) for Next.js along with it.
> 
> The fix I had was just moving the file somewhere into `src` and then typescript found it. The problem then (as described in the issue) is that Next.js's typedefinition is in root and your others are in `src(/types)` which is not ideal imo.
> 
> They converted it to a discussion and since I haven't heard anything of it though...

Makes sense, should we close and pin this then?

**Comment by zomars** [comment]
I think renaming to something like `custom-next-auth.d.ts` would be a sensible approach. It would make it explicit that we're augmenting a module instead of declaring an untyped one.
