### ISSUE TITLE
What about The Cloud?

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [t3-oss/create-t3-app#261]
**Is your feature request related to a problem? Please describe.**
Frontend and backend web app engineering can't be the full tech stack in a company that deploys live, public software. If `create-t3-app` wants to be a template for a complete software project, it has to factor in the rest of the infrastructure that makes real-world software projects possible. We have to answer the question "How is my app going to run?"

**Describe the solution you'd like**
It goes without saying that there's a massive cacophony of cloud services which will help you build and push your app, orchestrate deployments, and run your software. Most of those services are proprietary and contribute to vendor lock-in, which I'm guessing is in conflict with the values of this project. Despite how simple it'd be to throw `heroku deploy` into the mix, and despite how many people use similar cloud products, I would be pretty shocked if this project were to "pick a winner" among cloud platforms, so to speak.

There's good news, though. There are at least two technologies that we can safely assume will integrate gracefully with any architecture running on any cloud platform which, at this point, most vendors are assuming that you're already using for as much as you can. They are:

1. Containers
2. Kubernetes

I personally think mixing in those two technologies would be really well aligned with the T3 Axioms. This could start out small with a baked in `helm` chart, and evolve into a more full-featured open-source internal developer platform with techs like CrossPlane, KubeVela, and Argo.

**Describe alternatives you've considered**
- Just _not_ doing this and officially committing to the idea that `create-t3-app` is for frontend and backend software only.
- Creating a `create-t3-app` companion project template that deals with infrastructure which assumes you're planning on defining those things in a separate GitHub repo, but provides all the nice reasonable defaults for the infrastructure concerns of an app created with `create-t3-app`.

**Comment by nexxeln** [comment]
So if I understand you correctly, you want use to have a deployment guide?

**Comment by IsaacLeeWebDev** [comment]
> So if I understand you correctly, you want to add deployment guide?

I think we could go further and just add actual Kubernetes manifests and/or an official helm chart.

**Comment by nexxeln** [comment]
> > So if I understand you correctly, you want to add deployment guide?
> 
> I think we could go further and just add actual Kubernetes manifests and/or an official helm chart.

So you want to add a prompt for setting up kubernetes? I think that is way too opinionated and overkill.

**Comment by astridlol** [comment]
> > > So if I understand you correctly, you want to add deployment guide?
> > 
> > 
> > I think we could go further and just add actual Kubernetes manifests and/or an official helm chart.
> 
> So you want to add a prompt for setting up kubernetes? I think that is way too opinionated and overkill.

⬆

**Comment by juliusmarminge** [comment]
Yea I don't think Kubernetes is something every developer needs for their hobby apps. If you use Kubernetes I think you should set it up yourself.
