### ISSUE TITLE
Storybook?

### ISSUE THREAD

**Issue by felixlucien** [t3-oss/create-t3-app#262]
Has anyone thought of a storybook option?

Perhaps this is not aligned with the project objectives (Typesafe Stuff)?

Would anyone be able to recommend an alternative if Storybook is deemed unnecessary?

An option would be useful as the Storybook integration with Tailwind, NextJS looks a bit hairy?

Cheers all.

**Comment by nexxeln** [comment]
We will not be including Storybook. You probably don't need Storybook unless you're building a component library like Chakra.
