### ISSUE TITLE
Easy dev environment setup with Gitpod

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [t3-oss/create-t3-app#264]
**Is your feature request related to a problem? Please describe.**
This problem is actually _not_ faced by the consumers of this package, but the contributors to it.

Cloning a repo, installing tools, and setting up shop for development is always tedious. Additionally, dealing with issues that only happen on one version of one OS is a pain. Both of these problems only get worse over time as more people contribute and the tool and the code gets bigger.

**Describe the solution you'd like**
I think we can give future maintainers of this repo an easier setup and development experience by adding a few files to support Gitpod. They of course wouldn't need to ship with the package. This is purely a nice-to-have that helps significantly speed up the onboarding, development, and review process. 

**Describe alternatives you've considered**
- Supporting GitHub CodeSpaces instead, which is basically the same product but closed-source and proprietary.

**Comment by juliusmarminge** [comment]
Sorry for the delay.

I do not have any experience of this and therefore can't see the benefits this would bring.
