### ISSUE TITLE
next-auth.d.ts overwrites wrongly

### ISSUE THREAD

**Issue by Itsnotaka** [t3-oss/create-t3-app#268]
**Describe the bug**
next-auth.d.ts that was used in the newest version of T3 overwrites the import, which causes import error.

```ts
import { DefaultSession } from "next-auth";

declare module "next-auth" {
  /**
   * Returned by `useSession`, `getSession` and received as a prop on the `SessionProvider` React Context
   */
  interface Session {
    user?: {
      id?: string;
    } & DefaultSession["user"];
  }
}
```

**To Reproduce**
This issue has surfaced in my ongoing project however not shown on the newly created project, I used vscode to open both files.

**Expected behavior**
I was expecting to import next-auth while the above code overwrite even 
`import { DefaultSession } from "next-auth";`

**Comment by amyisdev** [comment]
do you set `baseUrl` in your tsconfig?
if so, this might be related to https://github.com/nextauthjs/next-auth/issues/4598

the workaround would be to move next-auth.d.ts from root to src/types

**Comment by Itsnotaka** [comment]
Ah, yes I did set baseUrl. Thank you.
