### ISSUE TITLE
Ask for project name when creating project on current dir "yarn create t3-app ."

### ISSUE THREAD

**Issue by ibrahimyaacob92** [t3-oss/create-t3-app#269]
**Describe the bug**

**To Reproduce**

1. Run this '...'
2. See error

**Expected behavior**

**Screenshots**

**Comment by juliusmarminge** [comment]
Could you provide some more information please?

**Comment by c-ehrlich** [comment]
I believe what the OP is referring to is that on `npx create-t3-app .`, the `name` in package.json also gets set to `.`.

A more sensible default to use in this case would be the name of the current directory - that's what create-next-app does for example. I personally don't think the extra step of asking the user to input a name is worth it, as you will need to edit large parts of package.json either way if you're building a large/serious app.

I'd be happy to implement using the folder name if you think it's a good idea.

**Comment by juliusmarminge** [comment]
> I believe what the OP is referring to is that on `npx create-t3-app .`, the `name` in package.json also gets set to `.`.
> 
> 
> 
> A more sensible default to use in this case would be the name of the current directory - that's what create-next-app does for example. I personally don't think the extra step of asking the user to input a name is worth it, as you will need to edit large parts of package.json either way if you're building a large/serious app.
> 
> 
> 
> I'd be happy to implement using the folder name if you think it's a good idea.

Sure, sounds sensible.

To the OP, next time when opening an issue, please fill in the form with information and not just submit the preset.

**Comment by ibrahimyaacob92** [comment]
sorry bad habit of mine, but thanks! love to see you guys making this project better and better
