### ISSUE TITLE
Add Postgres DB out of the box with Docker Compose

### ISSUE THREAD

**Issue by herbievine** [t3-oss/create-t3-app#270]
Databases are hard to understand when you start to code. This would make it easy to start with psql straight away. A new prompt to the CLI could be added like `What database solution do you want?`

**Comment by c-ehrlich** [comment]
Not a fan of this personally, it feels like adding a lot of extra weight to ct3a and not getting much in return.

**Comment by nexxeln** [comment]
> Databases are hard to understand when you start to code

Prisma makes this easy, most of their syntax works with all types of databases.
