### ISSUE TITLE
Next-auth fails with OAuthAccountNotLinked on second signin with Google OAuth + MySQL

### ISSUE THREAD

**Issue by cyremur** [t3-oss/create-t3-app#271]
**Describe the bug**
When using Google OAuth with MySQL, the next-auth Account creation silently fails.

**To Reproduce**

1. Setup create-t3-app with next-auth with Google OAuth and MySQL DB.
2. Push default schema `npx prisma db push`
3. Sign in via `/api/auth/signin`
4. Sign out via `/api/auth/signout`
5. Sign in via `/api/auth/signin`

**Expected behavior**
User is signed back into their account.

**Actual behavior**
Next-auth throws an error.
OAuthAccountNotLinked
![image](https://user-images.githubusercontent.com/5361181/182052916-7d50015f-bf8c-4459-9f67-154c9b686b08.png)

**Debugging results**
When using OAuth, next-auth creates an entry in both the User and the Account table. The Account table is used to verify repeated OAuth sign ins.

However, it turns out that some OAuth tokens (in my case from Google) are very long. The default DB Mapping for the type String is Text in PostgreSQL and SQLite but notably VARCHAR(191) in MySQL. This results in the INSERT statement into the Account table silently failing in the prisma adapter and a User being created without accompanying Account. That User has one and only one session where everything works as expected, and on second sign-in the missing entry in Account table will make the User inaccessible.
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#string

Note: I used PlanetScale because it was referenced in https://init.tips/others and it uses MySQL. IMO, it would be nice if create-t3-app fully supported that one out of the box with next-auth and prisma.

**Solution**

I fixed this issue by annotating the two relevant token columns `access_token` and `id_token` with an explicit `@db.text`:
```
// Necessary for Next auth
model Account {
    id                       String  @id @default(cuid())
    userId                   String
    type                     String
    provider                 String
    providerAccountId        String
    refresh_token            String?
    access_token             String? @db.Text
    expires_at               Int?
    token_type               String?
    scope                    String?
    id_token                 String? @db.Text
    session_state            String?
    user                     User    @relation(fields: [userId], references: [id], onDelete: Cascade)

    @@unique([provider, providerAccountId])
}
```

This schema should work fine for PostgreSQL, MySQL, and Microsoft SQL Server. It might however cause issues for SQLite, CockroachDB and MongoDB. I only tested with MySQL and SQLite: MySQL this works, SQLite fails on `npx prisma db push`.

I am not sure if this warrants changing the default values since it doesn't seem to be universally compatible, but I wanted to contribute a write-up of this error since Google OAuth + MySQL seems like a reasonably common use case.

**Comment by juliusmarminge** [comment]
Thank you for noticing this.

These fields should be marked `Text` according to the [Next-Auth.js docs](https://next-auth.js.org/adapters/prisma#setup)

I think we have has this brought up before and changed it... The caveat is that `Text` is not supported on `SQLite` which would make the `prisma db push` fail if you don't change to for example MySQL or PostgreSQL...

Maybe we should have a warning if the user selects Next-Auth.js saying they need to change their db provider? That way we could have the correct default model.

**Comment by juliusmarminge** [comment]
Feel free to PR this if you're down!

**Comment by cyremur** [comment]
So I've read in another issue that next Auth doesn't work with sqlite anyway. So the PR would change the schema used when prisma and Auth is selected with @db.text annotation and then print a warning that you may need to adjust the schema if you use something else than mysql/postgres/ms SQL. 

Yeah, I will open a PR with the schema annotation and we can take any further discussion there.

**Comment by cyremur** [comment]
Ok I just wanted to make super clear what is going on with `SQLite` so I ran a quick test on my existing app switching to that.

1. `SQLite` + next-auth works fine if you omit the `@db.text`. Whatever the default mapping for `String?` is seems to have enough capacity to hold the Google OAuth tokens at least.
2. `SQLite` does NOT support `@db.text` annotations and any attempts to use a schema that defines `sqlite` as adapter and uses that annotation will fail.

So there is a viable default configuration with a local `db.sqlite` that still feels like the nicest quickstart option, but you will run into really weird behaviour if you just assume you can switch out the connector string to a MySQL DB and call it a day.

IMO, my preferred solution here would be to leave `sqlite` without `@db.text` as the default config and just put it like this.

```
datasource db {
    provider = "sqlite" 
    // NOTE: When using MySQL, PostgreSQL or MS Server SQL, uncomment the @db.text annotations in model Account below
    // Further reading: 
    // https://next-auth.js.org/adapters/prisma#create-the-prisma-schema
    // https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#string
    url      = env("DATABASE_URL")
}
```

```
// Necessary for Next auth
model Account {
    id                String  @id @default(cuid())
    userId            String
    type              String
    provider          String
    providerAccountId String
    refresh_token     String? //@db.Text
    access_token      String? //@db.Text
    expires_at        Int?
    token_type        String?
    scope             String?
    id_token          String? //@db.Text
    session_state     String?
    user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)

    @@unique([provider, providerAccountId])
}
```

Too verbose?
