### ISSUE TITLE
typescript-eslint

### ISSUE THREAD

**Issue by filipjnc** [t3-oss/create-t3-app#272]
**Is your feature request related to a problem? Please describe.**
ESLint's default JavaScript parser cannot natively read in TypeScript-specific syntax and its rules don't natively have access to TypeScript's type information.

**Describe the solution you'd like**
Since type-safety is not optional and TypeScript is core to this stack, I think it would be fair to include:
- [ ] typescript-eslint as a dev dependency
- [ ] a minimal eslint configuration to wire typescript-eslint 

**Describe alternatives you've considered**
https://www.sandromaglione.com/techblog/create-nextjs-project-with-typescript-eslint-prettier-tailwindcss

**Comment by juliusmarminge** [comment]
Is this for CLI or App?

**Comment by filipjnc** [comment]
@juliusmarminge this would be for the scaffolded app. I wouldn't make it an option in the CLI.

**Comment by juliusmarminge** [comment]
Messed up my branching but implemented in #b20e983
