### ISSUE TITLE
feat: forward pass trpc headers during ssr

### ISSUE THREAD

**Issue by JonParton** [t3-oss/create-t3-app#280]
**Is your feature request related to a problem? Please describe.**

As [called out by Theo](https://clips.twitch.tv/SleepyVibrantGrasshopperDxCat-ZJjzoC-yQHmSmyDE) and [mentioned in this tRPC issue](https://github.com/trpc/trpc/issues/1811) currently `tRPC` has a bit of an unintuitive behaviour where during SSR Client headers are not merged and so it is impossible to access cookies, for say getting the users session from `next-auth` during SSR. 

When looking for the solution to this problem I turned to `t3-app` to try and see if SSR was working here and out of the box it wasn't!

**Describe the solution you'd like**

It looks like this header merging is just going to be documented rather then done by default in the tRPC implementation and so the `tRPC` Template for `t3-app` should include this bit of code?  

[template/addons/trpc/utils.ts](https://github.com/t3-oss/create-t3-app/blob/d021b2325301f0b56615ca10715d801ac9ff446d/template/addons/trpc/utils.ts#L18)
```ts
.......
export const trpc = setupTRPC<AppRouter>({
  config() {
    return {
      url: `${getBaseUrl()}/api/trpc`,
      transformer: superjson,

      // Additional code to merge headers below:
      headers: () => {
        if (ctx?.req) {
          // on ssr, forward client's headers to the server
          return {
            ...ctx.req.headers,
            "x-ssr": "1",
          };
        }
        return {};
      },

    };
  },
  ssr: false, // In t3-app SSR is false by default, but above is needed if turned on! 
});
.......
```

NOTE: This is the fix for tRPC V10 ... Not looked into where this goes in V9 yet! 

**Describe alternatives you've considered**

for tRPC to add this into the implementation but this does not look like it is going that way!

**Comment by TheoBr** [comment]
Yeah I'd be cool with this being included, it's super unintuitive to NOT have this during SSR. If we add it we should comment the hell out of it tho

**Comment by MahendraBishnoi29** [comment]
hey can you assign this to me :)

**Comment by nexxeln** [comment]
> hey can you assign this to me :)

Sure!

**Comment by rhenriquez28** [comment]
Wanted to chime in here since I think I have valuable experience with this. I had an issue recently with these headers while using SSR. I asked for help on the tRPC discord and Alex figured out that to use SSR effectively you need to remove the "connection" header, otherwise the request would fail with `TRPCClientError: fetch failed`.

You can check out Alex's solution here: https://github.com/KATT/unidici-fetch-reserved-header-crap/pull/1/files#diff-a9827ce1be32c607c948881a89b99c592f752898f9c49e0dea0b7199eb151029R49. Also, as far as I know this only happens in Node 18, haven't had the chance to test in other Node versions.

**Comment by TheoBr** [comment]
We've gotten no updates from @MahendraBishnoi29 so I'm going to remove him from assigned as I do want this to happen

**Comment by rhenriquez28** [comment]
Can you assign this to me then?

**Comment by nexxeln** [comment]
> Can you assign this to me then? Would love to work on it

Feel free!

**Comment by rhenriquez28** [comment]
Should I just add the section to forward the headers or should I also add the part where the "connection" header is removed as I mentioned in my previous [comment](https://github.com/t3-oss/create-t3-app/issues/280#issuecomment-1236129455)?
