### ISSUE TITLE
Moving to tRPC v10

### ISSUE THREAD

**Issue by ayoubphy** [t3-oss/create-t3-app#283]
Hello,

Is there a roadmap or a plan to move to v10 anytime soon ?

**Comment by c-ehrlich** [comment]
`npx create-t3-app@next` is already on v10 alpha

as long as tRPC v10 remains in alpha i don't think it makes sense to upgrade on the release branch

**Comment by ayoubphy** [comment]
I asked Alex about the state of v10, he said it's production ready, and if there will be any changes, they will be minor.

**Comment by juliusmarminge** [comment]
> I asked Alex about the state of v10, he said it's production ready, and if there will be any changes, they will be minor.

Yes, it 100% works and you can use it by using the `next-release`: `npx create-t3-app@next`. I exclusively use this myself.

However, there are still API changes up for debate so I think we're better off keeping it on next for now, and moving it to main once the API is 100% final.
