### ISSUE TITLE
Example for subscriptions?

### ISSUE THREAD

**Issue by lantos-lgtm** [t3-oss/create-t3-app#286]
**Is your feature request related to a problem? Please describe.**
Need to implement subscriptions to get data from the server to client in a non polling manner. 

**Describe the solution you'd like**
Would like a simple example of how to implement subscriptions with this t3-create-app

**Describe alternatives you've considered**
creating a WS server and then subscribing to the socket in the client but doing so would escape the use of TRPC

**Comment by juliusmarminge** [comment]
_Maybe_ when tRPC v10 is released where subscriptions supposedly should be a lot better. As of now, they're in a weird state even according to the creator.

**Comment by juliusmarminge** [comment]
Closing for now, perhaps we'll revisit this later

**Comment by sumanthneerumalla** [comment]
Trpc is now above version 10 now, with even version 11 out. Is it possible that this discussion could be reopened?

I have referenced some other sample projects that use TRPC with next.js but an official t3 example implementation would be ideal, especially using protectedProcedures and some sort of auth. Either clerk or nextauth.
