### ISSUE TITLE
Error: Cannot find module '../../../node_modules/use-sync-external-store/shim/index.js'

### ISSUE THREAD

**Issue by d2vin** [t3-oss/create-t3-app#290]
**Describe the bug**
Got the following error on a fresh install with all packages selected after running npm dev

**To Reproduce**
npx create-t3-app
y
typescript
*select all packages*
cd folder
npx prisma db push
npm run dev

1. Run this '...'
2. See error

**Expected behavior**
expect localhost:3000 to load uninterrupted 

**Screenshots**

**Comment by juliusmarminge** [comment]
Can you verify the version of react-query? This issue appears when using react-query v4 but should be fixed since a while back. Please run `npx create-t3-app@latest` to make sure you are using the latest version possible.

**Comment by TheoBr** [comment]
I just hit this as well - when I switched to `@latest` it worked as expected
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/6751787/183569603-da52d28c-ad62-44d0-94d8-22eedfb02a83.png">

**Comment by juliusmarminge** [comment]
@d2vin can you confirm it is working on latest for you as well?

**Comment by d2vin** [comment]
Hey Theo's on this thread, cool. Was actually using this for the _roundest-mon_ tutorial. Anyways, ended up going with the yarn install which worked, and if I use npm again I'll be sure to use @latest. Out of curiosity, does yarn install the latest version by default?
