### ISSUE TITLE
Warning about node is wrong

### ISSUE THREAD

**Issue by JoaoAlexNunes** [t3-oss/create-t3-app#292]
**Describe the bug**
When you have the most recent node version it appears a error saying node.js version is not compatible with next try to install the lts or if you have run this "nvm install --lts"

Shouldn't it be npm ?

**Screenshots**
![imagem](https://user-images.githubusercontent.com/57943137/183497793-48a77907-6b7b-44ba-b967-f165ef7be1c3.png)

**Comment by astridlol** [comment]
No, `nvm` is the Node Version Manager. So this looks about right.

**Comment by JoaoAlexNunes** [comment]
> No, `nvm` is the Node Version Manager. So this looks about right.

Yes yes never mind i read it wrong
