### ISSUE TITLE
Reasonable Defaults for Graceful Shutdown

### ISSUE THREAD

**Issue by IsaacLeeWebDev** [t3-oss/create-t3-app#294]
**Is your feature request related to a problem? Please describe.**
I hate reimplementing process signal and exit listeners in node-based server apps when there's so little variance between them when they're written correctly for your tech stack. 

Your software pretty much always works better when they're set up, and when they're not, it can lead to some really tedious debugging that involves ramping up on a bunch of relatively obscure OS-level functionality. Often times, these kinds of issues go unnoticed in young projects until after they're a big problem in production. I think it makes sense to just build some reasonable defaults for graceful shutdown into project templates like `create-t3-app` to cut down drastically on this flavor of obscure operational issue. 

**Describe the solution you'd like**
Adding reasonable default event handlers to the `@trpc/server` template.

Below is a pseudocode example:

```ts
// ~/<some-folder-near-server-root>/process-event-handlers.ts
process.on('SIGINT', () => {
  // stop handling new requests
  // `server.close()`
  // `prisma.Disconnect()`
  // flush logs
  // tell all the things to clean up
  // etc.
});
```

**Describe alternatives you've considered**
- Pick a package that just does something similar to one of these:
  - https://github.com/emostar/express-graceful-exit
  - https://www.npmjs.com/package/node-graceful
  - https://www.npmjs.com/package/exit-hook

**Comment by TheoBr** [comment]
Does...any other project do this by default?

**Comment by TheoBr** [comment]
Oh cool, Next already does this. Please stop opening issues on random repos for things they already do :) https://github.com/vercel/next.js/pull/36909

**Comment by asrvd** [comment]
it isnt that hard implementing it yourself, moreover ct3a exists to make the dx of "most" of the devs easier, I havent seen a lot of devs using graceful shutdown tbh

**Comment by IsaacLeeWebDev** [comment]
> Oh cool, Next already does this. Please stop opening issues on random repos for things they already do :) [vercel/next.js#36909](https://github.com/vercel/next.js/pull/36909)

Well this is embarrassing. I was under the impression that there was a lot less support for graceful shutdown from T3 stack tools than there was. Goes without saying that I shoulda thought of that _before_ making an issue. I apologize.

I did find one gotcha that might be worth covering in init.tips: Nextjs and tRPC will step on each other's toes if you're using subscriptions.

- [tRPC subscriptions need to be gracefully reconnected like this](https://trpc.io/docs/subscriptions#creating-a-websocket-server)
- [NextJS will only let you do that if you set a specific environment variable to `true`](https://nextjs.org/docs/deployment#manual-graceful-shutdowns). Otherwise, everyone's connections get dropped every time you deploy.

That all said, I think it's right to keep this issue closed since all that would be an entirely separate feature request.

Thanks for the quick replies, and for all the hard work going into this!
