### ISSUE TITLE
Include tRPC client 'loggerLink' for dev debugging

### ISSUE THREAD

**Issue by TheoBr** [t3-oss/create-t3-app#296]
tRPC has an awesome logger client built in for React Query that is a lifesaver

<img width="377" alt="image" src="https://user-images.githubusercontent.com/6751787/183571692-d7d9436b-f727-41ad-bc2d-27ee3f53f9ff.png">

Adding the following to the `_app.tsx` trpc config will add them in dev

```ts
{
...
      links: [
        loggerLink({
          enabled: (opts) =>
            process.env.NODE_ENV === "development" ||
            (opts.direction === "down" && opts.result instanceof Error),
        }),
      ],
 }
 ```

**Comment by TheoBr** [comment]
Wait this appears to be broken now rip :(

**Comment by nexxeln** [comment]
> 

lol, do we still want this then?

**Comment by c-ehrlich** [comment]
if its possible to get it working in both tRPC v9 and v10 (or only v10 i guess), i think it would be a good thing to add. those console outputs are nice to have by default.

**Comment by TheoBr** [comment]
If we can get it working I definitely want it in dev mode

**Comment by hnqg** [comment]
Well, it worked here. But I had to use the `httpBatchLink` as well. With only the `loggerLink` I was getting a `TypeError: link is not a function`. Tested in other projects with trpc in version `9.26.2` and got the same error.

That log really helps in development, and I also find the `httpBatchLink` a good thing to add to trpc config. What do you think @TheoBr , do you still think it's useful to add the `loggerLink` and the `httpBatchLink`?

```
const links = [
      loggerLink({
        enabled: (opts) =>
          process.env.NODE_ENV === 'development' ||
          (opts.direction === 'down' && opts.result instanceof Error),
      }),
      httpBatchLink({
        maxBatchSize: 10,
        url,
      }),
    ];

return {
      url,
      transformer: superjson,
      links,
      /**
       * @link https://react-query.tanstack.com/reference/QueryClient
       */
      // queryClientConfig: { defaultOptions: { queries: { staleTime: 60 } } },
    };
```

![image](https://user-images.githubusercontent.com/25696006/183981719-67634c5c-23ac-4d29-8343-34fb764f1d1d.png)

**Comment by Gejsi** [comment]
Tbh, I don't like the idea of having `httpBatchLink` enabled by default, it feels a little too opinionated.
I will open a PR soon for this issue.

**Comment by TheoBr** [comment]
@hnqg sorry just saw this now - yeah would be nice to add this I think

**Comment by juliusmarminge** [comment]
tRPC already batches requests by default so adding an explicit httpBatchLink seems scary (in the way we prescribe a default for how big your batches should be) unless it's really needed?

**Comment by kaminskypavel** [comment]
TIL that links order matters. here's the correct order 

```js
        links: [
            loggerLink({
                enabled: (opts) =>
                    isDevelopment() ||
                    (opts.direction === "down" && opts.result instanceof Error),
            }),

            httpBatchLink({
                url,
                headers: {
                    Authorization: `Bearer ${token}`
                }
            }),
        ],

```
