### ISSUE TITLE
Include ct3a version as metadata in generated app

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#298]
**Is your feature request related to a problem? Please describe.**
Manny bug-reports are cause people don't use the latest version, I.e only running `npx create-t3-app`. Having a way to tell which version was used may help debugging the issue

**Describe the solution you'd like**
Perhaps include a field in the package.json with what version was used to scaffold? It would "litter" the project and leave a trace which it currently doesn't have.

**Additional**
Alternative would be just leaving things as is, and maybe adding in a prerequisite of filing an issue is checking if the issue persists using latest version.

**Comment by c-ehrlich** [comment]
I think this is a good idea.

Did some initial research and it's ok to put arbitrary stuff in the package.json. The recommended method is to add a single entry, which can then contain as much stuff as you want. Therefore I'd suggest doing that already now even though we just want to have a single key for the time being. Something like:

```js
{
    // (...)
    "ct3a_metadata": {
        "init_version": "5.4.0"
    },
    // (...)
}
```

I could try to implement it this week.

**Comment by juliusmarminge** [comment]
The implementation would be really simple, we are already writing to the package.json here:

https://github.com/t3-oss/create-t3-app/blob/f060d59a4e53a6932c5dd9620a20efa7d1c96241/src/index.ts#L39-L45
