### ISSUE TITLE
Create-t3-app expo feature request

### ISSUE THREAD

**Issue by bu3alwa** [t3-oss/create-t3-app#299]
It would be great to have create-t3-app also create an expo app that links with trpc.

I was thinking something along the lines of if you need a server, mobile frontend, and web, t3-app can create a monorepo that has all three options and you can pick or choose which ones you want. So you could go mobile frontend with server, web frontend with server, the classic combined front and server, or all three. 

It would be great to also have the trpc client as a shared module that can be imported from a common modules folder so both web and mobile frontend can consume.

```
- root
 -- server
 -- mobile
 -- web
 -- common
```
or
```
- root
 -- server/web
 -- mobile
 -- common
```

The app can default to current way if only the option of just next.js.

Would like to know thoughts of the community and if this is useful for others.

**Comment by jacobgad** [comment]
possibly with the option of using turborepo

**Comment by nexxeln** [comment]
I think this is outside the scope of what create-t3-app is aiming to do.

Check out [zART](https://github.com/trpc/zart) and [create-kaol-app](https://github.com/chamatt/create-kaol-app).
