### ISSUE TITLE
Docker instuctions aren't working properly

### ISSUE THREAD

**Issue by kyuuaria** [t3-oss/create-t3-app#301]
The docker instructions added in #265 aren't working when not building locally or in other words when building without the .env file because of the way environment variables are handled and they are then missing in the building process which results in a build failure.

First of the .env file should be added to the .dockerignore since you most likely don't want it in your docker image. Regarding the environment variables situation some solution is required that is fixing this issue.

```
 > [builder 5/5] RUN yarn build:
#15 0.399 yarn run v1.22.19
#15 0.420 $ next build
#15 0.767 ❌ Invalid environment variables:
#15 0.767  DATABASE_URL: Required
#15 0.767 
#15 0.768 error - Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
#15 0.770 
#15 0.770 > Build error occurred
#15 0.771 Error: Invalid environment variables
#15 0.771     at file:///app/src/env/server.mjs:16:9
#15 0.771     at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
#15 0.771     at async Promise.all (index 0)
#15 0.771     at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
#15 0.771     at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
#15 0.771     at async Object.loadConfig [as default] (/app/node_modules/.pnpm/next@12.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/config.js:68:36)
#15 0.771     at async Span.traceAsyncFn (/app/node_modules/.pnpm/next@12.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
#15 0.771     at async /app/node_modules/.pnpm/next@12.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:68:28
#15 0.771     at async Span.traceAsyncFn (/app/node_modules/.pnpm/next@12.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
#15 0.771     at async Object.build [as default] (/app/node_modules/.pnpm/next@12.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:64:29)
#15 0.785 error Command failed with exit code 1.
#15 0.785 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nexxeln** [comment]
I don't know much about docker but the build failing without the environment variables is intended behavior. Why would you want to build with errors in your app?

**Comment by kyuuaria** [comment]
When building a docker image you build it without your envorionment variables and then when later running it you pass them in but that isn't possible here because they get checked at the building phase

**Comment by juliusmarminge** [comment]
> When building a docker image you build it without your envorionment variables and then when later running it you pass them in but that isn't possible here because they get checked at the building phase

The default `env` included is totally valid though? You can run a `build` straight after scaffold without any modifications?

**Comment by kyuuaria** [comment]
I created a new t3 app and followed the docker instructions but additionally added the `.env` file to the `.dockerignore` to test the behavior of building straight off the GitHub repo where you also don't have a `.env` file since it is getting ignored in the `.gitignore`. Furthermore it should be noted that you wouldn't want to have the `.env` file in your docker image anyway. If you aren't going to release your docker image to the public it is not that big of a deal but if you do you are practically giving out your local environment variables to everyone and that would be like leaving the key in a lock.

**Comment by juliusmarminge** [comment]
I have only ever run one Next app using Docker, and we did it with `compose` and included our env in the compose file. Is this what you are looking to do?

I guess a step we could add to the docker documentation is that you should remove line 1 in `next.config.mjs`:

https://github.com/t3-oss/create-t3-app/blob/7822c433df18011f0cc6748e2c499c0e4283386c/template/base/next.config.mjs#L1

since that is the thing that makes the env validate on build

**Comment by kyuuaria** [comment]
Yes that would be a solution but I would also recommend adding the `.env` to the `.dockerignore` because as I already said previously you wouldn't want to have that file in your docker image since you pass in your environment variables when running the docker container

**Comment by Mattszczp** [comment]
How about adding default values from server.mjs file as ARGs just to make zod happy during build and remove .env from the image by adding it to .dockerignore.

Then instruct them to pass .env file in docker run using `--env-file` if they're running locally. For running on K8s, ECS etc. they have gazillion options to pass those variables properly.

**Comment by juliusmarminge** [comment]
I think @c-ehrlich is working on this?

**Comment by c-ehrlich** [comment]
I have a busy week coming up so I doubt I'll get to this all that soon. If anyone else wants to open a PR for it in the meantime, you're very welcome to do so :)

**Comment by juliusmarminge** [comment]
> I have a busy week coming up so I doubt I'll get to this all that soon. If anyone else wants to open a PR for it in the meantime, you're very welcome to do so :) Otherwise I'll implement it sooner or later.

Wouldnt stress about it. I would assume that the people who are deploying to docker are in the vast minority

**Comment by kyuuaria** [comment]
Yes there is no hurry I simply removed line 1 in `next.config.mjs` for now. Just wanted to point this out.

**Comment by nexxeln** [comment]
@c-ehrlich are you working on this?

**Comment by makyfj** [comment]
Would it be a good idea to do something like these on   

 `DOMO_CLIENT_ID: z.string().nullish(),` so it runs during build time.
