### ISSUE TITLE
on Windows, path returned by `process.cwd()` breaks the path parser

### ISSUE THREAD

**Issue by BWsix** [t3-oss/create-t3-app#302]
**Describe the bug**

https://github.com/t3-oss/create-t3-app/blob/f060d59a4e53a6932c5dd9620a20efa7d1c96241/src/utils/parseNameAndPath.ts#L16-L19

On windows, process.cwd() returns something like: `D:\\path\\to\\project`, which breaks the above code since it uses `\\` instead of `/` to separate efferent segments of path.
Consequently, project generated by `create t3 app` will use an invalid app name:
![image](https://user-images.githubusercontent.com/57709309/183903030-07a0efd0-7863-4d07-b627-1dd4fe71cf24.png)

**Steps To Reproduce**

1. (on any windows computer i guess) `npx create-t3-app .`
2. see `package.json`

**Possible Solution**

Use nodejs's builtin path module to parse the path returned by process.cwd():
```ts
  // If the user ran `npx create-t3-app .` or similar, the appName should be the current directory
  if (appName === ".") {
    const parsedCwd = pathModule.resolve(process.cwd());
    appName = pathModule.basename(parsedCwd);
  }
```

**Comment by BWsix** [comment]
I made a working patch (not tested on devices other than Windows 10 yet tho) on my fork: [link](https://github.com/BWsix/create-t3-app/blob/4e4372ba7cb3752edc4b48cd381bdc7b71a708f6/src/utils/parseNameAndPath.ts#L18-L22)
Would you accept a PR?

**Comment by nexxeln** [comment]
Yeah sure make a PR we'll take a look!
