### ISSUE TITLE
NX monorepo template

### ISSUE THREAD

**Issue by egill15** [t3-oss/create-t3-app#314]
Hello everyone

I love create-t3-app and I was wondering of anyone know of any good generator / template where it has been used in nx monorepo?

Maybe i'm just being lazy about it all and should just do it myself. But then maybe someone has already done it :)

Thanks!

**Comment by juliusmarminge** [comment]
Not NX but might be helpful still: https://github.com/juliusmarminge/turbo-expo-next-starter

**Comment by Yedidyar** [comment]
hi, someone is trying to make this happen?
