### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Amantel** [t3-oss/create-t3-app#318]
### Provide environment information

  System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 23.97 GB / 31.33 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm

### Describe the bug

Hallo! 

After basic installation (with tRPC) and adding basic console.log on index page you will see a peculiar event. 
If you open dev console (chrome, firefox) and click there and then click on the app again - it will re-renders, for some reason. 

Here is a video: https://webmshare.com/play/DeQPM

Probably this is one of the helpful settings, but I can't find a way to turn this of. 

### To reproduce

```
npx create-t3-app
cd my-app
npm run dev
open http://localhost:3000/
add 'console.log' on line 13 of index.ts
...
watch for rerenders 
click somewhere in the console (for example)
click back on the body
```

**Comment by juliusmarminge** [comment]
This is React Query that is refetching on window focus which is intended behavior. Read here on how to configure when queries are being refetched: https://tanstack.com/query/v4/docs/guides/window-focus-refetching
