### ISSUE TITLE
feat: Small Enhancement to default t3 index page 

### ISSUE THREAD

**Issue by LuisEGV** [t3-oss/create-t3-app#321]
### Is your feature request related to a problem? Please describe.

This is not a huge issue, but I feel like the default index page could use some small changes to its UI in order to make the experience of entering the index file via mobile much nicer and clear up unnecessary text. 

### Describe the solution you'd like to see

My solution is to slightly alter the TechnologyCard component to not include the "documentation" text as I feel that its unnecessarily repeated, alter the hover tailwind class in the component as well as change the text size for sm devices for the main header in the page.

I already implemented a solution that I feel looks much better and works in mobile too, but just wanted feedback from other contributed as I know this is just a visual enhancement that might not be needed.

### Desribe alternate solutions

I think the alternative is to leave it as it is.

### Additional information

How it looks now

![alt text](https://firebasestorage.googleapis.com/v0/b/universal-graph.appspot.com/o/web1.png?alt=media&token=151ed2b0-c609-4f97-af90-7bf498bbe586)
![alt text](https://firebasestorage.googleapis.com/v0/b/universal-graph.appspot.com/o/phonever2.png?alt=media&token=15cec937-958b-46b2-85ea-984f2c855b0d)

How it could look with my proposed changes (I was hovering the card on the second image):
![alt text](https://firebasestorage.googleapis.com/v0/b/universal-graph.appspot.com/o/phonever.png?alt=media&token=0323cb94-e885-45ec-a32d-826e2221dfb7)
![alt text](https://firebasestorage.googleapis.com/v0/b/universal-graph.appspot.com/o/web2.png?alt=media&token=b12586f7-e491-4efa-8aef-ab980a68e577)

**Comment by asrvd** [comment]
I don't know why you would be thinking like the documentation links are "unnecessarily repeated" , can you elaborate on it?

**Comment by c-ehrlich** [comment]
Agreed, having obvious links to documentation is much more important than getting the default page (which will only ever be seen by people who have just bootstrapped an app!) to fit on a phone screen without scrolling.

I could see centering the h1 and maybe making it smaller. But I think the cards are fine as is.

**Comment by LuisEGV** [comment]
Hi guys, I was referring to the "documentation" text repeated in each card being unnecessary, not that we should not include the links to the documentation itself. The TechnologyCard component itself feels like a component that you can interact with as a whole, yet you need to actually click the "documentation" text in order to actually open the links. I attached a picture of what I am referring too below.


![alt text](https://firebasestorage.googleapis.com/v0/b/universal-graph.appspot.com/o/documentation.png?alt=media&token=63d6af2e-6fde-40f9-95b4-06fdf87f6233) 



So as you can see the purple section that I put in the image is where a person can click to go to the documentation, but it feels strange as it is a boundary that goes beyond the text, but does not include the whole card. But again, this is not a huge issue.

**Comment by asrvd** [comment]
so basically you want the links to open when someone clicks on the card and not on the text? Even so, we should add a text like "Read Documentation" on the card which will let people know that clicking on the card opens the documentation of that tech

**Comment by LuisEGV** [comment]
@asrvd Exsactly! And yeah I think leaving the "Read Documenation" or "Documeation" still makes sense like you pointed out.

**Comment by asrvd** [comment]
> @asrvd Exsactly! And yeah I think leaving the "Read Documenation" or "Documeation" still makes sense like you pointed out.  

sounds good to me

**Comment by LuisEGV** [comment]
@nexxeln Hi, yeah I can do a PR :) I can close this and then Ill open a PR later today.
