### ISSUE TITLE
feat: add ReactQueryDevtools to the project by default

### ISSUE THREAD

**Issue by itelo** [t3-oss/create-t3-app#329]
### Is your feature request related to a problem? Please describe.

ReactQueryDevtools is so helpful that I believe this should be a standard in the t3 stack, it's much more common to need it than doesn't, so I suggest adding it to the project.

### Describe the solution you'd like to see

I believe we are safe to always add it if a user chooses to use tRPC in the CLI.

### Desribe alternate solutions

In my perspective, we don't need to add it as an option in "`Which packages would you like to enable?`" step

### Additional information

I'll be glad to add this feature to the project :)

**Comment by nexxeln** [comment]
I personally have never used the dev tools, curious to see how many people want this, because if someone never uses it and its installed by default, its just bloat.

**Comment by astridlol** [comment]
> I personally have never used the dev tools, curious to see how many people want this, because if someone never uses it and its installed by default, its just bloat.

I've also never used the dev tools

**Comment by SeanCassiere** [comment]
I do use the react-query dev-tools, though I personally do not think it should be included.

My reasoning for not including it is mostly along the lines that the setup for the dev-tools is a simple NPM install and the import and rendering of the component.

**Comment by itelo** [comment]
I was thinking about this, and I believe putting it as a comment is enough. So it'll not be added, but the user has a hint where to put the devtool.

I'm suggesting this because it's the first time I'm using the t3 stack, and it took some time for me to figure out where the dev tool should go because I was unaware of `withTRPC` was actually an HoC with QueryProvider inside it.

```ts
<SessionProvider session={session}>
  {/*
    * Uncomment this to show the devtools
    * <ReactQueryDevtools initialIsOpen={false} /> 
    */}
    <Component {...pageProps} />
</SessionProvider>
```

**Comment by c-ehrlich** [comment]
i tend to use them sooner or later in most of my projects, but as for adding them to t3ca (commented out), i don't feel strongly for or against.

**Comment by TheoBr** [comment]
I think we should either do this or the trpc logger https://github.com/t3-oss/create-t3-app/issues/296#issuecomment-1211052574

**Comment by juliusmarminge** [comment]
I think this almost lands in the `npm install` section. A single line of boilerplate isn't enough imo, rather have we setup the tRPC logger instead?
