### ISSUE TITLE
feat: Add links to best practices for each tech

### ISSUE THREAD

**Issue by NotoriousGOR** [t3-oss/create-t3-app#331]
### Is your feature request related to a problem? Please describe.

As a beginner in basically every technology this CLI tool provides, it would be super helpful to have a guidebook to reference for best practices for each tool. Adding links to a certain Youtuber / Streamer's (@TheoBr) videos could be helpful for those who are lost like me and care about they why each tool is helpful and when is it best used and how.

### Describe the solution you'd like to see

Ideally, either in the documentation or in the initial Hello World screen, links to either a video or piece of documentation like NextAuth's "Tutorials and Explainers" that contains a general overview of best practices for TypeScript, NextAuth, etc. This is beneficial to not only new devs but also to those who are wanting to refine their skills and may have made bad decisions in the past.

### Desribe alternate solutions

Alternatively, you can just link to @TheoBr 's channel

**Comment by nexxeln** [comment]
We have some tutorials linked in the [readme](https://github.com/t3-oss/create-t3-app/blob/main/cli/template/base/README.md)!
