### ISSUE TITLE
minor bug: `next-auth.d.ts` gets added to `tsconfig.json` even if I don't select it when setting up the proejct.

### ISSUE THREAD

**Issue by timfee** [t3-oss/create-t3-app#343]
### Provide environment information

```
  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 290.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
```

### Describe the bug

It seems that `next-auth.d.ts` gets added to `tsconfig.json`'s `include`s no matter what. I wouldn't expect that entry to exist in `tsconfig.json` if I don't select it when setting up the project. 

### To reproduce

1. Set up project as follows:
   <img width="599" alt="Screenshot_2022-08-21_17-08-40_KLAbg6wX" src="https://user-images.githubusercontent.com/3246342/185817708-6257ad9c-15e2-4f5a-9f40-df50398d3782.png">
2. Open `tsconfig.json` and observe the extra entry:
```ts
"include": [
    "next-auth.d.ts",  // <- don't expect this
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
  ],
```

### Additional information

I know it's super nitpicky and probably doesn't cause any huge issues, but noticed it when I was debugging a related issue :)

**Comment by juliusmarminge** [comment]
I don't think this entry is needed at all anymore since we moved the file into `src/types`, should be picked up by the `**/*.ts` glob pattern?
