### ISSUE TITLE
bug: **Next.js error page (404, 400, 500) reload infinitely in development env**

### ISSUE THREAD

**Issue by Senbonzakura1234** [t3-oss/create-t3-app#358]
### Provide environment information
 - System:
    OS: Windows 10 10.0.22622
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 5.87 GB / 15.87 GB
 - Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.2 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD

 - T3 info: `"ct3aMetadata": { "initVersion": "5.6.0" },`

### Describe the bug

I'm not sure if this is a bug, i'm also not sure if this is T3 template issue or Next.js issue, but the app keep reloading when I'm on 404 or any other error page and it's really annoying any laggy, I want to investigate a way to stop this.

### To reproduce

- Create a T3 app
- Navigate to a page that doesn't exist to get a 404 error

**Comment by nexxeln** [comment]
Just scaffolded a new T3 app, and navigated to a 404 page, can't reproduce what you're saying.

![screenshot of 404 page](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/brave_1vU8qFzvkP.png)

Would love if you could make a video of gif of the issue

**Comment by Senbonzakura1234** [comment]
> Just scaffolded a new T3 app, and navigated to a 404 page, can't reproduce what you're saying.
> 
> ![screenshot of 404 page](https://camo.githubusercontent.com/ca391a02422e232260594e2d23e799b460bbae847794fc01c7261991002d5f2a/68747470733a2f2f75732d656173742d312e74697874652e6e65742f75706c6f6164732f6e657878656c2e6e656564732e726573742f62726176655f3176553871467a766b502e706e67)
> 
> Would love if you could make a video of gif of the issue

check F12, you will see the page reloaded, it doesn't shown here because the page content is simple to load

**Comment by nexxeln** [comment]
I still can't understand what you're saying, if you could make a video or gif that would be helpful

**Comment by Senbonzakura1234** [comment]
> I still can't understand what you're saying, if you could make a video or gif that would be helpful
[Record.zip](https://github.com/t3-oss/create-t3-app/files/9437401/Record.zip)
Pls check this

**Comment by Senbonzakura1234** [comment]
> > I still can't understand what you're saying, if you could make a video or gif that would be helpful
> 
> [Record.zip](https://github.com/t3-oss/create-t3-app/files/9437401/Record.zip) Pls check this

As you can see the script `on-demand-entries-client.js` keep running trying to reload the page, this, doesn't happened in production build though

**Comment by nexxeln** [comment]
> > I still can't understand what you're saying, if you could make a video or gif that would be helpful
> 
> [Record.zip](https://github.com/t3-oss/create-t3-app/files/9437401/Record.zip) Pls check this

I won't open a zip file from sorry, its very sus. Please make a GIF or a video and embed it in your markdown

**Comment by Senbonzakura1234** [comment]
> > > I still can't understand what you're saying, if you could make a video or gif that would be helpful
> > 
> > 
> > [Record.zip](https://github.com/t3-oss/create-t3-app/files/9437401/Record.zip) Pls check this
> 
> I won't open a zip file from a stranger sorry, its very sus. Please make a GIF or a video and embed it in your markdown

https://user-images.githubusercontent.com/43206347/187018508-844b77c6-a3c2-4ef0-aac0-f510208e2db7.mp4

Sorry i was just lazy to make a video and edit it

**Comment by nexxeln** [comment]
Okay I just reproduced this. Tried this in a `create-next-app` too, its happening there as well. So this is probably a nextjs issue, you should open an issue there
