### ISSUE TITLE
bug: New environment variables are not picked up by Typescript

### ISSUE THREAD

**Issue by hanzomaster** [t3-oss/create-t3-app#364]
### Provide environment information

```
  System:
    OS: Windows 10 10.0.22622
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 2.62 GB / 7.78 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
```

### Describe the bug

Typescript not recognize new env variables. Show error `Property does not exist`
![image](https://user-images.githubusercontent.com/49803999/187057058-1d0343ce-d4b9-40b8-ac3c-1b2001e054d6.png)

### To reproduce

1. Run `npx create-t3-app@latest` with all options checked:
![image](https://user-images.githubusercontent.com/49803999/187056836-90156e30-34f3-4e70-8975-d80e42f1043c.png)
2. Edit `.env` file with new variables:
![image](https://user-images.githubusercontent.com/49803999/187056895-ae8526c7-a138-4393-99c0-dcb357fd99d0.png)
3. Run `npm run build`

**Comment by nexxeln** [comment]
Looks like you didn't add them in the env variables schema

**Comment by hanzomaster** [comment]
Yep how silly of me
