### ISSUE TITLE
bug: look into resolving react versions

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#371]
### Provide environment information

```
npx envinfo --system --binaries

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 156.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

### Describe the bug

When running `pnpm install`, we fail on invalid peer dependencies and when running `npm ls react` we get this:

<img width="1777" alt="CleanShot 2022-08-29 at 17 00 17@2x" src="https://user-images.githubusercontent.com/51714798/187232151-64113372-6fb8-4bda-8d72-b96e2fe75f48.png">

Then, when running a build, we see a bunch of errors about breaking the rules of react, which must be cause of this? I can't find other issues that would cause this?

<img width="1084" alt="CleanShot 2022-08-29 at 17 04 40@2x" src="https://user-images.githubusercontent.com/51714798/187232696-4931bb6a-c787-4ec9-ba60-5cb76b63e44b.png">

### To reproduce

Clone and install deps, then run a build

**Comment by nexxeln** [comment]
Yeah just reproduced this. Not sure whats causing it tho? Maybe the astro integration is messing something up.

**Comment by juliusmarminge** [comment]
the react-typist too I think.. not sure if there is another lib that supports react 18
