### ISSUE TITLE
feat: index.tsx styling on template without tailwind

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#380]
### Is your feature request related to a problem? Please describe.

Index.tsx looks ugly when Tailwind isn't selected and it's not immediately clear that the list elements link to the docs.

### Describe the solution you'd like to see

Give the tailwind-less index.tsx some styling, to look the same or similar as the one with Tailwind. My suggestion would be to use an `index.module.css` file.

### Desribe alternate solutions

- Some other styling method
  - Putting it in `globals.css`
  - Creating some non-module css file
  - Inline styles
  - etc.
- Leaving it as is

**Comment by juliusmarminge** [comment]
Yes feel free to add it if you'd like.
