### ISSUE TITLE
bug(docs): docker guide doesn't work with prisma 

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#389]
### Provide environment information

-

### Describe the bug

Ref: https://discord.com/channels/966627436387266600/1015020993221238856

The current docker guide in the docs doesn't work when running the application using a docker container. The prisma client lives in node_modules which is not copied over by the default Dockerfile.

We should, if not coming up with a modified Dockerfile, at least mention this and find an appropriate resource to point them towards.

### To reproduce

Setup a full T3 App using the CLI.

Follow the Docker (Compose) guide from the docs.

You will get an error saying the Prisma Client isn't initialized when you launch the app.

I setup all the environment variables correctly and it worked for Dev, my client was properly setup in my local node_modules, but when I built the app image and launched it the prisma client got lost

**Comment by c-ehrlich** [comment]
will check out on the weekend :)

**Comment by SeanCassiere** [comment]
Just checked out the Discord, and I could be wrong about this, but I think you need to use a network between the containers.

This is the compose file, I used for one of my previous projects and I remember using networks for the containers to be able to talk to one-another.
 - Network assigned to the container - [link](https://github.com/SeanCassiere/message-box/blob/master/docker-compose.yml#L13-L14)
 - Creating the network for the stack - [link](https://github.com/SeanCassiere/message-box/blob/master/docker-compose.yml#L96-L97)

Docker-compose [documentation](https://docs.docker.com/compose/networking/) regarding networking.

**Comment by juliusmarminge** [comment]
> Just checked out the Discord, and I could be wrong about this, but I think you need to use a network between the containers.
> 
> 
> 
> This is the compose file, I used for one of my previous projects and I remember using networks for the containers to be able to talk to one-another.
> 
>  - Network assigned to the container - [link](https://github.com/SeanCassiere/message-box/blob/master/docker-compose.yml#L13-L14)
> 
>  - Creating the network for the stack - [link](https://github.com/SeanCassiere/message-box/blob/master/docker-compose.yml#L96-L97)
> 
> 
> 
> Docker-compose [documentation](https://docs.docker.com/compose/networking/) regarding networking.
> 
> 
> 
> 

That would just fix it locally since it would "borrow" the prisma client from your local machine. The prisma client must ship with the container somehow for it to work when you deploy it to Railway etc...
