### ISSUE TITLE
feat: Add option to use React Native/Expo

### ISSUE THREAD

**Issue by minsk-dev** [t3-oss/create-t3-app#405]
### Is your feature request related to a problem? Please describe.

[t3-oss/create-t3-turbo](https://github.com/t3-oss/create-t3-turbo) already has React Native/Expo. It would make sense to create the option for people to use RN with `create-t3-app` directly.

### Describe the solution you'd like to see

A new option added to the CLI that adds React Native.

### Desribe alternate solutions

-

### Additional information

Already discussed this with @juliusmarminge. I will create a PR to start doing this issue. We can discuss more about this either on my PR or here. Preferably here.

**Comment by juliusmarminge** [comment]
Just keep in mind that it should keep the same modularity we have today (which could be a challenge)

**Comment by minsk-dev** [comment]
I think this option will need to hijack default behavior in some way. The folder structure is pretty different... And the final result will be too

**Comment by minsk-dev** [comment]
What do you think of having this structure, @juliusmarminge? If the flag is `true`. Basically `create-t3-turbo` but with code inside `src`.

```
.
├── LICENSE
├── README.md
├── package-lock.json
├── package.json
├── src
│   ├── apps
│   │   ├── expo
│   │   │   ├── app.json
│   │   │   ├── assets
│   │   │   │   ├── adaptive-icon.png
│   │   │   │   ├── favicon.png
│   │   │   │   ├── icon.png
│   │   │   │   └── splash.png
│   │   │   ├── babel.config.js
│   │   │   ├── metro.config.js
│   │   │   ├── package.json
│   │   │   ├── src
│   │   │   │   ├── _app.tsx
│   │   │   │   ├── screens
│   │   │   │   │   └── home.tsx
│   │   │   │   ├── types
│   │   │   │   │   └── nativewind.d.ts
│   │   │   │   └── utils
│   │   │   │       └── trpc.ts
│   │   │   ├── tailwind.config.cjs
│   │   │   └── tsconfig.json
│   │   └── nextjs
│   │       ├── README.md
│   │       ├── next-env.d.ts
│   │       ├── next.config.mjs
│   │       ├── package.json
│   │       ├── postcss.config.cjs
│   │       ├── public
│   │       │   └── favicon.ico
│   │       ├── src
│   │       │   ├── env
│   │       │   │   ├── client.mjs
│   │       │   │   ├── schema.mjs
│   │       │   │   └── server.mjs
│   │       │   ├── pages
│   │       │   │   ├── _app.tsx
│   │       │   │   ├── api
│   │       │   │   │   ├── examples.ts
│   │       │   │   │   └── trpc
│   │       │   │   │       └── [trpc].ts
│   │       │   │   └── index.tsx
│   │       │   ├── styles
│   │       │   │   └── globals.css
│   │       │   └── utils
│   │       │       └── trpc.ts
│   │       ├── tailwind.config.cjs
│   │       └── tsconfig.json
│   └── packages
│       ├── api
│       │   ├── index.ts
│       │   ├── package.json
│       │   ├── src
│       │   │   ├── context.ts
│       │   │   ├── router
│       │   │   │   ├── index.ts
│       │   │   │   └── post.ts
│       │   │   └── trpc.ts
│       │   ├── transformer.ts
│       │   └── tsconfig.json
│       └── db
│           ├── index.ts
│           ├── package.json
│           ├── prisma
│           │   ├── db.sqlite
│           │   └── schema.prisma
│           └── tsconfig.json
├── tsconfig.json
└── turbo.json

23 directories, 50 files```

**Comment by minsk-dev** [comment]
Talked with @nexxeln and we both think that it makes sense to create another CLI for this because the scope is very different, and I would need to restructure everything so turbo/nexpo/react native could work. Will eventually update this thread with the new repo link

**Comment by ecrax** [comment]
Would love to see something like this, do you have any plans to integrate next-auth? I've seen some efforts to make next-auth work with expo ([https://github.com/nextauthjs/next-auth/issues/569](https://github.com/nextauthjs/next-auth/issues/569), [simple-expo-next-auth](https://github.com/Xodarap/simple-expo-next-auth) and [expo.canny.io/feature-requests/p/integration-with-nextauth](https://expo.canny.io/feature-requests/p/integration-with-nextauth)), but I think something more mature combined with the t3 stack would be awesome.
