### ISSUE TITLE
bug: Template's button shadow style is not working

### ISSUE THREAD

**Issue by sor4chi** [t3-oss/create-t3-app#418]
### Provide environment information

```
  System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 206.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - /opt/homebrew/bin/npm
    Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
```

### Describe the bug

https://github.com/t3-oss/create-t3-app/blob/b2357c93e0a91d867c45c3f6ba95d7f4b2477c32/cli/template/page-studs/index/with-auth-trpc-tw.tsx#L81
I found an invalid SingleQuote after `shadow-lg`. 
Shadow Style is not applied to Button due to this syntax error.

### To reproduce

Run create-t3-app with selecting nextAuth, trpc, and tailwind-css as third-party libs.

**Comment by nexxeln** [comment]
Thanks for reporting this. Just saw you forked the repo, are you making a PR?

**Comment by sor4chi** [comment]
@nexxeln 
I have just created a Pull Request. Please check.
