### ISSUE TITLE
feat: --with-test flag to include tests on generated project

### ISSUE THREAD

**Issue by ShaneMaglangit** [t3-oss/create-t3-app#429]
### Is your feature request related to a problem? Please describe.

I've recently just worked on setting up a testing library for a project I built with create-t3-app. Being relatively new with the stack, it has been quite a challenge to get everything up and working.

I am aware about Theo's opinion regarding tests, which I assume is a shared opinion in this community. However, I would like to argue that there exists a space where tests are wanted or perhaps even required. 

Thus, it would be a great  to have a feature that helps devs have a convenient and easy way of including tests on their project.

### Describe the solution you'd like to see

Include a `--with-test` flag that will include a test library setup on the generated project.

### Desribe alternate solutions

Have a testing library setup by default.

**Comment by nexxeln** [comment]
We don't discourage you from testing. If you wanna do it, just add a library and do it. You should react [Axiom 2](https://github.com/t3-oss/create-t3-app#1-solve-problems)

Some resources for testing a t3 app if anyone bumps into this in the future: 
 - [trpc/examples-kitchen-sink](https://github.com/trpc/examples-kitchen-sink)
 - [trpc/examples/next-prisma-starter](https://github.com/trpc/trpc/tree/next/examples/next-prisma-starter)
