### ISSUE TITLE
feat: Introduction revamp

### ISSUE THREAD

**Issue by barrybtw** [t3-oss/create-t3-app#432]
### Is your feature request related to a problem? Please describe.

https://create-t3-app-nu.vercel.app/en/introduction

The chosen text-color for the links don't mix very well with the chosen background, there needs to be way more contrast than as of now.

![image](https://user-images.githubusercontent.com/88448390/189901581-5c56f39a-b10c-4fd7-a33a-8ab54d9c4850.png)
![image](https://user-images.githubusercontent.com/88448390/189901634-ecf30b52-fbed-47c8-bb77-dd455d854dcf.png)
![image](https://user-images.githubusercontent.com/88448390/189901703-959fbaa3-0876-4eba-a742-cc41d747143b.png)

Not very readable.

### Describe the solution you'd like to see

A change in the styling of links on the documentation page.

### Desribe alternate solutions

...

**Comment by nexxeln** [comment]
We could make the color darker for light mode maybe

**Comment by juliusmarminge** [comment]
Yes I could add a lighthouse run for the ci to catch this in the future too
