### ISSUE TITLE
docs: Theme picker starts without a selected option

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#436]
### Provide environment information

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 143.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/Documents/dev/node_modules/.bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm

### Describe the bug

Currently when opening the docs, the theme picker starts out without either option being visibly selected.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/8353666/189958047-44a6bf98-6b30-4107-a4ef-ecbd372bdd3a.png">

### To reproduce

run docs, visit any page

**Comment by juliusmarminge** [comment]
wild suggestion, disable lightmode for now (remove toggle)

just get everything finished in darkmode so we can launch it, lets be real everyone is gonna use it in that mode anyways ;), then we can fix lightmode later

**Comment by juliusmarminge** [comment]
#439 disabled the toggle

closing and re-opening an issue for supporting lightmode
