### ISSUE TITLE
feat(docs): fix lightmode

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#440]
### Is your feature request related to a problem? Please describe.

#439 disabled lightmode since there we're a few bugs here and there and didn't want to have that slow us down launching the site.

Should have it in the future though. Anyone feel free to add it back. I put `FIXME`'s whereever i disabled stuff.

### Describe the solution you'd like to see

- Enabling the theme toggle
- Sorting out all the theming and css for lightmode
- Fix issue where toggle wasn't selected by default (#436)

### Desribe alternate solutions

Only running darkmode, which isn't too bad at the beginning.

**Comment by gabrielelpidio** [comment]
[#443](https://github.com/t3-oss/create-t3-app/pull/443) addresses this issue
