### ISSUE TITLE
feat(docs): Increased clarity for first time contributors 

### ISSUE THREAD

**Issue by benmarg** [t3-oss/create-t3-app#442]
### Is your feature request related to a problem? Please describe.

Currently the `How to Contribute` section of the contributing guidelines skips over adding and committing your contribution, it only mentions how to do so for the changeset. Given the number of first time contributors we have on this project, I think it's important the docs don't skip this step, even if it's kinda obvious. 

### Describe the solution you'd like to see

I think adding something such as: 

Now you can commit your changes. You can use `git status` to double check which files have not yet been staged for commit:
<img width="1029" alt="Screen Shot 2022-09-14 at 1 01 25 PM" src="https://user-images.githubusercontent.com/14111627/190250949-6e67755b-b08a-4c53-9a16-7cc0038152f0.png">

before the `gh create pr -web` step would help with clarity during the contribution process.

### Desribe alternate solutions

Leave as is.

**Comment by juliusmarminge** [comment]
We say this `When making commits, make sure to follow the convential commit guidelines, i.e. prepending the message with feat:, fix:, chore:, docs:, etc...`

**Comment by benmarg** [comment]
Ya I saw that part @juliusmarminge , I still think explicitly outlining the code that should needs to be ran would be useful, and maintain consistency with the rest of the contribution guide where the code for each part is outlined step-by-step.

Basically replacing that section you quoted with:

When you're ready to make commits, make sure to follow the convential commit guidelines, i.e. prepending the message with feat:, fix:, chore:, docs:, etc... You can use git status to double check which files have not yet been staged for commit:

And then the code block screenshot I attached initially. What do you think?

**Comment by juliusmarminge** [comment]
We could, I think people commit changes a bit differently but some reference is always good for people unfamiliar with Git.

Can you PR?
