### ISSUE TITLE
feat(docs): make <details> tag pretty

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#444]
### Is your feature request related to a problem? Please describe.

The default `<details>` tag looks a bit meh, we should probably style it:

<img width="634" alt="CleanShot 2022-09-15 at 09 48 54@2x" src="https://user-images.githubusercontent.com/51714798/190346672-bc96fbe1-677c-45b9-b1d6-36dcb80604a0.png">

https://create-t3-app-nu.vercel.app/en/deployment/docker

### Describe the solution you'd like to see

Docusaurus looks like this which is much prettier, but we should maybe do something custom.

<img width="1127" alt="CleanShot 2022-09-15 at 09 48 14@2x" src="https://user-images.githubusercontent.com/51714798/190346461-df0fa0d7-bb2f-4c95-964a-473f5779bb63.png">

https://trpc.io/docs/v10/react-queries#example

### Desribe alternate solutions

keeping it looking aweful

**Comment by gabrielelpidio** [comment]
Made a [PR](https://github.com/t3-oss/create-t3-app/pull/448) regarding this issue check out how it looks, and let me know if you have any thoughts

**Comment by minsk-dev** [comment]
pretty it is

**Comment by gabrielelpidio** [comment]
Seems like something overwrote the changes initially made on this #448: 

On #448:
![image](https://user-images.githubusercontent.com/30420087/191349428-853535c5-72c8-4d80-b723-91eea5ddacff.png)

Currently:
![image](https://user-images.githubusercontent.com/30420087/191349935-ecdf81eb-df59-44a9-97d5-44fe1297686c.png)

However, I agree it could be further improved the looks of it

**Comment by juliusmarminge** [comment]
I'll clear you @minsk-dev. If it's left when you're back from everything and still want to take it on just assign yourself again

**Comment by juliusmarminge** [comment]
Animating the disclosure would be nice too

**Comment by juliusmarminge** [comment]
> Aight I'm game I can smash this out this weekend.
> 
> 
> 
> So just to summarize: 
> 
> - Animate the slide up and down just like [the trpc doc](https://trpc.io/docs/v10/react-queries#example) does it
> 
> - Make it generally prettier, any specific wishes as to what constitutes prettier?

Awesome. No specifics imo so you're got free hands 🙌

**Comment by dayvster** [comment]
@juliusmarminge had a bit of free time, decided to look at it sooner than the weekend: https://github.com/t3-oss/create-t3-app/pull/596
