### ISSUE TITLE
feat(docs): move Theme-toggle to Navbar

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#445]
### Is your feature request related to a problem? Please describe.

The theme toggle is currently in the right sidebar when browsing docs, maybe we should move it to the navbar to be more standardized?

<img width="275" alt="CleanShot 2022-09-15 at 09 54 25@2x" src="https://user-images.githubusercontent.com/51714798/190348022-30d17900-8ffb-44d4-b4cf-f7720f15ae74.png">

### Describe the solution you'd like to see

-

### Desribe alternate solutions

-

**Comment by nexxeln** [comment]
I kinda like it there its different.

**Comment by c-ehrlich** [comment]
navbar would be better imo

**Comment by gabrielelpidio** [comment]
I made a PR with the change, to check how it looks

**Comment by benmarg** [comment]
> navbar would be better imo

I think after seeing it in @gabrielelpidio PR, I'm of the mind it looks better in the Nav bar as well.

**Comment by juliusmarminge** [comment]
it's in the navbar now, we can move it back if we don't like it. what do you think @nexxeln
