### ISSUE TITLE
bug(www): faq page content overlaps the right sidebar

### ISSUE THREAD

**Issue by nexxeln** [t3-oss/create-t3-app#470]
### Provide environment information

```/tmp/npx-345c9d3e.sh: 1: envinfo: not found```
That's interesting

### Describe the bug

faq page content overlaps the right sidebar

<img width="960" alt="image" src="https://user-images.githubusercontent.com/95541290/190900674-d25069de-88cd-477d-84bc-55456cd91a37.png">

### To reproduce

Go to the website

**Comment by benmarg** [comment]
Any idea on how to reproduce this? No overlap for me even when shrinking down the window pretty small 

![image](https://user-images.githubusercontent.com/14111627/190927504-5d0c4122-228c-447e-93f4-ae400591ddb0.png)

**Comment by juliusmarminge** [comment]
> Any idea on how to reproduce this? No overlap for me even when shrinking down the window pretty small 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/14111627/190927504-5d0c4122-228c-447e-93f4-ae400591ddb0.png)
> 
> 

Might be fixed already. Website is moving pretty quickly rn with many PRs per day

**Comment by nexxeln** [comment]
Yeah fixed on my end too now. Closing this.
