### ISSUE TITLE
feat: Gitpod support

### ISSUE THREAD

**Issue by Coyenn** [t3-oss/create-t3-app#472]
### Is your feature request related to a problem? Please describe.

Getting started with contributing to this repository could be made a lot easier.

### Describe the solution you'd like to see

Every one of my contributions so far has been made using an ephemeral development environment using [Gitpod](https://www.gitpod.io/docs/getting-started). Gitpod allows you to create a development environment with the click of a button. You can develop right from your browser or connect to it remotely using the Gitpod VSCode extension.

Although it is already possible to develop using Gitpod (by visiting https://www.gitpod.io/#https://github.com/t3-oss/create-t3-app), adding a config file would significantly improve this workflow because necessary extensions will already be installed automatically.

### Desribe alternate solutions

If possible, I would also like to include [prebuilds](https://www.gitpod.io/docs/prebuilds). If enabled, the Gitpod bot will add a comment to every PR with a link to create a dev environment similar to how the Vercel bot does it. This will make it easier to work with multiple PRs because instead of manually checking a PR out and initializing the project, Gitpod will already do that.

### Additional information

How it looks like for me when developing using Gitpod:
![Bildschirm­foto 2022-09-18 um 14 52 14](https://user-images.githubusercontent.com/61044138/190902991-3a19219b-c732-43d3-a60d-6ddac6fd3440.png)

The PR to add Gitpod support is #471

**Comment by juliusmarminge** [comment]
Reference #264
