### ISSUE TITLE
bug(docs): sticky navbar broke links 

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#474]
### Provide environment information

https://create-t3-app-nu.vercel.app/en/introduction#what-is-this-some-kinda-template

### Describe the bug

Clicking the link above is broken cause the navbar is in the way

the header that we link to should be visible when navigating to it.

when fixing this, also add smooth scroll behavior :)

### To reproduce

click the link

**Comment by juliusmarminge** [comment]
cc @gabrielelpidio @Coyenn

**Comment by Coyenn** [comment]
Fixed in #475
