### ISSUE TITLE
feat: add prettier-plugin-tailwindcss to cli and website

### ISSUE THREAD

**Issue by gabrielelpidio** [t3-oss/create-t3-app#480]
### Is your feature request related to a problem? Please describe.

As of now classes are being added to both the cli and the code and it gets pretty messy sometimes for example:
```js
//Without prettier plugin
class="absolute flex flex-col mt-1 transform transition-transform duration-300 ease-in-out z-50 bg-default shadow shadow-t3-purple-100"

//With prettier plugin
class="bg-default shadow-t3-purple-100 absolute z-50 mt-1 flex transform flex-col shadow transition-transform duration-300 ease-in-out"
```

### Describe the solution you'd like to see

Add plugin to website and cli generated code

### Desribe alternate solutions

- Keeping it only for website
- Not adding the plugin

### Additional information

~~Important: this wouldn't add prettier as a formatter to ct3a, instead, the generated code would be pre-formatted with `prettier-plugin-tailwindcss`~~
We could consider adding it to the cli if the user chooses to use tailwind
Would love to have your thoughts, I'll leave a Draft PR down below

**Comment by gabrielelpidio** [comment]
Draft PR: #481

**Comment by TheoBr** [comment]
Very much in favor of this, imo this plugin is necessary for the _proper_ tailwind experience and I think it's worth adding for the awareness boost alone

**Comment by gabrielelpidio** [comment]
Updated the issue and PR to add `prettier` and `prettier-plugin-tailwindcss` to the output of ct3a if the user chooses `tailwind`
