### ISSUE TITLE
bug(docs): footer overflow

### ISSUE THREAD

**Issue by mateuszaliyev** [t3-oss/create-t3-app#490]
### Provide environment information

n/a

### Describe the bug

There is horizontal overflow issue with documentation website caused by a `w-screen` class on a `<footer>` element.

![image](https://user-images.githubusercontent.com/82393815/191371857-271e0799-8d35-443f-a0ef-746bd5586d84.png)

### To reproduce

Visit https://create-t3-app-nu.vercel.app/ on a desktop device.

### Additional information

I'm willing to create a pull request.

**Comment by juliusmarminge** [comment]
Thanks 🙏
