### ISSUE TITLE
feat: Run different `.env` files (`dev`/`staging`/`prod`) using dotenv

### ISSUE THREAD

**Issue by benwinding** [t3-oss/create-t3-app#512]
### Is your feature request related to a problem? Please describe.

I would love to be able to run different configurations, like this:

``` sh
.env.local
.env.tests
.env.staging
.env.prod
// ^ something like this
```

- It's actually quite [difficult to find a solution to this on next.js](https://stackoverflow.com/questions/59462614/how-to-use-different-env-files-with-nextjs) 
- Different environment variable configurations of the application is a fairly common development concern.
- There's already a page dedicated to [environment variables in the docs](https://create-t3-app-docs.vercel.app/en/configuration/environment-variables), so it's kind of already related to that.

### Describe the solution you'd like to see

A small piece in the docs would be fine. There's already a fairly long section about using environment variables on the `create-t3-app` documentation site:

https://create-t3-app-docs.vercel.app/en/configuration/environment-variables

I think it would make sense to either put a link to _**multiple-environments**_ or something here ^ or event recommended library / approach.

### Desribe alternate solutions

There are many packages that try to solve this _(multiple `.env` files in next.js)_, but none of which I could personally get working; [env-cmd](https://www.npmjs.com/package/env-cmd), [react-env](https://github.com/andrewmclagan/react-env), [dotenv-cli](https://www.npmjs.com/package/dotenv-cli).

### Additional information

It's a hard problem that concerns most applications, that doesn't have a clear way to solve it in `next.js`.

Thanks for taking the time to read this request anyway 🙏 
Love the project and have personally learnt a lot from using it 👍

**Comment by c-ehrlich** [comment]
Personally I would prefer to defer to the [Next.js environment variable docs](https://nextjs.org/docs/basic-features/environment-variables), in particular the [environment variable load order](https://nextjs.org/docs/basic-features/environment-variables#environment-variable-load-order). I don't like the idea of endorsing `dotenv` or another package unless absolutely necessary.

**Comment by nexxeln** [comment]
Closing this as next.js has solved this problem.
