### ISSUE TITLE
feat: tailor .env to only include relevant keys

### ISSUE THREAD

**Issue by barrybtw** [t3-oss/create-t3-app#515]
### Provide environment information

5.13.1

### Describe the bug

When scaffolding an app, without next-auth there's still pieces added for it in the `.env` file provided.
```# Next Auth
NEXTAUTH_SECRET=""
NEXTAUTH_URL=http://localhost:3000


# Next Auth Discord Provider
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
```
Not sure if it's meant to be there or if it's a hassle to get out when not needed.

### To reproduce

Make an app, check `.env`.

**Comment by c-ehrlich** [comment]
The .env-example file says 
```
# Note that not all variables here might be in use for your selected configuration
```

We could make separate ones for different package combinations, but I'm not sure it's worth the hassle.

**Comment by JohnVicke** [comment]
haha wow sorry @CDE90, your pr must have been submitted while I was editing my description :bow:

**Comment by CDE90** [comment]
> haha wow sorry @ CDE90, your pr must have been submitted while I was editing my description 🙇

haha, no problem
