### ISSUE TITLE
feat: Add Prettier and Tailwind's Prettier plugin to templates

### ISSUE THREAD

**Issue by TheoBr** [t3-oss/create-t3-app#516]
### Is your feature request related to a problem? Please describe.

I got so excited thinking this was done already lol. I'm ready to die on this hill we should add this but I'll poll chat in a second

### Describe the solution you'd like to see

I'd like to see chat agree w/ me that this should be added by default

### Desribe alternate solutions

Theo being sad :(

**Comment by TheoBr** [comment]
Looking like a resounding YES 
<img width="477" alt="image" src="https://user-images.githubusercontent.com/6751787/192908346-f991926b-5972-46fc-a2b3-53ff4d441dbc.png">

**Comment by TheoBr** [comment]
Also fwiw 
<img width="460" alt="image" src="https://user-images.githubusercontent.com/6751787/192908578-ccddc0e3-e2a9-45c3-bf2b-3a5ab54a7ae5.png">

**Comment by nexxeln** [comment]
🥴

**Comment by B3nten** [comment]
Including prettier breaches the line between opinions on tech versus opinions on code style. Should lint rules be added as well?

**Comment by c-ehrlich** [comment]
I'd be in favor of including a minimal prettier config that's basically only the tailwind plugin. Would consider other settings if someone can make a good case for why we should include them. I don't think we need to have opinions about single vs double quotes or whatever.

**Comment by nexxeln** [comment]
> I'm confused why this discussion was closed. There isn't much discussion. And the linked PR doesn't actually do the work asked for in the description. If there is some sort of discussion happening in back channels can that at least be posted here for others to understand the conclusion that was arrived at?

It was implemented in #517. See the comment above.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/95541290/193316992-004b8310-9fef-4b2a-aff9-c2af0f88dfe2.png">
