### ISSUE TITLE
feat: Analytics for choices made in the CLI

### ISSUE THREAD

**Issue by bdsqqq** [t3-oss/create-t3-app#519]
### Is your feature request related to a problem? Please describe.

The "should we add prettier + tailwind plugin" discussion made me think collecting data on the usage or at least on the choices users made when initiating a project can be useful to guide decisions in the future.

The feature isn't very thought through yet, but I hope this issue can start a discussion on possible approaches and even the value this can or cannot bring.

### Describe the solution you'd like to see

Ideally, something that collects anonymous data. the CLI we could ask for consent and send the technologies selected by a user to a database when it finishes bootstrapping a project. I never did something like this but I'm almost sure it's a matter of shooting a POST to an API that handles storing the data somewhere.

### Desribe alternate solutions

There should be libraries that help with this but I couldn't find one easily and owning the solution might be a better choice.

### Additional information

This started on discord and @gabrielelpidio asked to open an issue on it.
https://discord.com/channels/966627436387266600/988912020558602331/1024905545456570439
![image](https://user-images.githubusercontent.com/37847523/192944051-f38b1838-8384-4a56-a8d6-1f73849a6149.png)

**Comment by nexxeln** [comment]
We had this idea a long time ago but we decided not to do it because getting data from the user who is just using a CLI seemed like a bad thing to do. And yeah I don't like the idea of adding another prompt to the CLI.

**Comment by juliusmarminge** [comment]
An alternative could be something like what Next does, add a small message saying we're collecting telemetry and if you don't want that start the cli with some flag 
```bash
TELEMETRY=0 npx create-t3-app
# or
npx create-t3-app --anonymous
```

**Comment by juliusmarminge** [comment]
I think we concluded this was not needed?

**Comment by c-ehrlich** [comment]
Yea I think so. Closing now, if someone disagrees feel free to reopen.
