### ISSUE TITLE
feat: more fitting theme

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#522]
### Is your feature request related to a problem? Please describe.

I'm sure we all love Poimandres and it's sorta become the T3 Theme but it doesn't really fit in with the rest of the colors on the site.

![CleanShot 2022-09-29 at 22 09 37](https://user-images.githubusercontent.com/51714798/193131984-f1d02ae1-3650-4004-b9bd-c9589b257d75.png)

Should we aim for something a bit more purple-ish? It's using Shiki so there should be plenty to pick from or you can modify some to your own preference. [I did it for tRPC and it's also using shiki for syntax-highlighter](https://github.com/trpc/trpc/blob/next/www/min-light-with-diff.json).

### Describe the solution you'd like to see

Theme more in-line with the rest of the theme of the site.

Maybe also include theming for both light and dark mode?

### Desribe alternate solutions

Not really a big deal so we could just leave it as is

**Comment by nexxeln** [comment]
What about dracula? Looks quite good with the theme of the website.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/95541290/193181178-bca11980-49c5-4112-b731-01cd74645ada.png">
dracula

<img width="960" alt="image" src="https://user-images.githubusercontent.com/95541290/193181082-cf070464-03d8-487c-a4ee-db4b68b6e1db.png">
dracula soft

I like dracula soft more.

**Comment by nexxeln** [comment]
Lemme know if you want me to make a PR or if you want your custom theme

**Comment by c-ehrlich** [comment]
I like how material-darker looks on the website

<img width="1552" alt="Screenshot 2022-09-30 at 12 39 16" src="https://user-images.githubusercontent.com/8353666/193252704-15767671-3c25-4162-8c15-6119742b7178.png">
<img width="1552" alt="Screenshot 2022-09-30 at 12 39 19" src="https://user-images.githubusercontent.com/8353666/193252712-ceab0b30-f715-4b98-ae7b-58318169e980.png">

**Comment by c-ehrlich** [comment]
That being said I don't feel strongly about this and if either of you have a preference I'd be happy merging just about anything that isn't the hotdog stand theme

**Comment by nexxeln** [comment]
I like the material dark more tbh now. Great suggestion.

**Comment by c-ehrlich** [comment]
Spent a bit more time looking at this and I think I like `material-palenight` even more than `material-darker`. What do you think?

The only thing I don't love is that on the material themes object keys are red

<img width="1552" alt="Screenshot 2022-09-30 at 15 16 31" src="https://user-images.githubusercontent.com/8353666/193278087-d762cbea-cb01-4319-8de6-f9058bc89091.png">
<img width="1552" alt="Screenshot 2022-09-30 at 15 16 35" src="https://user-images.githubusercontent.com/8353666/193278092-230f6280-2506-4235-9453-52c623f638c4.png">
<img width="1552" alt="Screenshot 2022-09-30 at 15 16 43" src="https://user-images.githubusercontent.com/8353666/193278099-a8df384d-4f95-43b5-838a-46bfbe2f9efd.png">

**Comment by nexxeln** [comment]
Yeah that's nice.
