### ISSUE TITLE
feat(ci): allow beta publishing from forks

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#541]
### Is your feature request related to a problem? Please describe.

Currently, our prerelease workflow only works for branches on this repo, meaning that any forked repos first has to be merged to an intermediate branch, then prereleased by adding the `autorelease` label then merged into main. This makes it so that the original author isn't credited in the changelog, since the PR to main will come from one of the maintainers.

See #533 and #529.

### Describe the solution you'd like to see

Being able to trigger a prerelease from forks. Currently authentication fails when doing so.

Probably cause of security reasons? Any workarounds?

### Desribe alternate solutions

keeping as is and just letting maintainers trigger release from intermediate branches and taking the credit in the changelog and release note :/

**Comment by mtmeyer** [comment]
Not sure if I've properly understood the issue but I discovered this GitHub article around approving forks to run workflows: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by juliusmarminge** [comment]
> Not sure if I've properly understood the issue but I discovered this GitHub article around approving forks to run workflows: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

The workflow runs but the npm authentication fails

**Comment by gzuzmark** [comment]
Hi is this a workflow run example of how it fails? https://github.com/t3-oss/create-t3-app/actions/runs/2868043633/jobs/4549811185?

**Comment by juliusmarminge** [comment]
> Hi is this a workflow run example of how it fails? https://github.com/t3-oss/create-t3-app/actions/runs/2868043633/jobs/4549811185?

No thats a different error with the versioning.
