### ISSUE TITLE
bug: "documentation" tag not being applied to PRs

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#547]
### Provide environment information

n/a

### Describe the bug

Some PRs to the website/docs are not automatically getting the "Documentation" label.

Examples: 
- https://github.com/t3-oss/create-t3-app/pull/544
- https://github.com/t3-oss/create-t3-app/pull/528
- https://github.com/t3-oss/create-t3-app/pull/527

Examples of PRs that **do** have the tag:
- https://github.com/t3-oss/create-t3-app/pull/539
- https://github.com/t3-oss/create-t3-app/pull/524
- https://github.com/t3-oss/create-t3-app/pull/521
- https://github.com/t3-oss/create-t3-app/pull/518

It seems like PRs that include changes to .md files get the tag, but PRs that only touch other parts of the website/docs do not.

### To reproduce

Open a PR that changes only non-.md website files (not 100% sure this is the pattern, but based on checking a few PRs it seems so)

**Comment by juliusmarminge** [comment]
I think #551 resolves this

**Comment by c-ehrlich** [comment]
Still seems bugged https://github.com/t3-oss/create-t3-app/pull/559

**Comment by juliusmarminge** [comment]
> Still seems bugged, but now in a different way #559
> 
> I think this might be a solution, but I don't know if it might break other things. Will give it a try [actions/labeler#399](https://github.com/actions/labeler/issues/399)

is it something to do with forks? I never have that issue when PRing from local branches?

**Comment by c-ehrlich** [comment]
> > Still seems bugged, but now in a different way #559
> > I think this might be a solution, but I don't know if it might break other things. Will give it a try [actions/labeler#399](https://github.com/actions/labeler/issues/399)
> 
> is it something to do with forks? I never have that issue when PRing from local branches?

Yes.

Based on my research before:
- it can be resolved by running the action on `pull_request_target` instead of `pull_request`
- however this is a security risk as `pull_request_target` has full read/write access, which shouldn't be granted when you use `actions/checkout` (reference: https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests)
- we could split it into two actions groups, one with the labeler on `pull_request_target` and the other with everything else on `pull_request`, but we would have to find a way to still make build conditional on the labeler

**Comment by c-ehrlich** [comment]
I tried using `on: workflow_run` in https://github.com/t3-oss/create-t3-app/pull/560 but didnt it to work so far
