### ISSUE TITLE
bug: beta.create.t3.gg mobile nav breaks on certain pages

### ISSUE THREAD

**Issue by bte234** [t3-oss/create-t3-app#555]
### Provide environment information

It's on https://beta.create.t3.gg
tested in google chrome 105.0.5195.125

### Describe the bug

The styling of certain pages' mobile dropdown menu is broken, having menu item text rendered on top of page content (image below)
![image](https://user-images.githubusercontent.com/26082352/193713672-49dfefa0-7828-4cba-bd1a-e85b334db29d.png)

### To reproduce

- Go to https://beta.create.t3.gg/en/usage/typescript
- Using the dev tool, change the width of the window to below 480
![image](https://user-images.githubusercontent.com/26082352/193713849-2eece335-cda8-4225-afa7-0393c6747cc4.png)
- As the window gets smaller, you can see more of the menu texts at the bottom without background color
![image](https://user-images.githubusercontent.com/26082352/193714138-c80b0e52-0c01-4f92-b32d-ae41d1e499a8.png)

This technically can affect all pages if the screen gets small enough, but realistically https://beta.create.t3.gg/en/usage/typescript , https://beta.create.t3.gg/en/usage/tailwind and https://beta.create.t3.gg/en/deployment/docker are the most noticeable ones that I can see the bug on my actual phone (Pixel 6)

### Additional information

Those pages mentioned above have the links that go way too long before breaking to newline, breaking them up earlier would fix the issue

Before
![image](https://user-images.githubusercontent.com/26082352/193714516-5d6dc4ee-2c09-45eb-a2e0-4af87e9b82f2.png)

Adding `word-break: break-word` to the links:
![image](https://user-images.githubusercontent.com/26082352/193714783-6b84e857-527c-4df1-b14c-5d82a02889bb.png)
![image](https://user-images.githubusercontent.com/26082352/193714812-ec70540c-03cf-4dcb-90ef-f2262877b5cb.png)

**Comment by c-ehrlich** [comment]
This works, but for some reason I can't get it working without `is:global`, whether I put it in `docs.astro` or `pageContent.astro`.

```
<style is:global>
  article td a {
    word-break: break-word;
  }
</style>
```

**Comment by bte234** [comment]
I was going to work on this issue, but it seems the problem has changed a bit since I opened it
The page's mobile layout is still shifted because of those long urls (the hamburger menu is almost at the center of the screen instead of being on the right in this screenshot)
![image](https://user-images.githubusercontent.com/26082352/194457721-4dd34b52-0e3f-47e4-a2cf-70e3c767935a.png)

However, the menu no longer have items without a background color like my old screenshot, though the header (logo, theme toggle and close button) can be scrolled out of the view (they scroll with the underlying page content instead of sticking on top, so if you are reading further down and open the menu, they won't appear since they are way up)
![image](https://user-images.githubusercontent.com/26082352/194457999-ae93bc00-0d8e-46ca-bb4a-31584663037b.png)

Should I deal with this in this same issue or should I open a new one?
