### ISSUE TITLE
bug: installation animation breaking on mobile for beta.create.t3.gg

### ISSUE THREAD

**Issue by SeanCassiere** [t3-oss/create-t3-app#556]
### Provide environment information

OnePlus Nord
Chrome 105.0.5195.136

### Describe the bug

This happens in the new beta website for create t3 app. 
Best shown in video format. See after the choice of 'Typescript' is selected. 
https://drive.google.com/file/d/1sRdMiJ9t9LydUXTWTbX9clKrZTaKiHFu/view?usp=drivesdk

### To reproduce

1. Browse to beta.create.t3.gg
2. Scroll down to the CLI installation animation

**Comment by juliusmarminge** [comment]
iPhone safari iOS 16.0 works ![image](https://user-images.githubusercontent.com/51714798/193793858-a2d6bbe4-65ab-4552-a9df-14bdc7098285.png)

**Comment by Nsttt** [comment]
Works on Android 12 

![Screenshot_2022-10-13-18-12-27-247_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/23436531/195654884-992b1b8c-b94a-44fd-80f2-297994cca735.jpg)

**Comment by Nsttt** [comment]
@c-ehrlich seems to be fixed
 ![Screenshot_2022-11-16-14-43-03-277_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/23436531/202196496-fc67a3db-2564-4c61-be37-38b223d577e7.jpg)

**Comment by nexxeln** [comment]
Thanks @Nsttt
