### ISSUE TITLE
bug: beta.create.t3.gg Nav theme flash on firefox

### ISSUE THREAD

**Issue by 0mns** [t3-oss/create-t3-app#558]
### Provide environment information

- Windows 
- Firefox

### Describe the bug

https://user-images.githubusercontent.com/38424856/193875304-f398a07b-df3b-4500-9735-8923cc457333.mp4

### To reproduce

Open beta.create.t3.gg on firefox
navigate

**Comment by 0mns** [comment]
in chrome theres a flashing outline in nav items

https://user-images.githubusercontent.com/38424856/193878188-b849648a-9cc9-4155-98b5-59101d8a27c4.mp4

**Comment by WagnerMoreira** [comment]
The same happens when we switch from light to dark theme, any page refresh causes that, is this code open source? I'd love to fix that and put up a PR

**Comment by juliusmarminge** [comment]
Fixed in #573
