### ISSUE TITLE
feat: Consider including @next/bundle-analyzer in the template

### ISSUE THREAD

**Issue by dtinth** [t3-oss/create-t3-app#584]
### Is your feature request related to a problem? Please describe.

In a T3-stack app we’re building, soon enough we run into this:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/193136/194515122-7777ec2b-36d1-489a-bc5a-f2c4364e4177.png">

We had to install [@next/bundle-analyzer](https://www.npmjs.com/package/@next/bundle-analyzer) in order to analyze what went wrong.

Having worked with many Next.js apps, for anything more than a toy project, installing `@next/bundle-analyzer` is an inevitable. I think it might make sense to generate an app with a bundle analyzer preconfigured.

### Describe the solution you'd like to see

Include https://www.npmjs.com/package/@next/bundle-analyzer in the template.

It is a no-op when building, unless `ANALYZE=true` environment variable is used when building, so by default it sits quietly but it’s there when you need it.

### Desribe alternate solutions

Manually install `@next/bundle-analyzer` in each project some time down the line (current status quo).

**Comment by c-ehrlich** [comment]
How difficult is the setup for this? What percentage of ct3a users need it? Intuitively it feels to me like something that should be left to the user.

**Comment by nexxeln** [comment]
This is really simple to add and shouldn't be a default in my opinion.

**Comment by c-ehrlich** [comment]
Closing this
