### ISSUE TITLE
feat: Arrow keys support at feachure picker

### ISSUE THREAD

**Issue by Yevhenii-Bakhmat** [t3-oss/create-t3-app#589]
### Is your feature request related to a problem? Please describe.

When you select the features that CLI should include in the template, It'd be cool if the selection button wasn't only "Space". 

### Describe the solution you'd like to see

Id love to check features with "Arrow Right" and uncheck with "Arrow Left" coz it would be easier as you use keys that are nearby with one hand.

### Desribe alternate solutions

This ain't critical at all but it would be nice to have it :)

### Additional information

<img width="367" alt="Снимок экрана 2022-10-08 в 10 45 42" src="https://user-images.githubusercontent.com/34962307/194696347-380120bb-79ba-44ec-8e50-41a1fdfe5304.png">

**Comment by juliusmarminge** [comment]
Im not familiar with Inquirer if you can modify the defaults?

**Comment by c-ehrlich** [comment]
reading through the inquirer docs there doesn't seem to be a documented way of either doing this or just allowing to listen for custom keypress events. its surely possible either by modifying inquirer or building our own thing, but doesn't seem worth the effort.

**Comment by Yevhenii-Bakhmat** [comment]
Yeah makes sense.
