### ISSUE TITLE
feat: make session optional in CreateContextOptions (discussion)

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#600]
### Is your feature request related to a problem? Please describe.

Currently we are doing: 

```ts
type CreateContextOptions = {
  session: Session | null;
};

/** Use this helper for:
 * - testing, so we dont have to mock Next.js' req/res
 * - trpc's `createSSGHelpers` where we don't have req/res
 **/
export const createContextInner = async (opts: CreateContextOptions) => {
  return {
    session: opts.session,
    prisma,
  };
};
```

This means that when SSGing pages that don't require the session, you need to explicitly pass `session: null` to `createProxySSGHelpers`.

### Describe the solution you'd like to see

Change it to

```ts
type CreateContextOptions = {
  session?: Session | null;
};
```

### Desribe alternate solutions

Leave it as is, make people pass `session: null` explicitly

### Additional information

One thing I don't love about this proposal is you still need to pass an empty object like

```ts
const ssgHelper = createProxySSGHelpers({
    router: appRouter,
    ctx: await createContextInner({}), // type error if empty object isn't passed
    transformer: superjson,
  });
```

So I'm not sure if it's actually better. Would like to hear opinions.

**Comment by dayvster** [comment]
could do 

```typescript
type CreateContextOptions = {
  session: Session | {};
};
```

But then it's not really all that typesafe.

**Comment by bte234** [comment]
If the only param of CreateContextOptions is optional, what if opts itself is optional in createContextInner? Something like
```ts
type CreateContextOptions = {
  session?: Session | null;
};

/** Use this helper for:
 * - testing, so we dont have to mock Next.js' req/res
 * - trpc's `createSSGHelpers` where we don't have req/res
 **/
export const createContextInner = async (opts?: CreateContextOptions) => {
  return {
    session: opts?.session,
    prisma,
  };
};
```

**Comment by c-ehrlich** [comment]
> could do
> 
> ```ts
> type CreateContextOptions = {
>   session: Session | {};
> };
> ```
> 
> But then it's not really all that typesafe.

This is not true - the thing that needs to be at least an empty object is not `session`, but `opts`. Also `{}` is not a type.





> If the only param of CreateContextOptions is optional, what if opts itself is optional in createContextInner? Something like

This seems to work well if it is assumed that all params of CreateContextOptions are optional. This is true in the template, and probably _most_ projects. If we use this we would have to comment the hell out of it. Will leave this open for a while if anyone has opinions :)

**Comment by juliusmarminge** [comment]
Doesn't really matter from a usage point, you'd still need to use the `session?.user` for example when accessing it.

If you think the DX is better by allowing it not to be passed I guess but I also like the explicitness and makes you think whether you should get the session or just omit it by passing `null` 🤷‍♂️

**Comment by juliusmarminge** [comment]
> Doesn't really matter from a usage point, you'd still need to use the `session?.user` for example when accessing properties on it - no matter if we add the `?` or not.
> 
> If you think the DX is better by allowing it not to be passed I guess but I also like the explicitness and makes you think whether you should get the session or just omit it by passing `null` 🤷‍♂️

**Comment by c-ehrlich** [comment]
After thinking about it some more I don't feel like the proposed change is meaningfully better. Closing this for now, but anyone is welcome to reopen.
