### ISSUE TITLE
bug: loading spinner hangs

### ISSUE THREAD

**Issue by nexxeln** [t3-oss/create-t3-app#610]
### Provide environment information

The envinfo thing isn't working for me. It's wsl ubuntu, zsh shell.

### Describe the bug

When choosing to install deps, the loading spinner hangs and doesn't spin. See this [video](https://us-east-1.tixte.net/uploads/this-vegetable.is-from.space/Alacritty-v0.10.0-portable_(1)_tMaj3KljMO.mp4)

I discovered this a few weeks ago but I also changed my terminal emulator recently so I thought it was something to do with that. But today in Theo's stream I saw the same thing happening in Primeagen's and [Theo's terminal](https://www.youtube.com/clip/UgkxlCiklntCCMYiIqUJqf8-uXm0rZmydnrz).

This is a high priority issue because this will make people think that the cli crashed.

### To reproduce

Run
```
pnpm create t3-app@latest
```

Say yes to install dependencies.

**Comment by c-ehrlich** [comment]
Can confirm on MacOS.
