### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by On0n0k1** [t3-oss/create-t3-app#640]
### Provide environment information

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 19.00 GB / 31.24 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.14.0/bin/npm

### Describe the bug

It's so simple I'm not even sure it is a serious bug.

It's a bug that happens when running the generated app with sqlite locally in docker.

The code in /src/env/schema.mjs throws an error when parsing environment variables.

This is because, in the .env file, we have:

DATABASE_URL=file:./db.sqlite

Which is not a valid url, in zod standards.

Changing validation to just z.string() instead of z.string().url() fix it. But validation of the path loses it's purpose.

### To reproduce

Run create-t3-app:
 - Enable all features;
 - Follow the steps to use docker and docker-compose;
 - Run 'Docker-compose up';
 - This error will happen even before noticing that NEXTAUTH_SECRET, DISCORD_CLIENT_ID and DISCORD_CLIENT_SECRET are missing;

### Additional information

It's clearly a silly bug. And it's very easy to fix. I'm not sure I should be making this issue.

I'm just worried that it might be a bit confusing for someone that never used the stack before. I found it because I'm carefully studying each line of code in the entire project.

Below is the change that makes the error go away. But I'm not sure if it's even worth it.

![fix](https://user-images.githubusercontent.com/61277568/197356862-4eb7dcef-3839-4291-92df-afe1dafc4e3c.png)

What are your thoughts on this?

**Comment by juliusmarminge** [comment]
z.string().url().parse('file:/db.sqlite'); has been valid in the past

**Comment by On0n0k1** [comment]
Thanks for the feedback. I will close the issue and keep looking at it then.

**Comment by On0n0k1** [comment]
Oh I found the error. The Docker-compose file from the tutorial had this environment variable.

![fixxx](https://user-images.githubusercontent.com/61277568/197358711-632d02a4-bf2d-4a67-b1bd-ef4f502b0cf5.png)

I was looking at the wrong file. Thanks!
