### ISSUE TITLE
feat: trpc subscription examples

### ISSUE THREAD

**Issue by willosof** [t3-oss/create-t3-app#641]
### Is your feature request related to a problem? Please describe.

The problem is mostly me having a hard time figuring out the whole underdocumented subscription stuff in tRPC.

### Describe the solution you'd like to see

T3 to implement a working subscriptions example.
* How to make it serverside
* How to use it in the frontend
* How to solve the `error TRPCClientError: Subscriptions should use wsLink` stuff

Mostly things I've gotten around on my own, but I think it would benefit the T3 users to get this solution without having to deal with the sidenote that subscriptions is mentionaed as in tRPC docs.

### Desribe alternate solutions

It could be better subscription docs in the trpc docs, but that's not T3's fault :)

**Comment by rhenriquez28** [comment]
I think this is more of a tRPC issue than a t3 issue. In this case, the actual problem that needs to be solved is better tRPC subscription docs. I do agree with you, the subscription docs are definitely lacking. It's something I've been wanting to fix for a while but I have never used subscriptions so it's hard for me to explain. Maybe you can take a shot at improving the docs yourself and submit a PR?

**Comment by c-ehrlich** [comment]
Agreed. While I agree that tRPC subscriptions docs could be better, I don't think the solution is to add stuff to the ct3a docs. We mostly want people to look in the docs for each package, not in ours. Also the tRPC docs clearly state that subscriptions are still a beta feature, so likely to have issues and can change anytime.
