### ISSUE TITLE
bug: TypeError: resolver is not a function

### ISSUE THREAD

**Issue by endalk200** [t3-oss/create-t3-app#659]
### Provide environment information

  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.50GHz
    Memory: 672.28 MB / 2.85 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.1 - ~/.nvm/versions/node/v16.14.0/bin/npm

### Describe the bug

I have removed the Discord provider from the nextauth file and added GitHub provider. After that I edited the env schema file and added my GitHub ID and secret. After that, I run the app and tried to sign in. The page throws the error `TypeError: resolver is not a function`

### To reproduce

1. Remove Discord provider from nextauth config file
2. Add GitHub provider
3. Edit the `src/env/schema.mjs` file and change discord related environment variables to GitHub.
4. Add your environment variables to `.env` file.
5. Run the app
6. Try to sign in by clicking the `Sign In` button.

**Comment by juliusmarminge** [comment]
Sorry for the delay on a response, I've been tackling 3 exams this week so haven't had much time for anything else.

Regarding your issue, I've tried reproducing it and I'm unable to. Could you provide a reproduction repo?

![CleanShot 2022-10-28 at 22 27 42](https://user-images.githubusercontent.com/51714798/198726453-f753bc55-7768-432b-a6ca-56f3df48c7b5.png)

![CleanShot 2022-10-28 at 22 27 55](https://user-images.githubusercontent.com/51714798/198726472-7f14ec8b-5b68-4a7f-af27-1658b348fa7e.png)

![CleanShot 2022-10-28 at 22 27 17](https://user-images.githubusercontent.com/51714798/198726404-8c804beb-d482-4e7d-afa1-eeb088bc76c4.png)

**Comment by endalk200** [comment]
Sure. Let me get started on that. Thanks for the response.

**Comment by endalk200** [comment]
I was able to resolve the issue by scaffolding with the latest version of the CLI. Thanks for the support.
