### ISSUE TITLE
feat: Next.js 13 support

### ISSUE THREAD

**Issue by martwozniak** [t3-oss/create-t3-app#660]
### Is your feature request related to a problem? Please describe.

A new version of next.js has been released, and as a result, t3stack needs to be updated.

### Describe the solution you'd like to see

Update next.js to version 13. 

### Desribe alternate solutions

Waiting until all dependencies have Next.js 13 support.

**Comment by juliusmarminge** [comment]
#657 

Try it out today using

```bash
npx create-t3-app@6.0.0-beta.7f9260b
```

**Comment by teknoalex** [comment]
What is the status right now of the status of the React Server Components support. I am starting a new project right now and it looks very promising

**Comment by c-ehrlich** [comment]
> What is the status right now of the status of the React Server Components support. I am starting a new project right now and it looks very promising

People are hacking on some stuff (you can check the tRPC Discord server if you're interested) but both RSCs themselves and anything we might build on top of them are still very much experimental.

**Comment by juliusmarminge** [comment]
> What is the status right now of the status of the React Server Components support. I am starting a new project right now and it looks very promising

I started a toy-project earlier this week with RSC but it really lacks some primitives for doing mutations right now. See here if you're interested in how you can use trpc with rsc https://github.com/juliusmarminge/linktree
