### ISSUE TITLE
doc: include a link to the documentation site in the index page.

### ISSUE THREAD

**Issue by endalk200** [t3-oss/create-t3-app#664]
### Is your feature request related to a problem? Please describe.

It is not related to a problem but it is nice to have. I haven't found the [create t3 app docs](https://beta.create.t3.gg/en/introduction) on time. After I found it has helped me a lot.

### Describe the solution you'd like to see

Include a link to the documentation site in the `index.tsx` file.

### Desribe alternate solutions

I think including a link to the docs in the first page the users see is helpful.

**Comment by c-ehrlich** [comment]
There is an all-new index file coming soon that has this and is nicer overall :)
