### ISSUE TITLE
feat: A detailed documentation for the folders and files

### ISSUE THREAD

**Issue by samyarkd** [t3-oss/create-t3-app#669]
### Is your feature request related to a problem? Please describe.

The problem is that i don't know what are the files and i want to read about them.
For example i don't know what is env folder and how to use it.

### Describe the solution you'd like to see

A detailed documentation about folder structure and files (Env folder, client.js...)

### Desribe alternate solutions

Commenting inside of files

**Comment by c-ehrlich** [comment]
We are working on this - [https://beta.create.t3.gg/en/usage/env-variables](https://beta.create.t3.gg/en/usage/env-variables)

**Comment by samyarkd** [comment]
Wow, that's awesome. Thank you
