### ISSUE TITLE
bug: `.yarnrc` is added to pnpm-based installation

### ISSUE THREAD

**Issue by axhamre** [t3-oss/create-t3-app#670]
### Provide environment information

 System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 34.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm

### Describe the bug

`.yarnrc` is added to pnpm-based installation

### To reproduce

Version: 6.6.0

- Follow the interactive installation wizard and pick PNPM as Node package manager
- Among the generated files, there's a `.yarnrc` in the root

**Comment by nexxeln** [comment]
This is intention because next-auth doesn't support node 18 yet. So let's say someone clones your project and uses yarn, they won't be able to install next-auth without that file. 

You can delete it but I'd recommend you keep it

**Comment by juliusmarminge** [comment]
> This is intentional because next-auth doesn't support node 18 yet. So let's say someone clones your project and uses yarn, they won't be able to install next-auth without that file. 
> 
> 
> 
> You can delete it but I'd recommend you keep it

Also it's for the noInstall mode, suppose you run the scaffolder and don't install the dependencies, you need the rc file for when you do.

**Comment by axhamre** [comment]
Oh OK I see, thanks! I'll close the issue then.

But IMHO: when I explicitly express that I want to use PNPM in the setup phase, both of the mentioned cases seem a bit unlikely 🤷‍♂️

**Comment by juliusmarminge** [comment]
> Oh OK I see, thanks! I'll close the issue then.
> 
> 
> 
> But IMHO: when I explicitly express that I want to use PNPM in the setup phase, both of the mentioned cases seem a bit unlikely 🤷‍♂️

I thought so too in the beginning, but often when I try out the beta, I use the command the GitHub bot gives me (which is in npx) and then say no to the install cause I want to use pnpm. Might just be me?
