### ISSUE TITLE
feat: Upgrade next-auth to v4.15.1 to support node  18

### ISSUE THREAD

**Issue by nianiam** [t3-oss/create-t3-app#680]
### Is your feature request related to a problem? Please describe.

Next-auth has _finally_ added support for node 18 (and also added full support for next ^13.0.1):

https://github.com/nextauthjs/next-auth/releases/tag/next-auth%40v4.15.1

### Describe the solution you'd like to see

Bumping the next-auth version and removing (or emptying) `.yarnrc`/`.npmrc`.

### Desribe alternate solutions

N/A

**Comment by c-ehrlich** [comment]
this will be fixed in https://github.com/t3-oss/create-t3-app/pull/673
