### ISSUE TITLE
doc: possible improvements and/or fixes

### ISSUE THREAD

**Issue by AyanavaKarmakar** [t3-oss/create-t3-app#686]
### Is your feature request related to a problem? Please describe.

1. [Broken markdown link](https://create-t3-app-nu.vercel.app/en/usage/tailwind) 

![TailwindCSSBrokenMDLink](https://user-images.githubusercontent.com/89210438/200057257-1dbf600e-a9b5-4753-9fb0-bb5c6657b826.png)

2. IMO, the documentation should consistently use either `NextJS` or `Next.js`, instead of a combination of both. 

![image](https://user-images.githubusercontent.com/89210438/200057705-4473db27-a830-4c4d-b68b-191d239b1a91.png) 

![image](https://user-images.githubusercontent.com/89210438/200057730-70862215-0dc2-4f21-a2bc-f2103664d8b0.png) 

![image](https://user-images.githubusercontent.com/89210438/200057762-cca1a08c-a7f6-41fc-b059-4b86aadf8e19.png)

![image](https://user-images.githubusercontent.com/89210438/200057781-29dd649a-3933-440f-950e-8543d120fa4c.png) 

![image](https://user-images.githubusercontent.com/89210438/200057799-2c3b97c7-c9df-4e0e-b474-07abd109c81e.png)

### Describe the solution you'd like to see

N/A

### Desribe alternate solutions

N/A

### Additional information

I am open to making a PR to fix this issue.

**Comment by juliusmarminge** [comment]
Next.js is the correct way,

Feel free to PR :)
