### ISSUE TITLE
bug: NextAuth.js usage page in the documentation possibly behaving weirdly on mid/small mobile screens

### ISSUE THREAD

**Issue by AyanavaKarmakar** [t3-oss/create-t3-app#692]
### Provide environment information

- Device — Samsung Galaxy M32
- One UI Version — 4.1
- Android Version — 12

### Describe the bug

- The navbar doesn't fill the screen

![MyDeviceImage1](https://user-images.githubusercontent.com/89210438/200136560-559291de-5b5c-42fb-ab4f-cb741a699454.png) 

- Text Overlap

![MyDeviceImage2](https://user-images.githubusercontent.com/89210438/200136587-7b488c25-6405-4719-8f84-c463e7392873.png) 

### To reproduce

1. Go to the [NextAuth.js](https://create-t3-app-nu.vercel.app/en/usage/next-auth) page in the documentation
2. Press <kbd>F12</kbd> to open chrome dev tools
3. Press <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>M</kbd> to toggle device toolbar
4. Select `iPhone 5/SE` in dimensions or just shorten the container using `Responsive` dimensions 

![ReproductionImage](https://user-images.githubusercontent.com/89210438/200137021-81029088-07e5-43a7-bf19-011c7d70d279.png)

### Additional information

I suspect this sentence is probably causing this issue. 

![SusImage](https://user-images.githubusercontent.com/89210438/200137547-16b00d7e-4970-4772-bab2-1e157cb647d6.png)

Rewording this sentence fixes the issue because of the now possible line breaks, which weren't possible before. _I may be wrong about this._ 

![NotASusImage](https://user-images.githubusercontent.com/89210438/200137716-a1346393-c272-4a82-bd75-7989e111dc0a.png)

P.S Not sure if rewording is the correct solution.

**Comment by Yevhenii-Bakhmat** [comment]
Yeah confirmed on iOS Firefox ![image](https://user-images.githubusercontent.com/34962307/200160511-e8f199a2-ca83-423e-81bb-8f6f35ecbe95.png)
