### ISSUE TITLE
feat: add project directory layout to docs

### ISSUE THREAD

**Issue by kroucher** [t3-oss/create-t3-app#693]
### Is your feature request related to a problem? Please describe.

At the moment, there isn’t a clear overview of the folder structure on what a freshly scaffolded create-t3-app looks like. There are decisions made (such as containing the app within the `src` directory), or recommendations taken (like the tRPC folder structure) that haven’t been discussed or explained.

### Describe the solution you'd like to see

It would be good to have a page/section added to an existing page that gives a brief explanation on what the folders purpose is and what files it would contain. It should be easily maintainable (I.e not a graphic), some suggestions could be a simple table like the following:

| Directory   | Purpose  |
|---|---|
|  `src`|  This is the main application directory that contains your Next.JS `pages` directory, the`server` directory for tRPC _etc etc_ |

Or it could use the same visual layout as tRPC’s [recommended folder structure](https://trpc.io/docs/v10/nextjs#recommended-file-structure) 

### Describe alternate solutions

None thought of, browsing other documentation sites and seeing folder structures explained made me think of it being a possibility for create-t3-app, completely open for discussion though.

### Additional information

I’m happy to submit a PR to add this, which can be iterated over by anyone else with changes they feel should be included.

**Comment by nexxeln** [comment]
I like the way tRPC does this. Feel free to make a PR
