### ISSUE TITLE
docs: better "more" menu on mobile

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#706]
### Is your feature request related to a problem? Please describe.

pointed out by @juliusmarminge - the "more" menu doesn't look great on mobile currently

![screenshot](https://user-images.githubusercontent.com/51714798/200500029-8aeb4371-6912-4d9a-b173-79a73964e56d.png)

### Describe the solution you'd like to see

* whatever it takes to make it look nicer
* possible ideas:
  * bit more spacing (both top and left?)
  * centering? (probably not, but worth a try?)

### Describe alternate solutions

keep as is

**Comment by AshSimmonds** [comment]
What page/search is that? Looks ok on mine.

![SbnG376RQd](https://user-images.githubusercontent.com/9034041/200568206-6f70f042-8653-4673-9f2c-cb19afb54be3.png)
