### ISSUE TITLE
bug: not logged in when rendering SSR

### ISSUE THREAD

**Issue by chamatt** [t3-oss/create-t3-app#715]
### Provide environment information

  System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 386.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm

### Describe the bug

Given a logged-in user, when the page renders server side, the user is not logged in yet, so the page shows the sign-in button. Only when it loads the client side that it fetches the login info and displays it.

Is this the expected behavior? Is there a way to have the session passed in during SSR so that useSession doesn't return null during the ssr render pass?

I saw this PR in the repo where it contained a snippet to passthrough the headers in tRPC (https://github.com/t3-oss/create-t3-app/pull/396), but it's not in the repo anymore (why was it removed?), and that is also not enough.

### To reproduce

- Create a t3-stack repo with next-auth

### Additional information

<img width="643" alt="image" src="https://user-images.githubusercontent.com/20344348/201009126-8c9b58b7-53ec-4217-94c9-2d7ea8e77544.png">

**Comment by juliusmarminge** [comment]
Get the session on server via gSSP and pass it down as props

**Comment by balazsorban44** [comment]
Explained here: https://next-auth.js.org/getting-started/client#sessionprovider
