### ISSUE TITLE
project-name can no longer be used to change directory

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#72]
**Describe the bug**
It is no longer possible to scaffold your app outside of the CWD due to the CLI's [validator](https://github.com/nexxeln/create-t3-app/blob/main/src/utils/validateAppName.ts).

**To Reproduce**

1. Run the CLI `npx create-t3-app`
2. Under project name, enter a path, e.g. `apps/web`.
3. The CLI's validator will warn that the name is not valid, see screenshots below.

**Expected behavior**
The app should scaffold with the name `web` under the `apps` directory.

**Screenshots**
![CleanShot 2022-06-28 at 17 58 40](https://user-images.githubusercontent.com/51714798/176226362-4df34f77-96fd-460d-a15d-d3c7f1e6ea6e.png)
![CleanShot 2022-06-28 at 18 00 39](https://user-images.githubusercontent.com/51714798/176226398-3e6d9cad-a4da-4e62-a123-06c732df05f5.png)

**Comment by nexxeln** [comment]
Do we even need validation?

**Comment by MWhite-22** [comment]
Being devil's advocate here, this will require a decent amount of edge case protection.

If we:
Parse anything before the final "/" as a change in the project directory
Parse anything after the finial slash as the actual package name

However, what if people want to name their packages to a scoped repo. For example, in a monorepo, i usually name my packages "@mw/PKG_NAME" such as  "@mw/configs" or "@mw/shared_ui"

**Comment by juliusmarminge** [comment]
> Do we even need validation?

Maybe its overkill

**Comment by juliusmarminge** [comment]
> Parse anything before the final "/" as a change in the project directory
> Parse anything after the finial slash as the actual package name

Previously this was all handled internally by `path` so you dont have to manually change directories.

**Comment by nexxeln** [comment]
Yeah I'm not sure what to do here, both points are valid

**Comment by juliusmarminge** [comment]
Initial testing of my function above seems promising.

![CleanShot 2022-06-28 at 18 20 31](https://user-images.githubusercontent.com/51714798/176230498-bdce3feb-031e-49e6-8744-4f5ee833e910.png)
![CleanShot 2022-06-28 at 18 21 28](https://user-images.githubusercontent.com/51714798/176230632-c38a891e-fadf-4416-81dc-99ad85db4bb0.png)
![CleanShot 2022-06-28 at 18 22 02](https://user-images.githubusercontent.com/51714798/176230741-a747b2d8-9fd3-4cbf-9d19-10fcaecb5e71.png)

**Comment by juliusmarminge** [comment]
Resolved in #135
