### ISSUE TITLE
docs: Change default font to Inter

### ISSUE THREAD

**Issue by complexengine** [t3-oss/create-t3-app#724]
### Is your feature request related to a problem? Please describe.

Default docs font on Firefox/Linux can be better.

### Describe the solution you'd like to see

Change the default font to Inter.

### Describe alternate solutions

Does not need an alternate solution.

### Additional information

N/A

**Comment by nexxeln** [comment]
Can you provide a screenshot on how it looks on firefox linux

**Comment by complexengine** [comment]
> Can you provide a screenshot on how it looks on firefox linux

![image](https://user-images.githubusercontent.com/31100120/201475909-68be9ca1-dae9-4c29-8887-4f0c8626e716.png)
