### ISSUE TITLE
feat: add support for email and password auth.

### ISSUE THREAD

**Issue by endalk200** [t3-oss/create-t3-app#734]
### Is your feature request related to a problem? Please describe.

The current nextauth addon only supports third-party providers. I am working on a team that uses this stack for some part of the platform we are building, and the others are microservices. Our authentication microservice implements a custom solution which is necessary for us. We have used Nextauth to integrate with our server which took some work to get right. 

### Describe the solution you'd like to see

Add an option when scaffolding using the CLI to add custom auth server configuration.

### Describe alternate solutions

Add detailed documentation of this can be done.

**Comment by endalk200** [comment]
If this issue is acceptable I can work on the implementation.

**Comment by c-ehrlich** [comment]
Are you referring to implementing this: https://next-auth.js.org/providers/credentials ?

A custom adapter for your own existing auth service is something that I think you will always need to build yourself, because we can't make any assumptions about your service. I'm curious what a "generic" version of this would look like, or if it's even possible.

**Comment by endalk200** [comment]
Yes. A generic version of this is possible. These are the problems we can solve:

1. Get the access token given by the provider (credentials provider which is our backend server). Having that access, the frontend can use it to send subsequent requests to the backend API.
2. Pass additional user information to the session data.

There are problems we can solve other than the aforementioned but they wouldn't be generic enough to be included here.

**Comment by nexxeln** [comment]
We are not big fans of password based authentication here, and next-auth's credentials provider isn't the best to work with. You end up doing a lot of stuff yourself. So yes, we won't be adding an option for credential auth. Whoever wants credential auth can do it on their own

**Comment by davidawad** [comment]
I really can't emphasize enough how important it would be to have this, there's plenty of reasons to make life easier for people. Not every app is going into production. 

As it stands right now there's actually no way to setup a quick app using just plain username password. (you have to use a third party or an email service for it to work, that's insane and shouldn't be the case.)

**Comment by nagy135** [comment]
totally agree with david, there should be option to simply verify agains array of dummy users with credentials login ....there are many usecases where social login is simply not gonna work (like admin pages with you creating users for clients). I m struggling with it currently, would be awesome to just add switch in cli
