### ISSUE TITLE
bug: layout shift on docs

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#738]
### Provide environment information

chrome on macos

### Describe the bug

There is layout shift on the docs (look at the navbar)

I believe this was introduced in a recent PR

https://user-images.githubusercontent.com/8353666/202033226-588be4b3-8003-4106-8470-7e70f49e3f3d.mov

### To reproduce

go on the homepage, click between docs and faq

**Comment by juliusmarminge** [comment]
Flawless on my end.

**Comment by c-ehrlich** [comment]
Weird since we're both on the same Chrome version (107.0.5304.110). I get it in a new incognito tab as well. Can someone else confirm or deny?

**Comment by juliusmarminge** [comment]
I get some interesting results with the devtools open and experimenting with `prefers-reduced-motion`: https://share.cleanshot.com/YM6ikc

**Comment by nexxeln** [comment]
> Flawless on my end.

Same here on brave on windows 11
