### ISSUE TITLE
bug: A week earlier this worked fine but now create-t3-app doesnt work hope it will be fixed soon!

### ISSUE THREAD

**Issue by Hunter-7010** [t3-oss/create-t3-app#740]
### Provide environment information

 System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 476.20 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.14.0 - /usr/local/bin/npm

### Describe the bug

after npx prisma db push
npm run dev doesnt work 

apple@192 project % npm run dev

### To reproduce

apple@192 project % npm run dev

> maxfood@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/apple/Documents/Next.js Projects/maxfood1/.env
/var/folders/96/tt1ts_9j7cz2kzmtmz75zhnm0000gp/T/dev-f2663a2d.sh: line 1: 96699 Segmentation fault: 11  next dev
apple@192 maxfood1 % 

### Additional information

i think this caused by the new trpc version update!
when i replace the dependencies with a week earlier dependencies it seems to work fine.

**Comment by juliusmarminge** [comment]
Works for me: https://share.cleanshot.com/6QEXEX

```
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 669.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/72875_1668555103269/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/72875_1668555103269/bin/npm
```

create-t3-app version 6.9.0 (with trpc rc.4)

**Comment by nexxeln** [comment]
> ###
> System: OS: macOS 10.15.2

Please share your ct3a version, its in `package.json`.

**Comment by Hunter-7010** [comment]
{
  "name": "my-t3-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "next build",
    "dev": "next dev",
    "postinstall": "prisma generate",
    "lint": "next lint",
    "start": "next start"
  },
  "dependencies": {
    "@next-auth/prisma-adapter": "^1.0.4",
    "@prisma/client": "^4.5.0",
    "@tanstack/react-query": "^4.10.0",
    "@trpc/client": "10.0.0-rc.4",
    "@trpc/next": "10.0.0-rc.4",
    "@trpc/react-query": "10.0.0-rc.4",
    "@trpc/server": "10.0.0-rc.4",
    "next": "13.0.2",
    "next-auth": "^4.15.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "superjson": "1.9.1",
    "zod": "^3.18.0"
  },
  "devDependencies": {
    "@types/node": "^18.0.0",
    "@types/react": "^18.0.14",
    "@types/react-dom": "^18.0.5",
    "@typescript-eslint/eslint-plugin": "^5.33.0",
    "@typescript-eslint/parser": "^5.33.0",
    "autoprefixer": "^10.4.7",
    "eslint": "^8.26.0",
    "eslint-config-next": "13.0.2",
    "postcss": "^8.4.14",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.13",
    "prisma": "^4.5.0",
    "tailwindcss": "^3.2.0",
    "typescript": "^4.8.4"
  },
  "ct3aMetadata": {
    "initVersion": "6.9.0"
  }
}

**Comment by c-ehrlich** [comment]
> when i replace the dependencies with a week earlier dependencies it seems to work fine.

Could you be more specific about what you mean by this?

**Comment by Hunter-7010** [comment]
> > when i replace the dependencies with a week earlier dependencies it seems to work fine.
> 
> Could you be more specific about what you mean by this?

When i replace the current dependencies with these:
  "dependencies": {
    "@next-auth/prisma-adapter": "^1.0.5",
    "@prisma/client": "^4.4.0",
    "@tanstack/react-query": "^4.10.0",
    "@trpc/client": "10.0.0-proxy-beta.17",
    "@trpc/next": "10.0.0-proxy-beta.17",
    "@trpc/react": "10.0.0-proxy-beta.17",
    "@trpc/server": "10.0.0-proxy-beta.17",
    "next": "12.3.1",
    "next-auth": "^4.16.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "superjson": "1.9.1",
    "zod": "^3.18.0"
  },
  it seems to work for me

**Comment by juliusmarminge** [comment]
Can you provide a reproduction example cause a fresh install works just fine

**Comment by Hunter-7010** [comment]
Found the problem, CTA is using next 13 under the hood that is why it was causing me problems
