### ISSUE TITLE
bug: NextAuth.js page broken on mobile screens

### ISSUE THREAD

**Issue by AyanavaKarmakar** [t3-oss/create-t3-app#744]
### Provide environment information

Any mobile device.

### Describe the bug

![devtools](https://user-images.githubusercontent.com/89210438/202090246-5dc50cf0-97e1-4c14-931d-f301f00897ea.png)

![mobileimage1](https://user-images.githubusercontent.com/89210438/202090686-faecb808-6c5e-4972-adb9-ac40f93b5663.png)

![mobileimage2](https://user-images.githubusercontent.com/89210438/202090663-19d3202c-f86a-489c-8180-c95a9228254b.png)

### To reproduce

Open https://beta.create.t3.gg/en/usage/next-auth on any mobile device.

**Comment by nexxeln** [comment]
Any idea on how to fix?

**Comment by AyanavaKarmakar** [comment]
https://github.com/t3-oss/create-t3-app/pull/695/commits/4f708b00ed5307e6620db698141b59bae5eb98ed fixed the issue previously by using `break-all`. The layout broke again after replacing `break-all` with `break-words` in https://github.com/t3-oss/create-t3-app/pull/695/commits/4f708b00ed5307e6620db698141b59bae5eb98ed. 

A quick hotfix would be rewording. This single line is causing all the layout issues in the NextAuth.js page:
![image](https://user-images.githubusercontent.com/89210438/202093695-9327c199-7ad8-42f0-a5c8-859bdf79b974.png)

Rewording:
![image](https://user-images.githubusercontent.com/89210438/202093799-797da7e3-5b80-45c6-b40b-05b88f389836.png)**

**Comment by juliusmarminge** [comment]
> https://github.com/t3-oss/create-t3-app/pull/695/commits/4f708b00ed5307e6620db698141b59bae5eb98ed fixed the issue previously by using `break-all`. The layout broke again after replacing `break-all` with `break-words` in https://github.com/t3-oss/create-t3-app/pull/737/commits/57039d4bad124adcfdac2c003da4b13d2b69239a. 
> 
> 
> 
> A quick hotfix would be rewording. This single line is causing all the layout issues on the NextAuth.js page:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/89210438/202093695-9327c199-7ad8-42f0-a5c8-859bdf79b974.png)
> 
> 
> 
> Rewording:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/89210438/202093799-797da7e3-5b80-45c6-b40b-05b88f389836.png)

That's not the problem, the problem is the iframes I believe. break-all causes other issues
