### ISSUE TITLE
docs: flash on nav items

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#751]
Flashing can prob be fixed later, its less annoying than the layout shift so this is good for now

![CleanShot 2022-11-16 at 15 23 08](https://user-images.githubusercontent.com/51714798/202205907-31aa6d16-f2da-4659-b40b-b169507996b5.gif)

_Originally posted by @juliusmarminge in https://github.com/t3-oss/create-t3-app/issues/750#issuecomment-1317115060_

**Comment by juliusmarminge** [comment]
> Hi @juliusmarminge, can take on this task as a new contributor? 

Go ahead 👍 I'll assign you

**Comment by umarfchy** [comment]
Hi @juliusmarminge, hope you're doing well. Is this issue fixed already? The flicker does seem to be as apprehensive in the current site as compared to the gif attached in the issue.

**Comment by Sboonny** [comment]
hi @umarfchy, I hope you have a nice day. The issue is still there, but you may have to open network in devtools and slow the loading of stylesheet to notice it. Btw 42069 stars nice 👍

**Comment by juliusmarminge** [comment]
I think it's fixed for the theme toggler but still there on the github icon

**Comment by juliusmarminge** [comment]
https://user-images.githubusercontent.com/51714798/203858754-c1008b6c-9da0-45ae-b6b0-859b4ec1a386.mp4

**Comment by umarfchy** [comment]
Got it. I'm on it. Thanks for the info 👍

**Comment by umarfchy** [comment]
Hi @juliusmarminge, Hope you're doing well. I think the issue has already been resolved by other changes. Unfortunately, didn't get much time thereafter to look into the issue. I'm unassigning myself from the issue. Thanks :)

**Comment by juliusmarminge** [comment]
Yep seems to be fixed!
