### ISSUE TITLE
feat: in translated docs, show if the English version is newer

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#770]
### Is your feature request related to a problem? Please describe.

With Arabic and Russian docs translations underway, we should start thinking about how to integrate the docs well. 

One common issue with docs translations is that they become out of date as the English version gets more updates. Explicitly showing that could give people a warning that there might be newer information, and maybe also motivate more people to contribute to translations. 

### Describe the solution you'd like to see

A component that shows up on translated docs if the English version of this page is newer than the translated version. 

Something like “This translation was last updated on (date). Since then there have been (number) revisions to the English version, with the newest one being on (date). Click here to see the English version of this page. Or click here to help us update the translated version” (I’m sure there is a better way to write this)

Of course this component would ideally be translated into each of the languages we support in the docs. 

### Describe alternate solutions

Not doing this

### Additional information

I don’t think it’s super urgent as all the incoming translations will be new for the time being, but it would be an awesome thing to have.

**Comment by juliusmarminge** [comment]
> I don’t think it’s super urgent as all the incoming translations will be new for the time being, but it would be an awesome thing to have.

yes i think it's a crucial thing to have.

we also need to make sure we have maintainers willing to review and update docs in the respective language - although i dont think that'll be a problem in this community.

**Comment by a4addel** [comment]
> we also need to make sure we have maintainers willing to review and update docs.
I'm ready for that.
