### ISSUE TITLE
docs(i18n): add spanish translation

### ISSUE THREAD

**Issue by hodeinavarro** [t3-oss/create-t3-app#776]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like to see

Add spanish translations of the brand new [create.t3.gg](https://create.t3.gg) documentation

### Describe alternate solutions

n/a

### Additional information

Submitting this issue to spread awareness and avoid multiple translation versions.

I'll probably assign myself this issue on the weekend, but if any other contributor already started this, I'll be happy to review the PR.

**Comment by c-ehrlich** [comment]
Closing this issue because the translation is in progress. Feel free to reopen if there is something important.
