### ISSUE TITLE
bug: Docs- Mobile pop out menu hidden incorrectly

### ISSUE THREAD

**Issue by DevMaxC** [t3-oss/create-t3-app#777]
### Provide environment information

https://create.t3.gg/
Chrome

### Describe the bug

![image](https://user-images.githubusercontent.com/20259746/202478003-4c82196d-ff95-4c74-9e88-d66f2f5de250.png)

When looking at the Docs- if the browser is 767px wide, the mobile nav menu is hidden incorrectly, meaning the button in the top right to expand/hide the menu, appears to do nothing.

### To reproduce

Go to- https://create.t3.gg/
Set browser width to 767px
Attempt to click the menu button top right

**Comment by Yevhenii-Bakhmat** [comment]
Im using Chrome and it isn't reproduced🤔.
![image](https://i.imgur.com/5Op3aq8.png)

**Comment by KarthikRaju391** [comment]
I came across the same bug

https://user-images.githubusercontent.com/67912316/202518376-f4d1e4d9-18e2-4cab-a40b-571f0e6440a5.mp4

Can I work on this issue?

**Comment by KarthikRaju391** [comment]
Hey @c-ehrlich , this is my first time contributing to a project. I have to create a new branch and edit code in that branch right?

**Comment by KarthikRaju391** [comment]
Hey @c-ehrlich , do I need to create a new branch and edit the code in there or can I just open a PR from the next branch itself?

**Comment by c-ehrlich** [comment]
> Hey @c-ehrlich , do I need to create a new branch and edit the code in there or can I just open a PR from the next branch itself?

Since you need to fork the repo, you can use any branch you want to inside your fork. However I would recommend to create a new one as it makes the workflow easier.

**Comment by nexxeln** [comment]
> Hey @c-ehrlich , do I need to create a new branch and edit the code in there or can I just open a PR from the next branch itself?

You can read our [contributing guide](https://github.com/t3-oss/create-t3-app/blob/next/CONTRIBUTING.md)
