### ISSUE TITLE
docs: One button to toggle the theme instead of 2 radiobuttons

### ISSUE THREAD

**Issue by muradbuyukasik** [t3-oss/create-t3-app#781]
### Is your feature request related to a problem? Please describe.

On my first visit to the docs site I start clicking around the page to test and explore, as I always do. I noticed that the theme toggle is not really a toggle in the sense that you can click the same element twice and have it... toggle.

Subconsciously, because there are only 2 options, I did expect this behavior:
1. Visit the page, it starts in dark mode due to my preferences
2. Click the sun icon, it switches to light mode
3. Click the sun icon again, expecting it to switch back to dark mode
4. Click the moon icon to get my desired action

![theme toggle 2](https://user-images.githubusercontent.com/10285764/202497074-82f12957-86c6-4f84-9ce5-09649d030811.gif)

### Describe the solution you'd like to see

Ideally the theme should toggle regardless of where you click within both label element's parent div. 

Like [NextAuth](https://next-auth.js.org/) does for example:
![theme toggle](https://user-images.githubusercontent.com/10285764/202496632-92dcd2aa-96b9-4dd8-b4db-069c4d11f873.gif)

### Describe alternate solutions

Instead of a single button like the example above, keep it as is but have the theme toggle between dark and light regardless whether you click on the sun or the moon.

### Additional information

I'm willing to do this! This would be my first time contributing to an open source project then.

**Comment by c-ehrlich** [comment]
I like keeping both icons / the current styling, but I think the entire thing could be the click target instead of just one icon.

**Comment by nexxeln** [comment]
> I like keeping both icons / the current styling, but I think the entire thing could be the click target instead of just one icon.

Agree, feel free to make a PR for this @muradbuyukasik
