### ISSUE TITLE
feat: Resize NextAuth logo for better Lighthouse score

### ISSUE THREAD

**Issue by smnschmnck** [t3-oss/create-t3-app#783]
### Is your feature request related to a problem? Please describe.

Theo was sad in yesterdays stream because the create.t3.gg site did not manage to receive a straight 100s Lighthouse score.

This was mostly due to the fact that the NextAuth logo has the dimensions of 653x722px although it is only being rendered at 32x40px in the final site.

### Describe the solution you'd like to see

Can be fixed by resizing the NextAuth Logo to 32x40px and updating it in the public/images folder.

### Describe alternate solutions

Use an SVG of the NextAuth logo but I could not find any SVG versions of it on the internet.

### Additional information

I am willing to do this.

**Comment by nexxeln** [comment]
Feel free to make a PR!
