### ISSUE TITLE
bug: Seems tRPC (or its config) doesn't work when internet is off on local machine?

### ISSUE THREAD

**Issue by sdoxsee** [t3-oss/create-t3-app#788]
### Provide environment information

npx envinfo --system --binaries
```
  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 589.69 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```
ct3a from package.json
```
  "ct3aMetadata": {
    "initVersion": "6.10.0"
  }
```

![image](https://user-images.githubusercontent.com/1173362/202592466-878abb14-5242-4b58-bfc7-8f0325172c07.png)

### Describe the bug

tRPC hangs on the hello endpoint. I just get `Loading tRPC query...` 

I don't see an error but no success either.

### To reproduce

Start up a freshly generated app (`npm run dev`) without the internet, open http://localhost:3000, I just get `Loading tRPC query...`. 

### Additional information

Turning on the internet solves this. Does something require the internet? There are many times that I work offline and this prevents progress.

**Comment by ronanru** [comment]
![image](https://user-images.githubusercontent.com/35634442/202653158-151531eb-c386-4621-8c38-5ade32185275.png)
Just tested it on my machine, it works as expected. 
I'm using Linux and the same ct3a version. Tried both node v19 and v16.

**Comment by AyanavaKarmakar** [comment]
Can reproduce on Windows 10.

![image](https://user-images.githubusercontent.com/89210438/202672617-b1e60253-ea39-4c26-a489-63308f2a8954.png)

```json
"ct3aMetadata": {
    "initVersion": "6.10.0"
  }
```

**Comment by sdoxsee** [comment]
Thanks @ronanru and @AyanavaKarmakar. I tried it on Ubuntu and it worked fine as well. Seems like MacOS and Windows?

**Comment by needim** [comment]
seems related to: https://tanstack.com/query/v4/docs/guides/network-mode

> Since React Query is most often used for data fetching in combination with data fetching libraries, the default network mode is [online](https://tanstack.com/query/v4/docs/guides/network-mode#network-mode-online).

> In this mode, Queries and Mutations will not fire unless you have network connection. This is the default mode. If a fetch is initiated for a query, it will always stay in the state (loading, error, success) it is in if the fetch cannot be made because there is no network connection. However, a [fetchStatus](https://tanstack.com/query/v4/docs/guides/queries#fetchstatus) is exposed additionally.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/271912/202838932-c496edbd-7d8f-480f-bb95-a9300ea7d378.png">

quick solution: change react-query networkMode configuration
`src/pages/api/auth/[...nextauth].ts`

```typescript
export const trpc = createTRPCNext<AppRouter>({
  config() {
    return {
      queryClientConfig: {
        defaultOptions: {
          queries: {
            networkMode:
              process.env.NODE_ENV === "development" ? "always" : "online",
          },
        },
      },
      transformer: superjson,
      links: [
        loggerLink({
          enabled: (opts) =>
            process.env.NODE_ENV === "development" ||
            (opts.direction === "down" && opts.result instanceof Error),
        }),
        httpBatchLink({
          url: `${getBaseUrl()}/api/trpc`,
        }),
      ],
    };
  },
  ssr: false,
});
```

**Comment by needim** [comment]
If you want also mutations to run:

```typescript
...
queries: {
  networkMode:
    process.env.NODE_ENV === "development" ? "always" : "online",
},
mutations: {
  networkMode:
    process.env.NODE_ENV === "development" ? "always" : "online",
},
...
```

**Comment by needim** [comment]
But, if you wanna develop an offline UX, you should revert it back.

**Comment by sdoxsee** [comment]
Thanks @needim. That definitely works for me. 

Should that be the default for both queries and mutations? An offline UX wouldn't be the most common scenario. 

It also baffles me why those default react-query settings don't seem to affect Linux (or Ubuntu).

**Comment by c-ehrlich** [comment]
I didn't know about this behaviour in tRPC either. But I don't think we should override the default behaviour as that would break peoples expectations.

**Comment by needim** [comment]
@c-ehrlich it is not a tRPC behavior actually. It is @tanstack/react-query configuration. (since tRPC uses react-query under the hood it looks like that) I agree with you about not changing the default behavior. 👍 

and I have no idea about this nor do I have a Linux to test this.
> It also baffles me why those default react-query settings don't seem to affect Linux (or Ubuntu).

developers should handle network situations like this.

**Comment by sdoxsee** [comment]
Sounds good. Glad we can at least capture this issue so that other devs can see the solution. Thanks for all your help.
