### ISSUE TITLE
feat: option to choose between Prisma and EdgeDB 

### ISSUE THREAD

**Issue by brunocrosier** [t3-oss/create-t3-app#789]
### Is your feature request related to a problem? Please describe.

Request: add a CLI option to let people choose between Prisma and EdgeDB (a fully typesafe open-source database, with better performance than Prisma)

### Describe the solution you'd like to see

There is a [PR in Next-Auth](https://github.com/nextauthjs/next-auth/pull/5781) to add an EdgeDB adapter, which will hopefully land soon.

The solution could be to let users running `npm create t3-app@latest` choose between Prisma or EdgeDB

### Describe alternate solutions

Only allow Prisma

### Additional information

I have already created a version of the scaffolded project locally - it is not too difficult to replace Prisma with EdgeDB. It's basically just a matter of:

1) Remove `schema.prisma` and replace it with an EdgeDB schema
2) in `client.ts`, export the EdgeDB client instead of `prisma`
3) in `context.ts` add `client` to the context instead of `prisma`

**Comment by nexxeln** [comment]
2nd T3 Axiom
> Bleed Responsibly
We love our bleeding edge tech. The amount of speed and, honestly, fun that comes out of new shit is really cool. We think it's important to bleed responsibly, using riskier tech in the less risky parts. This means we wouldn't ⛔️ bet on risky new database tech (SQL is great!). But we happily ✅ bet on tRPC since it's just functions that are trivial to move off.

**Comment by MiroslavPetrik** [comment]
@brunocrosier here is remix of t3 with edgedb
https://github.com/PastelStoic/create-t3-edgedb-app

**Comment by tsongas** [comment]
Risky new database tech? Um, it's built on Postgres which has been around for 37 years.

**Comment by brunocrosier** [comment]
> Risky new database tech? Um, it's built on Postgres which has been around for 37 years.

what made you think it was a good idea to comment this on an issue that was closed months ago?
