### ISSUE TITLE
feat: Prepare the UI for Languages written in Arabic script.

### ISSUE THREAD

**Issue by a4addel** [t3-oss/create-t3-app#792]
### Is your feature request related to a problem? Please describe.

* Add font that looks nice in Arabic, Farsi (and other languages written in Arabic script in General)
* Notice that some of these languages have unique characters like چ and پ in Farsi.
* Prepare the UI to Switch to RTL when it's needed.

### Describe the solution you'd like to see

Use the `Bahij` font for Arabic docs <a href="https://arabfonts.net/fonts/bahij-thesansarabic-bold">Bahij</a>
Use the `Dana` font for Farsi docs <a href="https://wikiarticle.xyz/i-post.php?ua=wga5n2gnylfontsara.ir/sq1ko4pdm/farsi-font/dana//tp9xw3nqs">Dana</a> 

(I'm not aware of the type License for these fonts, I will appreciate your help on this point.

### Describe alternate solutions

Not doing that

**Comment by c-ehrlich** [comment]
Are you aware of any other OSS projects that do a good job with Arabic/Farsi docs? Maybe we can learn from them.

**Comment by a4addel** [comment]
Yes, The React Libray has Arabic and Farsi Docs,
<a href="https://ar.reactjs.org/ ">https://ar.reactjs.org/ </a>
<a href="https://fa.reactjs.org/">https://fa.reactjs.org/</a>

**Comment by juliusmarminge** [comment]
> Prepare the UI to Switch to RTL when it's needed.

I think we support this, should just be putting `dir: "rtl"` in the frontmatter

**Comment by c-ehrlich** [comment]
This will be improved significantly by https://github.com/t3-oss/create-t3-app/pull/820

I don't want to tag that PR as "resolving" this because we'll probably need to do more afterwards, but wanted to have it linked here.

**Comment by c-ehrlich** [comment]
Closing this for now after #820 is merged, please open individual issues for any remaining bugs in rtl :)
