### ISSUE TITLE
bug: Issue handling middleware properly 

### ISSUE THREAD

**Issue by mthariath** [t3-oss/create-t3-app#793]
### Provide environment information

Environment info:
```
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 11.28 GB / 31.94 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

```
  "initVersion": "6.10.0"

### Describe the bug

I'm using the T3 starter and following [this guide](https://vercel.com/guides/nextjs-multi-tenant-application) for creating a multi-tenant application. I add the middleware.ts file prescribed by the guide, and my problem is that the middleware never runs with the matcher export needed (the middleware should only run for certain routes, so static files, Nextjs JS files, etc. can be served like normal; other requests will be rewritten to different endpoints, for the multitenant functionality.)

To make sure I wasn't crazy, I created a new app with create-next-app, added the middleware file, and it was behaving as expected.

### To reproduce

1. Create a T3 app
2. Add a file named `middleware.ts` to the src directory with the following contents:
```
// middleware.ts
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

// This function can be marked `async` if using `await` inside
export function middleware(request: NextRequest) {
  console.log('running')
  return NextResponse.next()
}

export const config = {
  matcher: [
    /*
     * Match all paths except for:
     * 1. /api routes
     * 2. /_next (Next.js internals)
     * 3. /fonts (inside /public)
     * 4. /examples (inside /public)
     * 5. all root files inside /public (e.g. /favicon.ico)
     */
    "/((?!api|_next|fonts|examples|[\\w-]+\\.\\w+).*)",
  ],
};
```
3. Run the development server and visit the browser. 

Expected result: "running" is logged in the serverside each time the page is visited.
Actual result: "running" is never logged, and the middleware doesn't run. 

As a sanity check, try creating an app with `create-next-app`. Create the same `middleware.ts` file, but this time in the root directory (since the default Next app doesn't use the src directory.) When you visit the page, the middleware should run as expected and the log should print.

Any ideas why the middleware isn't running as expected? It seems like the matcher is incorrectly filtering out requests - if I completely remove the config/matcher from the file, the middleware runs (but the problem is that it runs even when it shouldn't, i.e. it intercepts incorrect requests.)

I should also add that I'm using NextAuth without a Prisma backend - I'm connecting to a separate backend. NextAuth is configured with just a single Credentials provider. 

Thank you!!

**Comment by juliusmarminge** [comment]
Just tested and with your matcher it never runs, but changing it to a more simple one does.

Here's my test file:

```ts
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

// This function can be marked `async` if using `await` inside
export function middleware(request: NextRequest) {
  console.log("running");
  return NextResponse.next();
}

export const config = {
  matcher: "/",
};
```

Might be something wrong with the regex?

**Comment by mthariath** [comment]
So I continued testing, and found the issue - it's i18n configuration in the next.config file. If you remove that, it works as expected. 

The matcher is what it needs to be, so that static assets and other random Next stuff won't get intercepted - it works with the same matcher with regular CNA and if I remove the i18n config. 

It seems like it's a NextJS issue directly, so this issue can be closed, unless someone has some useful thoughts. I don't need i18n immediately, but it'd be nice!

**Comment by c-ehrlich** [comment]
> So I continued testing, and found the issue - it's i18n configuration in the next.config file. If you remove that, it works as expected.
> 
> The matcher is what it needs to be, so that static assets and other random Next stuff won't get intercepted - it works with the same matcher with regular CNA and if I remove the i18n config.
> 
> It seems like it's a NextJS issue directly, so this issue can be closed, unless someone has some useful thoughts. I don't need i18n immediately, but it'd be nice!

Interesting that i18n gets in the way of it, not sure why. Maybe open a similar issue in NextJS?
