### ISSUE TITLE
feat: Add an option to bootstrap a T3 app's auth for Web 3.0 apps

### ISSUE THREAD

**Issue by brunocangs** [t3-oss/create-t3-app#802]
### Is your feature request related to a problem? Please describe.

Authenticating a user on the Web 3.0 is a hard, but solved problem. However it requires lots of setup code for something that is crucial to the workflow of any application and I believe is something that could be useful to a lot of devs in the coming years, given the traction the Web 3.0 space is gaining.

### Describe the solution you'd like to see

I'd like to work on adding an option or template to the CLI that includes an integration for [siwe](https://www.npmjs.com/package/siwe) (Sign in with Ethereum), which [integrates very well with NextAuth](https://docs.login.xyz/integrations/nextauth.js) in case there's the interest of supporting this feature.

The current scenario of Web 3/Blockchain development has lots of end-to-end type-safe support, and integrates well with the tooling used by the T3 stack through [hardhat](https://hardhat.org/) and [typechain](https://www.npmjs.com/package/typechain). For example, on my app I have typings and interfaces automatically generated and connected for all of my smart contracts, available on my frontend through a package that uses `react-query` under the hood, [wagmi](https://wagmi.sh/)

Given how well described, and aligned with the Type Safety paradigm of the T3 stack, I'd like to know if supporting this is in the interest of the maintainers, and would love to build it myself as a contribution to the ecossystem

### Describe alternate solutions

We could add a reference link on the docs to the siwe/web 3 integration as reference if a fully integrated setup is not interesting

**Comment by t3dotgg** [comment]
No
