### ISSUE TITLE
bug: tweet section in landing page using dummy data in prod

### ISSUE THREAD

**Issue by AyanavaKarmakar** [t3-oss/create-t3-app#815]
### Provide environment information

N/A

### Describe the bug

https://user-images.githubusercontent.com/89210438/202898984-0e87b314-607b-4183-bf39-c82f0ffeeef3.mp4

### To reproduce

1. Go to https://create.t3.gg/
2. Scroll down to the tweets section

### Additional information

IIRC, three different tweets were shown there before. Or am I remembering wrong?

**Comment by c-ehrlich** [comment]
It seems our twitter api token has expired or become invalidated.

We need to either update it, or just hardcode/"fake" the tweets.

**Comment by juliusmarminge** [comment]
Wtf i just fixed this last night is twitter rate limiting me or something?

**Comment by iAverages** [comment]
If I am not mistaken, the build will fail if there is no twitter API token provided ([here](https://github.com/t3-oss/create-t3-app/blob/next/www/src/components/landingPage/tweets/tweets.astro#L25)). Are you sure Vercel has the twitter token added when building the docs?
