### ISSUE TITLE
feat: add finnish translation

### ISSUE THREAD

**Issue by LukaHietala** [t3-oss/create-t3-app#817]
### Is your feature request related to a problem? Please describe.

-

### Describe the solution you'd like to see

Add finnish translation to the documentation.

### Describe alternate solutions

-

### Additional information

-

**Comment by LukaHietala** [comment]
Is there any specific instruction for adding a new language to the project?

**Comment by juliusmarminge** [comment]
> Is there any specific instruction for adding a new language to the project?

No, not yet. we didn't quite anticipate this big interest in translating the docs.

Generally though:

1. make a copy of pages/en to pages/fi
2. File a draft PR to let others know you're working on it
3. One by one, translate the docs, add `lang: fi` in the frontmatter of the translated pages

There'll be some other stuff required with the sidebar but that doesn't yet work so we'll have to get back to you on that one.

**Comment by LukaHietala** [comment]
Thanks! I'll make a draft PR now.

**Comment by LukaHietala** [comment]
@juliusmarminge do I need to translate the frontmatter too or will it cause some issues.

**Comment by c-ehrlich** [comment]
> @juliusmarminge do I need to translate the frontmatter too or will it cause some issues.

We have a guide for translations now:
https://github.com/t3-oss/create-t3-app/blob/next/www/TRANSLATIONS.md

It's probably still a bit rough around the edges but should hopefully be enough to get you started. If not, we also have a `ct3a-translation` channel on discord now.

And here is an example of a translated file:
https://raw.githubusercontent.com/t3-oss/create-t3-app/cbb21673ada42873279bc4689a9966629081f1e4/www/src/pages/ru/installation.md

**Comment by c-ehrlich** [comment]
I see you've started working on this :) Closing the issues now, feel free to reopen if there's something important.
