### ISSUE TITLE
bug: booleans not parsed correctly in type-safe env variables

### ISSUE THREAD

**Issue by jwyce** [t3-oss/create-t3-app#818]
### Provide environment information

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 280.27 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/Library/Caches/fnm_multishells/2042_1668006154873/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/2042_1668006154873/bin/yarn
    npm: 8.11.0 - ~/Library/Caches/fnm_multishells/2042_1668006154873/bin/npm

### Describe the bug

KATT's [envsafe](https://github.com/KATT/envsafe) will correctly parse booleans in the .env file. 

Here when I add a boolean it always parses as a string and cannot validate it's a boolean. 

The type-safe env variables should be able to parse booleans

### To reproduce

1. create a .env file
2. add a boolean env variable `SHOULD_WORK=true`
3. add to server/client schema `SHOULD_WORK=z.boolean()`
4. use variable somewhere (like a console log)
5. run `npm run dev`

### Additional information

![image](https://user-images.githubusercontent.com/16946573/202922960-37e2c4b7-5f9b-41f7-ad5d-6dcea82857bd.png)

**Comment by juliusmarminge** [comment]
Thats because he internally converts the string to a boolean for you. We use raw Zod so you'd have to do that work yourself:

```ts
SOME_VAR: z.string().transform(s => s === 'true' || s === 't' || s === '1'),
```

**Comment by jwyce** [comment]
thanks for the clarification and the solution!
