### ISSUE TITLE
bug: the side menu href to the `en` docs when the locale is arabic

### ISSUE THREAD

**Issue by a4addel** [t3-oss/create-t3-app#821]
### Provide environment information

https://create-t3-ods0zsr9b-t3-oss.vercel.app/ar/introduction

### Describe the bug

the link href is `host/[..path]/en/foo` instead of `host/[..path]/ar/foo`

![Cdapture](https://user-images.githubusercontent.com/84184203/203036549-ddd4508c-dff3-4ebc-b480-59edc632f9e6.PNG)

### To reproduce

foo

**Comment by c-ehrlich** [comment]
opened a pr for this just now :)

https://github.com/t3-oss/create-t3-app/pull/820

until it's merged, i guess you will have to navigate manually by typing in the urls

**Comment by juliusmarminge** [comment]
Follow the translation guide for setting up the sidebar for your language and this will work
