### ISSUE TITLE
bug: margin of the logo in the RTL layout

### ISSUE THREAD

**Issue by a4addel** [t3-oss/create-t3-app#827]
### Provide environment information

Missing space between the logo and the btn.

https://create-t3-jj580d3na-t3-oss.vercel.app/ar/introduction

![Captssure](https://user-images.githubusercontent.com/84184203/203101062-75f64934-f231-4b48-a338-03b3d7286d92.PNG)

### Describe the bug

foo

### To reproduce

foo

**Comment by Sboonny** [comment]
The section is flex box, it's possible to use gap and not worry about mirror margin in that section.

**Comment by c-ehrlich** [comment]
This (and many other things) will be fixed by #820
