### ISSUE TITLE
feat: Italian Transaltion

### ISSUE THREAD

**Issue by micziz** [t3-oss/create-t3-app#833]
### Is your feature request related to a problem? Please describe.

Generally the more docs languages you have, the more accesible it is to developers. 

### Describe the solution you'd like to see

Translating the docs to Italian

### Describe alternate solutions

I don't know, maybe Google Translate? But that would cause some confusion and just be a hassle

**Comment by nexxeln** [comment]
Are you willing to contribute an Italian translation?

**Comment by micziz** [comment]
> Are you willing to contribute an Italian translation? None of the maintainers are Italian so we can't translate or review a translation. We depend on the community for that.

Yes! I'm going to start working on it.

**Comment by LukaHietala** [comment]
Google Translate is great for quick translation, but you also need to read the Google Translate translation and correct any technical terms.

**Comment by micziz** [comment]
> Google Translate is great for quick translation, but you also need to read the Google Translate translation and correct any technical terms.

I will se if this works

**Comment by LukaHietala** [comment]
Julius Marminge gave me these instructions, they might be useful.

```
1. make a copy of pages/en to pages/it
2. File a draft PR to let others know you're working on it
3. One by one, translate the docs, add lang: it in the frontmatter of the translated pages

There'll be some other stuff required with the sidebar but that doesn't yet work so we'll have to get back to you on that one.
```

**Comment by LukaHietala** [comment]
It is now merged. New link: https://github.com/t3-oss/create-t3-app/blob/next/www/TRANSLATIONS.md

**Comment by c-ehrlich** [comment]
Nice to see the Italian translation getting started!

I'm going to close this to help clean out our issues a bit, please continue discussions in the linked PR :)
