### ISSUE TITLE
bug: home page link don't work

### ISSUE THREAD

**Issue by PranayBajracharya** [t3-oss/create-t3-app#842]
### Provide environment information

Bug report

### Describe the bug

The links here are not clickable.

![image](https://user-images.githubusercontent.com/74179331/203556663-26e97c77-5845-463c-bdb9-33fada76af52.png)

### To reproduce

It is right there on the home page.

**Comment by c-ehrlich** [comment]
fixed by https://github.com/t3-oss/create-t3-app/pull/843
