### ISSUE TITLE
bug: layout shift on clicking and clicking out of the language select dropdown

### ISSUE THREAD

**Issue by nexxeln** [t3-oss/create-t3-app#855]
### Provide environment information

Brave browser on Windows 11

### Describe the bug

On clicking and clicking out of the language select dropdown, there is layout shift.

https://user-images.githubusercontent.com/95541290/203685235-12534d19-2fe6-460d-83a5-0446e134f1ee.mp4

### To reproduce

Replicate what's being done in the video

**Comment by juliusmarminge** [comment]
Weird considering I used Headless UI. Maybe some class conflicts?

**Comment by asrvd** [comment]
same here, trying to find out whats wrong here

**Comment by wiktor-falek** [comment]
I found out that regular <li> elements don't cause this issue, but <Listbox.Option> does. This happens with and without tailwind classes. Trying to figure out why.
