### ISSUE TITLE
bug: Typo in TRPC docs page

### ISSUE THREAD

**Issue by givensuman** [t3-oss/create-t3-app#865]
### Provide environment information

N/A

### Describe the bug

Between two of the code blocks in the TRPC page there is a typo that would lead to a type error IRL.

`appRouter` is defined to have `users` (line 2)
```
const appRouter = t.router({
  users: userRouter,
  posts: postRouter,
  messages: messageRouter,
});

export type AppRouter = typeof appRouter;
```
but is called on later as `user` (line 5)
```
import { useRouter } from "next/router";

const UserPage = () => {
  const { query } = useRouter();
  const userQuery = trpc.user.getById.useQuery(query.id);

  return (
    <div>
      <h1>{userQuery.data?.name}</h1>
    </div>
  );
};
```

### To reproduce

https://create.t3.gg/en/usage/trpc

### Additional information

Suggestion: Change "user" in the second code block above to "users"

**Comment by nexxeln** [comment]
Are you free to make a PR?

**Comment by givensuman** [comment]
> Are you free to make a PR?

Done 👍
