### ISSUE TITLE
docs: rename `T3 Collection` file to `Made with T3`

### ISSUE THREAD

**Issue by a4addel** [t3-oss/create-t3-app#870]
### Is your feature request related to a problem? Please describe.

the name T3 Collection does not describe the content of the page

### Describe the solution you'd like to see

 I think it will make more sense to name it `Made with T3`

### Describe alternate solutions

not renaming it

**Comment by nexxeln** [comment]
I think T3 collection is fine. What do you think @juliusmarminge?

**Comment by c-ehrlich** [comment]
I agree that "T3 Collection" doesn't really tell me what will be on the page. 

"Made with T3" makes sense currently, but it means that we can't add tutorials, apps that make T3 dev easier (like tRPC Playground), etc to the list later. 

If we add a bunch more stuff it could be possible to add "T3 Collection" as a category with pages for "Made with T3", "T3 Tools", etc

Not sure what's best tbh

**Comment by juliusmarminge** [comment]
> I think T3 collection is fine. What do you think @juliusmarminge @c-ehrlich? 

I'm a fan of tPRC's "Awesome Collection" https://trpc.io/docs/awesome but it would be sneaky to steal that one ;)

**Comment by c-ehrlich** [comment]
> > I think T3 collection is fine. What do you think @juliusmarminge @c-ehrlich?
> 
> I'm a fan of tPRC's "Awesome Collection" https://trpc.io/docs/awesome but it would be sneaky to steal that one ;)

Astro has a "showcase", I like that also https://astro.build/showcase/

**Comment by juliusmarminge** [comment]
Since no-one else have pushed for this change in over a month I'll go ahead and close as not planned.
