### ISSUE TITLE
docs (i18n): add portuguese (pt-BR) translations

### ISSUE THREAD

**Issue by wesleycoder** [t3-oss/create-t3-app#872]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like to see

Add portuguese (pt-BR) translations of the brand new create.t3.gg documentation.

### Describe alternate solutions

n/a

### Additional information

Following the [example](https://github.com/t3-oss/create-t3-app/issues/776) @hodeinavarro made:
Submitting this issue to spread awareness and avoid multiple translation versions.

I'll probably assign myself this issue by Dec 6, but if any other contributor already started this, I'll be happy to review and contribute on the PR.

**Comment by c-ehrlich** [comment]
We already have a Portuguese translation in progress, It's not marked explicitly as `pt` or `pt-br` but the person who opened the PR is based in Brazil. https://github.com/t3-oss/create-t3-app/pull/853

We are always happy to have more contributors and reviewers on translation - my experience on OSS is that people come and go, and we need a bare minimum of two people to keep a language up to date.

**Comment by wesleycoder** [comment]
Nice, I'll be helping on the existing PR then.
Thanks for raising the awareness.

**Comment by c-ehrlich** [comment]
closing this for now but feel free to reopen if there's something that doesn't fit in the PR for the pt translation
