### ISSUE TITLE
feat: update scaffolded README.md

### ISSUE THREAD

**Issue by AyanavaKarmakar** [t3-oss/create-t3-app#876]
### Is your feature request related to a problem? Please describe.

The [What’s next? How do I make an app with this?](https://create.t3.gg/en/faq#whats-next-how-do-i-make-an-app-with-this) section in the README is currently outdated and the text needs to be updated.

### Describe the solution you'd like to see

- Update the text
- Fix typos
- Update the tutorials list

### Describe alternate solutions

- Keep the text
- Fix typos
- Update the tutorials list

### Additional information

We can add these two tutorials to the README tutorials list since they are pretty useful IMO:

![image](https://user-images.githubusercontent.com/89210438/204087083-e74eeb68-f601-417a-89d5-bd7c9a5edf39.png)

The current list: 

![image](https://user-images.githubusercontent.com/89210438/204087114-5d87c009-7c4f-4b87-a9f1-a03910623138.png)

**Comment by nexxeln** [comment]
This is getting hard to maintain to be honest. I wonder if just put a link to the docs would suffice for the README.

**Comment by juliusmarminge** [comment]
> This is getting hard to maintain to be honest. I wonder if just put a link to the docs would suffice for the README.

I don't think we should remove the `What's next` section, but we should emphasize our docs more than we currently are.

The learning resources can definetely just be link to the docs section though

**Comment by juliusmarminge** [comment]
![CleanShot 2022-11-26 at 16 04 04@2x](https://user-images.githubusercontent.com/51714798/204095557-4a2a68e0-1130-40fc-9fe0-1f93b4ccca56.png)

suggestions

**Comment by nexxeln** [comment]
> ![CleanShot 2022-11-26 at 16 04 04@2x](https://user-images.githubusercontent.com/51714798/204095557-4a2a68e0-1130-40fc-9fe0-1f93b4ccca56.png)
> 
> suggestions

agree agree

**Comment by AyanavaKarmakar** [comment]
Maybe the docs and tutorial link can be grouped like this?

![image](https://user-images.githubusercontent.com/89210438/204099106-75f74e30-53a4-4b4b-b963-a44581b9dc5a.png)
