### ISSUE TITLE
Shouldn't there be only one h1 tag per page?

### ISSUE THREAD

**Issue by mnik01** [t3-oss/create-t3-app#88]
**Describe the bug**
For example, in with-trpc-tw.tsx file, we have 5 h1 tags.

**Expected behavior**
To have one h1 and others h2

**Comment by mnik01** [comment]
If i getting it right
Even if we use sections, it's recommended to use nesting of h1
As it mentioned here (with link to W3C)

![image](https://user-images.githubusercontent.com/39025497/177070596-92d4af02-42dd-4587-9b40-eababd37ba7c.png)
https://ahrefs.com/blog/h1-tag/#use-one-h1-per-page

**Comment by nexxeln** [comment]
Thank you for opening this issue, we definitely want to stick with best practices. Will take a look at the PR in a bit.

**Comment by nexxeln** [comment]
Implemented in #89
