### ISSUE TITLE
docs: provide other package managers for init commands

### ISSUE THREAD

**Issue by needim** [t3-oss/create-t3-app#892]
### Is your feature request related to a problem? Please describe.

no problem

### Describe the solution you'd like to see

add copiable buttons in the homepage for other package managers too.
- yarn create t3-app
- pnpm create t3-app
- cnpm? (I just noticed this pm recently)

### Describe alternate solutions

There are no alternate solutions actually.

### Additional information

CLI already knows which package manager runs create-t3-app and suggests that npm install, yarn, or pnpm install depending on the package manager.

**Comment by needim** [comment]
btw it is already in the readme, but not on docs page

**Comment by juliusmarminge** [comment]
It's here: https://create.t3.gg/en/installation

As for the landing page, `npm` is the "right" default - adding tabs for the others will look cluttered.
