### ISSUE TITLE
question: is type-safety enough?

### ISSUE THREAD

**Issue by needim** [t3-oss/create-t3-app#893]
### Is your feature request related to a problem? Please describe.

some quick thoughts on Prisma

- there is no migration revert functionality ([prisma docs](https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/generating-down-migrations))
- there is no built-in support for stored procedures (solution: seed stored procedures & run them via rawQuery)
- there is no sub-query support (using a custom query builder is needed for this for example [knex](https://knexjs.org/)) or writing a raw query is needed)
- there is no built-in soft delete functionality [issue](https://github.com/prisma/prisma/issues/3398#issuecomment-1013225648)
- looks like seeds are not supported for multi-schema setup ([docs](https://www.prisma.io/docs/guides/database/seed-database)) (can use raw migrations for this)

If I go deep enough and test Prisma in production, I think I can provide more minus points in this discussion.

### Describe the solution you'd like to see

better type-safe full-featured ORM?

### Describe alternate solutions

mikro-orm looks type-safe at some point but I didn't test it yet.

### Additional information

I'm using TypeORM in production for 4+ years. It is not type-safe and I'm suffering from it.

**Comment by needim** [comment]
my real question is this:

Is create-t3-app for MVPs or production-ready applications?

IMO prisma looks ok for MVPs but not good enough for complex apps.

**Comment by t3dotgg** [comment]
I'm building Ping on top of Prisma. It's fine. Since it's sql, you can replace it if you run into issues later on.

There are no better options. Feel free to make one yourself and let us know about it when you do.
