### ISSUE TITLE
bug: using create t3-app@latest UB when inserting '@' into project name

### ISSUE THREAD

**Issue by Ambushfall** [t3-oss/create-t3-app#896]
### Provide environment information

"6.10.3"

### Describe the bug

Generally, I don't believe this to be of high importance, however I'd like to mention it.

The t3 npm does not allow '@' symbol in the project name.

### To reproduce

`npm create t3-app@latest`
`? What will your project be called? my-t3@app`
`>> App name must be lowercase, alphanumeric, and only use -, _, and @`

### Additional information

![image](https://user-images.githubusercontent.com/95249049/204484919-f4178dcc-5f13-4276-a564-e77479632bea.png)

**Comment by nexxeln** [comment]
Don't put @ in your project name. This is intended behavior.

**Comment by AyanavaKarmakar** [comment]
@nexxeln shouldn't `@` be removed from here since it is kind of confusing devs into thinking `@` can be used in the project name?

![image](https://user-images.githubusercontent.com/89210438/204511018-b4a8f4ac-1018-47ee-83f1-7a10bda68de2.png)

**Comment by nexxeln** [comment]
> @nexxeln shouldn't `@` be removed from here since it is kind of confusing devs into thinking `@` can be used in the project name?
> 
> ![image](https://user-images.githubusercontent.com/89210438/204511018-b4a8f4ac-1018-47ee-83f1-7a10bda68de2.png)

Oh yeah I didn't notice that, feel free to make a PR for that
