### ISSUE TITLE
feat: tRPC WebSocket subscriptions

### ISSUE THREAD

**Issue by Sheraff** [t3-oss/create-t3-app#910]
### Is your feature request related to a problem? Please describe.

One of the goals of this stack is to enable developers to maintain up-to-date data on the front-end. There is a pretty standard issue when it comes to async data modifications where there is no easy way to tell the client when it's over.

For example, imagine a music app where I request a track:
```ts
publicProcedure.input(z.object({
  id: z.string(),
})).query(async ({ input, ctx }) => {
  const track = await ctx.prisma.track.findUnique({
    where: { id: input.id },
    select: {name: true, artist: true}
  })

  if (!track.artist) asyncFetchArtistFromExternalApi()

  return track
})
```

In this example, at request-time, the server realises it's missing some data and will start fetching it (`asyncFetchArtistFromExternalApi`) but it still responds with the data it currently has, so as not to make the client wait for too long.

At that point, how would you notify the client when `asyncFetchArtistFromExternalApi` has returned and there is some newer data to be fetched?

### Describe the solution you'd like to see

Since this stack has upgraded to tRPC v10, there is now an (experimental) subscription link available that makes use of Web Sockets for 2-way communication. This would be a perfect use-case for such a feature. As soon as `asyncFetchArtistFromExternalApi` returns, ping the client through a subscription and tell it to invalidate some of the `queryClient` cache.

Here's the link to the Subscriptions / Web Sockets part of the tRPC docs: https://trpc.io/docs/subscriptions

### Describe alternate solutions

Alternatively, it is still possible in user-land to develop that feature. Web Sockets are doable within this stack, and tRPC allows for a strongly-typed communication. It would just be nice to have that baked in the starter.

**Comment by c-ehrlich** [comment]
The first line of the tRPC subscriptions docs is:

> Subscriptions & WebSockets are in beta & might change without a major version bump.

Anyone who wants to use them is free to do so, but we're not leading them down that road.

**Comment by Cmoen11** [comment]
At least, this should be added to the roadmap, I think this feature is one of many leaking features of any full-stack solutions out there... Marking this as complete feel like you won't add it at all, makes me sad :(

**Comment by c-ehrlich** [comment]
> > The first line of the tRPC subscriptions docs is:
> > > Subscriptions & WebSockets are in beta & might change without a major version bump.
> > 
> > 
> > Anyone who wants to use them is free to do so, but we're not leading them down that road.
> 
> At least, this should be added to the roadmap, I think this feature is one of many leaking features of any full-stack solutions out there... Marking this as complete feel like you won't add it at all, makes me sad :(

The feature is already included in create-t3-app, you just need to read the tRPC docs to activate it ;)

**Comment by Sheraff** [comment]
> The feature is already included in create-t3-app, you just need to read the tRPC docs to activate it ;)

It's not exactly that simple though. tRPC does offer a way to use typed websockets, but
- if you enable it without writing a custom link, all of the requests will go through web-socket, which might prevent some forms of caching (a service worker, for example, does not intercept web-socket messages)
- if you follow the examples provided by tRPC, you'll be declaring a next server through `import {app} from "next"; app.prepare()` 
- you need to change your package.json `start` and `dev` scripts
- you should handle `SIGTERM` and `SIGINT` signals

And probably many things I didn't see in the doc.

So your position on not adding it while in beta is definitely valid depending on how "bleeding-edge" one wants to be. But your position on not adding it because it should be a user-land piece of code is more debatable IMO.

**Comment by ethangclark** [comment]
tRPC subscriptions are no longer considered unstable: https://trpc.io/docs/websockets

Getting it set up in a non-janky way is a major headache, though! Solving this fits very nicely in the t3 stack's mission.

Can we reopen this issue?
