### ISSUE TITLE
bug: docs - pagination arrows in rtl

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#930]
### Provide environment information

.

### Describe the bug

noticed by @ayterx in the arabic translation pr

https://github.com/t3-oss/create-t3-app/pull/791#issuecomment-1339186585

<img width="928" alt="image" src="https://user-images.githubusercontent.com/8353666/205928043-2870502b-57fa-47f5-b934-99bffdc9206e.png">

### To reproduce

open the newest test deployment from https://github.com/t3-oss/create-t3-app/pull/791, go to a page that has pagination

**Comment by Ayterx** [comment]
this is what I use rtl:-scale-x-100
