### ISSUE TITLE
bug: code title overlays "on this page" menu

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#940]
### Provide environment information

.

### Describe the bug

The title of code blocks overlays the "on this page" menu

<img width="410" alt="image" src="https://user-images.githubusercontent.com/8353666/206562433-d9c9c4f7-b9a3-4f68-b83d-c522175b2c2a.png">

### To reproduce

- navigate to any docs page that has a code section such as https://create.t3.gg/en/usage/next-auth
- use a screen size small enough that you get the "on this page" menu, and open it

**Comment by joeshajan** [comment]
Hey @c-ehrlich I would like to fix this issue can you assign this to me?

**Comment by nexxeln** [comment]
Done @joeshajan
