### ISSUE TITLE
feat: `Translate this page` button in docs under `More` menu

### ISSUE THREAD

**Issue by AyanavaKarmakar** [t3-oss/create-t3-app#944]
### Is your feature request related to a problem? Please describe.

Now that the site supports i18n, a `Translate this page` button under the `More` menu will be useful.

### Describe the solution you'd like to see

Like in [Astro Docs](https://docs.astro.build/en/getting-started/), for example.

![image](https://user-images.githubusercontent.com/89210438/206637717-d7f00679-93fe-4a5a-a306-b023889c489c.png)

The button will link to [TRANSLATIONS.md](https://github.com/t3-oss/create-t3-app/blob/next/www/TRANSLATIONS.md) and only show up on the `EN` pages.

### Describe alternate solutions

N/A

### Additional information

N/A

**Comment by c-ehrlich** [comment]
Seems reasonable to me
