### ISSUE TITLE
feat: Documentation improvement ideas - Add "When to use" section on NextJS page

### ISSUE THREAD

**Issue by zanzlender** [t3-oss/create-t3-app#948]
### Is your feature request related to a problem? Please describe.

I sometimes struggle to decide what technology is best suited for my project idea. 

### Describe the solution you'd like to see

I would like to have a brief overview of which types of apps/use cases/ideas are suitable to be built with NextJS and for which we should consider something else, or even avoid Next. Ideally with some examples. (Some of the things to consider about the backend is talked about in the intro video for Next, but I believe Theo talks about this in another video too but I can't remember which one it was...)

It makes sense to me for it to be after this part [Create T3 - Why should i use NextJS?](https://create.t3.gg/en/usage/next-js#why-should-i-use-it) 

### Describe alternate solutions

I don't know of alternatives... don't implement it if it's not that important I guess...

**Comment by c-ehrlich** [comment]
I agree that a "what is this good for / not good for" section could be good. I disagree that it should go in the Next.js page, because most people probably don't even read that page before starting their app. I'd prefer it right at the beginning. This thing from the Astro docs is great imo:

<img width="818" alt="image" src="https://user-images.githubusercontent.com/8353666/206695805-974112da-3463-42b3-8c78-d0159fd3ab23.png">

**Comment by juliusmarminge** [comment]
_Originally posted by https://github.com/Svadrut in #1041_:

> **Is your feature request related to a problem? Please describe.**
> I recently came upon [create-jd-app](https://github.com/OrJDev/create-jd-app) that is the solid-js version of create-t3-app and [create-t3svelte-app](https://github.com/zach-hopkins/create-t3svelte-app). I was surprised to see that it wasn't in the create-t3-app docs.
> **Describe the solution you'd like to see**
> Add create-jd-app and create-t3svelte-app to the other section in recommendations.
> **Describe alternate solutions**
> N/A
> **Additional information**
> I can make a PR if this issue goes through.

**Comment by c-ehrlich** [comment]
The other question is what to recommend / how to recommend it. Astro is an easy recommendation for mostly static sites. Solid Start looks great and I've been meaning to spend some time with it, but it's so new that I would personally only recommend it to those who are willing to bleed a bit irresponsibly. I might be wrong about that though. We could also just phrase it in a neutral way, something like "If you are interested in trying out a similar stack with SolidJS or Svelte, check out create-jd-app and create-t3svelte-app".
