### ISSUE TITLE
bug: the quotes' rotation is reverted in Arabic docs

### ISSUE THREAD

**Issue by Sboonny** [t3-oss/create-t3-app#950]
### Provide environment information

Environment: Gitpod

### Describe the bug

While adding missing paragraphs, one string had quotes in it. Checking the quotes in the demo will show this:

Reverted quotes
![image](https://user-images.githubusercontent.com/88248797/206837834-0fe2917a-099b-4ea3-96d6-1c3153ee955f.png)

Here is the string: `من السهل أن تَقع في فخ أن تُضيف “كل شئ” - لكننا لا نريد ذَلك صراحتاً`

Here is how it looks in the original

![image](https://user-images.githubusercontent.com/88248797/206837896-6a028ede-890c-4842-b2d3-224f2cc72c80.png)

### To reproduce

You can find quotes in https://create.t3.gg/ar/introduction#solve-problems

It will be wrapping around `create-t3-app`.

### Additional information

I have no idea what causing this and I would love to know. If I have to give a blind guess, maybe it is the font-family.

Edit: a quick check in the dev tools show this isn't font-family issue

**Comment by juliusmarminge** [comment]
I don't see quotes here, has this been fixed?

**Comment by Sboonny** [comment]
It exists still 😞, I have updated the link to solve_problems section. 

---

Btw, this isn't a big deal, but slightly goofy looking text, it's reverted French quotes with Arabic text. If you want to close this, feel free to 👍

**Comment by juliusmarminge** [comment]
> If you want to close this, feel free to 👍

Cool!
