### ISSUE TITLE
bug: Discord login not working

### ISSUE THREAD

**Issue by MightyCryptowall** [t3-oss/create-t3-app#952]
### Provide environment information

The Discord login don't work on second try.

### Describe the bug

You can login with discord on your first try, it works. But when you logout and login again it don't works.  

### To reproduce

Everything setup according to the https://create.t3.gg

I upload the code here: https://github.com/MightyCryptowall/discord-login-error-with-t3
clone and performed the step below to reproduce the error

Steps to reproduce the error
-> Your can login with discord on first time
-> You logout
-> When you login with discord for second time, the error appear

**Comment by c-ehrlich** [comment]
> ### Provide environment information
> The Discord login don't work on second try.
> 
> ### Describe the bug
> You can login with discord on your first try, it works. But when you logout and login again it don't works.
> 
> ### To reproduce
> Everything setup according to the https://create.t3.gg
> 
> I upload the code here: https://github.com/MightyCryptowall/discord-login-error-with-t3 clone and performed the step below to reproduce the error
> 
> Steps to reproduce the error -> Your can login with discord on first time -> You logout -> When you login with discord for second time, the error appear
> 
> ### Additional information
> _No response_

You're using next-auth 4.18.0 in your package-lock. Delete node_modules and package-lock, run `npm i` again (which should install next-auth 4.18.4) and it should work.

**Comment by e-osuna-g** [comment]
Thanks @c-ehrlich  that solved my issue too! thanks

**Comment by MightyCryptowall** [comment]
Thanks @c-ehrlich that solved my issue too

**Comment by TomYeoman** [comment]
I'm on 4.18.6 but still get the same

![image](https://user-images.githubusercontent.com/14075632/208995502-e933e4a3-ae0c-4938-bea2-0e72b957521c.png)

```
next-auth@^4.18.3:
  version "4.18.6"
  resolved "https://registry.yarnpkg.com/next-auth/-/next-auth-4.18.6.tgz#c23d02894a09e12d210cfb7041afa43fb1e897a4"
  integrity sha512-0TQwbq5X9Jyd1wUVYUoyvHJh4JWXeW9UOcMEl245Er/Y5vsSbyGJHt8M7xjRMzk9mORVMYehoMdERgyiq/jCgA==
  dependencies:
    "@babel/runtime" "^7.16.3"
    "@panva/hkdf" "^1.0.1"
    cookie "^0.5.0"
    jose "^4.9.3"
    oauth "^0.9.15"
    openid-client "^5.1.0"
    preact "^10.6.3"
    preact-render-to-string "^5.1.19"
    uuid "^8.3.2"
```
