### ISSUE TITLE
bug(docs): breadcrumbs causes layout shifts 

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#959]
### Provide environment information

https://create.t3.gg/en/introduction

### Describe the bug

https://user-images.githubusercontent.com/51714798/206909715-d33bda93-713a-4fba-ab30-9b04b521bbe6.mp4

### To reproduce

Go to https://create.t3.gg/en/introduction

check the breadcrumbs loading after page load.

### Additional information

Component: 
https://github.com/t3-oss/create-t3-app/blob/next/www/src/components/docs/breadCrumbs.tsx

Used: 
https://github.com/t3-oss/create-t3-app/blob/87f1a43499b6a0d74f8fb09898f6fe0ddd4746c9/www/src/components/docs/pageContent.astro#L23

uses `window` so prob has to be client loaded? maybe need some rewriting to make it work?

cc @asrvd

**Comment by juliusmarminge** [comment]
Can tackle #958 at the same time

**Comment by asrvd** [comment]
@juliusmarminge yes, I couldn't use Astro for the component as ts was giving some weird errors over there, but can be possibly fixed by converting it into an Astro component ? 🤔 

about #958 , I don't really understand what's going wrong there, but would look into it

**Comment by asrvd** [comment]
one thing we can do is ignore everything after `#` in the link to prevent it from appearing
