### ISSUE TITLE
Git fails to innitialize with create t3-app

### ISSUE THREAD

**Issue by matovu-farid** [t3-oss/create-t3-app#96]
**Describe the bug**
When I run the create `yarn create t3-app`
After choosing my preferred options, the scaffold builds successfully, however during the build, it attempts to initialise git and it fails.
Git can be initialised manually later by running `git init` after the build

**To Reproduce**
Steps to reproduce the behaviour:
- Run  yarn create  t3-app

2. See  error `✖ Failed: could not initialise git`

**Expected behaviour**
The git initialisation should not fail 

**Additional information**
- I am on a linux distro i.e Zorin Os
- I have git installed

**Screenshots**
![t3](https://user-images.githubusercontent.com/64433642/177117426-8b58effe-3b74-4f94-af78-fddc5b9ce014.png)

**Comment by nexxeln** [comment]
Unable to replicate. Is this happening every time you use the CLI? Have you tried using a different package manager?

**Comment by matovu-farid** [comment]
Hello @nexxeln,
Yes, it also happened when I used npm.
This time I run `npx create-t3-app@latest`
![t32](https://user-images.githubusercontent.com/64433642/177126408-aa96d3d1-359b-4c92-8cb6-0dc9d8bf1c40.png)

**Comment by matovu-farid** [comment]
My git version 
![git_version](https://user-images.githubusercontent.com/64433642/177127232-b6254a3b-bc00-4aeb-b135-c13acd7afd1b.png)

**Comment by nexxeln** [comment]
Maybe it's something OS specific. As far as I know, zorin is based on ubuntu. I'm also using ubuntu in WSL and works fine for me.

**Comment by matovu-farid** [comment]
@nexxeln  Okay just wanted to let you know about it. It is not detrimental to the creation of the app and someone can manually initialize git themselves. It's an awesome project :+1:

**Comment by nexxeln** [comment]
Maybe try updating git?

**Comment by nexxeln** [comment]
Found the issue, for initialising git we use
```
git init --initial-branch=main
```

This is a new feature released in git 2.28 https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch

Working on a fix right now

**Comment by asheeeshh** [comment]
revert back?

**Comment by asheeeshh** [comment]
i don't think forcing people to update git to use the cli is a good thing to do though..

**Comment by Dhravya** [comment]
I think this was discussed in the server right? that we can just initialise the repository with `git init`, and then change the branch using `git checkout -b main`

**Comment by juliusmarminge** [comment]
> I think this was discussed in the server right? that we can just initialise the repository with `git init`, and then change the branch using `git checkout -b main`

That had the side-effect of leaving behind an unused branch. Wouldn't something like:
```ts
const { stdout: gitVersion } = await execa("git --version");
// e.g. gitVersion = "git version 2.32.0 (Apple Git-132)"
const asNumber = ...; // parse the output
if (asNumber >= 2.28) {
  await execa("git init --initial-branch=main", { cwd: projectDir });
} else {
  await execa("git init", { cwd: projectDir });
  await execa("git checkout -b main", { cwd: projectDir }); // maybe?
}

**Comment by Dhravya** [comment]
Yeah. I think that's a better approach, leave an extra branch depending on the git version

**Comment by juliusmarminge** [comment]
> Yeah. I think that's a better approach, leave an extra branch depending on the git version

Leaving for work but I can have a PR out tonight.

Is the `git --version` output the same for every OS? So its parsable the same for all.

**Comment by Dhravya** [comment]
Yep, just checked the documentation, pretty sure it's the same command and the same response on every OS

I'm not sure about different versions though, maybe in an old version it was different? But this can just be YOLO'd and fixed as more users report issues

**Comment by asheeeshh** [comment]
> > I think this was discussed in the server right? that we can just initialise the repository with `git init`, and then change the branch using `git checkout -b main`
> 
> That had the side-effect of leaving behind an unused branch. Wouldn't something like:
> 
> ```ts
> const { stdout: gitVersion } = await execa("git --version");
> // e.g. gitVersion = "git version 2.32.0 (Apple Git-132)"
> const asNumber = ...; // parse the output
> if (asNumber >= 2.28) {
>   await execa("git init --initial-branch=main", { cwd: projectDir });
> } else {
>   await execa("git init", { cwd: projectDir });
>   await execa("git checkout -b main", { cwd: projectDir }); // maybe?
> }
> ```
> 
> be better?

this would be a better approach i think 👍🏼

**Comment by Temez1** [comment]
Got the same problem still with `git version 2.25.1`. WSL2, Ubuntu.

```
Initializing Git...
⠋ Creating a new git repo...
✖ Failed: could not initialize git. Update git to the latest version!
```
