### ISSUE TITLE
feat(docs): dynamic og-images 

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#986]
### Is your feature request related to a problem? Please describe.

This week we rolled out dynamic og images for trpc: https://twitter.com/ixahmedxii/status/1603517506525732881

![CleanShot 2022-12-16 at 20 58 38](https://user-images.githubusercontent.com/51714798/208178963-efb32113-e047-464d-844d-aa335da9363a.png)

Would be nice with something similar for our docs too

### Describe the solution you'd like to see

Dynamic OG Images for Documentation Pages

Things we can include:

- Title
- Description
- Language
- ???

Could also be a good time to change up the logo to the new one Theo announced on stream this week: https://t3.gg, https://github.com/t3dotgg/t3-astro/blob/main/public/images/t3/700.svg

### Describe alternate solutions

Drawback is it has some pitfalls in frameworks that's not Next.js: https://twitter.com/jullerino/status/1602346699359412225

Which might require us to do something similar to what we did in trpc and create a separate app that hosts it: https://github.com/trpc/trpc/tree/main/www/og-image

### Additional information

It was a bigger job than we first anticipated but here are some useful resources:

https://github.com/trpc/trpc/pull/3382
https://github.com/trpc/trpc/pull/3402
https://github.com/trpc/trpc/pull/3406

https://github.com/vercel/satori

**Comment by c-ehrlich** [comment]
I hate that this might require a separate app, but these images look so nice that it's probably worth it :)

**Comment by juliusmarminge** [comment]
> I hate that this might require a separate app, but these images look so nice that it's probably worth it :) 

Solution: migrate off of Astro to Nextra

**Comment by asrvd** [comment]
> > I hate that this might require a separate app, but these images look so nice that it's probably worth it :)
> 
> Solution: migrate off of Astro to Nextra

nextra is nice

**Comment by nahal04** [comment]
Check out [astro-og-image](https://github.com/tomaskebrle/astro-og-image)

**Comment by iAverages** [comment]
If we enable SSR with Astro and add the Vercel adapter we can use server endpoints in Astro. 
https://docs.astro.build/en/core-concepts/endpoints/#server-endpoints-api-routes

We can have a route that uses satori and the title/description within frontmatter to generate the images.

I can make a PR for this... Is there a preferred style for the OG images you guys (@c-ehrlich  @juliusmarminge) have in mind? If not I will probably do something similar to the TRPC OG images
