### ISSUE TITLE
React Redux and Redux Toolkit

### ISSUE THREAD

**Issue by FloweDewolf** [t3-oss/create-t3-app#99]
So, in my opinion, according to a guy who only uses tailwind option, t3 is unnecessary for me. So I think that redux boilerplate could be a good idea as an new option

**Comment by nexxeln** [comment]
If t3 is unnecessary for you, why are you using `create-t3-app`?

**Comment by FloweDewolf** [comment]
> If t3 is unnecessary for you, why are you using `create-t3-app`?

Because that project is a good idea, imo has potential and I would like t3 to be useful to me

**Comment by fbritoferreira** [comment]
@FloweDewolf It sound really wierd that you would want redux to be added if you are not using the project, but would like to understand why you feel is not useful to you. Maybe if you explain that it would be easier for people to understand what you are trying to do.

**Comment by TheoBr** [comment]
Lmao

**Comment by Dhravya** [comment]
what is this issue

**Comment by FloweDewolf** [comment]
It's just that t3 is generally a good idea, but so far it doesn't give me much. As far as I know, the idea of the project is not to install dependencies yourself but to have t3 already configure everything for us based on what we need. However, so far I'm only using tailwind, and somehow it doesn't save me time compared to if I just created a create-next-app project and installed tailwind. And I also believe that the project is for the people so it should not close only to those options that are there, and I most simply proposed a new option

**Comment by Dhravya** [comment]
So like, an option to include redux as well as other things that someone might want?

**Comment by nexxeln** [comment]
> And I also believe that the project is for the people so it should not close only to those options that are there

The project is for people who like using the t3 stack. I would suggest reading through https://init.tips. If you don't find the t3 stack useful, do **not** use this CLI. There are a lot of templates out there that come with next, tailwind and redux already set up. I would suggest using them if you don't like the t3 stack.

**Comment by pmakowski23** [comment]
Also
![image](https://user-images.githubusercontent.com/58031604/177139427-f8b91386-d141-4f41-81aa-abdffc2b3aa3.png)

**Comment by TheoBr** [comment]
@FloweDewolf the idea is, very specifically, to integrate the T3 Stack packages with annoying setup stories (tRPC, Prisma etc)

Go `npm install` your out of date deps yourself lol

**Comment by FloweDewolf** [comment]
> @FloweDewolf the idea is, very specifically, to integrate the T3 Stack packages with annoying setup stories (tRPC, Prisma etc)

Actually, I mistakenly assumed the intention of t3
You're right
