### ISSUE TITLE
bug: Fresh nextauth.ts with 2 errors (lint? ts?) next-auth has no exported member 'type' and ',' expected.ts

### ISSUE THREAD

**Issue by am1ru1** [t3-oss/create-t3-app#993]
### Provide environment information

  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm

### Describe the bug

Getting from VS, from fresh create-t3 (with Jest):

`Module '"next-auth"' has no exported member 'type'. Did you mean to use 'import type from "next-auth"' instead?ts(2614)`
and
`',' expected.ts(1005)`

![image](https://user-images.githubusercontent.com/4379186/208495171-d7d3fdc3-890c-4f65-b726-c3da0f4fc8f5.png)

### To reproduce

Fresh project and under file:
\src\pages\api\auth\[...nextauth].ts

**Comment by juliusmarminge** [comment]
Works on my end.

Can you confirm which version you're at? `NextAuth.js` has sometimes change their types in the past although I've never seen this particular typerror before...

<img width="479" alt="CleanShot 2022-12-20 at 09 26 05@2x" src="https://user-images.githubusercontent.com/51714798/208619267-39b18a6d-0b61-4416-834f-e4531c502f4b.png">

**Comment by am1ru1** [comment]
@juliusmarminge I have decided to remove NextAuth. But noticed NextPage, NextApiRequest, NextApiResponse seems to be having similar issue. 
Not sure how else to debug

2 Issues:
`Module '"next"' has no exported member 'type'. Did you mean to use 'import type from "next"' instead?`

![image](https://user-images.githubusercontent.com/4379186/208734058-b97e547a-580e-47b6-a0dd-459af340c408.png)
![image](https://user-images.githubusercontent.com/4379186/208734146-d1884e5c-9fc7-4a3a-a394-19b185e6c39b.png)

`',' expected.ts(1005)`

![image](https://user-images.githubusercontent.com/4379186/208734230-f5188d54-5662-4df8-ba0a-da65818983e4.png)


Versions:
```
  "dependencies": {
    "@prisma/client": "^4.5.0",
    "@tanstack/react-query": "^4.16.0",
    "@trpc/client": "^10.0.0",
    "@trpc/next": "^10.0.0",
    "@trpc/react-query": "^10.0.0",
    "@trpc/server": "^10.0.0",
    "next": "13.0.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "superjson": "1.9.1",
    "zod": "^3.18.0"
  },
  
    "devDependencies": {
    "@playwright/test": "^1.29.0",
    "@types/node": "^18.0.0",
    "@types/react": "^18.0.14",
    "@types/react-dom": "^18.0.5",
    "@typescript-eslint/eslint-plugin": "^5.33.0",
    "@typescript-eslint/parser": "^5.33.0",
    "autoprefixer": "^10.4.7",
    "eslint": "^8.26.0",
    "eslint-config-next": "13.0.2",
    "jest": "^29.3.1",
    "postcss": "^8.4.14",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.13",
    "prisma": "^4.5.0",
    "tailwindcss": "^3.2.0",
    "typescript": "^4.8.4"
  },
```

Eslintrc.json
```
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "plugins": ["@typescript-eslint"],
  "extends": ["next/core-web-vitals", "plugin:@typescript-eslint/recommended"],
  "rules": {
    "@typescript-eslint/consistent-type-imports": "warn"
  }
}

```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "noUncheckedIndexedAccess": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.cjs", "**/*.mjs", "xplaywright.config.xt"],
  "exclude": ["node_modules"]
}
```

prettier.config.cjs
```
/** @type {import("prettier").Config} */
module.exports = {
  plugins: [require.resolve("prettier-plugin-tailwindcss")],
};

```

**Comment by juliusmarminge** [comment]
pnpm i and restart languster server is the best advice i can think of

**Comment by am1ru1** [comment]
thanks @juliusmarminge . Have restart TS and ESlint servers, and removed node_modules and .next, and then yarn install.
Issue still persist. 
Could be my personal vscode/yarn/node/npm setup issue. Hopefully others might have suggestion

**Comment by am1ru1** [comment]
closing this issue.
